### ISSUE TITLE
.NET workspace fails with MSB6004

### ISSUE THREAD

**Issue by bbartels** [gitpod-io/gitpod#5360] opened 2021-08-24 14:57 UTC
### Bug description

The build in the workspace fails with the following error:

```/home/gitpod/dotnet/sdk/5.0.205/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB6004: The specified task executable location "/run/containerd/io.containerd.runtime.v2.task/k8s.io/9893fadb493f1802ef41dc3e7138768879832b73c9ee3e60759ad3c544a9d6ab/rootfs/home/gitpod/dotnet/dotnet" is invalid. [/workspace/template-dotnet-core-cli-csharp/dotnetcore.csproj]```

### Steps to reproduce

1. Create a new workspace from 'gitpod-io/template-dotnet-core-cli-csharp' template.
2. The terminal will display the error.

### Expected behavior

The build command should not fail

**Comment by aledbf** [comment] 2021-08-24 15:00
Closing. The root cause is this issue: #5090

**Closed by aledbf** 2021-08-24 15:00 UTC
