### ISSUE TITLE
Unable to login to gitpod .

### ISSUE THREAD

**Issue by ankit1999sahu** [gitpod-io/gitpod#2963] opened 2021-01-19 07:13 UTC
Unable to login to gitpod .
It shows authorization failed.
![Screenshot from 2021-01-19 11-36-30](https://user-images.githubusercontent.com/35842151/105000038-d78c1780-5a53-11eb-81c0-79b44334453a.png)

**Comment by gtsiolis** [comment] 2021-01-19 08:25
Hey @ankit1999sahu, see https://github.com/gitpod-io/gitpod/issues/2746#issuecomment-757423846.

Closing this as a duplicate of https://github.com/gitpod-io/gitpod/issues/2746.

**Closed by gtsiolis** 2021-01-19 08:25 UTC
