### ISSUE TITLE
[configurator] changed config isn't saved

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5464] opened 2021-08-31 15:44 UTC
In the configurator for a project without `.gitpod.yml` I see the inference running again on every load.
Even after I have manually changed the configuration.

**Comment by gtsiolis** [comment] 2021-09-08 18:24
Can reproduce this. Opening a new workspace with changed configuration does not load the changed configuration into the workspace.  ✔️

**Comment by JanKoehnlein** [comment] 2021-09-30 15:17
How can I reproduce this? 

If it must be fixed before the first shipping, please add it to groundwork before tomorrow.

**Comment by jankeromnes** [comment] 2021-09-30 16:14
> I see the inference running again on every load.
> Even after I have manually changed the configuration.

Just to clarify, it is expected to always see the spinner (because we always need to check for a potential committed `.gitpod.yml`).

However, if you have:
1. Manually changed the configuration
2. Clicked on `Run Prebuild` at least once

Then opening the Configurator should show you your manually changed configuration (after the spinner, but it should not show a green "Project type detected" followed by a freshly generated config)

**Comment by jankeromnes** [comment] 2021-09-30 16:17
To reproduce:

1. Add a new Project with a repository that doesn't have a `.gitpod.yml`
2. See the auto-detected config
3. Manually change the configuration
4. Click on `Run Prebuild` (as soon as a Prebuild is started, the config is saved)

Then, visit the Configurator page again for your Project.

Expected result: If you have not committed a `.gitpod.yml` since then, you should see your manually modified config (and not a freshly generated one).

I am not able to reproduce (it always restores my saved config)

**Comment by JanKoehnlein** [comment] 2021-10-01 06:22
That's what I tried as well, and I couldn't reproduce it either.

**Comment by jankeromnes** [comment] 2021-10-04 13:48
Closing as "working as intended" (i.e. please click on `Run Prebuild` at least once so that the generated config gets saved).

Otherwise, please re-open as a feature request to auto-save the first generated configuration (and possibly to generate it earlier when adding a Project, not just when loading the Configurator page).

**Closed by jankeromnes** 2021-10-04 13:48 UTC
Labels: type: bug, meta: :thinking: reporter-feedback-needed, component: dashboard, feature: teams and projects
