### ISSUE TITLE
Preview environment takes too long to start, causing workspace integration tests to fail

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#12628] opened 2022-09-02 18:49 UTC
### Bug description

Sometimes the preview envrionment takes too long to start, causing the initial workspace integration test job to fail.

### Steps to reproduce

Refer to this [internal conversation](https://gitpod.slack.com/archives/C03E52788SU/p1662051454479299) for context.

### Expected behavior

Ideally we'd wait longer for the environment to start, allowing for the tests to run, or the environment would start up quicker.

**Comment by mads-hartmann** [comment] 2022-09-05 07:53
Some quick thoughts
1. We should update your job to be resilient to errors from Werft. From a quick glance it looks like it's just failing if we get at 503 when polling the state of the jobs. In that case we can just ignore the error and poll again :relaxed:
1. We should have better insights the Werft API - currently we have no monitoring for that AFAIK

**Comment by mads-hartmann** [comment] 2022-09-05 08:05
And a quick clarification: The integration tests don't fail because the preview environments start too slowly, it's because we get an error when querying for the state of the Werft job for the preview environments. At least from looking at the logs from the job https://werft.gitpod-dev.com/job/gitpod-custom-to-stablization-test.19 mentioned in the thread ☺️

```
[build preview environment] Waiting for gitpod-build-wk-inte-test-20220901164435.0 to finish running. Current phase: PHASE_RUNNING. Sleeping 10 seconds.
Error: rpc error: code = Unavailable desc = Service Unavailable: HTTP status code 503; transport: received the unexpected content-type "text/html"
[slack notification and cleanup EXIT|PHASE] Slack notification and cleanup: EXIT
[slack notification] Sending Slack notificaition
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   507    0     2  100   505     10   2729 --:--:-- --:--:-- --:--:--  2740
```

**Comment by mads-hartmann** [comment] 2022-09-06 12:52
It looks like Werft is restarting quite often:

```
 kubectl -n werft get pods werft-0
W0906 12:52:20.714506  119023 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
NAME      READY   STATUS    RESTARTS   AGE
werft-0   1/1     Running   52         7d3h
```


Looking at the logs:

```
resource.type="k8s_pod"
resource.labels.cluster_name="core-dev"
resource.labels.location="europe-west1-b"
resource.labels.pod_name="werft-0"
```

We see quite a few readiness and liveness probes failing ([source](https://cloudlogging.app.goo.gl/y7garQUydamXAoJKA))


![Image](https://user-images.githubusercontent.com/83561/188640133-1272aa50-4a56-4a66-a54e-c534a838e912.png)

**Comment by kylos101** [comment] 2022-09-07 00:23
Nice detective work, @mads-hartmann ! 🚀 Do we limit the CPU or memory for werft pods? In other words, is it possible they might need more resources?

**Comment by mads-hartmann** [comment] 2022-09-07 13:52
Looking at the logs from the pod before it restarted using the following command

```sh
kubectl -n werft logs --previous --tail 10 werft-0
```

It looks like it might be the `github-integration` plugin which is getting data it doesn't know how to parse, and then decides to `exit 1`

```
time="2022-09-07T13:38:27Z" level=info msg="level=fatal msg=\"rpc error: code = Internal desc = grpc: failed to unmarshal the received message proto: cannot parse invalid wire-format data\"" plugin=github-integration-integration
time="2022-09-07T13:38:27Z" level=fatal msg="plugin error" error="exit status 1" plugin=github-integration
```

**Comment by mads-hartmann** [comment] 2022-09-07 13:58
Looking at the last 30 days this has happened 120 times, so it isn't a regression in the latest version fo Werft which was deployed 8 days ago.

[Source](https://cloudlogging.app.goo.gl/g37bPBqUyyWBxXip8)

![Screenshot 2022-09-07 at 15 57 50](https://user-images.githubusercontent.com/83561/188897039-88d8c740-053d-4b25-8ad6-95c1f64870f2.png)

**Comment by mads-hartmann** [comment] 2022-09-20 09:23
We're now running version 0.3.7 of werft - I'll check back tomorrow to see if the restarts have stopped.

**Comment by mads-hartmann** [comment] 2022-09-27 11:52
It hasn't restarted in over 4 days 

```
kubectl -n werft get pods werft-0
NAME      READY   STATUS    RESTARTS   AGE
werft-0   1/1     Running   0          4d4h
```

And it only restarted twice in the last 7 since the release 

![Image](https://user-images.githubusercontent.com/83561/192517982-4a6a17b7-cbec-44c0-930e-74935093c59a.png)

Closing this for now.

**Closed by mads-hartmann** 2022-09-27 11:52 UTC
Labels: type: bug, aspect: testing, team: platform
