### ISSUE TITLE
Use GitHub email alias instead of private email

### ISSUE THREAD

**Issue by k3nsei** [gitpod-io/gitpod#3186] opened 2021-02-14 16:34 UTC
It would be nice to have github email alias instead of private email adress when creating pod from GitHub.
With new option to hide private emails and blocking commits which contains them it annoying to constantli changing git config.

For example mine is `190422+k3nsei@users.noreply.github.com`

**Comment by jankeromnes** [comment] 2021-02-15 08:38
Hi @k3nsei!

Please try adding these two environment variables in https://gitpod.io/settings/ : 

- Name: `GIT_AUTHOR_EMAIL`, Value: `190422+k3nsei@users.noreply.github.com`, Org/Repo: `*/*`
- Name: `GIT_COMMITTER_EMAIL`, Value: `190422+k3nsei@users.noreply.github.com`, Org/Repo: `*/*`

And then stop/restart any existing Gitpod workspaces, or just create new Gitpod workspaces.

I think that should do it.

**Comment by jankeromnes** [comment] 2021-02-15 08:40
Also, closing as a duplicate of https://github.com/gitpod-io/gitpod/issues/387. Thanks again!

**Closed by jankeromnes** 2021-02-15 08:40 UTC
Labels: git provider: github, type: question

**Comment by k3nsei** [comment] 2021-02-19 10:08
@jankeromnes Thanks :)
