### ISSUE TITLE
Error: operation not permittied: missing create permission on workspace. 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#2046] opened 2020-10-22 12:19 UTC
### Describe the bug

Sometimes it randomly happens that a workspace does not start with the below error:

```
Error: operation not permittied: missing create permission on workspace. 
```

![image](https://user-images.githubusercontent.com/46004116/96870324-2abcf100-148a-11eb-9e0b-236dfe20da7b.png)

The issue seems to happen on both staging and production. 

### Steps to reproduce

This happens randomly while opening workspaces.

**Comment by csweichel** [comment] 2020-11-18 08:55
duplicate of #2189

**Closed by csweichel** 2020-11-18 08:55 UTC
Labels: bug, staging
