### ISSUE TITLE
Invalid Host header

### ISSUE THREAD

**Issue by bbhxwl** [gitpod-io/gitpod#9885] opened 2022-05-10 01:14 UTC
### Bug description

I run my nodejs project, Vue, open the preview, don't show anything, only errors.

### Steps to reproduce

I run my nodejs project, Vue, open the preview, don't show anything, only errors.

**Comment by axonasif** [comment] 2022-06-03 20:30
Duplicate of https://github.com/gitpod-io/gitpod/issues/9921

**Closed by axonasif** 2022-06-03 20:30 UTC
Labels: type: bug
