### ISSUE TITLE
Bulk delete workspaces

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#6839] opened 2021-11-22 17:10 UTC
## Is your feature request related to a problem? Please describe

Sometimes I want to clear up old workspaces, especially when I have a lot. It's rather frustrating that the delete process is three clicks (select workspace -> delete -> confirm) which makes deleting more than 2-3 a very tedious experience.

## Describe the behaviour you'd like

Have a bulk delete button with a select box next to the workspace status icon

![image](https://user-images.githubusercontent.com/275848/142904870-96d26782-5917-4f5f-ad38-277649ee9a5f.png)

**Comment by gtsiolis** [comment] 2021-11-25 11:12
Thanks @MrSimonEmms! Agree, making it easier to delete multiple or all workspaces sounds definitely interesting. Closing this as a duplicate of https://github.com/gitpod-io/gitpod/issues/4233 but feel free to reopen if this describes a different problem. Cc @jldec

**Closed by gtsiolis** 2021-11-25 11:12 UTC
