### ISSUE TITLE
not able to signin

### ISSUE THREAD

**Issue by Ankyji05** [gitpod-io/gitpod#2754] opened 2021-01-10 08:17 UTC

**Comment by Ankyji05** [comment] 2021-01-10 08:18
I'm not able to sign-in in the gitpod

**Comment by akosyakov** [comment] 2021-01-10 13:14
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by akosyakov** 2021-01-10 13:14 UTC
