### ISSUE TITLE
bricked workspace due to the interactive shell

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1171] opened 2020-02-03 02:28 UTC
### Describe the bug

Apparently using https://gitpod.io/#https://github.com/RXT0112/Zernit/tree/ab89261e064596a2ab3de97588f40ce7f0b253be which seems to result in interactive shell causes the workspace to lock out and run forever

![image](https://user-images.githubusercontent.com/11302521/73621072-eb691e80-4634-11ea-96f4-ebdcf41ccb42.png)

Cannot be removed:
![image](https://user-images.githubusercontent.com/11302521/73621077-f15eff80-4634-11ea-89df-53dbe292ed0e.png)

And cannot be accessed ('Open' button doesn't work)

If the repository is openned through the gitpod.io prefix link it results in following and hangs forever:
![image](https://user-images.githubusercontent.com/11302521/73621174-6599a300-4635-11ea-890f-3c62d21a3836.png)

The build has interactive shell expecting to parse a number to choose a language which seems to cause this
(no image provided)

Openning the repository causes it to open a parallel workspace:
![image](https://user-images.githubusercontent.com/11302521/73621292-d50f9280-4635-11ea-8576-d94f7d4617b1.png)

So these 4 bricked workspaces are wasting 4 seconds every 1 second of the 50h end-user's FOSS plan which will deplate it in 12 hours and 4 minutes.

I suspect that this may waste the free FOSS hours of the end-user

### Steps to reproduce

Open https://gitpod.io/#https://github.com/RXT0112/Zernit/tree/ab89261e064596a2ab3de97588f40ce7f0b253be

### Expected behavior

Do not lock out the end-user from the workspace

### Proposed solution

Non-interactive shell should be used

**Comment by JesterOrNot** [comment] 2020-02-03 03:00
@Kreyren 
Hey, A few issues, it seems that the problem is one of the packages is installing this keyboard application that is interactive and hangs waiting for input.  I've prepared a PR
https://github.com/RXT0112/Zernit/pull/32
![image](https://user-images.githubusercontent.com/50386709/73622294-c5c12280-45fe-11ea-9714-5598960a5e01.png)
I've also took the liberty of condensing you layers, for future refrece don't do
```dockerfile
RUN apt-get update
RUN apt install -y foo
```
Instead do
```dockerfile
RUN apt-get update \
    && apt-get install -y foo
```
A few reasons:
A. this condenses layering (making builds faster)
B. This prevents bugs with versioning
See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get

**Comment by Kreyren** [comment] 2020-02-03 03:50
@JesterOrNot merged, thanks for info!

What about the bricked workspaces?

**Comment by JesterOrNot** [comment] 2020-02-03 03:55
Wait what do you mean by 'bricked' I thought you just meant that the work-space wouldn't start. Can you explain?

**Comment by Kreyren** [comment] 2020-02-03 04:02
@JesterOrNot I believe that this caused the workspaces running in the background without me being able to run, stop or delete them which caused my 100H of FOSS plan to run out in the matter of minutes.. I remember getting a warning message for 50 minutes remaining and after 5 minutes it locked me out.

**Comment by JesterOrNot** [comment] 2020-02-03 04:05
So to be clear you think that this is due to the Dockerfile issue?

**Comment by Kreyren** [comment] 2020-02-03 04:10
@JesterOrNot based on available info i've concluded it to be the case or i am worse nolifer then i though

**Comment by JesterOrNot** [comment] 2020-02-04 12:55
Closing this issue due to it being solved please reopen this issue or file a new one if this pops up agaiin :smile:

**Closed** 2020-02-04 12:56 UTC
