### ISSUE TITLE
Garbage ANSI characters in the terminal

### ISSUE THREAD

**Issue by apolopena** [gitpod-io/gitpod#3878] opened 2021-04-09 20:01 UTC
### Bug description

Terminal output using ANSI escape characters are prone to getting mangled and will appear partially and unescaped.

**Note**: This issue was not present prior to the first live push of the [March 2021 milestone](https://github.com/gitpod-io/gitpod/milestone/12).

### Steps to reproduce

This might not reproduce easily as this seems asynchronous in nature.
If you run an ANSI colored spinner in the terminal and have other process running, that may reproduce it.
Or have a look below at the Example Respository section.

### Expected behavior

ANSI Garbage characters should not be displayed in an ANSI supported terminal.

### Example repository

Here is an example of the issue occuring with `npm` output:
![image](https://user-images.githubusercontent.com/3060702/114233742-a88a9100-9932-11eb-80ce-7b6863b37fe9.png)

I have since removed the color from the spinner in a project of mine but you can see this issue in realtime in this old branch (which I will change/delete in the future):
https://github.com/apolopena/gitpod-laravel8-starter/tree/development

**Comment by akosyakov** [comment] 2021-04-11 06:05
maybe resolved by https://github.com/gitpod-io/gitpod/pull/3870 already

**Comment by akosyakov** [comment] 2021-04-12 07:43
I could not reproduce it with https://github.com/gitpod-io/gitpod/pull/3870

**Closed by akosyakov** 2021-04-12 07:43 UTC
Labels: editor: code, type: bug
