### ISSUE TITLE
[self-hosted] Prevent the use minio default secret_key/access_key

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#2890] opened 2021-01-13 16:02 UTC
Gitpod comes with a [default value for secret_key/access_key](https://github.com/gitpod-io/gitpod/blob/master/chart/values.yaml#L417-L418). This is likely to lead to insecure Gitpod installations, because many will not change those values. Our current "saving grace" is that minio is not available from outside the cluster - that's not much in the way of security to begin with and likely to change (see #2001).

Instead, we should fail the Gitpod installation if default values (could be `'''` empty string) are used. The installers would auto-generate a random value for those keys, and the docs would make changing those keys mandatory.

**Comment by jgallucci32** [comment] 2021-01-15 19:56
The issue with failing the installer for not changing defaults is the buck doesn't stop with Minio and it could go on forever. For instance, gitpod doesn't use trusted SSL certs by default, should the installer fail because it's insecure? Mysql uses default root credentials, should it fail for that as well?

I get the merit behind it (and security-wise it makes sense), but if a stock Helm chart cannot be deployed it might discourage users from even looking into Gitpod because of the work and level of knowledge required to get a basic deployment going.

One option could be to issue a Warning to make it very clear this is for non-production use (and to change the values in production).

**Comment by csweichel** [comment] 2021-01-29 06:51
When installing using the Terraform scripts we should certainly generate secrets using Terraform.

Alternatively: we could use helm-generated keys. They would change at every update/installation, but that should not matter much, because they're primarily used within the Gitpod installation anyways.

**Comment by corneliusludmann** [comment] 2021-02-02 08:25
The first part of the issue is fixed in #2988: https://github.com/gitpod-io/gitpod/blob/9495f3a82b3ece1f1eb616ad5e4fe7c7aa908073/chart/templates/_helpers.tpl#L332-L333

However, we should probably keep this issue open for the second step: generating secrets in Terraform.

**Comment by geropl** [comment] 2021-04-13 07:18
@corneliusludmann Please re-open if still relevant.

**Closed by geropl** 2021-04-13 07:18 UTC
Labels: component: install, self-hosted
