### ISSUE TITLE
Terminal does not load

### ISSUE THREAD

**Issue by Sxpherr** [gitpod-io/gitpod#5858] opened 2021-09-24 12:13 UTC
I have this issue for two days now, it always shows me that (I tried and different workspaces)![image](https://user-images.githubusercontent.com/66752592/134672339-f919a411-3c63-4fbe-882a-1cd0efb5aa4d.jpeg)

**Comment by akosyakov** [comment] 2021-09-24 13:03
Which version of VS Code do use latest or stable? Which versions of device, operating system, browser?

**Comment by Sxpherr** [comment] 2021-09-24 13:08
> Which 
I'm using ipados 15, firefox and the latest version

**Comment by akosyakov** [comment] 2021-09-27 07:04
duplicate of https://github.com/gitpod-io/gitpod/issues/5040

**Closed by akosyakov** 2021-09-27 07:04 UTC
Labels: meta: :thinking: reporter-feedback-needed, editor: code
