### ISSUE TITLE
Support custom email addresses

### ISSUE THREAD

**Issue by philschatz** [gitpod-io/gitpod#4101] opened 2021-04-28 20:36 UTC
Hello!

Github allows users to [Block command line pushes that expose my email](https://github.com/settings/emails) but it seems gitpod does not notice that setting and instead uses my primary GitHub email when generating the workspace `~/.gitconfig` file.

![image](https://user-images.githubusercontent.com/253202/116468321-543e4700-a836-11eb-9842-e259821d3e73.png)

It seems like there are at least 2 different ways to solve this niche problem:

1. Change something like [manager/create.go](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/pkg/manager/create.go#L531) to allow `GIT_COMMITTER_EMAIL` if the user has set it in their "Variables" list
2. Change something like [server/.../github-auth-provider.ts](https://github.com/gitpod-io/gitpod/blob/main/components/server/src/github/github-auth-provider.ts#L65) to store the email address that GitHub expects (e.g. `253202+philschatz@users.noreply.github.com`) if no public emails are present.

Would either of these approaches (or some other ones) work? If so, it's probably just a couple of lines to fix but I'm happy to try making the changes!

**Comment by AlexTugarev** [comment] 2021-04-29 05:39
Hey @philschatz,
This is a duplicate of https://github.com/gitpod-io/gitpod/issues/387.

The comprehensive approach would be to add an optional `commitEmail` next to the `primaryEmail`, so that it would be filled in for both GitHub and GitLab users.

**Comment by philschatz** [comment] 2021-05-03 22:55
@AlexTugarev , Thanks for that feedback. I created a Pull Request (#4115) which I believe uses the comprehensive approach you mentioned.

**Comment by corneliusludmann** [comment] 2021-07-08 15:24
Fixed with #4115

**Closed by corneliusludmann** 2021-07-08 15:24 UTC
