### ISSUE TITLE
GitLab G-mail login issues

### ISSUE THREAD

**Issue by Nisarg2910** [gitpod-io/gitpod#2826] opened 2021-01-11 13:30 UTC
### Describe the bug

Whenever I try to sign in using GMAIL, it says me Sorry, something went wrong 😓
Authorization failed. Please try again.
Though my credentials are correct.

### Steps to reproduce

Open GitLab from Crio workspace and try logging in and try to log-in using g-mail.

### Expected behavior

After trying to log-in, it displays a message like Sorry, something went wrong 😓
Authorization failed. Please try again.

**Comment by jankeromnes** [comment] 2021-01-11 16:20
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by jankeromnes** 2021-01-11 16:20 UTC
