### ISSUE TITLE
Not oppening

### ISSUE THREAD

**Issue by jhcxavier** [gitpod-io/gitpod#1113] opened 2020-01-18 14:00 UTC
**Describe the bug**

The gitpod is not opening, not even loading!
**To Reproduce**

just try to open any project
**Expected behavior**

load the project
**Additional Information**

**Comment by jankeromnes** [comment] 2020-01-18 16:59
Thank you for reporting this. I think this is a duplicate of #1110 and also Gitpod should work again now.

**Closed by jankeromnes** 2020-01-18 16:59 UTC
