### ISSUE TITLE
Black blocks in terminal at every underscore

### ISSUE THREAD

**Issue by TamaMcGlinn** [gitpod-io/gitpod#12190] opened 2022-08-18 06:28 UTC
### Bug description

Whenever an underscore _ is encountered in the terminal window, a black box is drawn around that character.

![Screenshot from 2022-08-18 08-27-04](https://user-images.githubusercontent.com/5008897/185309315-328de3f2-ade9-490d-a56a-ed4c660bd1c0.png)

### Steps to reproduce

Type `echo "_hi"` into a terminal window.

### Expected behavior

It should look the same as on a native terminal, just `_hi`

**Comment by axonasif** [comment] 2022-08-18 14:24
Possible duplicate of https://github.com/gitpod-io/gitpod/issues/12145

**Comment by akosyakov** [comment] 2022-08-18 14:49
Do you use Firefox?

**Closed** 2022-08-18 14:52 UTC
Labels: type: bug
