### ISSUE TITLE
After, I log on to gitpod workspace, its showing sorry cant authorize

### ISSUE THREAD

**Issue by Subham18Sharma** [gitpod-io/gitpod#2750] opened 2021-01-10 07:24 UTC

**Comment by akosyakov** [comment] 2021-01-10 13:14
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by akosyakov** 2021-01-10 13:14 UTC
