### ISSUE TITLE
500 Internal Server Error nginx/1.14.1

### ISSUE THREAD

**Issue by ColbyWTaylor** [gitpod-io/gitpod#1128] opened 2020-01-21 18:56 UTC
**Describe the bug**

Receiving this error (along with students) in the middle of session, unable to connect to github to push as well.

500 Internal Server Error
nginx/1.14.1

**To Reproduce**

Open any workspace...

**Expected behavior**

That it stays open!

**Additional Information**

Have been having more issues lately- any idea what it may stem from ?

**Comment by Waffle552** [comment] 2020-01-22 19:57
This issue occurs for me at 1:30 PM CST every day.

**Comment by jankeromnes** [comment] 2020-01-23 13:09
Update: We've implemented a fix that should prevent these `Error 50x` events from happening again.

We'll continue to monitor the situation for a few days to validate this fix. If you see such an error again, please kindly report it here, cc @RDIL @JesterOrNot @HSSANT.

Once the fix is confirmed we'll close this issue, and we're also planning to publish a blog post with more details on what happened and how we've fixed it.

**Comment by RDIL** [comment] 2020-01-23 13:12
Thanks Jan, your the best 😃

**Comment by jankeromnes** [comment] 2020-01-23 14:52
(Thanks @RDIL! But all the praise goes to @geropl @32leaves @svenefftinge and @meysholdt. 😊)

**Comment by davelavoie** [comment] 2020-01-23 20:38
Unfortunately I'm still getting a 500 error right now...

**Comment by geropl** [comment] 2020-01-24 16:23
Hi @davelavoie ,

thanks for reporting!

Could you elaborate where exactly you noticed the `50x` or what you where doing?

**Comment by davelavoie** [comment] 2020-01-24 21:01
Currently it's not happening, but while it was happening, I was simply browsing the front-end of a WordPress install.

**Comment by jelaniwoods** [comment] 2020-01-27 14:42
I'm experiencing a 504 error just trying to log in with Github.

**Comment by RDIL** [comment] 2020-01-27 14:43
It just started happening aah

**Comment by HSSANT** [comment] 2020-01-27 15:10
its impossible to access again. Seriously thinking about hire a better
service. I cant work properly day after day because of gitpod.

**Comment by svenefftinge** [comment] 2020-01-27 17:05
We are all super sorry and work with highest priority to get this reliably working.

**Comment by jankeromnes** [comment] 2020-01-27 17:26
I concur with Sven, we're really sorry about these repeated disruptions @RDIL and @HSSANT, and we're doing our best to make Gitpod durably more stable.

The `500 internal server error` described in this issue should no longer happen. However, we're currently seeing the `Error 504` again: #1151

We're still unclear why specifically the US region started having all these different bugs recently, while the EU and Asia Pacific regions continue to operate smoothly (like the US before). We're able to mitigate each specific bug as it appears relatively quickly, but it's currently our top priority to understand the deeper issues making the US region so unstable. We're currently looking at whether this is due to the particular datacenter we're in; or if it's due to some US-specific workloads we run; or if Gitpod's scary-fast growth could be the reason its biggest region is now suddenly showing signs of stress. We want Gitpod to be always fast & reliable, and we'll make any efforts necessary to achieve this.

**Comment by jankeromnes** [comment] 2020-01-28 19:08
[Update] We've found and fixed what we believe was the root cause of all these US issues. More details here: https://github.com/gitpod-io/gitpod/issues/1151#issuecomment-578933856

An immense thank you for all your good will, understanding, and help in getting this resolved.

**Closed by jankeromnes** 2020-01-28 19:08 UTC
Labels: bug, operations
