### ISSUE TITLE
Cannot pull image: Back-off pulling image after creating new workspace

### ISSUE THREAD

**Issue by vicentemovil** [gitpod-io/gitpod#1979] opened 2020-10-12 09:08 UTC
### Describe the bug
Everytime I try to create a Workspace I get the following error:
cannot pull image: Back-off pulling image "reg.gitpod.io:8081/remote/cb6df334-f5d2-4290-b14d-5d31d943569c"; last backup failed: workspace does not exist. Please contact support if you need the workspace data.

**Comment by vicentemovil** [comment] 2020-10-12 09:12
Now everytime i try to create a workspace I get the following error:

**We are having trouble parsing your context
Error: Cannot read property 'sha' of undefined**

**Comment by corneliusludmann** [comment] 2020-10-12 09:16
Thanks for reporting. We are currently investigating this issue.

**Comment by corneliusludmann** [comment] 2020-10-12 09:25
Should be fixed now. Could you please test it again?

It was an SSL cert issue for some of our users. Sorry for the inconvenience.

**Comment by jankeromnes** [comment] 2020-10-12 09:28
I can confirm that the problem was fixed.

Will update https://status.gitpod.io

**Closed by jankeromnes** 2020-10-12 09:28 UTC
Labels: critical, operations

**Comment by Domchap90** [comment] 2020-10-12 09:34
yes fixed now
