### ISSUE TITLE
Caret Placement

### ISSUE THREAD

**Issue by GDJason12** [gitpod-io/gitpod#482] opened 2019-04-14 01:44 UTC
**Describe the bug**

When I delete a mistake from the text, the caret misplaces and it bugs the entire IDE.
**To Reproduce**

1. Place the caret in the correct pos.
**Expected behavior**

Caret is placed in the correct order, doesn't make bugs, and the caret is after the letter.

**Comment by akosyakov** [comment] 2019-04-15 04:36
@GDJason12 hi, thank you for the issue

Do you mean something like that https://github.com/theia-ide/theia/issues/3796?

**Comment by svenefftinge** [comment] 2019-04-16 08:41
I think it is a duplicate of #339 
(Are you on a Chromebook)

**Closed by svenefftinge** 2019-04-16 08:41 UTC
