### ISSUE TITLE
500 Internal Server Error nginx/1.14.1 when tried to open workspace

### ISSUE THREAD

**Issue by HSSANT** [gitpod-io/gitpod#1126] opened 2020-01-21 14:10 UTC
Hello again.
500 Internal Server Error nginx/1.14.1 when tried to open workspace

@jankeromnes could you please check? 

Thanks.

**Comment by geropl** [comment] 2020-01-21 14:16
@HSSANT Thanks for reporting, we're on it. Any other observation that could help?

**Comment by geropl** [comment] 2020-01-21 14:31
I'm closing this as the US cluster is working again. Please re-open if that's not the case for you!

**Closed by geropl** 2020-01-21 14:31 UTC
Labels: bug

**Comment by jankeromnes** [comment] 2020-01-23 09:05
FYI this specific problem is now tracked in #1128. We're currently able to fix this intermittent problem within 30 minutes whenever it appears, and we're working toward fixing the root cause to prevent it from happening again.
