### ISSUE TITLE
404 on workspace start, but the container is running

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#2300] opened 2020-11-26 14:31 UTC
On redirect to the workspace I ended up here:

<img width="1236" alt="Screen Shot 2020-11-26 at 15 06 16 copy" src="https://user-images.githubusercontent.com/914497/100362629-f645d300-2ffb-11eb-91ef-1e5568e09eb3.png">

Browser's history shows I ended up here via https://e7ef1956-87ad-4001-918b-0ee9e0c729a7.ws-eu02.gitpod-staging.com/ which seems to be a regular start URL

/cc. @akosyakov

**Comment by csweichel** [comment] 2020-11-26 14:49
duplicate of https://github.com/gitpod-io/gitpod/issues/2299

**Closed** 2020-11-26 14:50 UTC
Labels: bug, staging
