### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by davidar** [gitpod-io/gitpod#3833] opened 2021-04-08 05:27 UTC
### Bug description

VSCode is giving me various "command not found" errors when trying to perform some actions.

### Steps to reproduce

e.g. click the "add to .gitpod.yml" menu item on an extension

### Expected behavior

The actions would complete without error.

### Example repository

I'm not sure what is causing this bug, but it didn't occur with Theia.

![image](https://user-images.githubusercontent.com/24291/113972956-e332f180-987e-11eb-8a42-9b71bae75bf4.png)

**Comment by akosyakov** [comment] 2021-04-08 05:49
Could you share the workspace id please?

**Comment by davidar** [comment] 2021-04-08 10:08
`amethyst-tapir-5ya1y52x`

**Comment by akosyakov** [comment] 2021-04-08 11:37
From logs it looks like duplicate of https://github.com/gitpod-io/gitpod/issues/3797

**Closed by akosyakov** 2021-04-08 11:37 UTC
Labels: editor: code, type: bug
