### ISSUE TITLE
User restriction configuration does not take effect

### ISSUE THREAD

**Issue by HuaxingL** [gitpod-io/gitpod#12757] opened 2022-09-08 08:25 UTC
### Bug description

After setting the email address on the KOTS configuration page, it can still register the gitpod instance as another email address

### Steps to reproduce

1.Set the email address on the KOTS configuration page and save it, the example is as follows：
![image](https://user-images.githubusercontent.com/111476113/189072809-5c42f2b9-aec0-4f3b-9f8c-200e3bb91894.png)
2.Sign in with a different email address：
![image](https://user-images.githubusercontent.com/111476113/189073216-91aa422a-c6db-4c10-a347-29edde793be7.png)

**Comment by MrSimonEmms** [comment] 2022-09-08 10:05
This is a duplicate of #12738

**Closed** 2022-09-08 10:10 UTC
Labels: type: bug, team: webapp, team: self-hosted
