### ISSUE TITLE
Don't Open GitBucket

### ISSUE THREAD

**Issue by kumimaru** [gitpod-io/gitpod#1204] opened 2020-02-08 04:01 UTC

**Comment by JesterOrNot** [comment] 2020-02-08 15:43
Can you explain your issue?

**Comment by svenefftinge** [comment] 2020-02-09 19:21
I assume this is about BitBucket support. So closing it as dupe of https://github.com/gitpod-io/gitpod/issues/626

**Closed by svenefftinge** 2020-02-09 19:21 UTC
