### ISSUE TITLE
Error 403 for served app

### ISSUE THREAD

**Issue by jibe-b** [gitpod-io/gitpod#2057] opened 2020-10-25 13:49 UTC
The exposed port of my node app returns sometimes a 403 error.

https://9000-********-*****-****-****-************.ws-eu01.gitpod.io/

![Screenshot from 2020-10-25 14-47-24](https://user-images.githubusercontent.com/6146483/97108965-0c950200-16d1-11eb-924e-45fc99536dc7.png)

**Comment by jibe-b** [comment] 2020-10-25 13:52
Thankfully it only lasts less than 5 minutes. It is nonetheless annoying when paying a monthly rate.

**Comment by corneliusludmann** [comment] 2020-10-26 09:21
Hi @jibe-b,

With that little information, it is difficult to say what could be the cause. Is it reproducible? Could you provide an [example repo](https://stackoverflow.com/help/minimal-reproducible-example) or at least which process serves the app at port 9000?

**Comment by jibe-b** [comment] 2020-10-26 12:48
The app served is a node app, serving gatsby (static site generator).

The issue came erratically so no, I don't know how to reproduce it either.

In case it happens again I will update this issue, hopefully providing more information.

**Comment by corneliusludmann** [comment] 2020-10-26 13:26
Thanks for the feedback. I'll close this issue for now. Feel free to re-open it if you have more information. :+1:

**Closed by corneliusludmann** 2020-10-26 13:26 UTC
Labels: reporter-feedback-needed
