### ISSUE TITLE
Clone of repository fails

### ISSUE THREAD

**Issue by ascheman** [gitpod-io/gitpod#111] opened 2018-10-22 11:43 UTC
**Describe the bug**
When opening a new repo (https://github.com/dukecon/dukecon_server) with gitpod, I get the following error:  `An error occurred during 'git clone', the repository or branch could not be accessed.`

**To Reproduce**
Call `https://gitpod.io/#https://github.com/dukecon/dukecon_server`. This is my first try ever with gitpod. On first time I was even asked to give some permissions to gitpod. The DukeCon-Org was not authorized from the beginning, but I pressed the "grant"-Button during the authorization dialogue. However, nothing happened, so probably some permissions are missing?

**Expected behavior**
What ever gitpod does usually: Start an IDE + POD and enable to work on the desired repository ...

**Comment by ascheman** [comment] 2018-10-22 11:54
Sometimes I the message `We have trouble parsing your context
Error: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
Please file an issue if you think this is a bug.`  on subsequent tries to open the repo.

**Comment by ascheman** [comment] 2018-10-22 11:57
Like `We have trouble parsing your context
Error: Unauthorized
Please file an issue if you think this is a bug.`

**Comment by ascheman** [comment] 2018-10-22 11:59
Sometimes I see some messages, e.g.,
- starting ...
- pulling docker images ...
- starting (5/5)

Then it fails.

**Comment by AlexTugarev** [comment] 2018-10-22 12:01
@aschemann, I'm afraid this is caused by service unavailability of GitHub, see [status](https://status.github.com/messages).

**Comment by svenefftinge** [comment] 2018-10-24 16:42
Closing this as github is back to normal. Please reopen if you still see this.

**Closed by svenefftinge** 2018-10-24 16:42 UTC
