### ISSUE TITLE
GitHub OAuth needs `workflows` scope

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#1188] opened 2020-02-05 14:46 UTC
If you try to update a GitHub actions / CI workflow file in Gitpod, you can't push it:
```bash
! [remote rejected]   master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/ci.yml` without `workflow` scope)
error: failed to push some refs to 'sensoredRepoName'
```

**Comment by JesterOrNot** [comment] 2020-02-05 14:47
Duplicate of #984

**Closed by JesterOrNot** 2020-02-05 14:47 UTC
