### ISSUE TITLE
Unable to start workspace. Stuck at stopping.

### ISSUE THREAD

**Issue by pybern** [gitpod-io/gitpod#12938] opened 2022-09-14 03:14 UTC
### Bug description

Attempts to start a workspace goes from preparing to stopping and gets stuck there. The workspace was last used a couple of hours ago.

### Steps to reproduce

Open workspace.

### Workspace affected

https://pybern-dream-ujgolxy8don.ws-us64.gitpod.io/

**Comment by pybern** [comment] 2022-09-14 04:57
#12939 linking similar issue

**Comment by axonasif** [comment] 2022-09-14 07:11
Hey @pybern, you can raise a ticket via https://www.gitpod.io/contact/support regarding your workspace issue.

**Comment by axonasif** [comment] 2022-09-14 07:13
Related: https://github.com/gitpod-io/gitpod/issues/12908

**Comment by geropl** [comment] 2022-09-15 08:19
@kylos101 I think there are two or three parts in here:
 1. Why can't the workspace start properly?
 2. Why does bridge receive updates for `stopping`, but never sees any `stopped` state?
 3. Why does bridge not clean those cases up, eventually? (being worked on in #12902 )

Regarding:
 1. Sounds like an effect of https://github.com/gitpod-io/gitpod/issues/12908. D'accord?
 2. Is Team Workspace looking into this? We could help with providing traces for a single workspaces as an example :thinking: Or: Did this happen because we de-registered the cluster before all workspaces were in `stopped` case? Then we started working on it already (#6770).

**Comment by geropl** [comment] 2022-09-26 07:55
I assume this is a dupe of #12902 and #6770 right now. Will close this as those have already been scheduled.

**Closed by geropl** 2022-09-26 07:55 UTC
Labels: type: bug, :question: clarification required
