### ISSUE TITLE
Request startWorkspace failed with message: 13 INTERNAL: cannot resolve workspace image: hostname required

### ISSUE THREAD

**Issue by vkton115** [gitpod-io/gitpod#7345] opened 2021-12-22 08:25 UTC
### Bug description

getting this error message. unable to open my workspace
Request startWorkspace failed with message: 13 INTERNAL: cannot resolve workspace image: hostname required

happened during class and constant refreshing eventually got it to work. but now i'm trying to work on homework outside of classtime and it keeps failing.

### Steps to reproduce

> log in
> go to workspaces
> attempt to open workspace

**Comment by axonasif** [comment] 2021-12-22 08:34
This is an ongoing issue, please keep an eye on https://www.gitpodstatus.com/incidents/g0kjpr3lbvbw

All we can do is wait patiently and stay calm 😀

**Comment by alexadark** [comment] 2021-12-23 12:12
It says the issue is solved, but for me, it is stills happening...

**Comment by axonasif** [comment] 2021-12-23 12:32
> It says the issue is solved, but for me, it is stills happening...

The gitpod team is aware.
You can subscribe to https://www.gitpodstatus.com/incidents/4f25shfbb632/ for updates

**Comment by kylos101** [comment] 2021-12-23 21:20
Hi @alexadark are you still having trouble? I assume no, but, wanted to double check before closing the issue. Let us know?

**Comment by alexadark** [comment] 2021-12-24 08:45
@kylos101 yes thanks, all is fine now

**Closed** 2021-12-24 13:02 UTC
