### ISSUE TITLE
Sometimes users are not routed to their workspace on start, remaining on the dashboard / parsing context

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#14061] opened 2022-10-20 21:53 UTC
### Bug description

As a user, when this happens, I remain on the context URL, like https://gitpod.io/#https://github.com/openfaas/faas-cli/pull/902, but never land on the workspace cluster at https://kylos101-faascli-qptn5bvl7k9.ws-us72.gitpod.io/. A way to remedy, is to hit F5, at which point a pop-up shows me my workspace name, which I can then click, and then I land on the workspace cluster.

### Steps to reproduce

Try making many workspaces (usually manifests itself in 6-8 attempts). If you're unable to recreate from the EU, hop onto a US VPN and try again

### Workspace affected

kylos101-faascli-qptn5bvl7k9

### Expected behavior

I should rather quickly (usually less than 3-5 seconds, a long time would be ~10 seconds) be routed to the workspace cluster, where I can see preparing workspace, allocating resources, pulling images, etc.

### Example repository

Really, it should manifest (eventually) with any

### Anything else?

We have traces enabled at 100% for workspace clusters. However, to diagnose this end-to-end, we may need to enable tracing 100% at webapp (at least temporarily).

**Comment by kylos101** [comment] 2022-10-25 05:15
@geropl is this something you could schedule for an upcoming week? It feels like to effectively troubleshoot this, we might need to enable tracing for Honeycomb 100% in the application cluster...at least for a short time period.

**Comment by geropl** [comment] 2022-10-25 06:16
@kylos101  scheduled it, and we should investigate and see if we can find a workaround, maybe registering listeners early. But as mentioned in sync this stems from the fact that the `StartWorkspace` timing and contract changed.

**Comment by kylos101** [comment] 2022-10-27 00:21
:wave: @geropl two questions to help myself remember, and others get context:
1. When you say timing, are you referring to how slow node scale-up may magnify this issue?
2. Can you share an example of what you mean by contract changed?

**Comment by kylos101** [comment] 2022-10-27 00:22
@geropl house keeping question - I see the status is no longer scheduled, and now there's two  extra fields: area=workspace and week=week 44 (next week). Cool! What does it mean to not have a status?

**Comment by svenefftinge** [comment] 2022-11-08 07:19
see also #13070

**Comment by svenefftinge** [comment] 2022-11-08 07:21
I think we should fix this by making `StartWorkspace` in ws-manager return as early as possible and then use the status updates to report any problems or state changes going forward. Is that something team workspace could do?

**Comment by geropl** [comment] 2022-11-08 08:29
> I think we should fix this by making StartWorkspace in ws-manager return as early as possible and then use the status updates to report any problems or state changes going forward

Yes, that's the long-term goal.

> Is that something team workspace could do?

We've discussed this for quite some time now. @svenefftinge In the context of this issue instead of waiting for Team Workspace, I'd rather try if we can remove some of our assumptions in the dashboard. E.g., we could quickly check if listening on instance updates/polling for workspace instance _before_ `startWorkspace` returns helps here. If yes, that'd be an acceptable short-term fix here.

**Comment by akosyakov** [comment] 2022-11-09 11:51
We tried to explore an idea here: https://github.com/gitpod-io/gitpod/pull/14547 by introducing artificial timeouts in ws-manager. It does not seem that listening to events help if there is an PVC since they are created before the pod. It does help if there are issues after creation of the pod. 

I'm not sure how to verify the change. One idea is to have a look at percentiles of createWorkspace call on server and whether it improves [[1](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22histogram_quantile%280.9,%20sum%28rate%28gitpod_server_api_calls_duration_seconds_bucket%7Bmethod%3D%5C%22createWorkspace%5C%22,%20cluster%3D%5C%22prod-meta-eu02%5C%22%7D%5B5m%5D%29%29%20by%20%28le%29%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D)]. Another is to add analytic event to track duration of `createWorkspace` from the dashboard it could allow us to narrow down the analysis to Gitpod team.

See also internal thread [[1](https://gitpod.slack.com/archives/C0201TXMV54/p1667900318570049)]

**Comment by svenefftinge** [comment] 2022-11-14 11:23
I think we all agree that ultimately ws-manager should return immediately. As this seem to be hard with the current design and there are ideas of a new version of that would solve it, I'm trying to make "as small as possible" intermediate fix to the UX part of the problem.

**Comment by svenefftinge** [comment] 2022-11-15 15:27
The PR is merged and deployed. I couldn't reproduce the described issue and can also verify from [the logs](https://cloudlogging.app.goo.gl/znDAbMmsnb51jtMA8) that the change has an effect.

**Closed by svenefftinge** 2022-11-15 15:27 UTC
Labels: type: bug, :question: clarification required
