### ISSUE TITLE
Error 504

### ISSUE THREAD

**Issue by Peristratus** [gitpod-io/gitpod#3516] opened 2021-03-20 03:17 UTC
### Bug description

Cannot log in to github of gitpod 

### Steps to reproduce

Access gitpod.io click on login with github get a 504 error message with a sad face

**Comment by jankeromnes** [comment] 2021-03-22 09:23
Thanks for reporting this incident! Duplicate of https://github.com/gitpod-io/gitpod/issues/3515

**Closed by jankeromnes** 2021-03-22 09:23 UTC
