### ISSUE TITLE
Error: Not connected to message bus

### ISSUE THREAD

**Issue by leonbagdag** [gitpod-io/gitpod#1112] opened 2020-01-18 13:30 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by gleehokie** [comment] 2020-01-18 14:11
I'm seeing the same:

Request startWorkspace failed with message: Not connected to message bus

**Comment by MichaelDHarris** [comment] 2020-01-18 15:26
@jankeromnes @JesterOrNot

**Comment by JesterOrNot** [comment] 2020-01-18 15:31
Can you send some debugging information from dev-tools console?

**Comment by MichaelDHarris** [comment] 2020-01-18 15:34
@JesterOrNot We can't open the workspace to get to the dev-tool console. Everything stops at the loading page with an error message and turns the gitpod logo red.

**Comment by JesterOrNot** [comment] 2020-01-18 15:39
I was able to reproduce the issue
![image](https://user-images.githubusercontent.com/50386709/72666268-1ec17180-39d6-11ea-9c02-1ab8ee2da0bb.png)

**Comment by MichaelDHarris** [comment] 2020-01-18 15:41
@JesterOrNot this is the exact issue

**Comment by JesterOrNot** [comment] 2020-01-18 15:45
Contacting team now!

**Comment by jankeromnes** [comment] 2020-01-18 16:51
Thank you for reporting this. Duplicate of #1110 and should work again.

**Closed by jankeromnes** 2020-01-18 16:51 UTC

**Comment by MichaelDHarris** [comment] 2020-01-18 18:17
Confirmation that the issue is resolved. Thank you.

**Comment by oswaldojerezz** [comment] 2021-03-23 15:01
![image](https://user-images.githubusercontent.com/48268734/112167777-59183700-8bb6-11eb-906e-01f60bc88d9c.png)
This issue is still up

**Comment by literal-line** [comment] 2021-03-23 15:08
I'm having the same issue too

**Comment by delucca** [comment] 2021-03-23 15:11
It looks like Gitpod crashed :(

**Comment by AlessioToniolo** [comment] 2021-03-23 23:01
Yeah I have the same issue, and I thought that it was a free trial/overused hours on gitpod.
