### ISSUE TITLE
When i go to Online IDE then open in new tab. i signed up with GitHub. but it is showing that "Sorry, something went wrong 😓 Authorization failed. Please try again."

### ISSUE THREAD

**Issue by MaitriManiya** [gitpod-io/gitpod#2828] opened 2021-01-11 14:18 UTC

**Comment by jankeromnes** [comment] 2021-01-11 16:22
Hi @MaitriManiya! I assume that you may also have a GitLab identity associated to your Gitpod account.

In that case, please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

Closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by jankeromnes** 2021-01-11 16:22 UTC
