### ISSUE TITLE
Epic: As a Self Hosted User, I would like to be able to force our devs to use the IDE that I specify

### ISSUE THREAD

**Issue by AndyDevman** [gitpod-io/gitpod#11073] opened 2022-07-01 09:30 UTC
## Background

Currently, when a user first accesses a workspace in Gitpod, they are prompted to chose an IDE to use.
The option to select which IDE to use is also subsequently available to users within the Gitpod UI under preferences.
![image](https://user-images.githubusercontent.com/46032005/176867084-dd6c4b16-50c5-47c7-aa7b-7fe7820ec20a.png)

## Desired Behaviour

For self hosted Gitpod users, I'd like to be able to switch off the prompt to choose an IDE and also remove the preferences option for users.   Ultimately I would like to be able to force users to use the IDE that I specify.  

## Proposal

Implement a configuration option to enable this within the config.go, so that self hosted users can have the option to disable IDE choice for their users and force them to use the IDE which has been administratively configured.

**Comment by corneliusludmann** [comment] 2022-07-01 10:12
Related / duplicate of https://github.com/gitpod-io/gitpod/issues/6731

**Comment by loujaybee** [comment] 2022-09-01 18:30
[Quote from the community](https://discord.com/channels/816244985187008514/1014887108835553342/1014944090825166923)

> We're considering the idea of limiting the list of available IDEs to users to just be VSCode, this is due to external limitations on our end with the others. Is this at all possible in the installer config? Whether that be to disable its use upon workspace startup or remove the others from the list entirely in their preferences.

**Comment by loujaybee** [comment] 2023-04-20 12:16
This does look like a duplicate of: https://github.com/gitpod-io/gitpod/issues/6731

I'll close this one, please track on that issue ! 🙏

**Closed by loujaybee** 2023-04-20 12:16 UTC
Labels: self-hosted, editor: code (browser), team: IDE, editor: jetbrains, editor: code (desktop), type: epic, feature: policy
