### ISSUE TITLE
can't start workspace

### ISSUE THREAD

**Issue by brandonkal** [gitpod-io/gitpod#1109] opened 2020-01-18 07:42 UTC
Request startWorkspace failed with message: Not connected to message bus
Please file an issue if you think this is a bug.

**Comment by svenefftinge** [comment] 2020-01-21 15:46
Thanks for reaching out. It is a duplicate of https://github.com/gitpod-io/gitpod/issues/1104 and has been resolved.

**Closed by svenefftinge** 2020-01-21 15:46 UTC
