### ISSUE TITLE
Can't add new subscription

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#695] opened 2019-07-25 16:44 UTC
**Describe the bug**
I'm trying to add a new person to my team (subscription) but it says "Gitpod User Not Found"

Normally this happens when they have not completed the GitHub integration entirely but in this case, we tried everything.

**To Reproduce**
![2019-07-25 12 42 34](https://user-images.githubusercontent.com/426452/61892437-c81d2400-aed9-11e9-882a-bdb6c274e27e.gif)

**Expected behavior**
A success message and have the user added.

**Comment by jankeromnes** [comment] 2019-07-25 17:29
Ah, I think I know what the bug is... could you please try without the `https://` prefix?

Sorry, this is silly, I'll try to improve the UX by accepting various common formats here.

**Comment by alesanchezr** [comment] 2019-07-25 19:26
I tried both ways before reporting it. It's something different. 🤔

**Comment by alesanchezr** [comment] 2019-07-25 19:28
![2019-07-25 15 28 01](https://user-images.githubusercontent.com/426452/61902771-d4f94200-aef0-11e9-946d-8295ae2c2db6.gif)

**Comment by jankeromnes** [comment] 2019-07-25 20:03
Oh, then it's indeed a different bug. I'm so sorry about that.

We're looking into it, and will try to fix it as fast as possible, but it may take until tomorrow because most of the team is currently offline.

**Comment by jankeromnes** [comment] 2019-07-26 06:32
Hi again @alesanchezr, we have found the root cause of this bug (thanks @AlexTugarev!)

It seems that @JonathanePerez renamed their GitHub account since joining Gitpod, and it turns out that Gitpod doesn't handle such renames yet (it handles other changes like primary email, but not account name). Sorry about that, and thanks a lot for uncovering this bug!

We'll fix it, but meanwhile, please try inviting @JonathanePerez using their original account name if you have it.

**Comment by alesanchezr** [comment] 2019-07-26 15:35
Ok we'll do, thanks!

**Comment by alesanchezr** [comment] 2019-07-26 16:05
It worked, thanks!

**Comment by jankeromnes** [comment] 2019-07-26 16:21
Great news! Thanks for the update, and sorry again about the trouble.

Also, the bug had been fixed in `master` (thanks @alextugarev and @geropl!) and will be deployed next Wednesday if all goes well -- with a few other surprises that we hope you're going to like. :)

**Closed** 2019-07-31 10:12 UTC
Labels: bug
