### ISSUE TITLE
gitpod workspace auth issue

### ISSUE THREAD

**Issue by konne** [gitpod-io/gitpod#8631] opened 2022-03-07 09:33 UTC
### Bug description

This morning I started a new workspace and just had a weird behavior. 
In the command line, it asked me for my GitHub username and password and
in one of my init scripts, it failed to update a gitpod Variable see error message.

![Bildschirmfoto 2022-03-07 um 10 25 55](https://user-images.githubusercontent.com/1100969/157004676-cd45cb1b-bdc5-4009-a276-ad31a133b6c2.png)

It only happened once. I started another workspace from a different branch and it just worked

### Steps to reproduce

see bug desc

### Workspace affected

vizlib-gucci-irlaw4t8ggf.ws-eu34xl

**Comment by mustard-mh** [comment] 2022-03-07 19:11
This maybe eu <-> us cluster db-sync problem

**Comment by konne** [comment] 2022-03-17 10:05
@mustard-mh 
I got now the message from my developers that this happens multiple times since yesterday 
It happens than it tries to save a ENV Variable with the gp cli

![image](https://user-images.githubusercontent.com/1100969/158785887-6529015b-161b-4388-b0a0-1ca627635087.png)

**Comment by geropl** [comment] 2022-04-05 08:50
I think this is a symptom of the same issue: https://github.com/gitpod-io/gitpod/issues/8703

**Comment by geropl** [comment] 2022-04-05 12:41
After investigating with @AlexTugarev we're quite confident that we identified the route cause, and that this issue is a dupe of #8703. Closing this in favor of that issue.

@konne If you feel we're missing out an aspect please feel free to re-open with additional context! :pray:

**Closed by geropl** 2022-04-05 12:41 UTC
Labels: type: bug, team: webapp
