### ISSUE TITLE
Authorization failed. Please try again. This is what displayed when i tried to open the workspace and logged in with gitlab

### ISSUE THREAD

**Issue by Varunkalra18** [gitpod-io/gitpod#2959] opened 2021-01-18 10:30 UTC

**Comment by geropl** [comment] 2021-01-18 12:21
Hi @Varunkalra18 ,

that sounds bad. Could you elaborate on how you got there?

 - Are you a long time user/fresh user?
 - Are you using Gitpod the first time within days/weeks, or is it just another workspace?
 - Did it happen on other workspaces, too?
 - What happened when you tried to open it again?

**Comment by csweichel** [comment] 2021-01-19 06:24
sounds like a duplicate of #2818

**Closed** 2021-01-19 09:13 UTC
Labels: meta: :thinking: reporter-feedback-needed
