### ISSUE TITLE
Bitbucket access broken

### ISSUE THREAD

**Issue by AniX** [gitpod-io/gitpod#2437] opened 2020-12-06 23:38 UTC
### Describe the bug
I can't access Bitbucket repository anymore in existing or new workspaces. It sounds like it is a duplicate of https://github.com/gitpod-io/gitpod/issues/2420 That ticket is closed, but I don't understand the resolution. It still doesn't work for me.

I've tried to resolve by removing and restoring the access again by myself, but without success.

### Steps to reproduce
1. Create a new workspace by using e.g. `gitpod.io/#https://bitbucket.org/myproject/myrepo`. Will show error `We are having trouble parsing your context - Error: Unauthorized`
2.Alternatively, open existing worksapce, select `Pull` gives error `Request pull failed with message: Authentication failed. You may not have permission to access the repository or the repository may have been archived.`

### Expected behavior
I should be able to create new workspaces and/or pull/push to the repos as usual. If auth is expired, I should be prompted for fresh Bitbucket auth, but it doesn't happen.

### Additional information
I have revoked Gitpod from _Bitbucket app authorizations_ page in my Bitbucket settings. But Bitbucket still shows under _Gitpod > Access Control_ with all checkboxes turned on. I can't disable any of these Bitbucket permissions on the page neither (I never could though). I'm also not prompted at startup of workspace to refresh auth again.

(Note: Bitbucket auth was always quite short-lived and I had to refresh auth again quite frequently, but nothing works anymore this time)

https://d00364a3-8b07-4a78-919f-14027fbbc1ca.ws-eu03.gitpod.io/

### Example repository
Affects all of our private Bitbucket repos.

**Comment by AniX** [comment] 2020-12-07 01:15
OK, the solution was much easier ... I just signed out from Gitpod and logged back in using the Bitbucket account. After that the _existing_ workspaces seem to work fine again.

However, I still can't create a new workspace with e.g. `gitpod.io/#https://bitbucket.org/myproject/myrepo/src/master/`

> cannot initialize workspace: cannot initialize workspace: exit status 42
> Please file an issue if you think this is a bug.

**Comment by svenefftinge** [comment] 2020-12-07 05:56
The fix will be deployed this morning.

**Comment by svenefftinge** [comment] 2020-12-07 06:03
see also https://github.com/gitpod-io/gitpod/issues/2420

**Comment by svenefftinge** [comment] 2020-12-07 08:34
duplicate of #2420

**Closed by svenefftinge** 2020-12-07 08:34 UTC
Labels: bug, critical

**Comment by AlexTugarev** [comment] 2020-12-07 09:18
@AniX, fyi we've just deployed the fix.

**Comment by AniX** [comment] 2020-12-07 14:17
I want to confirm that all my issues are resolved. Many thanks!
