### ISSUE TITLE
Workspace of crio is not opening

### ISSUE THREAD

**Issue by Pavan-Kumar122** [gitpod-io/gitpod#2730] opened 2021-01-09 17:51 UTC
Sorry, something went wrong 😓
Authorization failed. Please try again.

**Comment by akosyakov** [comment] 2021-01-10 06:21
Please go to gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of https://github.com/gitpod-io/gitpod/issues/2746 Please reopen if you did not try to login with GitLab account.

**Closed by akosyakov** 2021-01-10 06:21 UTC
