### ISSUE TITLE
Workspace loads as white screen

### ISSUE THREAD

**Issue by patheard** [gitpod-io/gitpod#3124] opened 2021-02-06 03:07 UTC
### Describe the bug
Since the service impacting bug on Feb 4th, I cannot load any workspaces (new or existing).  Starting them from the dashboard or `https://gitpod.io#<repo_url>` causes them to go through the workspace building steps, but then I get a white screen.

Also odd, the white screen workspace URL never refreshes with the `/workspaces/<workspace-name>` URL segment that you get on a properly loaded workspace.

### Steps to reproduce
1. Attempt to start workspace from dashboard or `https://gitpod.io#<repo_url>`.
2. Workspace goes through 3 loading steps, but then a white screen appears.

### Expected behavior
Workspace starts and loads into code editor.

### Additional information
* I tested with a new GitHub account and the new workspace (`fuchsia-sheep-0j4wxnha`) loaded as expected for the new account.
* I'm seeing this behaviour in latest Chrome or Edge, with existing login or fresh login in incognito windows.
* Console log from white screen workspace `turquoise-urial-jsntm0j2`:
```js
start-workspace.js:105 /start: started workspace instance: bca00071-7230-4792-929d-d1d497900c86

/manifest.json:1 Manifest: property 'start_url' ignored, should be same origin as document.

/_supervisor/v1/status/supervisor:1 Failed to load resource: the server responded with a status of 502 ()

workbench.web.api.js:19062 Uncaught (in promise) Error: [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character
    at _validateUri (workbench.web.api.js:19062)
    at new URI (workbench.web.api.js:19142)
    at new Uri (workbench.web.api.js:19356)
    at Uri.with (workbench.web.api.js:19235)
    at Function.joinPath (workbench.web.api.js:19316)
    at ExtUri.joinPath (workbench.web.api.js:25715)
    at BrowserMain.getRemoteUserDataUri (workbench.web.api.js:334951)
    at BrowserMain.registerFileSystemProviders (workbench.web.api.js:334899)
    at BrowserMain.initServices (workbench.web.api.js:334831)
    at async BrowserMain.open (workbench.web.api.js:334743)
```

### Example repository
https://github.com/patheard/cucumber-puppeteer

**Comment by taylorcoffelt** [comment] 2021-02-06 04:04
I am also experiencing this issue

**Comment by mikents** [comment] 2021-02-06 04:23
+1. Can't start any workspace, new or existing.

**Comment by akosyakov** [comment] 2021-02-06 12:53
A duplicate of https://github.com/gitpod-io/gitpod/issues/3114

**Closed by akosyakov** 2021-02-06 12:53 UTC
