### ISSUE TITLE
Cannot create new project on self-hosted September RC build

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13395] opened 2022-09-28 08:13 UTC
Self-hosted RC builds have been deployed and cofigured to authenticate against GitHub.
This means that users should be able to create projects with GitHub repositories.
Trying to create a new project results in a spinner, which never stops.

#### To reproduce

- Log in to a SH test deployment (see [notion](https://www.notion.so/gitpod/Self-Hosted-Release-2022-09-0-0534b6ba181b476cb1826e358a7149f9#60d436b917f3403da062a88301c31837) internal)
- Click on your personal account context at the top left
- Click on new project

<img width="1110" alt="Screenshot 2022-09-28 at 10 09 03" src="https://user-images.githubusercontent.com/849592/192725879-fef2a4f6-5318-4a19-a434-5da78865dadb.png">

**Comment by jankeromnes** [comment] 2022-09-28 08:20
Thanks! I was able to reproduce this.

Opening the browser console, I see this error:

```
Error: Request getProviderRepositoriesForUser failed with message: UnauthorizedError
```

(However, I also see that the "New Workspace" modal is able to fetch repositories -- you can try this yourself by hitting Cmd+O from anywhere in the dashboard.)

**Comment by jankeromnes** [comment] 2022-09-28 08:25
Going into `/integrations`, I see that my GitHub token has zero permissions. Also, trying to grant permissions fails (modal closes again, there is no visible error but also no permissions are added).

| No permissions | Cannot grant any permissions |
| --- | --- |
| <img width="1438" alt="Screenshot 2022-09-28 at 10 23 31" src="https://user-images.githubusercontent.com/599268/192728447-e32fa18d-b601-4ca6-aee2-b9148662e32b.png"> | <img width="527" alt="Screenshot 2022-09-28 at 10 22 24" src="https://user-images.githubusercontent.com/599268/192728469-c1435be3-be82-4473-afa7-833d78cbba37.png"> |

**Comment by jankeromnes** [comment] 2022-09-28 09:37
I believe this might be a problem in how the GitHub integration was configured for this Self-Hosted installation, because it doesn't seem to have an OAuth App. [Context](https://gitpod.slack.com/archives/C02EN94AEPL/p1664356086871249?thread_ts=1664308949.936319&cid=C02EN94AEPL) (internal)

**Comment by andrew-farries** [comment] 2022-09-30 07:31
I can confirm that I am able to create a new project on the newly configured AKS SH test installation.

Closing this as a configuration error with the previous test environment.

**Closed by andrew-farries** 2022-09-30 07:31 UTC
Labels: self-hosted, team: webapp
