### ISSUE TITLE
[observability] create an alert when file descriptors exhausted

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#12935] opened 2022-09-14 02:04 UTC
## Is your feature request related to a problem? Please describe

create an alert when file descriptors exhausted

## Describe the behaviour you'd like

Having an alert when the number of file descriptors exhausted

## Describe alternatives you've considered

None

## Additional context

https://gitpod.slack.com/archives/C04245JPHKL/p1663083593170859

**Comment by jenting** [comment] 2022-09-16 06:25
I tried different views of the metrics `process_open_fds`, to send the alerts as soon as possible.

![image](https://user-images.githubusercontent.com/49380831/190570248-b924ad51-cb5d-4311-ab98-625b6c560c48.png)

However, view with the sum of `process_open_fds`, at 09/13 05:30 UTC, the value is still slow.

We could consider sending alerts if the sum of `process_open_fd` over 3,000,000, but it indicates that the alert will be sent out after 09/13 10:00 UTC. But I think it's too late to send the alert out.

![image](https://user-images.githubusercontent.com/49380831/190570733-7663c0ae-eb63-4ae8-9e8f-a0f19a17ce25.png)

Any suggestion to make the alerts send out as soon as possible? @kylos101

**Comment by kylos101** [comment] 2022-09-19 05:00
@jenting can you share the query you found most promising?

**Comment by kylos101** [comment] 2022-09-21 01:13
:wave: hey @jenting , have you tried an alert like this? https://www.robustperception.io/alerting-on-approaching-open-file-limits/

**Comment by kylos101** [comment] 2022-09-21 01:31
Hey @jenting , I recommend trying to write an alert that is node or workspace based, rather than cluster based.

**Comment by jenting** [comment] 2022-09-22 05:26
For the node-based metric `node_filefd_allocated`, the [grafana query](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22H%22,%22editorMode%22:%22code%22,%22expr%22:%22node_filefd_allocated%7Bcluster%3D%5C%22us64%5C%22%7D%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D,%7B%22refId%22:%22B%22,%22editorMode%22:%22code%22,%22expr%22:%22node_filefd_allocated%7Bcluster%3D%5C%22eu64%5C%22%7D%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221662681600000%22,%22to%22:%221663891199000%22%7D%7D). 

If we write an alert that is node-based, and the alert criteria is the current file descriptors / total file descriptors, we can see that the current file descriptors is far far away to total file descriptors. The [grafana query](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22H%22,%22editorMode%22:%22code%22,%22expr%22:%22node_filefd_allocated%7Bcluster%3D%5C%22us64%5C%22%7D%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D,%7B%22refId%22:%22B%22,%22editorMode%22:%22code%22,%22expr%22:%22node_filefd_allocated%7Bcluster%3D%5C%22eu64%5C%22%7D%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D,%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22node_filefd_maximum%7Bcluster%3D%5C%22us64%5C%22%7D%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D,%7B%22refId%22:%22C%22,%22editorMode%22:%22code%22,%22expr%22:%22node_filefd_maximum%7Bcluster%3D%5C%22eu64%5C%22%7D%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221662681600000%22,%22to%22:%221663891199000%22%7D%7D).

Therefore, we can't use the criteria `node_filefd_allocated{cluster="<cluster-name>"}/node_filefd_maximum{cluster="<cluster-name>"}` as the alert rule.

**Comment by kylos101** [comment] 2022-10-05 04:54
@jenting I recommend handing this off to @utam0k , as he is on-call this week, to see if he can finish.

@utam0k perhaps you could look later this week?

**Comment by utam0k** [comment] 2022-10-14 08:36
@jenting This incident was caused by ws-manager with PVC after all, right? So I don't think the alert really needs to be issued until just before the fd of the node is depleted, which is about 80% of the time. What do you think?

**Comment by jenting** [comment] 2022-10-14 08:38
> This incident was caused by ws-manager with PVC after all, right? So I don't think the alert really needs to be issued until just before the fd of the node is depleted, which is about 80% of the time. What do you think?

I agree with you. We could put the threshold 80% and I did check our overall fd usage, we are far away from 80%. (If I remember correctly, the fd usage is under 10%).

**Comment by utam0k** [comment] 2022-10-14 08:40
The problem with the fd of the supervisor should have been a side issue and not the root cause.

**Comment by jenting** [comment] 2022-10-14 08:48
> The problem with the fd of the supervisor should have been a side issue and not the root cause.

Yes, I think the ws-manager failed to handle any pod event.
It caused all related components which would interact with the ws-manager might be impacted. For example, the component does not handle the connection between the ws-manager correctly.

**Comment by kylos101** [comment] 2022-10-14 21:47
@utam0k if we no longer need an alert, please close this issue as not planned?

@jenting is there a separate issue that needs to be created to solve `s-manager failed to handle any pod event.`? If yes, can you share if this is related to PVC or in general? I ask to limit scope, so we can focus on closing this issue (either by creating an alert or losing this because we don't need an alert, and making a separate issue to track if needed).

**Comment by kylos101** [comment] 2022-10-17 21:34
@utam0k if we no longer need an alert, please close this issue as not planned?

**Comment by kylos101** [comment] 2022-10-17 21:34
@jenting is there a separate issue that needs to be created to solve s-manager failed to handle any pod event.? If yes, can you share if this is related to PVC or in general? I ask to limit scope, so we can focus on closing this issue (either by creating an alert or losing this because we don't need an alert, and making a separate issue to track if needed).

**Comment by jenting** [comment] 2022-10-17 23:19
> @jenting is there a separate issue that needs to be created to solve s-manager failed to handle any pod event.? If yes, can you share if this is related to PVC or in general? I ask to limit scope, so we can focus on closing this issue (either by creating an alert or losing this because we don't need an alert, and making a separate issue to track if needed).

No, we don't need to create a new issue to solve ws-manager failed to handle any pod event.

Let's link to the culprit issue #13007 and close this one.

**Comment by kylos101** [comment] 2022-10-18 02:32
Okay, thanks! I will close this issue as won't fix.

**Closed by kylos101** 2022-10-18 02:32 UTC
Labels: team: workspace

**Comment by utam0k** [comment] 2022-10-18 05:30
Thanks a lot @jenting and @kylos101
