### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by sql1610** [gitpod-io/gitpod#1111] opened 2020-01-18 10:06 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by sql1610** [comment] 2020-01-18 10:06
We have trouble parsing your context
Error: Not connected to message bus

**Comment by jankeromnes** [comment] 2020-01-18 17:00
Thank you for reporting this. Duplicate of #1110 and should work again.

**Closed by jankeromnes** 2020-01-18 17:00 UTC
