### ISSUE TITLE
Unable to start new workspaces

### ISSUE THREAD

**Issue by jrebey** [gitpod-io/gitpod#888] opened 2019-11-02 22:36 UTC
**Describe the bug**
Error: (HTTP code 500) server error - stat /var/lib/docker/165536.165536/tmp: no such file or directory
Please file an issue if you think this is a bug.

**To Reproduce**
https://gitpod.io/#https://github.com/jrebey/xbvr

**Expected behavior**
Gitpod reads .gitpod.yml and .gitpod.dockerfile, builds the workspace and starts it

**Additional Information**

**Comment by JesterOrNot** [comment] 2019-11-04 02:24
see #890

**Comment by JesterOrNot** [comment] 2019-11-04 02:39
Also @jrebey it builds
![image](https://user-images.githubusercontent.com/50386709/68096995-f798e080-fe79-11e9-8d62-f411bb8264f7.png)

**Comment by geropl** [comment] 2019-11-04 09:05
Closing in favour of #890 as they have the same root cause. Please re-open if that's not tru.e

**Closed by geropl** 2019-11-04 09:05 UTC
Labels: bug
