### ISSUE TITLE
"server" should reload Configmap if it changes

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5584] opened 2021-09-08 06:23 UTC
When deploying a new version, https://gitpod.io/api/version no longer shows the new version even though it is deployed.

This seems to be because the value of "version" is now passed into server via configmap and no longer via ENV variable on the container. This means k8s will no longer restart server if the value changes and we need to do this ourselves.

proposal: 
a) server should reload the configmap if it changes
b) on helm level, here should be a checksum on the configmap.

expectaiton:
* after a deploy, https://gitpod.io/api/version should show the deployed version.

**Comment by akosyakov** [comment] 2021-09-08 07:09
@csweichel will it be covered as part of https://github.com/gitpod-io/gitpod/issues/5565#issuecomment-914949316?

**Comment by JanKoehnlein** [comment] 2021-09-08 08:30
Closed as duplicate of #5565

**Comment by geropl** [comment] 2021-09-08 13:13
Re-opening because this is not necessarily a duplicate of #5565, and can be easily fixed independently.

**Closed** 2021-09-08 13:30 UTC
Labels: component: server, groundwork: in review, team: meta
