### ISSUE TITLE
failed to create containerd container error

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5246] opened 2021-08-17 20:12 UTC
While investigating containerd-restarts, I noticed we get this error rather often:

> time="2021-08-17T16:22:10.841896693Z" level=error msg="CreateContainer within sandbox \"4bf05fc08e7a95c8b2f04f3066f6f55739a42746973ce457d596b0a08d09edaf\" for &ContainerMetadata{Name:workspace,Attempt:0,} failed" error="failed to create containerd container: cannot load seccomp profile \"/var/lib/kubelet/seccomp/workspace_default_main.1254.json\": open /var/lib/kubelet/seccomp/workspace_default_main.1254.json: no such file or directory"

[Example](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-08-17T16:22:12Z;query=%22cannot%20load%20seccomp%20profile%22%0Atimestamp%3D%222021-08-17T16:22:10.842059Z%22%0AinsertId%3D%22o5ikatsxyvk74ro4%22;timeRange=P2D?project=gitpod-191109)

When searching for [4bf05fc08e7a95c8b2f04f3066f6f55739a42746973ce457d596b0a08d09edaf](https://console.cloud.google.com/logs/query;query=%224bf05fc08e7a95c8b2f04f3066f6f55739a42746973ce457d596b0a08d09edaf%22;timeRange=P2D;cursorTimestamp=2021-08-17T16:37:00.317489Z?project=gitpod-191109) it looks like the container gets created eventually. 

However, I see the error three times with the first and the last one being 10sec apart. Besides eliminating errors from our logs, this may be an opportunity to increase workspace start performance.

**Comment by JanKoehnlein** [comment] 2021-08-20 09:39
We're currently swamped in groundwork. As the container eventually starts, I am not scheduling this now. Feel free to bring this in again.

**Comment by AlexTugarev** [comment] 2021-08-25 13:42
This issue currently breaks prebuilds on staging.

**Comment by princerachit** [comment] 2021-10-01 07:12
I cannot see this error in our logs anymore.
Looking at the code I suspect this error could occur when a workspace is scheduled while an installation of a different version of gitpod is in progress.

In nut shell this is what I think happened:
1. Cluster had version X of gitpod installed
2. An attempt to install new version of gitpod was made
3. ws-daemon was not completely rolled out
4. scheduler checked if a pod with requiredService ws-daemon exists -> It was true as an older version already existed
5. Scheduler scheduled the workspace on the node -> It expected a seccomp profile `workspace_default_main.1254.json` which was not created yet because of (3)
6. We saw failure message

**Comment by princerachit** [comment] 2021-10-01 09:55
Since we are not seeing this error and the explanation above is most likely the cause, I am closing this issue.

**Closed by princerachit** 2021-10-01 09:55 UTC
Labels: groundwork: in progress, team: workspace
