### ISSUE TITLE
New upcoming Gitpod cannot run 3 docker pull during prebuild

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#3671] opened 2021-03-31 05:03 UTC
### Update March 31: 
Previously (last night), running 2 docker pull commands during prebuild would reproduce the bug.
But this morning, running 3 docker pull commands is required to reproduce the bug.

### Bug description

In the new (upcoming) Gitpod version, running **3** `docker pull` commands during prebuild, would result in loss of docker images, and any files created during prebuild.

(Current Gitpod version doesn't have this bug, and work as expected)

### Steps to reproduce

In the new (upcoming) Gitpod version:
1. Run more than **3** `docker pull` commands during prebuild.
1. Generate a file during prebuild.
1. After prebuild, when workspace starts - no docker images and no files generated during prebuild exist.

### Expected behavior

Similar to current Gitpod version, that all docker images that were downloaded during prebuild, and all the files generated during prebuild, would exist when starting a new workspace.

### Example repository

https://github.com/shaal/gitpod-bug-repro/tree/bug/docker-pull

**Comment by rfay** [comment] 2021-03-31 10:27
This seems like a super-important bug to solve. There are several mysterious aspects to it. Why does it fail just from pulling two docker images? Why on failure is the entire state of the prebuild destroyed?

**Comment by shaal** [comment] 2021-03-31 18:07
Sure. I tested here and it failed now 
https://main.staging.gitpod-dev.com/#prebuild/https://github.com/shaal/gitpod-bug-repro/tree/bug/docker-pull

**Comment by shaal** [comment] 2021-03-31 18:08
@svenefftinge I don't know if this is related to `self hosted`. I saw you added that tag.

**Comment by aledbf** [comment] 2021-03-31 20:51
@shaal I am working on a fix for this issue.

The issue here is not related to docker or any of the changes/fixed in this cycle but to a permission issue during the termination of the workspace. In particular with commands using `sudo`. I am working in a fix for this issue in https://github.com/gitpod-io/gitpod/pull/3684

**Comment by aledbf** [comment] 2021-03-31 20:54
@shaal thank you for the repository that reproducing the issue :+1:

**Comment by shaal** [comment] 2021-03-31 21:02
I'm so happy it will be resolved before the new version of Gitpod comes out!
(is there an ETA for the new version?)

**Comment by svenefftinge** [comment] 2021-04-01 08:58
> (is there an ETA for the new version?)

We will release and announce it next Thursday.

**Comment by csweichel** [comment] 2021-04-01 14:15
> The docker problem is triggered because during termination supervisor cannot kill the docker-up process. This means the docker graph never stored the state after all the pulls.

Is that because supervisor does not run as `root` while `docker-up` does?
If so, we should enable supervisor to properly sigint/sigterm those processes, too prior to them receiving sigkill.

**Closed** 2021-04-01 17:27 UTC
