### ISSUE TITLE
Terminal not working in Gitpod workspaces for a specific user

### ISSUE THREAD

**Issue by bravoalpha79** [gitpod-io/gitpod#3481] opened 2021-03-17 15:55 UTC
### Bug description

The student's workspace opens with the terminal tab open, but the terminal is never initialised (no prompt, black screen only).

https://apricot-dolphin-twrbop1z.ws-eu03.gitpod.io/#/workspace/sql

Strangely enough, when the student shares their workspace with me, the terminal initialises normally on my end.

Any attempt by the student to create a new workspace ends in the same result - the workspace opens, but the terminal is never initialised.

I even created a workspace of my own (from the student's repo) and at my end terminal works OK, but when I create a snapshot of that workspace and share it with the student, the terminal again doesn't work on their end:

https://gitpod.io/#snapshot/b2bcfafa-bab1-4599-81f0-06bc2d637739

We tried:
- stopping and restarting workspace
- logging out and back into Gitpod
- creating a duplicate workspace

No change.

### Steps to reproduce

Unknown, issue visible only on student's side. 

### Expected behavior

Terminal is initialised upon workspace start and can be used normally.

**Comment by akosyakov** [comment] 2021-03-18 07:47
Which IDE do you use?

**Comment by bravoalpha79** [comment] 2021-03-18 08:26
Hi Anton,

I thought *Gitpod *was the IDE. :)

It's Theia.

**Comment by akosyakov** [comment] 2021-03-18 10:21
@bravoalpha79 ok :) which editor then? did he switched to VS Code here: https://www.gitpod.io/docs/feature-preview/#default-ide?

**Comment by bravoalpha79** [comment] 2021-03-18 10:23
:) No no, it was Theia all the way, both on my side and on the student's,
in both workspace instances above.

**Comment by kiehozero** [comment] 2021-03-24 10:21
I get the same issue on Firefox, but on Chrome it works fine. Obviously not preventing me from getting any work done, just hoping it narrows the problems down.

**Comment by rfay** [comment] 2021-03-26 00:31
I have this problem. I can't use the terminal on any gitpod instance, using Chrome. If I try to start a new terminal it just hangs there. 

<img width="1004" alt="Welcome_—_ddev-gitpod_—_Gitpod_Code" src="https://user-images.githubusercontent.com/112444/112560234-5aa15500-8d98-11eb-930b-58a8b0f0cee7.png">

**Comment by akosyakov** [comment] 2021-03-26 08:11
@rfay for VS Code we track it here: https://github.com/gitpod-io/gitpod/issues/3127 looking to resolve it this month.

**Comment by akosyakov** [comment] 2021-03-27 13:55
i close it as a duplicate of https://github.com/gitpod-io/gitpod/issues/3127 I think it is the same root cause, i.e. a deadlock in the supervisor.

**Closed by akosyakov** 2021-03-27 13:55 UTC
Labels: component: ide, component: supervisor, type: bug

**Comment by LuigiSousa** [comment] 2022-11-21 19:08
This error came back again
