### ISSUE TITLE
Evicted: Pod The node was low on resource: [DiskPressure]

### ISSUE THREAD

**Issue by martingr1** [gitpod-io/gitpod#1229] opened 2020-02-17 14:10 UTC
### Describe the bug
I get the message Evicted: Pod The node was low on resource: [DiskPressure], when loading my workspace. It won't load. 

### Steps to reproduce
Start GitPod, click open workspace.

### Expected behavior
Workspace to open.

### Additional Information
N/A

**Comment by jankeromnes** [comment] 2020-02-17 15:04
Thank you @martingr1 for filing this issue. We're investigating this problem.

Closing as duplicate of #1187. Please add any information that could help the investigation there (workspace IDs, URLs, screenshots, etc.)

**Closed by jankeromnes** 2020-02-17 15:04 UTC
