### ISSUE TITLE
Workaround is required to use .Net because of the `/proc/$$/maps` problem in shiftfs

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#10122] opened 2022-05-19 10:19 UTC
### Bug description

Official .net installation instructions do not work, and the user needs to know about the [available workaround](https://github.com/gitpod-io/workspace-images/pull/820) or use the [Gitpod .Net template](https://www.gitpod.io/docs/languages/dotnet) to be able to work with .net.

### Steps to reproduce

Try installing .Net without using [this workaround](https://github.com/gitpod-io/workspace-images/pull/820/files#diff-e61257c086bb2853d3c0a57811258909c7f9d27cb693466a82f5715bf06478adR14).

### Expected behavior

No workaround or "hack" should be needed to install .net or use images with .net.

### Anything else?

[Internal Slack thread](https://gitpod.slack.com/archives/C01KPEPNBD0/p1652817172981449)

**Comment by utam0k** [comment] 2022-05-20 00:04
If this issue will be resolved, we don't need to use this workaround
https://github.com/toby63/shiftfs-dkms/issues/21

**Comment by aledbf** [comment] 2022-05-24 19:24
@atduarte I think the dotnet template loads a really old image. We should trigger a rebuld

**Comment by chiyancheung** [comment] 2022-05-24 21:24
Thanks. The template compiles successfully now. 

I changed it to a web API project.

I'm not exactly sure how to test it from my computer. When I go to the endpoint, I keep getting an "HTTP ERROR 502". Any thoughts?

Thanks.

**Comment by utam0k** [comment] 2022-05-24 22:55
@chiyancheung Hi, thanks for your report. Can I ask you to make sure the ports you want to open are opened.
https://www.gitpod.io/docs/config-ports

**Comment by chiyancheung** [comment] 2022-05-24 23:36
The browser tab opens up when I run the project, but I'm still getting HTTP ERROR 502. I think port 7095 is open.  Can you take a look at my .gitpod.yml? 

image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build

vscode:
  extensions:
    - muhammad-sammy.csharp

ports:
  - port: 7095
    onOpen: open-browser
    visibility:   public

**Comment by chiyancheung** [comment] 2022-05-25 01:01
Here's a sample of the HTTP ERROR 502 issue. This one is using port 7161:

https://gitpodio-templatedotnet-kvy95zipxwz.ws-us45.gitpod.io/

Any ideas?

**Comment by utam0k** [comment] 2022-05-25 01:22
@chiyancheung Thanks for your information. Can I ask you to give me your codes?

**Comment by utam0k** [comment] 2022-05-25 02:57
@chiyancheung Thanks! I checked your application. Please change `localhost` to `0.0.0.0`. And I got `404`.

**Comment by chiyancheung** [comment] 2022-05-25 10:18
Thanks for looking into it. I changed all "localhost" to "0.0.0.0" in the launchSettings.json file. When I run the app now, I get the following error:
------------
Port 7161 Not Found
Please make sure this port is exposed and your application is up and running.
------------
.gitpod.yml still has port 7161 open. Any ideas? Thanks.

**Comment by chiyancheung** [comment] 2022-05-25 19:07
When I tried to share a snapshot of a workspace created with this template (https://gitpod.io#snapshot/6f44b742-c526-4b21-94cc-ff21f0477255), the recipient would get the following error: 

Oh, no! Something went wrong!
Unauthorized
Authorize with github.com

They were able to open a snapshot created from a different workspace & template. Do you think the issue is related to the template and do you have any suggestions?

Thanks!

**Comment by chiyancheung** [comment] 2022-05-25 21:09
When I tried to put .Net code in a regular workspace, I get this message: 

"The .NET Core SDK cannot be located. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path." 

How do I install .NET Core SDK in my workspace?

Thanks.

**Comment by utam0k** [comment] 2022-05-29 23:54
@chiyancheung Thanks for your adding information. But the problem you pointed out maybe a little different from this issue. Can I ask you to create the issue? If you will create it, we can check and schedule it.

**Comment by hm2075** [comment] 2022-06-11 18:39
I think you guys are over complicating this

all you need is


```
image: mcr.microsoft.com/dotnet/sdk:6.0

tasks:
  - name: DOTNET
  - init: |
          cp -r /usr/share/dotnet /workspace
          dotnet restore
    command: /workspace/dotnet/dotnet watch run
```


effectively use the image from ms,   then copy the dotnet file to workspace and use that

**Comment by utam0k** [comment] 2022-06-13 23:24
@hm2075 Thanks for your suggestion. Did that work on the SaaS gitpod? This issue came from the https://github.com/gitpod-io/gitpod/issues/8901.

**Comment by joeizy** [comment] 2022-06-14 10:58
This issue came up when googling so let me know if I should open a new one or not but below comment seems related.

When I use vscode locally, the auto-generated build & run doesn't work. I get the error: `The terminal process failed to launch: Path to shell executable "dotnet" is not a file or a symlink.`

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/11180858/173559716-447dce01-5a28-452b-a964-362edad8bab0.png">

This happens even when using the https://github.com/gitpod-io/template-dotnet-core-cli-csharp template.

Here are two workarounds I was able to find but neither is ideal because you should be able to run `dotnet new`, open in vscode desktop, and immediately hit debug/run.

1. [change build tasks to 'shell' from 'process'](https://github.com/joeizy/gitpod-template-dotnet-core-cli-csharp/commit/dfa2447669c9aafc0882448cc38b65c36c3101d7) in branch [working-task-as-shell](https://github.com/joeizy/gitpod-template-dotnet-core-cli-csharp/tree/working-tasks-as-shell)
2. [change build task command - full path to dotnet](https://github.com/joeizy/gitpod-template-dotnet-core-cli-csharp/commit/c3a3f55bf6176b618c798d6d4883851641ee1bf8) in branch [working-command-full-path](https://github.com/joeizy/gitpod-template-dotnet-core-cli-csharp/tree/working-command-full-path)

These workarounds also work in vscode in browser.

**Comment by hm2075** [comment] 2022-06-14 19:13
> @hm2075 Thanks for your suggestion. Did that work on the SaaS gitpod? This issue came from the #8901.

yes,  tested on gitpod cloud

**Comment by utam0k** [comment] 2022-06-19 23:26
> > @hm2075 Thanks for your suggestion. Did that work on the SaaS gitpod? This issue came from the #8901.
> 
> yes, tested on gitpod cloud

Thanks. Can I ask you to give me an output that you will run `cat /proc/self/maps`

**Comment by utam0k** [comment] 2022-06-19 23:34
@joeizy Thanks for your report. That problem you mentioned is not related to this issue, but I want to say again that thanks for your report. Can I ask you to create another issue, if you want.

**Comment by aledbf** [comment] 2022-06-21 19:59
Closing. This is still related to kernel versions. We roll back to v5.15, and this is working as expected now.
The fix is already in place for gen49 and will be available on Thursday.

![Screenshot from 2022-06-21 15-57-05](https://user-images.githubusercontent.com/161571/174886997-ed4241a6-d740-4556-9855-2d400597b9e6.png)

**Closed by aledbf** 2022-06-21 19:59 UTC
Labels: type: bug, team: workspace

**Comment by utam0k** [comment] 2022-06-21 23:28
@aledbf @kylos101 Great! Thanks.
