### ISSUE TITLE
"Open in VS Code" doesn't work if settings.json is not writeable

### ISSUE THREAD

**Issue by john-shaffer** [gitpod-io/gitpod#8355] opened 2022-02-21 16:22 UTC
### Bug description

"Open in VS Code" requires write access to the User settings.json.

![Screenshot from 2022-02-21 10-06-25](https://user-images.githubusercontent.com/53870456/154992356-1ee1c235-e5ea-4119-aee9-9d84f76a625e.png)

I manually added the "remote.SSH.defaultExtensions" config to my settings.json, but I cannot add the path to the SSH config because it changes each time. It would be fine if I could set a consistent path to the SSH config.

### Steps to reproduce

Click "Open in VS Code".

### Expected behavior

It should work without having to write to my config files.

**Comment by axonasif** [comment] 2022-02-22 04:38
Thanks for raising! Our ide-team will be updating the connection method of VS Code desktop soon to direct SSH without any helper program, hopefully this should resolve the issue. Please see

- https://github.com/gitpod-io/gitpod/issues/7184

**Comment by loujaybee** [comment] 2022-03-04 11:42
Thanks @axonasif, yeah the more specific issue for SSH gateway integration is here: https://github.com/gitpod-io/gitpod/issues/8513. I'm going to close this one, as it appears almost as a duplicate of: https://github.com/gitpod-io/gitpod/issues/5889, which should also be fixed by https://github.com/gitpod-io/gitpod/issues/8513... let's use that one to track this issue 🙏

**Closed** 2022-03-04 11:42 UTC
Labels: team: IDE
