### ISSUE TITLE
Unable to start new workspace

### ISSUE THREAD

**Issue by jeffwilde** [gitpod-io/gitpod#1633] opened 2020-06-26 02:28 UTC
While attempting to launch any new workspace from github, i am presented with this error:

> Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: Error response from daemon: No such image: gitpod.io/image-builder/selfbuild:be4a5a83176295d4d4ab67e8772a73c3f5db59fcaea403390ac2e3fef9a80120
> Please file an issue if you think this is a bug. 

![image](https://user-images.githubusercontent.com/6980603/85813686-e4e95980-b731-11ea-9376-d6d4dca15ca0.png)

This started happening a few hours ago to repositories that previously had no launch problems. I am able to start pre-existing workspaces (built before the error started occuring) without error. 

Appears to be related to https://github.com/gitpod-io/gitpod/issues/1072.

**Comment by svenefftinge** [comment] 2020-06-26 08:54
This is a duplicate of https://github.com/gitpod-io/gitpod/issues/1627 and has been fixed.

**Closed by svenefftinge** 2020-06-26 08:54 UTC
