### ISSUE TITLE
Console opens with WinForms

### ISSUE THREAD

**Issue by DaniilNapuda** [gitpod-io/gitpod#1560] opened 2020-05-28 12:30 UTC
**I made a test program WinForm, but when I open it, the program opens with CMD, but I didn’t want to. How to fix it?**

- Screen:

![Error](https://user-images.githubusercontent.com/65886954/83140464-52e13780-a118-11ea-809f-7a011314cc83.png)

- Code:

using System;
using System.Drawing;
using System.Windows.Forms;

class MForm : Form {
    public MForm() {
        Text = "Programm";

        ms.Parent = this;
        
        ToolStripMenuItem file = new ToolStripMenuItem("&File");
        ToolStripMenuItem exit = new ToolStripMenuItem("&Exit", null,
            new EventHandler(OnExit));          
        exit.ShortcutKeys = Keys.Control | Keys.X;
        file.DropDownItems.Add(exit);

        ms.Items.Add(file);
        MainMenuStrip = ms;
        Size = new Size(250, 200);

        CenterToScreen();
    }

    void OnExit(object sender, EventArgs e) {
       Close();
    }
}

class MApplication {
    public static void Main() {
        Application.Run(new MForm());
    }
}

**Comment by Kreyren** [comment] 2020-05-29 10:39
@DaniilNapuda How is this relevant to gitpod? O.o

**Comment by Kreyren** [comment] 2020-05-29 10:53
***kreyren** wasn't sure what the issue is without having a windows in VM so he asked on freenode*

@DaniilNapuda From Freenode.net/##csharp

> that means that his application type in his project settings is set to console project and not windows application

![image](https://user-images.githubusercontent.com/11302521/83251736-591ff400-a1aa-11ea-8882-18bcc5bf2773.png)

---

For similar issues I am recommending [Freenode.net](https://freenode.net/) it's an [IRC](https://en.wikipedia.org/wiki/Internet_Relay_Chat) server that is filled with community members and professionals willing to help for free

See https://freenode.net/kb/answer/registration for registration

See https://webchat.freenode.net/##csharp for web-based frontend ^-^

This is an issue tracker for [gitpod](https://gitpod.io/) so mensioned are more competent to help with programming language specific questions :p

---

Also fixed the indentation for you ^-^

https://gist.github.com/Kreyren/2f7af020b1b42e4a3019cc2194af3e94

---

Closing as invalid

**Closed by Kreyren** 2020-05-29 10:53 UTC
Labels: invalid
