### ISSUE TITLE
Epic: SaaS Availability Zone in Asia

### ISSUE THREAD

**Issue by Thomas-Gitpod** [gitpod-io/gitpod#12429] opened 2022-08-26 09:48 UTC
### Summary

Some of our customers require an availability zone within Asia in order to deliver Gitpod in a multinational setting.

### Context

The customer is requiring a setting in which people from North Africa and India are able to work on Gitpod seamlessly. With the current availability zones this would lead to higher latencies and in return not a good user experience.

### Value

In this case it is being asked for by a large client, anyhow this will probably be done down the line to attend to Gitpodders all around the world. We could use the need by the customer to fast forward this implementation.

### Acceptance Criteria

- [ ] Cloud Region is successfully set up

### Measurement

- [ ] Cloud Region is successfully set up

**Comment by gtsiolis** [comment] 2022-08-26 09:51
@Thomas-Gitpod see also relevant issue in https://github.com/gitpod-io/gitpod/issues/5534 and epic in https://github.com/gitpod-io/gitpod/issues/7489.

**Comment by axonasif** [comment] 2022-08-26 09:54
Duplicate of #7489

**Closed by axonasif** 2022-08-26 09:54 UTC
Labels: type: epic
