### ISSUE TITLE
Supervisor unit tests are flaky

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#14210] opened 2022-10-26 18:51 UTC
### Bug description

Supervisor tests for the terminal panic in CI runs:
* https://werft.gitpod-dev.com/job/gitpod-build-mp-protocol-team-apis.2

### Steps to reproduce

https://werft.gitpod-dev.com/job/gitpod-build-mp-protocol-team-apis.2

**Comment by andreafalzetti** [comment] 2022-11-04 14:02
Thanks for opening the issue, I've noticed we have two similar ones. Can we close this as duplicate of https://github.com/gitpod-io/gitpod/issues/14425? cc @easyCZ

**Comment by jeanp413** [comment] 2022-12-21 20:23
Closing this as duplicate of https://github.com/gitpod-io/gitpod/issues/14425

**Closed by jeanp413** 2022-12-21 20:23 UTC
Labels: type: bug, team: IDE
