### ISSUE TITLE
Can not install VIM extension

### ISSUE THREAD

**Issue by maksimr** [gitpod-io/gitpod#5592] opened 2021-09-08 08:12 UTC
### Bug description

Can not install VIM extension from Open marketplace or manually

### Steps to reproduce

STR:

- Open gitpod
- Open [Install extensions]
- Find [VIM] extension
- Try to install

STR 2:
- Download VIM extension from VS Code marketplace
- Open [Install extensions]
- Install local extension

### Expected behavior

It should be possible to install VIM extension

### Anything else?

https://github.com/gitpod-io/gitpod/issues/3259#issuecomment-914589071
[vscodevim.vim-1.21.7.vsix.zip](https://github.com/gitpod-io/gitpod/files/7127133/vscodevim.vim-1.21.7.vsix.zip)

**Comment by akosyakov** [comment] 2021-09-08 08:16
duplicate of https://github.com/gitpod-io/gitpod/issues/5590

**Closed by akosyakov** 2021-09-08 08:16 UTC
