### ISSUE TITLE
[prebuild] Run inside user's region

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#9872] opened 2022-05-09 13:16 UTC
Currently prebuild are mainly executed in the US cluster because it's closed to GitHub exit nodes. This means all prebuild's snapshots are stored in `us-west1`. This is bad because for all EU workspaces based on a prebuild we have to pay egress traffic on a) when the prebuild is run and b) on every workspace start.

We know which region:
 - a user first connected with (user bucket region)  is in when registering
 - a user is currently connected (not necessarily when they trigger the prebuild)

We should try to leverage that knowledge to run the prebuild closer the where it's most likely going to be used.

**Comment by jankeromnes** [comment] 2022-05-09 13:54
Thanks for scheduling this!

Closing as duplicate of https://github.com/gitpod-io/gitpod/issues/6650 and scheduling that one instead.

**Closed by jankeromnes** 2022-05-09 13:54 UTC
Labels: component: server, type: improvement, aspect: cost efficiency
