### ISSUE TITLE
Failing of download packages during pre-builds have killed our Gitpod experience

### ISSUE THREAD

**Issue by skinny85** [gitpod-io/gitpod#1607] opened 2020-06-16 16:05 UTC
Hey all,

I've recently enabled pre-builds for our [AWS CDK](https://github.com/aws/aws-cdk)  project. Unfortunately, they always fail with a weird error while downloading NPM packages with `yarn`:

```
gitpod /workspace/aws-cdk $  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
kspace/.gitpod/prebuild-log-0 ] && cat /workspace/.gitpod/prebuild-log-0; trueor 
> }
gitpod /workspace/aws-cdk $ {
> yarn build --skip-test --no-bail
> }; exit
yarn run v1.22.4
$ ./build.sh --skip-test --no-bail
=============================================================================================
installing...
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/jsii-pacmak/-/jsii-pacmak-1.6.0.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/workspace/aws-cdk/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

🍌 This task ran as part of a workspace prebuild.
🎉 You just saved 4 minutes of watching your code build.
```

This makes for a pretty bad experience for people starting a new workspace with our project, because, instead of getting a nice working environment out-of-the box, they get an error message, and they have to invoke a build of our project manually (which they might not know how to do).

Here's my take on the problems:

1. Would really like to know why downloading NPM packages in pre-builds behaves differently than in the workspace itself (never had any issues with that during workspace builds).
2. I think failing pre-builds should **not** be used. Instead, the standard `init` commands should be executed, as if the pre-build was not enabled. Otherwise, the experience is pretty bad for open-source project contributors.
3. Can I now disable pre-builds on that repo, to revert to the previous experience, without doing a code change to the `.gitpod.yml` file?

Thanks,
Adam

**Comment by jankeromnes** [comment] 2020-06-17 07:31
Hi @skinny85,

> I've recently enabled pre-builds for our AWS CDK project. Unfortunately, they always fail with a weird error while downloading NPM packages with `yarn`:

> ```
> error An unexpected error occurred: "https://registry.yarnpkg.com/jsii-pacmak/-/jsii-pacmak-1.6.0.tgz: ESOCKETTIMEDOUT".
> ```

> 1. Would really like to know why downloading NPM packages in pre-builds behaves differently than in the workspace itself (never had any issues with that during workspace builds).

So, `yarn` should not behave differently in prebuilds and in workspaces. It's just sometimes a bit unreliable, and it occasionally fails on network requests just like in your example.

Now, unfortunately, when such a `yarn` network flake is captured in a Gitpod prebuild, every new workspace for that repository will get the cached (failed) prebuild, until the (failed) prebuild is replaced by a new (fixed) prebuild.

As potential mitigations, you could:

- Run `yarn` with `--network-timeout` set to a large value (reduce probability of timeouts)
- If a prebuild still fails, you can re-trigger it:
  - Either manually using the `#prebuild/` URL prefix (https://gitpod.io/#prebuild/https://github.com/aws/aws-cdk) to re-trigger a prebuild on the same upstream commit
  - Or push a new commit to https://github.com/aws/aws-cdk (every push triggers a new prebuild)

> 2. I think failing pre-builds should **not** be used. Instead, the standard `init` commands should be executed, as if the pre-build was not enabled. Otherwise, the experience is pretty bad for open-source project contributors.

That's a great point, and I agree with you. I believe the thought was that, if a prebuild fails, developers may want to see the error log (otherwise, the prebuild just fails silently, and you get a slower workspace init without quite knowing why).

However, it would probably be better UX to discard failed prebuilds (and fall back to non-prebuilt workspaces as you suggested), and instead offer a Gitpod dashboard with a list of all prebuilds for your repositories (and their status/logs), just like other CI systems.

> 3. Can I now disable pre-builds on that repo, to revert to the previous experience, without doing a code change to the `.gitpod.yml` file?

Yes, you can configure which repositories should be prebuilt or not in https://github.com/apps/gitpod-io > `Configure` -- but I see that you've already been able to disable prebuilds of AWS CDK for now.

Many thanks for the useful feedback. 👍

**Comment by skinny85** [comment] 2020-06-19 17:43
Thanks for the response @jankeromnes .

> Hi @skinny85,
> 
> > I've recently enabled pre-builds for our AWS CDK project. Unfortunately, they always fail with a weird error while downloading NPM packages with `yarn`:
> 
> > ```
> > error An unexpected error occurred: "https://registry.yarnpkg.com/jsii-pacmak/-/jsii-pacmak-1.6.0.tgz: ESOCKETTIMEDOUT".
> > ```
> 
> > 1. Would really like to know why downloading NPM packages in pre-builds behaves differently than in the workspace itself (never had any issues with that during workspace builds).
> 
> So, `yarn` should not behave differently in prebuilds and in workspaces. It's just sometimes a bit unreliable, and it occasionally fails on network requests just like in your example.
> 

I can tell you that every single pre-build for the aws/aws-cdk repository (save perhaps one) that I've seen has failed on `yarn` downloading packages with the above error message. I have not seen that error a single time when running `yarn` from a running Gitpod workspace.

Can you please dig a little deeper into this? I'm 100% convinced there is a difference in the network setup between a pre-build and a workspace that makes this happen. Feel free to try and reproduce it yourself, I don't think you'll have much issues doing it.

**Comment by skinny85** [comment] 2020-06-19 22:09
And currently, even though the Gitpod app has permissions to the aws/aws-cdk repo:

<img width="504" alt="gitpod-app-permissions" src="https://user-images.githubusercontent.com/460937/85182803-9eca5c80-b23e-11ea-9b3c-d70161b85a8d.png">

The pre-builds functionality suddenly stopped working completely. Every new workspace for aws/aws-cdk triggers a new build, even though `master` has not moved:

```
gitpod /workspace/aws-cdk $  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> yarn build --skip-test --no-bail
> }
...
```

I gotta say, this feature has a ton of potential, but the user experience of it has not been great 😕.

**Comment by Kreyren** [comment] 2020-06-20 10:46
***kreyren** wonders if he should try to figure out some solution or continue playing Faster Than Light*

**Comment by jankeromnes** [comment] 2020-06-22 13:38
Hi @skinny85, thank you for the feedback, and sorry for the awkward prebuild UX. We’ll improve it in the coming weeks.

> I can tell you that every single pre-build for the aws/aws-cdk repository (save perhaps one) that I've seen has failed on `yarn` downloading packages with the above error message. I have not seen that error a single time when running `yarn` from a running Gitpod workspace.

Hm, maybe this difference could be caused by excessively high load on our prebuild servers? Interactive workspaces and (headless) prebuilds don’t run on the same servers, and we’ve noticed that the prebuild servers are often running at max CPU these days. In any case, we’ll fix that issue first, if only to make prebuilds faster.

> Can you please dig a little deeper into this? I'm 100% convinced there is a difference in the network setup between a pre-build and a workspace that makes this happen. Feel free to try and reproduce it yourself, I don't think you'll have much issues doing it.

Will for sure dig deeper into this, and also try to find out if there is something special about aws/aws-cdk that makes `yarn` time out more frequently. Many other repositories (like https://github.com/eclipse-theia/theia) also frequently run prebuilds with `yarn`, but aren’t seeing timeouts as often (especially when [using `yarn --network-timeout 100000` in their `.gitpod.yml`](https://github.com/eclipse-theia/theia/blob/52a43ce94cf30dd95e7ac983151ebb5ece5b932d/.gitpod.yml#L15)).

> And currently, even though the Gitpod app has permissions to the aws/aws-cdk repo:
> [...]
> The pre-builds functionality suddenly stopped working completely. Every new workspace for aws/aws-cdk triggers a new build, even though `master` has not moved:

Ah, sorry, that’s actually the other way around.

Gitpod prebuilds are only created when **new commits** are pushed to the repo, and only if the Gitpod app is **enabled for the repo at the time of push**. So:
- Enabling the Gitpod app but pushing zero new commits **does not** trigger a prebuild
- Pushing new commits while the Gitpod app is disabled **does not** trigger a prebuild (even if you enable it afterwards)
- Creating new Gitpod workspaces for a repository **does not** trigger a prebuild (it just uses a prebuild if one is already available for the requested repo/branch/commit hash, but falls back to non-prebuild if no prebuild can be found)

In order to trigger a Gitpod prebuild for a branch, one must:
1. First make sure that the Gitpod app is enabled for the repo & branch
2. Then push a change to that branch (e.g. a new commit) -- this should trigger a prebuild (and every subsequent push as well)

Another, more sure-fire way to trigger a Gitpod prebuild (once, but not on subsequent pushes) is to use the `#prebuild/` URL prefix, e.g. by clicking on:

https://gitpod.io/#prebuild/https://github.com/aws/aws-cdk

(Clicking on the link above will forcefully start a prebuild for aws/aws-cdk’s current `master` branch, and when that prebuild is complete, it will be used by every new workspace created on `master`.)

Hope this clarifies the feature a little.

> I gotta say, this feature has a ton of potential, but the user experience of it has not been great 😕.

I agree, and I’m sorry for all the confusion our current prebuild UX has caused you.

As a first step, I think that a sort of “Prebuild Dashboard”, where you can see all your prebuilds, whether in progress, succeeded or failed, with direct access to the targeted repo/branch/commit and to the full build logs, would be awesome and would bring a lot of clarity. Maybe it could also list your repositories, and whether or not prebuilds are currently enabled for them (this could double-check whether the webhook works).

**Comment by skinny85** [comment] 2020-06-22 17:08
> Ah, sorry, that’s actually the other way around.
> 
> Gitpod prebuilds are only created when **new commits** are pushed to the repo, and only if the Gitpod app is **enabled for the repo at the time of push**. So:
> 
> * Enabling the Gitpod app but pushing zero new commits **does not** trigger a prebuild
> * Pushing new commits while the Gitpod app is disabled **does not** trigger a prebuild (even if you enable it afterwards)
> * Creating new Gitpod workspaces for a repository **does not** trigger a prebuild (it just uses a prebuild if one is already available for the requested repo/branch/commit hash, but falls back to non-prebuild if no prebuild can be found)
> 
> In order to trigger a Gitpod prebuild for a branch, one must:
> 
> 1. First make sure that the Gitpod app is enabled for the repo & branch
> 2. Then push a change to that branch (e.g. a new commit) -- this should trigger a prebuild (and every subsequent push as well)
> 
> Another, more sure-fire way to trigger a Gitpod prebuild (once, but not on subsequent pushes) is to use the `#prebuild/` URL prefix, e.g. by clicking on:
> 
> https://gitpod.io/#prebuild/https://github.com/aws/aws-cdk
> 
> (Clicking on the link above will forcefully start a prebuild for aws/aws-cdk’s current `master` branch, and when that prebuild is complete, it will be used by every new workspace created on `master`.)
> 
> Hope this clarifies the feature a little.

Sorry, I choose a poor wording. What I meant to say was that a pre-build for that commit should have been created already, because the `master` branch has not moved for a long period of time, and I've created workspaces using that commit already.

I posted this comment on Friday. Since then, there have been many commits to master, and for all of them, the Gitpod app had permissions to access the repository (since Friday, like in the screenshot). And yet, not a single pre-build has been executed for none of those commits; I just spun up a new workspace, and it just started a build directly in the workspace.

That's the weird behavior I meant in my comment; the fact that I never know whether this functionality actually works or not.

> > I gotta say, this feature has a ton of potential, but the user experience of it has not been great 😕.
> 
> I agree, and I’m sorry for all the confusion our current prebuild UX has caused you.
> 
> As a first step, I think that a sort of “Prebuild Dashboard”, where you can see all your prebuilds, whether in progress, succeeded or failed, with direct access to the targeted repo/branch/commit and to the full build logs, would be awesome and would bring a lot of clarity. Maybe it could also list your repositories, and whether or not prebuilds are currently enabled for them (this could double-check whether the webhook works).

That would be amazing. Right now, this feels like "magic", and I have no control or visibility whether this functionality is correctly enabled for my repository, and whether the contributors to my project benefit from it (or if it's actually the reverse: whether it's actually harming their contribution experience!).

Thanks a lot for your comments @jankeromnes !

**Comment by skinny85** [comment] 2020-06-25 20:40
This just happened to me:


```
installing...
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/jsii-pacmak/-/jsii-pacmak-1.7.0.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/workspace/aws-cdk/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

🍌 This task ran as part of a workspace prebuild.
🎉 You just saved 5 minutes of watching your code build.
```

Notice that not a single package has been downloaded successfully from NPM during the pre-build.

This can't be a coincidence; there has to be some fundamental difference between the networking setups of a workspace and a pre-build.

**Comment by svenefftinge** [comment] 2020-06-26 10:07
Prebuilds run within the same cluster similar nodes. So there is nothing I can think of that would make a difference for the network. It could be that the prebuild nodes are too busy (IO-wise) so they trigger the yarn timeouts more often. Will check that.

The latest prebuild looks good, though.
```
All OK.
Done in 2933.80s.

🍌 This task ran as part of a workspace prebuild.
🎉 You just saved an hour of watching your code build.
```

**Comment by svenefftinge** [comment] 2020-06-26 10:48
I have created a PR, to make your prebuilds stable. 
https://github.com/aws/aws-cdk/pull/8751

**Comment by jankeromnes** [comment] 2020-07-02 07:59
Awesome! I think @svenefftinge's PR fixes this issue, and it got merged.

We'll also work on significantly improving the prebuild UX soon.

**Closed by jankeromnes** 2020-07-02 07:59 UTC
