### ISSUE TITLE
Got an error while authorizing

### ISSUE THREAD

**Issue by nehasoni05** [gitpod-io/gitpod#2769] opened 2021-01-10 13:30 UTC
### Example repository

![Screenshot (21)](https://user-images.githubusercontent.com/67725607/104124305-24962c80-5376-11eb-98ec-4400e280905d.png)

**Comment by csweichel** [comment] 2021-01-11 06:43
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by csweichel** 2021-01-11 06:43 UTC

**Comment by nehasoni05** [comment] 2021-01-11 07:27
Thank you
