### ISSUE TITLE
[prebuilds] More effective rate-limit (Rate-limit prebuilds per user?)

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#14791] opened 2022-11-18 14:27 UTC
We currently do rate limit Prebuilds per `contextURL`m but this leaves lot's of opportunity to accidentally shoot yourselves in the foot. Examples:
 - copying a repo (how this turn into webhooks out depends on the SCMs instance configuration, actually)
 - installing a noisy bot on your repo

We should also rate-limit on a per user basis.

**Comment by svenefftinge** [comment] 2022-11-21 11:00
As @AlexTugarev pointed out in https://github.com/gitpod-io/gitpod/pull/14796 the limiting is done by `cloneURL` (not `contextURL`) which makes sense. The incident we had last week was probably caused by races with the underlying DB state. I suggest closing this.

**Comment by geropl** [comment] 2022-11-25 08:21
I think the core issue is that we rely on a static rate limit per time. Because of this, we fear we will block users for too long if we tighten the limit, thus ending up with one that's very open - and not limiting enough.
I will turn this into a leaking bucket limit, which will allow us to tighten the limit considerably while still remaining responsive.

**Comment by shaal** [comment] 2022-11-29 01:32
How is it going to work? Is the planned limit per branch? or per repo?

How would it work with the following scenario?
I push chances to a branch, prebuild starts running. 
After 1 minute I find and issue, commit and push the same branch.
The current prebuild will be cancelled, and a new prebuild will start.

Will the new rate limit affect the scenario above?

**Comment by geropl** [comment] 2022-11-30 10:22
@shaal In theory: yes. But the limit is high enough (50 calls/10mins) that is should not affect most usecases (we double checked with prod data).

Note that: This is only a temporary measure to safeguard against usage mistakes, until we a) grant per-project controls and b) better schedule the incoming prebuilds.

**Closed** 2022-11-30 10:44 UTC
Labels: component: server, type: incident, :gear: Groundwork
