### ISSUE TITLE
Self-Hosted: Can not create a Project

### ISSUE THREAD

**Issue by vavdoshka** [gitpod-io/gitpod#9085] opened 2022-04-01 21:18 UTC
### Bug description

When try to create a project nothing happens:

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/11683992/161341526-da40f304-83b7-4e7a-b115-c7661cf3ccb9.png">

### Steps to reproduce

Install GitPod using Installer v2022.03.0 (also reproduced on v2022.01.0) on AWS EKS.
No specific values are set in the installer config, just a custom domain name.

Use GitLab auth provider.
Open Projects -> New Project

screen hangs as showed above

### Expected behavior

a new project can be added

### Anything else?

Here is the log capture during time frame when I click on New Project

```
agent-smith-7f89c agent-smith {"level":"debug","message":"procfs detector run","serviceContext":{"service":"agent-smith","version":"commit-b121fec8e215abd2d0328ef28b8808a59852cb4c"},"severity":"DEBUG","time":"2022-04-01T21:11:27Z"}
registry-facade-vw7qs registry-facade {"addr":":32223","level":"info","message":"HTTPS registry server listening","serviceContext":{"service":"registry-facade","version":"commit-b121fec8e215abd2d0328ef28b8808a59852cb4c"},"severity":"INFO","time":"2022-04-01T21:00:49Z"}
registry-facade-vw7qs kube-rbac-proxy I0401 21:00:47.877059       1 main.go:379] Listening insecurely on [192.168.80.54]:9500
ws-proxy-5b5877c8cf-44blc kube-rbac-proxy I0401 21:00:46.931574       1 main.go:379] Listening insecurely on [192.168.75.124]:9500
ws-proxy-5b5877c8cf-44blc ws-proxy {"level":"info","logger":"controller.pod","message":"Starting workers","reconciler group":"","reconciler kind":"Pod","serviceContext":{"service":"ws-proxy","version":"commit-b121fec8e215abd2d0328ef28b8808a59852cb4c"},"severity":"INFO","time":"2022-04-01T21:00:47Z","worker count":1}
I0401 21:11:38.051162   12182 request.go:665] Waited for 1.039693928s due to client-side throttling, not priority and fairness, request: GET:https://REDACTED.gr7.us-east-1.eks.amazonaws.com/api/v1/namespaces/gitpod/pods/ws-manager-bridge-5bcbb5fbcd-m26qn/log?container=ws-manager-bridge&follow=true&sinceSeconds=172800&tailLines=1
ws-manager-bridge-5bcbb5fbcd-m26qn ws-manager-bridge {"component":"ws-manager-bridge","severity":"DEBUG","time":"2022-04-01T21:11:24.548Z","message":"controlling instances","payload":{"installation":"default"}}
ws-manager-bridge-5bcbb5fbcd-m26qn kube-rbac-proxy I0401 21:01:22.863863       1 main.go:379] Listening insecurely on [192.168.36.113]:9500
ws-daemon-722lr kube-rbac-proxy I0401 21:00:47.949444    9211 main.go:379] Listening insecurely on [192.168.84.7]:9500
ws-daemon-722lr ws-daemon {"bvail":61061341184,"level":"debug","message":"checked for available disk space","minBytesAvail":21474836480,"serviceContext":{"service":"ws-daemon","version":"commit-b121fec8e215abd2d0328ef28b8808a59852cb4c"},"severity":"DEBUG","time":"2022-04-01T21:10:47Z"}
openvsx-proxy-0 openvsx-proxy {"level":"info","message":"OpenVSX proxy has been started ... listening on port 8080 ☕ ...","serviceContext":{"service":"openvsx-proxy","version":""},"severity":"INFO","time":"2022-04-01T21:00:34Z"}
content-service-74697bc867-7qjql content-service {"level":"info","message":"🧫 content-service is up and running. Stop with SIGINT or CTRL+C","serviceContext":{"service":"content-service","version":"commit-b121fec8e215abd2d0328ef28b8808a59852cb4c"},"severity":"INFO","time":"2022-04-01T21:00:31Z"}
proxy-578ff48487-kdlk9 kube-rbac-proxy I0401 21:00:32.932700       1 main.go:379] Listening insecurely on [192.168.47.13]:9500
proxy-578ff48487-kdlk9 proxy {"level":"info","ts":1648847497.1743805,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.14.172:51890","proto":"HTTP/1.1","method":"GET","host":"192.168.14.172:32432","uri":"/","headers":{"Connection":["close"],"User-Agent":["ELB-HealthChecker/2.0"],"Accept-Encoding":["gzip, compressed"]},"tls":{"resumed":false,"version":771,"cipher_suite":49199,"proto":"","proto_mutual":true,"server_name":""}},"common_log":"192.168.14.172 - - [01/Apr/2022:21:11:37 +0000] \"GET / HTTP/1.1\" 0 0","user_id":"","duration":0.000011652,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
server-5694f4c646-clrn4 server {"component":"server","severity":"DEBUG","time":"2022-04-01T21:11:25.163Z","message":"ws connection handler","payload":{"clients":1}}
server-5694f4c646-clrn4 kube-rbac-proxy I0401 21:01:23.770901       1 main.go:379] Listening insecurely on [192.168.48.10]:9500
image-builder-mk3-55bf554fd5-xmflq kube-rbac-proxy I0401 21:00:46.056554       1 main.go:379] Listening insecurely on [192.168.58.209]:9500
image-builder-mk3-55bf554fd5-xmflq image-builder-mk3 {"level":"debug","message":"pre-cached Docker ref","ref":"docker.io/gitpod/workspace-full:latest","resolved-to":"docker.io/gitpod/workspace-full@sha256:b484ad49d47bf70776de1d1333379d6b5f1d56c0a3fc1f31a24eb273ef772e3e","serviceContext":{"service":"image-builder-mk3","version":"commit-b121fec8e215abd2d0328ef28b8808a59852cb4c"},"severity":"DEBUG","time":"2022-04-01T21:00:48Z"}
blobserve-5cf456888d-jx8nz kube-rbac-proxy I0401 21:00:32.807868       1 main.go:379] Listening insecurely on [192.168.69.221]:9500
blobserve-5cf456888d-jx8nz blobserve {"level":"info","message":"blobspace GC complete","serviceContext":{"service":"blobserve","version":"commit-b121fec8e215abd2d0328ef28b8808a59852cb4c"},"severity":"INFO","spaceFreed":0,"time":"2022-04-01T21:10:32Z"}
messagebus-0 rabbitmq 2022-04-01 21:01:25.137906+00:00 [info] <0.783.0> connection <0.783.0> (192.168.48.10:45690 -> 192.168.91.69:5672): user 'gitpod' authenticated and granted access to vhost '/'
ws-daemon-hlgvr ws-daemon {"bvail":64532824064,"level":"debug","message":"checked for available disk space","minBytesAvail":21474836480,"serviceContext":{"service":"ws-daemon","version":"commit-b121fec8e215abd2d0328ef28b8808a59852cb4c"},"severity":"DEBUG","time":"2022-04-01T21:10:48Z"}
ws-daemon-hlgvr kube-rbac-proxy I0401 21:00:47.771110   27404 main.go:379] Listening insecurely on [192.168.6.252]:9500
ide-proxy-5fcb8f4645-h98pf ide-proxy {"level":"info","ts":1648846830.4362195,"msg":"serving initial configuration"}
proxy-578ff48487-kdlk9 proxy {"level":"info","ts":1648847512.1220894,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.39.232:20090","proto":"HTTP/1.1","method":"GET","host":"192.168.39.232:32432","uri":"/","headers":{"Connection":["close"],"User-Agent":["ELB-HealthChecker/2.0"],"Accept-Encoding":["gzip, compressed"]},"tls":{"resumed":false,"version":771,"cipher_suite":49199,"proto":"","proto_mutual":true,"server_name":""}},"common_log":"192.168.39.232 - - [01/Apr/2022:21:11:52 +0000] \"GET / HTTP/1.1\" 0 0","user_id":"","duration":0.000021703,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
proxy-578ff48487-kdlk9 proxy {"level":"info","ts":1648847512.1262996,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.76.0:39272","proto":"HTTP/1.1","method":"GET","host":"192.168.76.0:32432","uri":"/","headers":{"Connection":["close"],"User-Agent":["ELB-HealthChecker/2.0"],"Accept-Encoding":["gzip, compressed"]},"tls":{"resumed":false,"version":771,"cipher_suite":49199,"proto":"","proto_mutual":true,"server_name":""}},"common_log":"192.168.76.0 - - [01/Apr/2022:21:11:52 +0000] \"GET / HTTP/1.1\" 0 0","user_id":"","duration":0.000006162,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
proxy-578ff48487-kdlk9 proxy {"level":"info","ts":1648847512.1297052,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.14.172:3214","proto":"HTTP/1.1","method":"GET","host":"192.168.14.172:32432","uri":"/","headers":{"Connection":["close"],"User-Agent":["ELB-HealthChecker/2.0"],"Accept-Encoding":["gzip, compressed"]},"tls":{"resumed":false,"version":771,"cipher_suite":49199,"proto":"","proto_mutual":true,"server_name":""}},"common_log":"192.168.14.172 - - [01/Apr/2022:21:11:52 +0000] \"GET / HTTP/1.1\" 0 0","user_id":"","duration":0.000005213,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
proxy-578ff48487-kdlk9 proxy {"level":"info","ts":1648847512.1539237,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.14.172:28714","proto":"HTTP/1.1","method":"GET","host":"192.168.14.172:32432","uri":"/","headers":{"Connection":["close"],"User-Agent":["ELB-HealthChecker/2.0"],"Accept-Encoding":["gzip, compressed"]},"tls":{"resumed":false,"version":771,"cipher_suite":49199,"proto":"","proto_mutual":true,"server_name":""}},"common_log":"192.168.14.172 - - [01/Apr/2022:21:11:52 +0000] \"GET / HTTP/1.1\" 0 0","user_id":"","duration":0.000008942,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
proxy-578ff48487-kdlk9 proxy {"level":"info","ts":1648847512.1546948,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.76.0:22900","proto":"HTTP/1.1","method":"GET","host":"192.168.76.0:32432","uri":"/","headers":{"Accept-Encoding":["gzip, compressed"],"Connection":["close"],"User-Agent":["ELB-HealthChecker/2.0"]},"tls":{"resumed":false,"version":771,"cipher_suite":49199,"proto":"","proto_mutual":true,"server_name":""}},"common_log":"192.168.76.0 - - [01/Apr/2022:21:11:52 +0000] \"GET / HTTP/1.1\" 0 0","user_id":"","duration":0.000005965,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
proxy-578ff48487-kdlk9 proxy {"level":"info","ts":1648847512.173815,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.39.232:59380","proto":"HTTP/1.1","method":"GET","host":"192.168.39.232:32432","uri":"/","headers":{"Connection":["close"],"User-Agent":["ELB-HealthChecker/2.0"],"Accept-Encoding":["gzip, compressed"]},"tls":{"resumed":false,"version":771,"cipher_suite":49199,"proto":"","proto_mutual":true,"server_name":""}},"common_log":"192.168.39.232 - - [01/Apr/2022:21:11:52 +0000] \"GET / HTTP/1.1\" 0 0","user_id":"","duration":0.0000052,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
proxy-578ff48487-kdlk9 proxy {"level":"info","ts":1648847512.1835475,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.76.0:42696","proto":"HTTP/1.1","method":"GET","host":"192.168.76.0:32432","uri":"/","headers":{"Connection":["close"],"User-Agent":["ELB-HealthChecker/2.0"],"Accept-Encoding":["gzip, compressed"]},"tls":{"resumed":false,"version":771,"cipher_suite":49199,"proto":"","proto_mutual":true,"server_name":""}},"common_log":"192.168.76.0 - - [01/Apr/2022:21:11:52 +0000] \"GET / HTTP/1.1\" 0 0","user_id":"","duration":0.000006234,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
proxy-578ff48487-kdlk9 proxy {"level":"info","ts":1648847512.1847079,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.39.232:17327","proto":"HTTP/1.1","method":"GET","host":"192.168.39.232:32432","uri":"/","headers":{"Connection":["close"],"User-Agent":["ELB-HealthChecker/2.0"],"Accept-Encoding":["gzip, compressed"]},"tls":{"resumed":false,"version":771,"cipher_suite":49199,"proto":"","proto_mutual":true,"server_name":""}},"common_log":"192.168.39.232 - - [01/Apr/2022:21:11:52 +0000] \"GET / HTTP/1.1\" 0 0","user_id":"","duration":0.000005341,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
proxy-578ff48487-kdlk9 proxy {"level":"info","ts":1648847512.187159,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.14.172:39911","proto":"HTTP/1.1","method":"GET","host":"192.168.14.172:32432","uri":"/","headers":{"Connection":["close"],"User-Agent":["ELB-HealthChecker/2.0"],"Accept-Encoding":["gzip, compressed"]},"tls":{"resumed":false,"version":771,"cipher_suite":49199,"proto":"","proto_mutual":true,"server_name":""}},"common_log":"192.168.14.172 - - [01/Apr/2022:21:11:52 +0000] \"GET / HTTP/1.1\" 0 0","user_id":"","duration":0.00000427,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
```

Also in my GitLab App I have these scopes authorized:
<img width="845" alt="image" src="https://user-images.githubusercontent.com/11683992/161342344-ac3db9c0-f89b-4671-9317-c35301d1212f.png">

While when look in GitPod it shows:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/11683992/161342443-ccf33d9e-625e-4db9-be2d-db3e149f557a.png">

when try to "update permissions" with selected scope it says 

"Oh, no! Something went wrong! Authorization with "gitlab.com" is not permitted."

**Comment by pawlean** [comment] 2022-04-02 19:18
Thanks for reporting @vavdoshka! I've assigned this to the relevant Engineering team.

**Comment by corneliusludmann** [comment] 2022-04-06 08:52
Thanks for reporting. I'm closing this issue as a duplicate of #8536. Please let me know in case you disagree.

**Closed by corneliusludmann** 2022-04-06 08:52 UTC
Labels: type: bug, git provider: gitlab, self-hosted, team: webapp
