### ISSUE TITLE
bower install ETIMEDOUT

### ISSUE THREAD

**Issue by mikepsinn** [gitpod-io/gitpod#409] opened 2019-03-24 16:42 UTC
**Describe the bug**
 `bower install` returns `ETIMEDOUT Request to https://registry.bower.io/packages/ngFitText failed: ETIMEDOUT` for all packages.  Packages not installed.

**To Reproduce**
- Clone https://github.com/QuantiModo/quantimodo-android-chrome-ios-web-app
- `npm install -g bower`
- `bower install` in root of repo

**Expected behavior**
Should install packages to src/lib folder.

**PS**
Also, thanks for all your great work here. It's really an awesome platform!  :D

**Comment by mikepsinn** [comment] 2019-03-24 16:46
It's not a temporary issue because I've been facing it for a week.

**Comment by meysholdt** [comment] 2019-03-25 13:14
Interesting. I can reproduce the issue and I also get the following message (among others):

```
Request to https://registry.bower.io/packages/ngFitText failed with ETIMEDOUT, retrying in 1.2s
```

However, when I run `wget https://registry.bower.io/packages/ngFitText` I get the expected (I believe) response from the server, which is 
```
{"name":"ngFitText","url":"https://github.com/patrickmarabeas/ng-FitText.js.git"}
```

I get the same response when I run wget locally.

So I assume the network connectivity in Gitpod is ok.

**Comment by svenefftinge** [comment] 2019-03-25 14:32
> So I assume the network connectivity in Gitpod is ok.

Still it doesn't work reliably while locally it does.

**Comment by jankeromnes** [comment] 2019-03-26 07:06
See also https://stackoverflow.com/questions/22915961/bower-install-failed-with-etimedout

Maybe `bower` doesn't like Gitpod's workspace network configuration? There might be something we can do with ENV variables or a `.bower` config.

**Comment by meysholdt** [comment] 2019-03-26 10:20
This turns out to be a DNS issue. It took a while to diagnose this, but the good news is that we should be able to fix it.

**Comment by mikepsinn** [comment] 2019-03-26 16:29
Thanks so much, @meysholdt! 😀

**Comment by meysholdt** [comment] 2019-03-28 07:25
this is fixed now, please try again. 

After opening https://gitpod.io/#https://github.com/QuantiModo/quantimodo-android-chrome-ios-web-app and installing bower via `npm install -g bower`, the command

`time bower install` finishes successfully within 
```
real    0m13.813s
user    0m12.097s
sys     0m6.937s
```

**Closed by meysholdt** 2019-03-28 07:25 UTC
