### ISSUE TITLE
Minio rapidly increasing size (> 160GB) due to prebuilds not being deleted as expected

### ISSUE THREAD

**Issue by Torsten85** [gitpod-io/gitpod#12416] opened 2022-08-25 23:01 UTC
### Bug description

In our gitpod instance, we are currently 3 users with about 6 workspaces in total.
Our server did just run out of free storage space... after investigation, I found that the minio volume is about 160 GB now. Inside there are 3 user folders with more that a 100(!) subfolders in  `/var/lib/k3s/storage/pvc-..._gitpod_minio/gitpod-user-.../workspaces`.

So what are those? Snapshots? Because there is no way we had such many workspaces over all... and we didn't intentionally creating snapshots either. 
Today I had only one workspace active but the number of folder in my minio user directory kept growing. 

### Steps to reproduce

Just use the system and monitor the needed storage space

### Expected behavior

gitpod should not create those files or at least automatically remove them.

### Anything else?

The recommended `calico` backend did not work in our environment, so we kept the default `flannel` backend. But that seems unrelated.

**Comment by kylos101** [comment] 2022-08-26 17:16
hey @Torsten85 :wave: , those are indeed backups for old workspaces, which you can restart. Can you share the version of Gitpod that you're running for posterity? 

There is a mechanism in our `server` component that cleans up old snapshots, however based on what you're describing it sounds like it isn't triggering soon enough, or configured at all, to prevent your disks from filling up. For example, when triggered, it'd delete the files from object storage, and update the database records in the database accordingly (so that you cannot restart a workspace where its snapshot has been removed). 

Hey @jimmybrancaccio :wave: , have you worked this type of support question before? If no, may I ask you to escalate to the webapp team (cc: @gitpod-io/engineering-webap ). Also, I'm not sure what installer default is being used configuration wise to do object storage maintenance, but, it might make sense to double check that, too.

cc: @pawlean for posterity

**Comment by kylos101** [comment] 2022-08-26 17:52
@geropl moving to webapp inbox [because of :point_up: ](https://github.com/gitpod-io/gitpod/issues/12416#issuecomment-1228737672).

**Comment by geropl** [comment] 2022-08-29 07:17
Hey @Torsten85 , could you provide an example of the folder structure you're observing? :thinking:
Is it really workspace backups that are being created? Or is it other data (we for instance store VSCode sync data there as well, and it depends on your extensions what and how much those store there)?

**Comment by Torsten85** [comment] 2022-08-29 07:43
hey @geropl, the folder structure is quite simple:

in `/var/lib/rancher/k3s/storage/pvc-3d06009f-e1f3-456d-9f59-ad5dd2ad637e_gitpod_minio` is one subfolder per gitpod user: 

```
ls -l
drwxr-xr-x 4 1001 root 4096 Aug  8 14:21 gitpod-user-5bd913c2-1d08-48ac-ac9f-95696f280d87
drwxr-xr-x 4 1001 root 4096 Jul 28 10:24 gitpod-user-9c0b129b-0d23-4514-ad5f-705ccd664b9c
drwxr-xr-x 4 1001 root 4096 Aug 19 08:55 gitpod-user-ce699d72-e9cb-49dd-a71c-28efdfa2b547
```

in each user folder are blobs and workspaces:
```
cd gitpod-user-ce699d72-e9cb-49dd-a71c-28efdfa2b547/
du -sh *
724K	blobs
58G	workspaces
```

and in the workspaces folder are a lot of subfolders:
```
cd workspaces
du -sh *
3.3G	websites-1im9hkouy0z
696M	svausweismo-0p4cf7xorof
714M	svausweismo-0pyyu5w2ih8
1.1G	svausweismo-69a1buw7bo9
1.4G	svausweismo-6f5r5gnmf08
599M	svausweismo-6g8iwa8vpuh
1.4G	svausweismo-6rwwfq0e4h3
599M	svausweismo-7iadml74nlg
1.4G	svausweismo-7qq6cnu27o1
695M	svausweismo-7w2tjrk2d1y
694M	svausweismo-8c41gp5trxg
1.4G	svausweismo-8eja5nfjcl9
1.4G	svausweismo-8vjd8fvci52
16M	svausweismo-951wn31i7jf
695M	svausweismo-a74dydbzfjq
694M	svausweismo-ajq402stie8
2.7G	svausweismo-ansytz97txs
695M	svausweismo-ar22mrlg8ul
695M	svausweismo-cloepw8o5d5
4.1G	svausweismo-crxmanour8d
695M	svausweismo-cujj2n3ckun
602M	svausweismo-d7mtxjx7rev
695M	svausweismo-ebyxvradsz3
599M	svausweismo-ef1rvvgsvhp
3.8G	svausweismo-eoi3lo5mpou
3.4G	svausweismo-f9l0lccm453
1.4G	svausweismo-fp0adscpgr5
1.4G	svausweismo-g2ueoo0terx
694M	svausweismo-gphf1gmise1
589M	svausweismo-hj8yq1piest
695M	svausweismo-ird5xjb99of
1.3G	svausweismo-j40k9yo9tlg
1.4G	svausweismo-kpbapimrpi3
1.7G	svausweismo-kr6exy66dkq
1.3G	svausweismo-mikorr92859
1.4G	svausweismo-o5pnlkfq8du
1.3G	svausweismo-q81bxml0xbs
1.1G	svausweismo-qwfbmsenk5m
120M	svausweismo-rpw29h40gz2
599M	svausweismo-sjhvxgjx3di
2.7G	svausweismo-snc3mbryllj
16M	svausweismo-tezwn319p92
1.8G	svausweismo-u2b5wlrnsb8
695M	svausweismo-ubayl4lidy6
1.3G	svausweismo-utk29vl1eea
1.4G	svausweismo-vt801t88ohm
481M	svausweismo-vvzxoawui99
431M	svausweismo-wnjijgyklql
715M	svausweismo-yjaobmt0lko
```

each subfolder in workspaces simply has a `full.tar` file:
```
cd websites-1im9hkouy0z/
du -sh *

3.3G	full.tar
```


But the user im using as an example here currently has no workspaces (neither active nor inactive)

**Comment by Torsten85** [comment] 2022-09-01 09:44
Small addition: Reinstalled everything, this time with the `calico` backend, but the folders are growing again.

**Comment by geropl** [comment] 2022-09-06 07:08
Thank you @Torsten85 ! Based on that data I think the workspaces you're seeing there are Prebuilds. This might be if you are the one who registered the prebuild webhook.

Either:
 A) The workspace deletion is broken with minion (rather unlikely, but easy to reproduce + verify)
 B) Prebuild GC is not or mis-configured. Or it works as expected, but the period to keep them alive is too big.

**Comment by Torsten85** [comment] 2022-09-06 10:12
@geropl Thanks. You are right... only the users who have registered the prebuild hook seeing the rapidly increasing folder count!

So I think its case "B". But how do I configure the prebuild garbage collector? I've just used kots to install everything.

**Closed** 2022-09-26 09:12 UTC
Labels: type: bug, self-hosted, component: server
