### ISSUE TITLE
Cant create workspace

### ISSUE THREAD

**Issue by mauroindigne** [gitpod-io/gitpod#1235] opened 2020-02-19 06:58 UTC
### Describe the bug

When opening a new Gitpod of this template, im greeted with and error message and can not open my workspace 
### Steps to reproduce

- Open a template
- click Green "gitpod" button
- message pops up with error 
### Expected behavior

I need my work space to be opened.

**Comment by svenefftinge** [comment] 2020-02-19 07:28
thanks for reporting, it is a duplicate of #1236

**Closed by svenefftinge** 2020-02-19 07:28 UTC

**Comment by svenefftinge** [comment] 2020-02-19 07:30
works again, sorry for this.
