### ISSUE TITLE
We are having trouble parsing your context Error: GitHub API Error. Status: 500

### ISSUE THREAD

**Issue by Viserion77** [gitpod-io/gitpod#3211] opened 2021-02-17 22:15 UTC
### Describe the bug

A can't create my workspace...

### Steps to reproduce

Click here
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/Viserion77/Digital-Park)

### Expected behavior

Open workspace and install docker image of flutter

### Additional information

Before I had already created workspace, but I deleted it to recreate and test

### Example repository

https://github.com/Viserion77/Digital-Park/tree/Viserion77/gitpod-setup

**Comment by AlexTugarev** [comment] 2021-02-18 06:28
Hi @Viserion77, thanks for reporting!
From our metrics and logging this looks looks like an error from GitHub API servers. There was an incident reported in https://www.githubstatus.com/incidents/bnd3tpf66m0b. Though they don't mention the API endpoints, we've seen GitHub server errors (code 500) at that time. 
As the issue with GitHub is already resolved, please try again. I could no longer reproduce the error from above.

**Comment by csweichel** [comment] 2021-02-18 08:37
Closing for now. If the issue persists, pelase re-open.

**Closed by csweichel** 2021-02-18 08:37 UTC
Labels: git provider: github
