### ISSUE TITLE
My workspace will not start "OCI runtime create failed"

### ISSUE THREAD

**Issue by wadeziegler** [gitpod-io/gitpod#1513] opened 2020-05-15 01:51 UTC
### Describe the bug
My workspace will not start with the following error.
failed to create containerd task: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/theia/supervisor\": stat /theia/supervisor: no such file or directory": unknown
Please file an issue if you think this is a bug.

### Steps to reproduce
From Gitpod workspaces page, start the workspace https://d0a61b19-78d1-4ec3-9787-32930729e2a1.ws-us02.gitpod.io/

### Expected behavior
My workspace should start.

### Additional information
https://d0a61b19-78d1-4ec3-9787-32930729e2a1.ws-us02.gitpod.io/

### Example repository
This is a private repository.
![image](https://user-images.githubusercontent.com/3179523/82002821-b39a4b80-9613-11ea-891d-63b19d239544.png)

**Comment by carlosdp** [comment] 2020-05-15 01:56
Same happening to my team, looks like an outage

**Comment by Kreyren** [comment] 2020-05-15 04:39
Closing as duplicate of https://github.com/gitpod-io/gitpod/issues/1511

**Closed by Kreyren** 2020-05-15 04:39 UTC
