### ISSUE TITLE
Investigate how to add support for AWS ECR

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#14914] opened 2022-11-24 08:42 UTC
Investigate how to achieve ~https://github.com/gitpod-io/gitpod/issues/14891~ #12104 

- [x] ~build eks environment~ (We use the preview env with private AWS ECR)
- [x] setup private ECR
- [x] setup identity in IAM with proper roles
- [x] setup service account in EKS to use identity from ☝ 
- [x] run some experiments to determine a design that works. Options:
   - [x] ...define an ECR secret that rotates every 12h (because it expires after that amount). See [this](https://github.com/gitpod-io/gitpod/issues/14914#issuecomment-1329603328) for a summary and follow the link for background.
   - [x] ...setup a service account, and use it to get a JWT with `registry-facade` and `image-builder-mk3`
   - [x] ...setup a service account, and use it to get a JWT with `blobserve`
 
The AWS SDK will be helpful for both. To prototype sooner, it might be easier to start off by experimenting using the AWSCLI.

**Comment by atduarte** [comment] 2022-11-24 08:44
@kylos101 suggestion for image-builder-mk3:

### Possible idea

Have bob proxy (which runs in a separate network and mount namespace [[1](https://github.com/gitpod-io/gitpod/blob/bce5754a359c44784355c6a94c79eacc63649139/components/workspacekit/cmd/rings.go#L547)][[2](https://github.com/gitpod-io/gitpod/blob/bce5754a359c44784355c6a94c79eacc63649139/components/image-builder-mk3/pkg/orchestrator/orchestrator.go#L376)][[3](https://github.com/gitpod-io/gitpod/blob/bce5754a359c44784355c6a94c79eacc63649139/components/image-builder-bob/cmd/proxy.go#L95-L96)]) [exchange a service account OIDC token for AWS role credentials via STS](https://aws.amazon.com/es/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/#:~:text=Now%20you%20can,call%20manually%3A), and use the credentials to [push to ECR](https://docs.aws.amazon.com/AmazonECR/latest/userguide/security_iam_service-with-iam.html#security_iam_service-with-iam-roles).

In workspacekit, read the service account file's token into memory, hide the service account file from the workspace container somehow (see protecting the service account, below), and store it as an environment variable beginning with WORKSPACEKIT_ ([so it's not added to the workspace envs](https://github.com/gitpod-io/gitpod/blob/bce5754a359c44784355c6a94c79eacc63649139/components/workspacekit/cmd/rings.go#L369-L374))
bob proxy reads the new WORKSPACEKIT_<var> environment variable to get the service account token.
bob proxy exchanges the service account token for an AWS credential using awscli
bob proxy uses the credential to do auth for pushing images.

### Protecting the service account

If we add the service account to the imagebuild pod, it'll be available to the workspace container's file system. We cannot delete the service account from the file system because it is read-only. But, we need to prevent bob build from being able to access&use the service account for image build workloads, while allowing bob proxy to exchange the service account for an AWS role credential. 🤔

Perhaps we can do something with ws-daemon, to change the mount for the service account on the workspace container? For example, after workspacekit prepares the WORKSPACEKIT_<var> environment variable, alter the mount such that it points at an empty file ([similar in concept to this, but done at runtime](https://stackoverflow.com/a/38536698))? 🤷

### Limitations
We'll need to check for STS limitations. For example, say we have two or more image builds running, can they all negotiate credentials and push to ECR at the same time using the same service account? It's possible (1) subsequent exchanges invalidate prior credentials, causing image pushes to fail (2) subsequent exchanges fail until the first one is expired or enters a grace period, causing image pushes to fail (and perhaps forcing us to cache and centralize negotiated credentials).

**Comment by kylos101** [comment] 2022-11-28 19:04
@sagor999 a second option, is option 2 [here](https://github.com/gitpod-io/gitpod/issues/12104), where we support ECR, but rotate a secret on a schedule (say every 12h) rather than leverage a service account to retriever a JWT token at runtime.

**Comment by kylos101** [comment] 2022-11-29 01:52
@sagor999 moving to `in-progress` as this is actively being worked. 

Also, also a heads up, the werft jobs you used to produce AWS infra will "dispose" of the AWS infra after a time period (I think 24h).

So, if you need it to persist, we should follow-up with @adrienthebo. I believe he can help us "keep it around" until we're ready to delete it.

**Comment by csweichel** [comment] 2022-11-29 09:50
image-builder, bob proxy and registry-facade all serve their auth using the [`dockerconfigjson`](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) format. Bob proxy requires this data to be in a secret so that we need not pass this data to image build workspaces.

All hiding from actual workloads is already implement in bob proxy, nothing needs to change here.

We already have automatic reloading of the relevant secrets in image-builder and registry-facade (#14679). All we need now is something that updates those secrets. @mrzarquon produced a first version of such a mechanism: https://github.com/mrzarquon/ecr-registry-refresh/blob/wip/k8s/main.py#L42-L46. The equivalent function in Go is [`GetAuthorizationToken`](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ecr#Client.GetAuthorizationToken).

Given the far reaching permissions required to update the secret (`get` and `patch`/`update` on secrets within the namespace), it seems prudent to run this updater as separate deployment rather than give the image-builder SA such wide ranging permissions.

**Comment by kylos101** [comment] 2022-12-02 21:04
@jenting, may we ask for your help with this issue? Also, let me know if you have AWS experience or not. If you do not, we might want to see if we can get you some sync time with someone who does, to help serve as a primer/shortcut.

I [requested](https://gitpod.slack.com/archives/C020VCB0U5A/p1670012195883039) AWS access for you. 🙏 

[This comment](https://github.com/gitpod-io/gitpod/issues/14914#issuecomment-1330361811) from Chris describes an ideal solution that we could use.  Let's catch up when you return on Monday?

**Comment by jenting** [comment] 2022-12-05 11:35
> @jenting, may we ask for your help with this issue? Also, let me know if you have AWS experience or not.

Yes!
 
> [This comment](https://github.com/gitpod-io/gitpod/issues/14914#issuecomment-1330361811) from Chris describes an ideal solution that we could use. Let's catch up when you return on Monday?

I will
- bootstrap a AWS EKS cluster with [terraform + kots to install the Gitpod](https://github.com/gitpod-io/gitpod/tree/main/install/infra/single-cluster/aws).
- use the repo https://github.com/nuxeo-cloud/aws-iam-credential-rotate#rotate-ecr-credentials to proof and test the ECR credential rotation works as expected.

@csweichel will we garbage collect the old container image? I ask because I know we will remove the workspace content from object storage once the workspace is removed over X days. But I am not sure about the behavior of the container image garbage collection part.

**Comment by kylos101** [comment] 2022-12-05 16:29
@jenting does ECR have any GC capabilities that are "native"? For example, if an image isn't pulled after X days, delete it.

**Comment by kylos101** [comment] 2022-12-05 20:35
@jenting [internally](https://gitpod.slack.com/archives/C02F19UUW6S/p1670247525598599?thread_ts=1670198410.247859&cid=C02F19UUW6S), you mentioned:

> , I will use the [repo](https://github.com/nuxeo-cloud/aws-iam-credential-rotate#rotate-ecr-credentials) and run it as a sidecar container to periodically rotate the ECR credential.

A sidecar in which pod? Why a sidecar? I ask because of @csweichel 's [comment](https://github.com/gitpod-io/gitpod/issues/14914#issuecomment-1330361811): 

> it seems prudent to run this updater as separate deployment rather than give the image-builder SA such wide ranging permission

For example, why not run a separate deployment or cronjob?

**Comment by kylos101** [comment] 2022-12-06 22:41
> @csweichel will we garbage collect the old container image?

@jenting good question! May I ask you to create a separate issue and add to the Team Workspace inbox? 🙏 

cc: @aledbf and @csweichel for 👀

**Comment by kylos101** [comment] 2022-12-07 01:04
For posterity, @jenting tested a prototype with a Kubernetes Cronjob, and it worked well. He's still working through some 401 and 502 errors. @jenting please share solution details with @csweichel and @aledbf , including anticipated failure modes, and how we might alert/recover. :pray:

**Comment by jenting** [comment] 2022-12-07 13:59
I found the root cause of the HTTP status 401 and 502 errors.

It's because credentials requests from the [nexeo-cloud/aws-iam-credential-rotate repo](https://github.com/nuxeo-cloud/aws-iam-credential-rotate#rotate-ecr-credentials) are the private ECR endpoint (and it did not support request public ECR credential now). But I created a public ECR registry for testing. Why did I choose the public ECR registry? Because I check our GCP uses a public container registry for the base-image and workspace-image folders.

@csweichel for AWS ECR, do we need to change it to a private registry? Because I think it's more secure, and the container image built for users might contain credentials or security information.

- 👍 I did a hack to use a public ECR credential + AWS public ECR registry, and the image build works.
- 👎 I tested using a private ECR credential + AWS private ECR registry, and the image builds failed with an unauthorized error (I think some of the code does not use credentials to check whether the image exists or not).
![image](https://user-images.githubusercontent.com/49380831/206197734-e4f2116d-e022-4b83-811d-9b4f0bf1cb47.png)

I'd like to know the AWS ECR security strategy (public or private) and then choose which way to go next.

**Comment by csweichel** [comment] 2022-12-07 15:16
> 

What do the logs of image-builder say?

**Comment by jenting** [comment] 2022-12-08 01:42
@kylos101 said that Gitpod Dedicated is security first.
So I will go the way to make the image-builder work well against private container registry.

**Comment by jenting** [comment] 2022-12-08 05:35
> > 
> 
> What do the logs of image-builder say?

The bob proxy said

```console
#5 exporting config sha256:cf5d3a5ee979d18090785869b3c0c7a02759992aa2701a939fb1ec51979c7ccc 0.0s done
#5 pushing layers
{"file":"auth.go:30","func":"func1","host":"691173103445.dkr.ecr.us-west-1.amazonaws.com","level":"info","message":"authorizing registry access","serviceContext":{"service":"bob","version":""},"severity":"INFO","time":"2022-12-08T03:34:20.545741577Z","user":""}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","URL":"https://691173103445.dkr.ecr.us-west-1.amazonaws.com/v2/build/base-images/blobs/sha256:418ad0ba0e8c4c1788f10e2a5a4bdceb6a7f3d02a19139dc430b3bacf73a221e","error":"failed to find supported auth scheme: not implemented","file":"proxy.go:183","func":"func1","level":"warning","message":"cannot add responses although response was Unauthorized","serviceContext":{"service":"bob","version":""},"severity":"WARNING","time":"2022-12-08T03:34:20.546035691Z"}
```

**Comment by jenting** [comment] 2022-12-08 07:21
Remove the `https://` from the credential auth file, the image push to and pull from the remote private AWS ECR works well.

It was
```json
{
  "auths": {
    "https://$ACCOUNTID.dkr.ecr.$REGION.amazonaws.com": {
      "auth": 
    }
  }
}
```

to

```json
{
  "auths": {
    "$ACCOUNTID.dkr.ecr.$REGION.amazonaws.com": {
      "auth": 
    }
  }
}
```

**Comment by kylos101** [comment] 2022-12-08 15:46
@jenting , how does the following behave?

1. an imagebuild workspace starts with current credentials (A)
2. immediately following the imagebuild start, but after bob proxy has already started, the credentials are rotated (creating a new secret, B)
3. is bob proxy still able to push the image?

**Comment by kylos101** [comment] 2022-12-08 22:53
@jenting I was talking with @aledbf , and there's an additional challenge that you'll need to consider for when working with ECR. 

The challenge is, the image build process must be able to create the image repository at the time of image build. In other words, our understanding is, the repo is created now when working with ECR. 

What is your experience so far? For example, when building images, if you try in two different Git repos, in two separate branches in each Git repo, how many image repos get created in ECR? 2, 4, or something else? I'm not sure what constraint would cause image builder to need to create a new repo.

**Comment by jenting** [comment] 2022-12-09 05:48
> The challenge is, the image build process must be able to create the image repository at the time of image build. In other words, our understanding is, the repo is created now when working with ECR.

From my understanding now. The image-builder registry working with ECR is from these two [baseImageRepository, and workspaceImageRepository](https://github.com/gitpod-io/gitpod/blob/f3fcfbf003425f947bf3a0a28e452709623b6d74/components/image-builder-mk3/config-schema.json#L9-L10).

I did test two Git repos with image builds. The container images are push under baseImageRepository, and workspaceImageRepository. So, I haven't found a scenario in the image-builder that needs to create a new container registry.

FYI: [AWS does not support creating the container registry](https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html#:~:text=The%20Amazon%20ECR%20repository%20must%20exist%20before%20you%20push%20the%20image.) during `docker push` command.

**Comment by jenting** [comment] 2022-12-09 08:29
For registry-facade: 
1. Mirror the container images `supervisor`, `workspacekit`, `docker-up` from the GCP container registry to AWS private ECR.
2. Change the registry-facade configmap and restart registry-facade.
3. All works well with open the workspace, prebuild, and image build.

**Comment by jenting** [comment] 2022-12-09 12:08
For Deployment `blobserve`, `ide-service`, `server`, `ws-proxy`:
1. Mirror the container images `supervisor`, and `ide/code` from the GCP container registry to AWS private ECR.
   Check the ConfigMap `ide-config`, so we know which [supervisor container image](https://github.com/gitpod-io/gitpod/blob/44dfc5e19be3b89d96ab25f2f83476d57aa7b8ef/install/installer/pkg/components/ide-service/ide_config_configmap.go#L56) and [ide/code container images](https://github.com/gitpod-io/gitpod/blob/44dfc5e19be3b89d96ab25f2f83476d57aa7b8ef/install/installer/pkg/components/ide-service/ide_config_configmap.go#L88-L89) we need to mirror.
2. Update the ConfigMap `blobserve`, `ide-config`, `server-ide-config`, `ws-proxy` from GCP container registry to AWS private ECR.
3. Rollout restart the Deployments
    ```console
    kubectl rollout restart deploy/blobserve
    kubectl rollout restart deploy/ide-service
    kubectl rollout restart deploy/server
    kubectl rollout restart deploy/ws-proxy
    ```
4. Open the workspace, check the workspace and IDE can launch

**Comment by jenting** [comment] 2022-12-09 12:18
> @jenting , how does the following behave?
> 
> 1. an imagebuild workspace starts with current credentials (A)
> 2. immediately following the imagebuild start, but after bob proxy has already started, the credentials are rotated (creating a new secret, B)
> 3. is bob proxy still able to push the image?

I triggered rotate AWS ECR credential every minute and keep running the image build several times. All good.

**Comment by aledbf** [comment] 2022-12-09 12:27
> FYI: [AWS does not support creating the container registry](https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html#:~:text=The%20Amazon%20ECR%20repository%20must%20exist%20before%20you%20push%20the%20image.) during docker push command.

Yes, that feature needs to be added in image-builder-bob, before pushing the image to ECR.

**Comment by kylos101** [comment] 2022-12-12 00:45
To recap, a container registry is a collection of container repositories, and a container repository is a collection of images.

> So, I haven't found a scenario in the image-builder that needs to create a new container registry.

There is no scenario where `image-builder` must create a container registry. 

`image-builder` "may" need to create repositories before image build can be successful, though. @jenting , when you did the `image-builder` testing, how did you create the `baseImageRepository` and `workspaceImageRepository` repositories? Was it explicitly done before image build, or implicitly done as part of image build? 

If you delete both `baseImageRepository` and `workspaceImageRepository` from the registry in ECR , and then run an image build again, what happens? Do you have to create the repos? Does another process create the repos implicitly?

> @aledbf could you elaborate more on the scenario that would trigger the image builder to create a new container registry?

There should be no scenario where image builder creates a new container registry. The `container registry` must be created before we install Gitpod, so it's hostname can be specified at install time.

> FYI: [AWS does not support creating the container registry](https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html#:~:text=The%20Amazon%20ECR%20repository%20must%20exist%20before%20you%20push%20the%20image.) during docker push command.

@jenting do you mean AWS does not support creating the container repository for `baseImageRepository` and `workspaceImageRepository` at `docker push` time? If it does not support, how is image build being successful? Something must be creating them.

**Comment by jenting** [comment] 2022-12-12 01:11
For the baseImage and workspaceImage repositories, I created them manually.

**Comment by kylos101** [comment] 2022-12-12 01:43
> For the baseImage and workspaceImage repositories, I created them manually.

Thank you for clarifying, @jenting ! 🙏 

It looks like there is an explicit `CreateRepository` [permission](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonelasticcontainerregistry.html#amazonelasticcontainerregistry-actions-as-permissions:~:text=Grants%20permission%20to%20create%20an%20image%20repository) available. 

Does the secret we're using with `image-builder-bob` have rights to create repositories? It would be nice, perhaps as part of `bob proxy`, such that if no repo exists, `bob proxy` created the repos before pushing. This way, no image build and subsequent workspace start would ever fail due to the repos not existing, because if they do not exist, we'd create them.

**Comment by kylos101** [comment] 2022-12-12 03:21
In order to finish this investigation, so we can finish the implementation for ECR by Friday, Dec 16, we need the following:

- [ ] Define concrete permissions needed for the service account to interact with ECR. This will have a corresponding secret in the Kubernetes cluster.
   * The secret will be rotated by a new component (CronJob) which you'll create in #12104 
   * image-builder-bob will be updated in a separate issue so that `bob proxy` can leverage this secret to create base and workspaceImage repositories, so that it can then push related images that are built

**Comment by kylos101** [comment] 2022-12-12 03:46
@utam0k can you help us determine [which permissions](https://github.com/gitpod-io/gitpod/issues/14914#issuecomment-1345814079) are needed for the service account to interact with ECR?

**Comment by jenting** [comment] 2022-12-12 05:02
> We need the ECR credential updater to run immediately for the cluster fresh install. However, the Kubernetes CronJob does not support running first when the CronJob is created. So we could create a one-time Job first to update the ECR credential once. (The job is copied from the cronjob template).

@aledbf @csweichel 
Are you okay with this design? The cons I could think of is we probably will have two jobs running simultaneously. One is the job created by the CronJob; the other is the one-time job after a fresh installation. But it would not bring the race condition problem because the last rotation won. Just a bit nit that we need to create a one-time job dedicated to the cluster fresh installation.

**Comment by aledbf** [comment] 2022-12-12 14:23
@jenting I think we don't need the additional one-time Job. Assume we can do that when we install a new cell in Gitpod cloud as part of the bootstrap process.

**Comment by kylos101** [comment] 2022-12-12 14:26
Thanks @aledbf ! 

@jenting this means we need to build the binary with leeway and package it in a docker image (just like the installer). 

This way, we'll use the binary in two places:
1. The cron job
2. The cell boot strapping process @aledbf mentioned (to do this, they'll pull the binary from the docker image)

**Comment by kylos101** [comment] 2022-12-16 21:44
Closing as we now have refresh-credential component. 

Will create follow-on issues for:  
1. refresh-credential being installed in application cluster, so its pull secret can be refreshed
2. blobserve, to refresh its pull secret via a file watcher
3. s3 support to work with IRSA (a service account, and not require a secret with a client id and secret)
4. ecr support to work with IRSA (a service account, and not require a secret with a client id and secret)

**Closed by kylos101** 2022-12-16 21:44 UTC
