### ISSUE TITLE
Add native support for AWS ECR

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#14891] opened 2022-11-23 14:14 UTC
## Is your feature request related to a problem? Please describe

Provide native support to use ECR as a container registry and also allows the use of IAM Roles for Service Accounts (in pods)

## Additional context

https://aws.amazon.com/es/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

**Comment by kylos101** [comment] 2022-11-23 21:31
:wave: @csweichel today you mentioned this would impact `image-builder-mk3` and `registry-facade`. I'll leave this in a `breakdown` status, to show this requires investigation. 

@sagor999, when you return from vacation, may we ask you to investigate and socialize a proposed solution with @csweichel? 

I spent some time investigating `image-builder-mk3` :point_down:.

## image-builder-mk3

### Possible idea
Have `bob proxy` (which runs in a separate network and mount namespace [[1](https://github.com/gitpod-io/gitpod/blob/bce5754a359c44784355c6a94c79eacc63649139/components/workspacekit/cmd/rings.go#L547)][[2](https://github.com/gitpod-io/gitpod/blob/bce5754a359c44784355c6a94c79eacc63649139/components/image-builder-mk3/pkg/orchestrator/orchestrator.go#L376)][[3](https://github.com/gitpod-io/gitpod/blob/bce5754a359c44784355c6a94c79eacc63649139/components/image-builder-bob/cmd/proxy.go#L95-L96)]) [exchange a service account OIDC token for AWS role credentials via STS](https://aws.amazon.com/es/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/#:~:text=Now%20you%20can,call%20manually%3A), and use the credentials to [push to ECR](https://docs.aws.amazon.com/AmazonECR/latest/userguide/security_iam_service-with-iam.html#security_iam_service-with-iam-roles). 

   1. In `workspacekit`, read the service account file's token into memory, hide the service account file from the workspace container somehow (see **protecting the service account**, below), and store it as an environment variable for `WORKSPACEKIT_BOBPROXY_AUTH`
   2.  `bob proxy` reads the `WORKSPACEKIT_BOBPROXY_AUTH` environment variable now to get auth. Change `bob proxy` to optionally exchange the token for an AWS credential using `awscli`, and use the credential to do auth for pushing images.

### Protecting the service account
If we add the service account to the imagebuild pod, it'll be available to the workspace container's file system. We cannot delete the service account from the file system because it is read-only. But, we need to prevent `bob build` from being able to access&use the service account for image build workloads, while allowing `bob proxy` to exchange the service account for an AWS role credential. :thinking: 

Perhaps we can do something with `ws-daemon`, to change the mount for the service account on the workspace container? For example, after `workspacekit` prepares the `WORKSPACEKIT_BOBPROXY_AUTH` environment variable, alter the mount such that it points at an empty file ([similar in concept to this, but done at runtime](https://stackoverflow.com/a/38536698))? :shrug: 

### Limitations
We'll need to check for STS limitations. For example, say we have two or more image builds running, can they all negotiate credentials and push to ECR at the same time using the same service account? It's possible (1) subsequent exchanges invalidate prior credentials, causing image pushes to fail (2) subsequent exchanges fail until the first one is expired or enters a grace period, causing image pushes to fail (_and perhaps forcing us to cache and centralize negotiated credentials_).

**Comment by utam0k** [comment] 2022-11-25 00:20
Come to think of it, we do have experience with EKS. Maybe we can give ourselves some hints?
https://github.com/gitpod-io/amazonlinux-testing

**Comment by utam0k** [comment] 2022-11-25 00:23
@aledbf In terms of the registry-facade, the API basically follows the OCI distribution spec, so there should be no need to make any changes to that part of the API, right? Shouldn't there be an impact on IPFS?
Is it correct that the part that needs to be changed is the authentication and authorization part that uses the API?

**Comment by atduarte** [comment] 2022-11-28 10:43
Duplicate of #12104

**Closed by atduarte** 2022-11-28 10:43 UTC
