### ISSUE TITLE
Not able to login from github

### ISSUE THREAD

**Issue by naspnrd** [gitpod-io/gitpod#2904] opened 2021-01-14 12:14 UTC

**Comment by gtsiolis** [comment] 2021-01-14 12:33
Hi @naspnrd! Could you share more information on the issue? For example, what steps are you following and what errors or warnings are you seeing. 🏓

**Comment by AlexTugarev** [comment] 2021-01-14 13:10
Closing as duplicate of https://github.com/gitpod-io/gitpod/issues/2746

**Closed by AlexTugarev** 2021-01-14 13:10 UTC
Labels: aspect: auth, meta: :thinking: reporter-feedback-needed
