### ISSUE TITLE
Import GitHub App installations to Projects

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#4661] opened 2021-06-30 07:33 UTC
The problem to solve is to streamline the Gitpod App installation for prebuilds. Now that we introduce Projects to be associated with installations of the prebuild app, we might think of migrating the "old style" entries in the DB. Maintaining both adds unwanted complexity to the handling of prebuilds at least. 

One idea is to create projects for the currently active installations and add the installers as owner of the team to be created in the same process.

**Comment by svenefftinge** [comment] 2021-07-05 07:20
Can share more information about what the problem is you want to solve? Having an installation stored separtated from the project makes a lot of sense. What is "old style"?

**Comment by AlexTugarev** [comment] 2021-07-06 06:09
> Having an installation stored separated from the project makes a lot of sense.

We started out with storing the App installation ID attached to the project. Now that you are asking, I don't see a good reason to drop the extra sink for the installation.



Technically, the only thing to clean up would be the pending state of App installations, which we would drop eventually.

**Comment by jankeromnes** [comment] 2021-08-02 19:52
> Now that you are asking, I don't see a good reason to drop the extra sink for the installation.

Hmm, but does this mean that we no longer want to migrate the "old style" entries in the DB? (I.e. close this issue for now.)

From really far away, it seems unnecessary to me to "automagically" create new Projects & Teams for current installations. Better let users do that action explicitly (it's easy to create Project even if you already have the app installed, right?)

Are there really two pathways that add complexity to prebuilds? 🤔 Could be worth discussing in a call.

**Comment by AlexTugarev** [comment] 2021-08-03 05:54
> it's easy to create Project even if you already have the app installed, right?

have you tried that already?

Given the known issues with "OAuth vs GH-App", I'd see a fraction of installers not being able to see their installation in the New Project wizard. Importing as personal Project would remove that risk.

> Are there really two pathways that add complexity to prebuilds?

Which complexity do you mean? We already have the association of prebuilds to projects in place, the rest remains as is.

**Comment by gtsiolis** [comment] 2021-08-06 11:26
Closing this, following the update in https://github.com/gitpod-io/gitpod/issues/5076#issuecomment-894140788.

**Closed by gtsiolis** 2021-08-06 11:26 UTC
Labels: roadmap item: teams & projects, 🧑‍🚀 crew: teams and projects
