### ISSUE TITLE
Feedback Issue: 

### ISSUE THREAD

**Issue by DhanielB** [gitpod-io/gitpod#14621] opened 2022-11-11 14:52 UTC
### Objective

i'm having a lot of problems with gitpod, my time limit is over and i hadn't saved my files, now i'm about to be **fired**, if i don't submit the project by monday **my boss fires me**, **_HOPE SOME SOLUTION AND FAST_**

**Comment by axonasif** [comment] 2022-11-11 15:48
Duplicate of https://github.com/gitpod-io/gitpod/issues/14622

**Closed by axonasif** 2022-11-11 15:48 UTC
Labels: feedback-issue
