### ISSUE TITLE
Authorization failed

### ISSUE THREAD

**Issue by ramtoppo12** [gitpod-io/gitpod#2774] opened 2021-01-10 13:57 UTC
### Describe the bug

I dont able to login gitlab

**Comment by csweichel** [comment] 2021-01-11 06:42
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by csweichel** 2021-01-11 06:42 UTC
