### ISSUE TITLE
Investigate increase of InstanceStartFailures

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#11557] opened 2022-07-22 07:38 UTC
### Bug description

Today I was paged 3 times in a few hours for `InstanceStartFailures` at the following times:

- [8:01 am GMT+2 (22/07/2022)](https://gitpod.pagerduty.com/incidents/Q27ZN74YVD4ZLE)
- [9:06 am GMT+2 (22/07/2022)](https://gitpod.pagerduty.com/incidents/Q1HO75MF14E1NW)
- [10:49 am GMT+2 (22/07/2022)](https://gitpod.pagerduty.com/incidents/Q037I4YHGW3P5J)

By looking at the [Grafana dashboard](https://grafana.gitpod.io/d/Gj5DE-O7k/meta-overview?orgId=1&viewPanel=38&from=now-12h&to=now) it seems to be an increasing trend recently, so @geropl and I agreed on creating this ticket to schedule some investigations.

<img width="1654" alt="Screenshot 2022-07-22 at 09 36 47" src="https://user-images.githubusercontent.com/2318450/180388702-5164854f-7dd3-4d25-a8be-381863958502.png">

### Steps to reproduce

N/A

**Comment by geropl** [comment] 2022-09-01 08:00
FYI: A number of PRs has been merged to a) filter out noise b), but also improve logging and tracing of such events. Waiting for the next deployment to have more insights here.

**Comment by geropl** [comment] 2022-09-15 09:43
This root cause here has been fixed (bad reporting).

**Closed by geropl** 2022-09-15 09:43 UTC
Labels: type: incident, team: webapp
