### ISSUE TITLE
Omnisharp extension loading failed

### ISSUE THREAD

**Issue by hm2075** [gitpod-io/gitpod#7397] opened 2021-12-30 19:37 UTC
### Bug description

On restart of a workspace

![image](https://user-images.githubusercontent.com/53794682/147782893-a54aa09b-cffa-403f-87af-a6f68061a4d7.png)

refreshing the browser will usually cause the extension to install just fine,   or have to manually install it again from extensions

bug wasnt present in 0.10,    currently using main.2090 self hosted

### Steps to reproduce

dotnet core 5/6

add c#  extension ,   shutdown workspace,   start workspace

**Comment by TylerZeroMaster** [comment] 2022-01-12 16:53
I have been investigating a similar issue with the [redhat.vscode-xml](https://open-vsx.org/extension/redhat/vscode-xml) extension. 

Starting or reloading a workspace that has a xml document open commonly results in a variety of error messages and the absence of xml validation. If no xml document is open when your workspace loads, everything works as expected.

### Steps To Reproduce
1. Install the redhat.vscode-xml extension
2. Open a xml document
3. Reload the GitPod workspace

Some examples of errors I have seen are:
- Couldn't start client XML Support
- Downloading the XML Language Server... (progress dialog that never progresses)
- LemMinX not found, falling back to java version (missing file)
- Do you trust this extension (yes/no)

This might be an issue with the extension itself; however, the **errors occur during or before extension activation**. That makes it very difficult to say for sure.

I have not had these problems with the xml extension outside of GitPod.

**Comment by loujaybee** [comment] 2022-02-14 10:12
Moving to scheduled for investigation. @filiptronicek could you check if this is still an issue? 🙏

**Comment by filiptronicek** [comment] 2022-02-14 15:07
Hi there @hm2075 👋! Could you please provide a bit more detailed reproduction steps? You mentioned this not working in self hosted, have you tried using [gitpod.io](https://gitpod.io/)?

I tried to reproduce the issue, but I am not sure how to exactly check whether the extension is working, since I couldn't find any logs from the extension after just installing it (although I needed to install dotnet manually, after that, executing <kbd>CSharp: List process for attach</kbd> probably executed successfully, see attached screenshot)
<img width="475" alt="image" src="https://user-images.githubusercontent.com/29888641/153889448-e0aef4d1-e4e3-408e-9512-3fb7dd44a5c4.png">

**Closed** 2022-06-11 18:28 UTC
Labels: type: bug, meta: :thinking: reporter-feedback-needed, editor: code (browser), team: IDE
