### ISSUE TITLE
KOTS: prerender yaml & validate patch files, prior to proceeding with deploy

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#13149] opened 2022-09-21 00:59 UTC
## Is your feature request related to a problem? Please describe

Customer patch files do not get validated before we deploy. This can be painful during outage windows, where they're trying to proceed with an upgrade, have a malformed file, but don't necessarily know why the upgrade is failing.

## Describe the behaviour you'd like

A pre-flight check should fail if the patch file causes rendered yaml to fail validation. This would ideally prevent the upgrade from continuing and clearly show the administrator what failed.

## Describe alternatives you've considered

n/a

**Comment by kylos101** [comment] 2022-09-21 01:00
@lucasvaltl @corneliusludmann a customer ran into this issue recently when doing an update of a self-hosted Gitpod installation.

cc: @atduarte @aledbf

**Comment by corneliusludmann** [comment] 2022-09-21 05:46
Thanks, @kylos101 for raising this feature request. I'll close this as a duplicate of https://github.com/gitpod-io/gitpod/issues/12015.

We couldn't implement this easily in the past. However, the refactoring @MrSimonEmms did recently enables this. We will have this in the next release.

**Closed by corneliusludmann** 2022-09-21 05:46 UTC
Labels: self-hosted
