### ISSUE TITLE
Downloading a running workspace result in an error

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#5103] opened 2021-08-07 01:36 UTC
### Bug description

While a workspace is running, going to https://gitpod.io/workspaces and downloading that workspace results in this page -
![image](https://user-images.githubusercontent.com/22901/128583819-949d1f08-e75f-47e7-a0b6-b9e9e8a927e5.png)

### Steps to reproduce

1. Start a Gitpod workspace
1. Go to https://gitpod.io/workspaces
1. The running workspace should have a green circle to the left of it and a 3 vertical dots options-menu to the right of it.
1. Click on the options-menu, and choose Download
1. Confirm you see the error page as above.

### Expected behavior

The `Download` option should be disabled and not clickable from the options-menu of a running workspace.
or
Allow downloading a running workspace.

### Example repository

(any repo)

**Comment by pawlean** [comment] 2021-08-09 08:31
I confirm that I can replicate this issue as well 🤔  

![CleanShot 2021-08-09 at 09 30 33](https://user-images.githubusercontent.com/17087373/128678825-ca3b4bf4-9527-44bd-a5da-ad139fcded9b.png)

**Comment by gtsiolis** [comment] 2021-08-09 11:02
Thanks @shaal! Closing this as a duplicate of https://github.com/gitpod-io/gitpod/issues/4977. See also https://github.com/gitpod-io/gitpod/issues/4977#issuecomment-895131507.

**Closed by gtsiolis** 2021-08-09 11:02 UTC
Labels: type: bug
