### ISSUE TITLE
Unable to boot a Workspace : fails at "Building Workspace Image"

### ISSUE THREAD

**Issue by Poslovitch** [gitpod-io/gitpod#2429] opened 2020-12-05 10:55 UTC
### Describe the bug

A new workspace (generated from this link: https://gitpod.io/#https://github.com/Chocobozzz/PeerTube) is unable to boot up. It fails at "Building Workspace Image".

### Steps to reproduce

1. Click [this link](https://gitpod.io/#https://github.com/Chocobozzz/PeerTube)
2. Wait & see.

### Expected behavior

The Workspace should boot up properly.

#### Affected workspaces
1. `e67ef9b1-3713-4352-8200-f9944ea98aba`
2. `bb868edb-16cd-41b5-a154-d085a046f8c7`

#### Logs
```
Pulling from gitpod/workspace-postgres
Digest: sha256:6a8ab9f9da206eec85ef9ba061640bfbea453cbd59f671d4680bc4e648fd9314
Status: Image is up to date for gitpod/workspace-postgres:latest
 ---> 02309be800ad
Step 2/6 : ENV TRIGGER_REBUILD 1
 ---> Using cache
 ---> 2055f7f4f783
Step 3/6 : RUN sudo apt-get update -q && sudo apt-get install -qy  ffmpeg  openssl  redis-server
 ---> Using cache
 ---> c33204c54166
Step 4/6 : COPY --chown=gitpod:gitpod support/docker/gitpod/setup_postgres.sql /tmp/
 ---> Using cache
 ---> 0d5ce1365a46
Step 5/6 : RUN pg_start && psql -h localhost -d postgres --file=/tmp/setup_postgres.sql && pg_stop
 ---> Running in fae696d65071
mkdir: cannot create directory ‘/workspace’: Permission denied
pg_ctl: directory "/workspace/.pgsql/data" does not exist



build failed: cannot build base image: The command '/bin/sh -c pg_start && psql -h localhost -d postgres --file=/tmp/setup_postgres.sql && pg_stop' returned a non-zero code: 1

Error: build failed: cannot build base image: The command '/bin/sh -c pg_start && psql -h localhost -d postgres --file=/tmp/setup_postgres.sql && pg_stop' returned a non-zero code: 1
```

#### Screenshot

![image](https://user-images.githubusercontent.com/20014332/101240670-13ac2880-36f1-11eb-9c23-5c5e4addc654.png)

### Example repository

https://github.com/Chocobozzz/PeerTube

**Comment by jankeromnes** [comment] 2020-12-05 11:30
Hi again @Poslovitch, many thanks for filing this issue!

I think I know what the problem is. PeerTube's Gitpod Dockerfile attempts to initialize a PostgreSQL database:

https://github.com/Chocobozzz/PeerTube/blob/95bd9515b86e577033d9929c829c77c0df761acf/support/docker/gitpod/Dockerfile#L15

For some reason, this now fails with "Permission denied", when `pg_start` tries to create it with `mkdir -p`:

https://github.com/gitpod-io/workspace-images/blob/c9896cde76e0698b1ed1b93ad464d77f87dd96e6/postgres/Dockerfile#L13

Probably user `gitpod` is not authorized to create directories under `/`.

However, probably setting up the PostgreSQL database doesn't even make sense in the Dockerfile, because everything under `/workspace` will get replaced anyway when you start a Gitpod workspace (because `/workspace` is replaced by a mounted partition where the repository then gets cloned into -- i.e. everything you put in `/workspace` in the Dockerfile will be gone at runtime).

So, instead, I think the proper fix is to set up the PostgreSQL database not in the Dockerfile but in the `.gitpod.yml` tasks once the workspace is running. I'll prepare a PR.

**Comment by jankeromnes** [comment] 2020-12-07 08:49
Fixed in https://github.com/Chocobozzz/PeerTube/pull/3401

**Closed by jankeromnes** 2020-12-07 08:49 UTC
