### ISSUE TITLE
Prebuild is running but I cannot see the log

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#8394] opened 2022-02-22 15:42 UTC
### Bug description

It seems that the headless log server is not able to find the prebuild?

![image](https://user-images.githubusercontent.com/22901/155166758-2753e60d-4a6c-41eb-8730-2fb681e87830.png)

### Steps to reproduce

Start a prebuild, check the log?

**Comment by kylos101** [comment] 2022-03-02 21:41
Hi @shaal , this is a duplicate of #8446 and item number 1. I am going to close this, and recommend you subscribe to that issue.

**Closed by kylos101** 2022-03-02 21:41 UTC
Labels: type: bug, feature: prebuilds, team: webapp
