### ISSUE TITLE
Column 'avatarUrl' cannot be null

### ISSUE THREAD

**Issue by ranzbak** [gitpod-io/gitpod#4066] opened 2021-04-26 11:39 UTC
### Bug description

When some users connect, they need to accept the terms of service, and after that the interface stalls.
After +- 30 seconds the error "Sorry, something went wrong 😓 Error 504" appears.
For other users the tos accept works fine.

I'm runnig a self-hosted installation:
- Rancher 2.5
- RKE v1.19.9
- Kubernetes network layer Flannel
- Gitpod 0.8.0
- Gitlab 13.10.3-ee
- Deployment Helm and Helmfile

[gitpod-values.zip](https://github.com/gitpod-io/gitpod/files/6376726/gitpod-values.zip)

### Steps to reproduce

I log in to Gitlab as admin, impersonate on of the users that has the problem, and try to open a Gitpod session.

### Expected behavior

When accepting the terms of service, Gitpod continues to the workspace.

### Example repository

Sorry, something went wrong 😓
Error 504
Please file an issue if you think this is a bug.

### Anything else?

I have searched through the logs of Gitpod, but I can't find a reason why it should not work for some persons.
All users that authenticate on Gitlab, do so via Active directory credentials.

**Comment by ranzbak** [comment] 2021-04-26 14:46
Hi,

I found the problem, it seems that accounts without an avatar set in Gitlab, cannot use Gitpod.

This error is in the server log:
 QueryFailedError: ER_BAD_NULL_ERROR: Column 'avatarUrl' cannot be null

Adding an avatar to the user his account fixes the problem.

I'm not sure what I should do to allow users without an avatar image to access Gitpod.
A more specific error than '504' might have saved time finding the error, is improved error handling in the planning?

**Comment by ranzbak** [comment] 2021-04-26 14:54
Here the whole error:
```
"error": "QueryFailedError: ER_BAD_NULL_ERROR: Column 'avatarUrl' cannot be null\n    at new QueryFailedError (/app/node_modules/typeorm/error/QueryFailedError.js:27:28)\n    at Query.<anonymous> (/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:207:45)\n    at Query.<anonymous> (/app/node_modules/mysql/lib/Connection.js:502:10)\n    at Query._callback (/app/node_modules/mysql/lib/Connection.js:468:16)\n    at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)\n    at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)\n    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:278:23)\n    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:76:12)\n    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)\n    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:91:28)\n    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:502:10)\n    at Socket.emit (events.js:315:20)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:295:12)\n    at readableAddChunk (_stream_readable.js:271:9)\n    at Socket.Readable.push (_stream_readable.js:212:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)",
```

**Comment by AlexTugarev** [comment] 2021-04-28 07:41
Hi @ranzbak! Thanks for reporting!
It's strange that the self-hosted GitLab doesn't return any avatar URL, as it usually does even if a user didn't upload an image file.
Anyway this sounds like it can be fixed in Gitpod as well.

**Comment by ranzbak** [comment] 2021-05-05 11:20
Thanks, let me know when the fix has been merged, so I can roll out the fix.
It's less than ideal to instruct people to set an avatar, if they want to use Gitpod.

**Comment by JanKoehnlein** [comment] 2021-06-01 07:18
@AlexTugarev are you still on this or should we take over?

**Comment by AlexTugarev** [comment] 2021-06-01 07:19
@JanKoehnlein 🙏🏻  please go ahead and thanks 💯

**Comment by corneliusludmann** [comment] 2021-06-15 12:28
Unfortunately, I'm not able to reproduce this. Our self-hosted GitLab instance seems to set an avatar for each new user.

However, I think this change (https://github.com/gitpod-io/gitpod/commit/7be8e08cbb3613a0b3f4634506dda9541244edd1) would make sense in general and would also help to solve this particular problem:

```diff
diff --git a/components/gitpod-db/src/typeorm/transformer.ts b/components/gitpod-db/src/typeorm/transformer.ts
index 68a74d3c..7aa22ae9 100644
--- a/components/gitpod-db/src/typeorm/transformer.ts
+++ b/components/gitpod-db/src/typeorm/transformer.ts
@@ -11,7 +11,7 @@ import { EncryptionService } from "@gitpod/gitpod-protocol/lib/encryption/encryp
 export namespace Transformer {
     export const MAP_EMPTY_STR_TO_UNDEFINED: ValueTransformer = {
         to(value: any): any {
-            if (value === undefined) {
+            if (value === undefined || value === null) {
                 return '';
             }
             return value;
```

Alternatively, we could check here for `null`:

https://github.com/gitpod-io/gitpod/blob/dba6a376154a3a03ece93f4634333f705d5ee9e7/components/server/src/gitlab/gitlab-auth-provider.ts#L76-L76

@AlexTugarev What do you think?

**Comment by ranzbak** [comment] 2021-06-17 09:44
Looks like the patch that should solve this :-)

**Comment by AlexTugarev** [comment] 2021-06-18 09:58
@corneliusludmann, any idea why avatar_url is not present? I have not found a way to disable that. 

It's too bad, that the typings are not in sync with the API service.

**Comment by corneliusludmann** [comment] 2021-06-18 10:33
> @corneliusludmann, any idea why avatar_url is not present? I have not found a way to disable that.

No, was not able to reproduce. Tried gitlab.com and our self-hosted GitLab.

**Closed** 2021-06-18 10:43 UTC
Labels: aspect: auth, self-hosted, type: bug

**Comment by corneliusludmann** [comment] 2021-06-18 10:45
@ranzbak The issue is solved in the `main` brunch and will be deployed by the end of the month. Thanks for your patience.
