### ISSUE TITLE
Not creating new workspaces or opening existing ones

### ISSUE THREAD

**Issue by mparkcode** [gitpod-io/gitpod#1514] opened 2020-05-15 02:10 UTC
### Describe the bug

Hi, trying to create a new workspace or open an existing one results in the following error

failed to create containerd task: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/theia/supervisor\": stat /theia/supervisor: no such file or directory": unknown
Please file an issue if you think this is a bug.

This happens on workspaces created from the template https://github.com/Code-Institute-Org/gitpod-full-template

### Steps to reproduce
Try to create a new workspace or open existing

### Expected behavior
Workspace to be created / existing one to open

**Comment by bramrodrigo89** [comment] 2020-05-15 02:22
Hello, I am experiencing the same issue while creating a new workspace or opening an existing one.

**Comment by Kreyren** [comment] 2020-05-15 04:38
Relevant: https://github.com/gitpod-io/gitpod/issues/1511
Relevant: https://github.com/gitpod-io/gitpod/issues/1513

**Comment by Kreyren** [comment] 2020-05-15 04:39
Closing as duplicate of #1511

**Closed by Kreyren** 2020-05-15 04:39 UTC
