### ISSUE TITLE
I am having issues trying to open my project at gitpod.io    Evicted: Pod The node had condition: [DiskPressure]. Please file an issue if you think this is a bug.

### ISSUE THREAD

**Issue by dricajulio** [gitpod-io/gitpod#923] opened 2019-11-13 13:56 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by JesterOrNot** [comment] 2019-11-13 14:00
This is probably a Kubernetes issue

**Comment by jankeromnes** [comment] 2019-11-13 14:13
Hi @dricajulio, thank you for reporting this issue, and sorry that this is happening.

It looks indeed like a problem with one of our Kubernetes cluster nodes. We checked all production nodes, console and monitoring, but everything seemed fine on our side.

- Which geographical region are you in? (Europe, North America, or Asia?)
- And if you try opening your project again, does this problem still happen?

**Comment by yellow-strelitzia** [comment] 2019-11-15 02:26
Hi,
I had also encountered same issue, [DiskPressure].
My region is Asia, and re-open my project never resolve issue.
Hope this is helpful to find out root cause.

**Comment by RDIL** [comment] 2019-11-19 17:20
Same with #935 , but I'm in USWEST region

**Comment by jankeromnes** [comment] 2020-02-17 15:01
Closing as duplicate of #1080. Please add any more details there (workspace IDs, URLs, screenshots, etc).

**Closed by jankeromnes** 2020-02-17 15:01 UTC
