### ISSUE TITLE
something went wrong on login

### ISSUE THREAD

**Issue by SapnaDorbi** [gitpod-io/gitpod#2737] opened 2021-01-09 18:57 UTC

**Comment by dragonDScript** [comment] 2021-01-09 19:01
?

**Comment by akosyakov** [comment] 2021-01-10 06:27
Please go to gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by akosyakov** 2021-01-10 06:27 UTC
