### ISSUE TITLE
Clicking Login when already logged in causes 2 tabs to open

### ISSUE THREAD

**Issue by pzmarzly** [gitpod-io/gitpod#367] opened 2019-03-07 20:57 UTC
- be logged in
- tab 1: on `https://www.gitpod.io/index.html`
- click Open, tab 1 stays unchanged and opens tab 2 at `api.gitpod.io` or something like this.
- tab 2 opens tab 3 at `https://gitpod.io/workspaces/`
- tab 2 redirects itself to `https://gitpod.io/workspaces/`

You are left with 3 tabs, one at `https://www.gitpod.io/index.html` and two at `https://gitpod.io/workspaces/`

**Comment by svenefftinge** [comment] 2019-03-07 21:30
Outch. Thanks for reporting. We've changed a url (api.gitpod.io) today and it seems like the redirect logic is not working great...

**Comment by svenefftinge** [comment] 2019-03-08 09:31
Fixed now.

**Comment by pzmarzly** [comment] 2019-03-08 14:53
Nope, now it opens 2 tabs, both on `https://gitpod.io/workspaces/`, still that's 1 too many.

**Comment by jankeromnes** [comment] 2019-03-08 20:14
Hi @pzmarzly, thank you for reporting this issue! I was able to reproduce your problem, so re-opening.

> - be logged in

✔️

> - tab 1: on https://www.gitpod.io/index.html

✔️

> - click Open, tab 1 stays unchanged and opens tab 2 at api.gitpod.io or something like this.

I don't find any "Open" that I can click on in https://www.gitpod.io/index.html. Do you mean "Login"?

> - tab 2 opens tab 3 at https://gitpod.io/workspaces/

I only have 1 tab at this point, but when I click on "Login" in that tab, it indeeds opens https://gitpod.io/workspaces/ in another tab.

But then it also redirects itself to https://gitpod.io/workspaces/, just like you said.

I have now two tabs on https://gitpod.io/workspaces/, which is really strange.

**Comment by DiegoGca** [comment] 2019-03-11 08:47
I faced this issue weeks ago, however I did not report it because I thought it was an error by my side - had mouse problems.

**Comment by jankeromnes** [comment] 2019-03-13 12:54
This happens because the button is inside a `<a href="https://gitpod.io/api/login"> </a>`, but it also has `'click'`-listener `() => { window.open('https://gitpod.io/api/login'); }`.

I think the click listener can be removed.

**Comment by AlexTugarev** [comment] 2019-09-09 15:15
The issue is no longer present with the new website.

**Closed by AlexTugarev** 2019-09-09 15:15 UTC
Labels: bug, critical
