### ISSUE TITLE
Prebuild logs stop streaming

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#8684] opened 2022-03-09 11:16 UTC
When a prebuild is running, after some time the UI becomes unable to render streaming logs for the prebuild.

# Repro
1. Add/Clone https://gitlab.com/gitpod-milan/gitpod-large-image
1. Add the repository as a project to your Gitpod account
1. Push a commit to master of the repository
1. Navigate to the project view -> Prebuilds
1. Watch the logs, after around 5 minutes, no more logs are streamed
1. When the page is reloaded, no logs are shown at all (not even previous logs)
1. The same behaviour can be onbserved when starting a workspace from a context URL - https://gitpod.io/#https://gitlab.com/gitpod-milan/gitpod-large-image/-/tree/main - the view ends up being blocked. 

<img width="1360" alt="Screenshot 2022-03-09 at 11 59 05" src="https://user-images.githubusercontent.com/1419286/157431230-8a39bdeb-c5d3-4e63-9a11-2ad43d77cd72.png">
<img width="944" alt="Screenshot 2022-03-09 at 12 01 55" src="https://user-images.githubusercontent.com/1419286/157431241-78bbd083-61ec-4dd6-8fa7-9aa9eff51e74.png">
<img width="1445" alt="Screenshot 2022-03-09 at 12 03 47" src="https://user-images.githubusercontent.com/1419286/157431250-22577b57-2f1b-46a6-896d-d62d137259a4.png">
<img width="629" alt="Screenshot 2022-03-09 at 12 06 36" src="https://user-images.githubusercontent.com/1419286/157431290-eebf3741-742d-4011-9212-bd30049be26e.png">
<img width="891" alt="Screenshot 2022-03-09 at 12 06 41" src="https://user-images.githubusercontent.com/1419286/157431294-e43aa45e-444f-4bf5-a54a-469dcdfca934.png">

# Expected behaviour
* Logs continue to be streamed into the view, even after browser reloads and longer prebuilds

**Comment by laushinka** [comment] 2022-03-09 13:24
Can reproduce!

**Comment by easyCZ** [comment] 2022-03-09 13:27
As it happens, this particular prebuild also times out even though the task should complete after 10 minutes with an exit code 0.
Once it times out, logs become available. But only the logs up until the 5 minute mark, any logs after are not printed.

<img width="692" alt="Screenshot 2022-03-09 at 13 35 30" src="https://user-images.githubusercontent.com/1419286/157450827-feddd2fc-3faf-4286-a0a2-b9ab917ed7fa.png">

Once it fails, the logs contain a `context deadline` log message but display the failure at the top of the log stream, not at the bottom.

**Comment by geropl** [comment] 2022-06-09 11:30
@AlexTugarev This should have been fixed a while ago when Team IDE fixed a supervisor bug which caused every listener to hang when single listener got stuck with writing.

**Comment by AlexTugarev** [comment] 2022-06-10 06:59
Just double-checked this, and indeed this issue seems to be fixed by supervisor changes. Thanks @gitpod-io/engineering-ide!

<img width="1155" alt="Screen Shot 2022-06-10 at 08 58 00" src="https://user-images.githubusercontent.com/914497/173008595-342d3fd9-2c93-4826-9e3a-da0482a6b59e.png">

<img width="1068" alt="Screen Shot 2022-06-10 at 08 57 48" src="https://user-images.githubusercontent.com/914497/173008593-1c9b76d8-d0b1-4818-85af-6b3e59fe4747.png">

**Closed by AlexTugarev** 2022-06-10 06:59 UTC
Labels: type: bug, team: webapp
