### ISSUE TITLE
[browser extension] flakiess too much on github

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#14579] opened 2022-11-10 04:30 UTC
### Bug description

Not showing gitpod button.

![image](https://user-images.githubusercontent.com/3759816/201000802-5a9ab97b-7976-47ff-b161-cc70baaab8bd.png)

### Steps to reproduce

Not stable reproduce, but occured too frequently recently.

### Anything else?

Maybe add a second button just in case, see second arraw near sourcegraph button.

**Comment by axonasif** [comment] 2022-11-14 13:34
cc @corneliusludmann @gtsiolis

**Comment by gengjiawen** [comment] 2022-11-24 07:54
Anyone working on this ? This is quite annoying, happens everyday.

**Comment by gtsiolis** [comment] 2022-11-24 08:57
Hey @gengjiawen! I don't know anyone working on this.

Could you list some steps to reproduce this?

There are a couple more similar issues like https://github.com/gitpod-io/gitpod/issues/8171.

**Comment by gengjiawen** [comment] 2022-11-24 09:00
I think it's different, since my case the button disappears. Is it possible you can sentry to browser extension to track this ?

Or add a second button like sourcegraph ?

**Comment by gtsiolis** [comment] 2022-11-24 09:10
Can you confirm this is always the case even after page reload?

We did fix an issue with the button disappearing in https://github.com/gitpod-io/gitpod/issues/13609 but the button is still going invisible in some cases, especially after the introduction of the new browser on GitHub[[1](https://github.blog/2022-11-15-a-better-way-to-search-navigate-and-understand-code-on-github/)], https://github.com/gitpod-io/gitpod/issues/14117.

**Comment by gtsiolis** [comment] 2022-11-24 09:41
Thanks, @gengjiawen! Seems then like a duplicate of https://github.com/gitpod-io/gitpod/issues/14117. I'll close this one but feel free to reopen of this describes a different issue.

**Closed by gtsiolis** 2022-11-24 09:41 UTC
Labels: type: bug, component: browser-extension, good-first-issue

**Comment by gengjiawen** [comment] 2022-11-24 09:42
When will new release available ? This is really annoying.

**Comment by gtsiolis** [comment] 2022-11-24 09:50
@gengjiawen Someone from the team or the community has to pick up https://github.com/gitpod-io/gitpod/issues/14117 first. It would really help if you could add there any steps to reproduce the issue mentioned here.

**Comment by gengjiawen** [comment] 2022-11-25 01:32
> It would really help if you could add there any steps to reproduce the issue mentioned here.

flakiness. 

It's just normal use-case, sometimes I just open a github project, the button just not there.
I think the extension lacks error report and trace too, perhaps add sentry will help here.
