### ISSUE TITLE
i get message. " authorization falied,plese try again " when i connect from gitlab

### ISSUE THREAD

**Issue by ShivamParadkar** [gitpod-io/gitpod#2834] opened 2021-01-11 17:09 UTC

**Comment by csweichel** [comment] 2021-01-12 07:07
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by csweichel** 2021-01-12 07:07 UTC
