### ISSUE TITLE
Gitpod workspaces dashboard won't open

### ISSUE THREAD

**Issue by kevinhq** [gitpod-io/gitpod#3546] opened 2021-03-23 04:00 UTC
### Bug description

Gitpod workspaces dashboard won't open

### Steps to reproduce

Go to this: https://gitpod.io/workspaces/, login with Github, and it's never load

### Expected behavior

Go to this: https://gitpod.io/workspaces/, login with Github, and it loads the list of my workspaces

Is there a problem on the Gitpod's end again?

**Comment by kevinhq** [comment] 2021-03-23 04:01
update: even if it loads, it said no workspaces found.

**Comment by Bubbler-4** [comment] 2021-03-23 04:27
#3499 and #3515 are definitely coming again. It actually went back to last Friday's status.

* Workspaces page gives nothing (same "Connection got disposed" error on the console)
* If I try to start a workspace (by entering the workspace's address directly), it gives me "Connection got disposed" after a few minutes

@jankeromnes, please check this issue.

**Comment by Bubbler-4** [comment] 2021-03-23 06:11
Looks fine now. (Workspaces page, workspace startup time, build time are all OK)

**Comment by meysholdt** [comment] 2021-03-23 08:00
duplicate of https://github.com/gitpod-io/gitpod/issues/3548. Apologies for the trouble.

**Closed by meysholdt** 2021-03-23 08:00 UTC
