### ISSUE TITLE
Bugs when open gitpod workspaces

### ISSUE THREAD

**Issue by kivirus** [gitpod-io/gitpod#7343] opened 2021-12-22 03:04 UTC
### Bug description

when I open my workspaces I have got the error  `Request startWorkspace failed with message: 13 INTERNAL: cannot resolve workspace image: hostname required` and can't open workspace
![workspace_fail](https://user-images.githubusercontent.com/26292087/147028512-8c42d7a8-d76a-47dc-aa27-19a60597959e.PNG)

### Steps to reproduce

Go to /workspaces page and open workspace

**Comment by kunxin-chor** [comment] 2021-12-22 05:10
Same issue here

**Comment by princerachit** [comment] 2021-12-22 06:50
Hi, we have identified the issue. Please follow https://www.gitpodstatus.com/ for latest updates.

**Comment by bitsnaps** [comment] 2021-12-22 07:13
This is happening for me with any workspace, including the example workspaces available on the [home page](https://www.gitpod.io/), the issue is not resolved yet!

**Comment by AjXUthaya** [comment] 2021-12-22 07:18
Same issue in ws-eu23, unable to create new + start existing

**Comment by appcoders** [comment] 2021-12-22 08:15
Same issue on self-hosted enviroment.

**Comment by appcoders** [comment] 2021-12-22 12:00
Dispite the issue should be fixed 
https://www.gitpodstatus.com/
Monitoring - Gitpod workspaces are starting now. We're continuing to monitor the situation.
Dec 22, 11:36 UTC

it still does not work on self-hosted env.

**Comment by kylos101** [comment] 2021-12-22 21:18
Hello, I am going to close this issue, as it is for the saas and [this incident](https://www.gitpodstatus.com/incidents/g0kjpr3lbvbw), which is resolved.

@appcoders it looks like you're having trouble with self-hosted. Does #599 cover your issue, or is there another issue going on? If there's another issue, it would be ideal to create a new one - this way we can socialize in that context. Appreciate your feedback!

**Comment by appcoders** [comment] 2021-12-23 08:15
@kylos101 We found the reason in here https://github.com/gitpod-io/gitpod/pull/7280#issuecomment-999630814.
So this is resolved for self-hosted. Thanks.

**Comment by kylos101** [comment] 2021-12-23 13:42
Thanks for confirming @appcoders !

**Closed by kylos101** 2021-12-23 13:42 UTC
