### ISSUE TITLE
Authorization failed issue

### ISSUE THREAD

**Issue by gursimarh** [gitpod-io/gitpod#2738] opened 2021-01-09 19:14 UTC
I tried logging in multiple times even through multiple devices and still I'm getting the authorization failed please try again message.  Please look into the matter ASAP

**Comment by akosyakov** [comment] 2021-01-10 06:22
Please go to gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of https://github.com/gitpod-io/gitpod/issues/2746 Please reopen if you did not try to login with GitLab account.

**Closed by akosyakov** 2021-01-10 06:22 UTC
