### ISSUE TITLE
Cant see files in workspace

### ISSUE THREAD

**Issue by jimbobding** [gitpod-io/gitpod#2436] opened 2020-12-06 23:12 UTC
Hi.
Not sure if this is a bug or something that I have pressed accidentally, but my gitpod workspace timed out and when I logged back in I can not see any of my files or code it just all blank. I can still run a port 800 and see the physical site that I have been working on. 
Has anybody else had this issue or anybody know of a fix for this?

**Comment by svenefftinge** [comment] 2020-12-07 06:02
Maybe a bug. could you try pressing F1 and choose "Reset Workspace Layout"? I hope that fixes it.

**Comment by svenefftinge** [comment] 2020-12-25 21:57
I think this is due to some layout restoring issues.

**Comment by svenefftinge** [comment] 2020-12-25 22:02
duplicate of https://github.com/gitpod-io/gitpod/issues/2193

**Closed by svenefftinge** 2020-12-25 22:02 UTC
Labels: reporter-feedback-needed

**Comment by jimbobding** [comment] 2020-12-26 12:40
It was a display issue I worked out by playing around with the display
settings

**Comment by huy-lv** [comment] 2022-11-14 14:19
there is no option: Reset workspace layout

**Comment by axonasif** [comment] 2022-11-14 14:26
cc @jeanp413

**Comment by jeanp413** [comment] 2022-11-14 18:56
There's `View: Reset View Locations` command
