### ISSUE TITLE
Whenever I try to login gitpod with my gitlab account, it showing "Sorry something went wrong" message again and again.

### ISSUE THREAD

**Issue by KmrAnish04** [gitpod-io/gitpod#2933] opened 2021-01-15 18:06 UTC

**Comment by KmrAnish04** [comment] 2021-01-15 18:06
Whenever I try to login gitpod with my gitlab account, it showing "Sorry something went wrong" message again and again.

**Comment by svenefftinge** [comment] 2021-01-17 12:10
probably a duplicate of #2746

**Closed by svenefftinge** 2021-01-17 12:10 UTC
