### ISSUE TITLE
Ports view disappears after drag & drop (web)

### ISSUE THREAD

**Issue by davemecha** [gitpod-io/gitpod#13698] opened 2022-10-09 13:07 UTC
### Bug description

When moving the ports view to another location (e.g. into the side panel on the left) the view disappears and can not be activated from any menu any more. 

### Steps to reproduce

* Drag the ports view and drop it into the left side-bar.
* The view does not appear

### Expected behavior

The view should be visible where dropped

### Anything else?

As a workaround, the browser window with the IDE could be refreshed. After the refresh the ports view is visible where it was dropped.

**Comment by jeanp413** [comment] 2022-10-10 22:42
@davemecha I guess you are using firefox? This is duplicate of https://github.com/gitpod-io/gitpod/issues/13377

**Comment by davemecha** [comment] 2022-10-11 08:19
@jeanp413 No, I'm not using Firefox. I'm using Chrome OS on a Chromebook. And it doesn't appear to be a duplicate to me.

I don't have any issues with the ports view after launching the workspace. And it's not about the ports view being empty. It's just not there and cannot be retrieved.

**Comment by akosyakov** [comment] 2022-10-11 10:28
@jeanp413 could you have a look again please

**Comment by jeanp413** [comment] 2022-10-11 20:54
Fixed in https://github.com/gitpod-io/openvscode-server/commit/4e566342849b494651383099088327dfeab91c86, should be deployed with vscode recovery release tomorrow

**Closed by jeanp413** 2022-10-11 20:54 UTC
Labels: type: bug, editor: code (browser), feature: ports, team: IDE

**Comment by akosyakov** [comment] 2022-10-17 10:52
@jeanp413 VS Code Desktop is not affected?

**Comment by jeanp413** [comment] 2022-10-17 15:07
nope there's no `when` condition in gitpod-remote
