### ISSUE TITLE
Enable prebuilds for the default branch when adding a project for a GitLab or Bitbucket repository

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7424] opened 2022-01-03 18:09 UTC
### Problem to solve

When adding a GitLab or Bitbucket (https://github.com/gitpod-io/gitpod/pull/7422) project, a webhook is being added. Prebuilds are by default enabled for the default branch for GitHub repositories. However, prebuilds are not enabled for the default branch until you manually trigger a prebuild using the prefixed URL. See relevant docs[[1](https://www.gitpod.io/docs/prebuilds#gitlab)][[2](https://www.gitpod.io/docs/prebuilds#bitbucket)] for GitLab and Bitbucket repositories.

🍊 🍊 🍊 🍊 

See relevant comment in https://github.com/gitpod-io/gitpod/pull/7031#discussion_r766136431:

> Eventually we will most probably need to separate project addition and project configuration steps so that these can be done separastely. 💭

### Proposal

To maintain a similar behavior within the product, we could consider enabling prebuilds when adding a repository as proejct without requiring triggering manully the first prebuild.

**Comment by AlexTugarev** [comment] 2022-01-04 11:53
> Prebuilds are by default enabled for the default branch for GitHub repositories. However, prebuilds are not enabled for the default branch until you manually trigger a prebuild using the prefixed URL.

Quickly checked with the behavior of https://github.com/gitpod-io/gitpod/pull/7422, and I need to disagree on that. There seems to be no limitation on branches once the webhook events are registered and a config can be fetched from the repository, it starts to prebuild, see ...

<img width="1505" alt="Screen Shot 2022-01-04 at 12 48 50" src="https://user-images.githubusercontent.com/914497/148054826-4f5661dc-f314-429c-8372-693f4157c7e1.png">

**Comment by jldec** [comment] 2022-01-09 21:16
Closing as non-reproducible. Please file a new issue with repro steps if you believe this is still a problem. Thanks.

**Closed by jldec** 2022-01-09 21:16 UTC
Labels: type: feature request, git provider: gitlab, git provider: bitbucket, component: dashboard, feature: prebuilds, team: meta
