### ISSUE TITLE
Authorization failed

### ISSUE THREAD

**Issue by hussainaltaf8** [gitpod-io/gitpod#2867] opened 2021-01-12 15:17 UTC
![2021-01-12](https://user-images.githubusercontent.com/74441398/104333523-55fa2e00-5517-11eb-9b25-0509fd30c5d4.png)

**Comment by hussainaltaf8** [comment] 2021-01-12 15:19
Authorization failed during creating a workspace by given link.

**Comment by csweichel** [comment] 2021-01-13 06:42
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by csweichel** 2021-01-13 06:42 UTC
