### ISSUE TITLE
Extensions are not working

### ISSUE THREAD

**Issue by Kaushik-Kalesh** [gitpod-io/gitpod#4604] opened 2021-06-24 14:30 UTC
### Bug description

I took a week's break from gitpod.io, coming back I see none of my extensions are working.
I am getting a warning like so, **we cannot connect to the Extensions Marketplace at this time, please try again later.**

### Steps to reproduce

Open a workspace, you will notice that your extensions (if you already had any) aren't working.
Open the Extensions Marketplace, you will get the error.

### Expected behavior

The Extensions should be available, and the Extensions Marketplace should be accessible too.

### Example repository

https://lime-cattle-vznwc972.ws-us08.gitpod.io/

### Anything else?

I want my extensions back, and the mentioned bug should be fixed too please.

**Comment by aledbf** [comment] 2021-06-24 14:36
Closing. Duplicate of https://github.com/gitpod-io/gitpod/issues/4600

**Closed by aledbf** 2021-06-24 14:36 UTC
