### ISSUE TITLE
Exposed public port cannot bind

### ISSUE THREAD

**Issue by Glydric22** [gitpod-io/gitpod#14647] opened 2022-11-13 21:52 UTC
### Bug description

When i configure gitpod.yml i set
```
- name: web
port: 80
visibility: public
```
and the port shows on exposed ports as open, but if i run `python -m http.server 80` or every server on 80 it say cannot bind to 0.0.0.0/80, other ports are working

### Steps to reproduce

add 
```
- name: web
port: 80
visibility: public
```
to config.yaml 
run 
`python -m http.server 80`

### Expected behavior

the server should be up and working

**Comment by axonasif** [comment] 2022-11-14 13:42
Possible duplicate of https://github.com/gitpod-io/gitpod/issues/9376

**Closed** 2022-11-14 13:42 UTC
Labels: type: bug

**Comment by axonasif** [comment] 2022-11-18 11:41
@Glydric22 use:

```bash
sudo -E $(command -v python3) -m http.server 80
```

**Comment by axonasif** [comment] 2022-11-21 08:58
> Seems to work... but why?

It's basically how your shell works, `sudo` doesn't preserve the user-environment variables by default, `-E` flags makes it do. Moreover, `$(command -v python3)` is expanded to `/home/gitpod/.pyenv/shims/python3` before it gets passed as an argument to `sudo`, so `sudo` can directly execute `python3` without iterating over `PATH` env-var to avoid possible conflict as we're using `-E` flag.
