### ISSUE TITLE
cannot create directory: Permission denied

### ISSUE THREAD

**Issue by beaufortfrancois** [gitpod-io/gitpod#266] opened 2019-01-24 10:39 UTC
**Describe the bug**
I cannot create directory in `workspace/`. It works in `/tmp`.

**To Reproduce**
1. Create a new workspace by going to https://gitpod.io/#https://github.com/GoogleContainerTools/skaffold/
2. Enter `mkdir foo`

**Expected behavior**
`foo` folder should be created.
Instead I get "mkdir: cannot create directory ‘foo’: Permission denied"

For info, `worskpace` folder seems to belong to `root`.
```
$ ls -larth /workspace
total 12K
drwxr-xr-x 1 root root 4.0K Jan 24 10:35 ..
drwxr-xr-x 3 root root 4.0K Jan 24 10:35 src
drwxr-xr-x 3 root root 4.0K Jan 24 10:35 .
```

![image](https://user-images.githubusercontent.com/634478/51672807-b0b5ba80-1fcc-11e9-9435-bf8d8fa11c32.png)

**Comment by beaufortfrancois** [comment] 2019-01-24 10:39
FYI @dgageot @jankeromnes

**Comment by geropl** [comment] 2019-01-24 10:50
`/workspace` is the mount point we use to clone repositories into. As this does not work for Go and it's specific folder structure, we try to detect Go projects and create the following folder structure: https://docs.gitpod.io/45_Config_Go.html.

There is an ongoing discussion over whether and how to change this: https://github.com/gitpod-io/gitpod/issues/57

**Comment by svenefftinge** [comment] 2019-01-24 10:52
That is not the issue here. Strangely, the projects are checked out as root.

**Comment by svenefftinge** [comment] 2019-01-24 10:56
For some reason even the `/workspace` folder is owned by `root`.
It should be owned by `gitpod` and in other workspaces it is.

**Comment by 32leaves** [comment] 2019-01-24 12:31
The root cause of this issue is that our current use of `chown` does not handle the symlink structure in this repo very well (`github.com/GoogleContainerTools/skaffold/vendor/github.com/karrick/godirwalk/testdata/symlinks/dir-symlink/...`). There's a fix ready which should soon land in Gitpod.

**Comment by beaufortfrancois** [comment] 2019-01-24 12:34
Thank you @32leaves!
Which issue/PR can I subscribe to in order to keep track of this?

**Comment by dgageot** [comment] 2019-01-24 13:14
@32leaves I saw you closed the issue and assumed it was fixed. But when I try again, I still see the same issue.

**Comment by jankeromnes** [comment] 2019-01-24 13:31
> Which issue/PR can I subscribe to in order to keep track of this?

Unfortunately, the fix is in our backend infrastructure, which isn't open source yet. 😕 So this issue is the best place to keep track of our fix. (We've basically switched from using Go chown to Linux chown, and are planning to deploy the fix in 30min or so.)

> I saw you closed the issue and assumed it was fixed. But when I try again, I still see the same issue.

Sorry about that, I think that was a mistake. Let's close this issue once it is actually fixed in Gitpod production.

**Comment by 32leaves** [comment] 2019-01-24 14:05
@beaufortfrancois the fix is deployed and the [skaffold](https://gitpod.io/#https://github.com/GoogleContainerTools/skaffold/) repo works now as expected. Thank you for bringing this to our attention :)

**Closed by 32leaves** 2019-01-24 14:05 UTC
Labels: bug, critical

**Comment by beaufortfrancois** [comment] 2019-01-24 14:11
It works great now! Thanks for the quick fix.
