### ISSUE TITLE
Error: cannot start a workspace because no workspace clusters are available

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#8172] opened 2022-02-12 09:25 UTC
### Bug description

This issue seems to be quite frequent, the error message `Error: cannot start a workspace because no workspace clusters are available` is probably seen after being stuck in `Allocating Resources` for a while.

Users who reported to be facing this issue:

- @shaal [on Discord](https://discord.com/channels/816244985187008514/816246578594840586/939715845934968864), workspace-id: `shaal-drupalpod-x8u7hhb95tu`
- @megatank58 [on Discord](https://discord.com/channels/816244985187008514/816246578594840586/939722222795366430), workspace-id: `megatank58-website2-o050xdvntnt`
- @CarterQC [on Discord](https://discord.com/channels/816244985187008514/816246578594840586/941823668009459752), workspace-id: `awaiting-reply`
- @Dogkiller87 [on Discord](https://canary.discord.com/channels/816244985187008514/941982753044443176/941983116464119869), workspace-id: `4geeksacademy-htmlhello-pzttg3zw2pi`
- More will be added here when found....

Internal discussion on Slack[^1]
cc @kylos101 

[^1]: https://gitpod.slack.com/archives/C02F19UUW6S/p1644118483199979

**Comment by sagor999** [comment] 2022-02-12 15:21
duplicate of #8173

**Closed by sagor999** 2022-02-12 15:21 UTC
Labels: type: bug, priority: highest (user impact), team: workspace
