### ISSUE TITLE
Trying to start a self-hosted instance, but it keeps failing.

### ISSUE THREAD

**Issue by dtwilliams10** [gitpod-io/gitpod#2229] opened 2020-08-19 22:42 UTC
I'm trying to stand up a self-hosted instance on my own hardware using minikube to start the cluster. I have filled in the values.yaml file but when I try to start the cluster it consistently fails with: 
`Error: template: gitpod-selfhosted/charts/gitpod/charts/minio/templates/deployment.yaml:192:20: executing "gitpod-selfhosted/charts/gitpod/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled`

Any thoughts or suggestions? I'm trying to run it on an up to date CentOS 7 box with the latest release of Kubernetes.

**Comment by meysholdt** [comment] 2020-12-07 10:50
Closing as duplicate of https://github.com/gitpod-io/gitpod/issues/1740

**Closed by meysholdt** 2020-12-07 10:50 UTC
Labels: self-hosted
