### ISSUE TITLE
Epic: MVC API for user and team management

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13765] opened 2022-10-11 12:51 UTC
Enterprise customers need to automate their Gitpod user management so that they can onboard and maintain users in their Gitpod teams. 

The goal of this epic is to provide a minimal solution for user management through an API.

Details and breakdown tbd.

**Comment by loujaybee** [comment] 2022-10-24 18:45
Closing as duplicate of: https://github.com/gitpod-io/gitpod/issues/10799

**Closed by loujaybee** 2022-10-24 18:45 UTC
Labels: team: webapp, type: epic
