### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by bgoonz** [gitpod-io/gitpod#3549] opened 2021-03-23 04:34 UTC
### Bug description

Error: Connection got disposed.

### Steps to reproduce

Open a repo with gitpod

### Expected behavior

it should work as intended

### Example repository

Right now... all of mine

![report](https://user-images.githubusercontent.com/66654881/112093310-91e0ed80-8b6f-11eb-9fac-ae4466c67f91.PNG)

**Comment by meysholdt** [comment] 2021-03-23 08:01
duplicate of https://github.com/gitpod-io/gitpod/issues/3548. Apologies for the trouble.

**Closed by meysholdt** 2021-03-23 08:01 UTC
