### ISSUE TITLE
vim is broken

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#8111] opened 2022-02-09 02:29 UTC
### Bug description

latest vim not working

### Steps to reproduce

open any repo and install vim

### Anything else?
From console, maybe upstream issue ?
```console
Activating extension 'vscodevim.vim' failed: Cannot find module '../util/child_process'.
```

Update: 
Temp solution: install good old vim https://github.com/gitpod-io/gitpod/issues/8111#issuecomment-1034790930

Fallback to 1.21.10 works. Maybe reopen https://github.com/gitpod-io/gitpod/issues/6310

cc @akosyakov

**Comment by akosyakov** [comment] 2022-02-09 04:56
Please make sure to report it in upstream. It sounds like a new version was published which pulls node deps in browser target?

**Comment by gengjiawen** [comment] 2022-02-09 06:23
Uptream: https://github.com/VSCodeVim/Vim/issues/7469

**Comment by gengjiawen** [comment] 2022-02-09 06:44
For anyone don't want to suffer the long waiting pain, please search vim for gitpod.

I have uploaded the good old vim 1.21 to openvsx.

**Comment by jeanp413** [comment] 2022-02-09 12:49
@gengjiawen quick question, couldn't you just install the old version through vscode ui instead of uploading it to openvsx? is that a bug?

**Comment by filiptronicek** [comment] 2022-02-10 09:40
> @gengjiawen quick question, couldn't you just install the old version through vscode UI instead of uploading it to openvsx? is that a bug in the UI?

Thinking the same, if you install the extension, there is a menu when you click on the caret next to the <kbd>Uninstall</kbd> button. @gengjiawen, could you try if this works? I'm not really sure how to make sure whether Vim is working correctly 😕 
<img width="755" alt="image" src="https://user-images.githubusercontent.com/29888641/153379663-f9a396c3-a558-47d0-9151-5fad4f148298.png">

**Comment by gengjiawen** [comment] 2022-02-10 11:11
> couldn't you just install the old version through vscode UI instead of uploading it to openvsx? is that a bug in the UI?

I don't want to do it in every my opened gitpod workspace.


> could you try if this works? I'm not really sure how to make sure whether Vim is working correctly 

It works. But you have to reload it. I have uninstall this one, I have publish another one using my name as publisher

<img width="308" alt="image" src="https://user-images.githubusercontent.com/3759816/153395068-3fa194a4-1458-4396-98c1-88813544e594.png">

**Comment by fiveable-jferg** [comment] 2022-02-16 21:28
So yesterday I was able to just downgrade to version 1.21.10 and things worked fine, but today it's showing: 

![image](https://user-images.githubusercontent.com/88333913/154359950-eda3b280-df9e-4d82-a8a0-340369e0e617.png)

even if I downgrade.  I'm not sure if this is due to a change on the gitpod side or on the upstream side, but it makes gitpod effectively useless for me.  :cry:

**Comment by jeanp413** [comment] 2022-02-17 00:00
@fiveable-jferg Did this happen in the same workspace or in a new one? what happens if you uninstall and reinstall again, does the issue persist?

**Comment by fiveable-jferg** [comment] 2022-02-17 01:54
Same workspace.  Issue persists across workspace restarts (haven't tried fully rebuilding the workspace).  It's in the .gitpod.yml.  I've switched to @gengjiawen's republished version for the time being, but obviously not an ideal solution.

**Comment by akosyakov** [comment] 2022-02-17 05:51
@fiveable-jferg as a workaround you can switch to VS Code Desktop integration of Gitpod in preferences: https://gitpod.io/preferences

**Comment by mustard-mh** [comment] 2022-02-17 06:40
With `stable` vscode, we can use `.gitpod.yml` to specify a version of vim, and it works for me with version `1.21.10`

But vim `1.21.10` will fail with `insider` vscode

|.gitpod.yml|Works|
|:-:|:-:|
|![img](https://user-images.githubusercontent.com/20944364/154417210-35cdfa83-f52e-44b9-9676-54a4e87bc2de.png)|![img](https://user-images.githubusercontent.com/20944364/154417092-3aae8800-2616-4cbf-9bdf-d329b1d9ca9b.png)|

<img width="965" alt="image" src="https://user-images.githubusercontent.com/20944364/154419474-a6d1e25c-fdf5-430c-a03c-9ba5ecd055ce.png">

cc @akosyakov @jeanp413 @filiptronicek

**Comment by akosyakov** [comment] 2022-02-17 07:24
I don't think it is a good idea to add user level extensions to .gitpod.yml.

But it is certainly good news that you can still use stable VS Code Web with VIM extension. VS Code Insiders can have temporarily regressions, since it is untested nightly build of our and MS changes.

**Comment by jeanp413** [comment] 2022-02-17 13:32
From my testing, when vim is listed in `.gitpod.yml` file it doesn't work in either stable or insiders, plus it auto updates to latest version which should not be the case. Uninstalling and reinstalling manually from extensions view and then downgrading to version `1.21.10` works fine

**Comment by jeanp413** [comment] 2022-02-18 19:20
Fixed in https://github.com/VSCodeVim/Vim/pull/7520#issuecomment-1044861338, already published into open-vsx too :tada:

**Closed by jeanp413** 2022-02-18 19:20 UTC
Labels: type: bug, feature: vscode-extension

**Comment by jeanp413** [comment] 2022-02-20 01:17
BTW the bug where specifying a specific version of an extension in gitpod.yml but then it auto-updates to latest version is a known upstream issue https://github.com/microsoft/vscode/issues/63903, you could comment and upvote so it gets more attention to get fixed

**Comment by akosyakov** [comment] 2022-02-23 07:28
[here](https://github.com/VSCodeVim/Vim/issues/7530) is an issue to prevent such breakage please upvote 🙏
