### ISSUE TITLE
Problems re-opening a workspace

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#2547] opened 2020-12-15 18:54 UTC
So a student @ajiva84 is having this problem when opening a previous workspace: 
![image](https://user-images.githubusercontent.com/426452/102258090-8aa8a480-3edb-11eb-9bb6-710b176bf05a.png)

Here is the workspace URL: https://gitpod.io/workspace-download/get/b5aa7dca-73d9-44ba-acc0-bf06f6cde5a3

What could be the issue?

**Comment by gtsiolis** [comment] 2020-12-15 20:19
Hey @alesanchezr! This is most probably a duplicate of https://github.com/gitpod-io/gitpod/issues/2525.

We're planning deploy a new version on gitpod.io tomorrow morning at 06:00 CET.

Let us know if you are still not able to open that workspace after the deployment. /cc @ajiva84

**Comment by alesanchezr** [comment] 2020-12-15 23:50
Oh ok, thank you @gtsiolis

**Comment by ajiva84** [comment] 2020-12-16 00:12
Sure will check and let you know.

**Closed** 2020-12-25 21:47 UTC
Labels: bug, reporter-feedback-needed
