### ISSUE TITLE
Code Highlighting & Emmet Support don't work

### ISSUE THREAD

**Issue by bravoalpha79** [gitpod-io/gitpod#2444] opened 2020-12-07 10:35 UTC
### Describe the bug
Since the outage on Friday 04/12/2020, multiple students have reported various issues on their workspaces:

- code highlighting not working (all code displayed as plain white text),
- Emmet code shortcuts not available, or available only partially (e.g. working in HTML but not in CSS),
- some workspaces not accessible at all since Friday (stuck in opening state indefinitely, without any feedback).

Some issues seem to be workspace-related (the student that couldn't open his workspace was able to create a new one from the repo and that one worked), but some seem to be user-wide (code highlighting for the student worked on neither his workspace nor on mine shared, even though it worked normally at my end).

For the Emmet shortcuts, it seems that manual installing of the CSS Language Features and HTML Language Features extensions helped restore the functionality.

### Steps to reproduce
Workspace that wouldn't open at all: https://c4812cfa-7975-45bf-9b06-62367ca91af0.ws-eu03.gitpod.io/#/workspace/V_Getable

### Expected behavior
Workspaces should open without errors.
Code highlighting should work.
Emmet support should work.

**Comment by NielMc** [comment] 2020-12-07 10:44
I am getting the following error if I try and open a github repo as a gitpod workspace. 
failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/theia/supervisor\": stat /theia/supervisor: no such file or directory": unknown; last backup failed: workspace content was never ready. Please contact support if you need the workspace data.

**Comment by tobiasfeistmantl** [comment] 2020-12-07 11:58
We have the same problem! We can't work at all.

**Comment by svenefftinge** [comment] 2020-12-07 12:14
We are working on it.

**Comment by akosyakov** [comment] 2020-12-07 12:56
@bravoalpha79 Could you share workspace ID for which code highlighting won't work? And a snapshot if possible thank you. You can email me anton at gitpod.io if it is confidential.

**Comment by svenefftinge** [comment] 2020-12-07 13:03
> I am getting the following error if I try and open a github repo as a gitpod workspace.
> failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: "/theia/supervisor": stat /theia/supervisor: no such file or directory": unknown; last backup failed: workspace content was never ready. Please contact support if you need the workspace data.

This has been solved and is a duplicate of https://github.com/gitpod-io/gitpod/issues/2445
Sorry for blocking you.

**Comment by svenefftinge** [comment] 2020-12-07 13:04
I have changed the title to make this issue focus on the problem regarding syntax coloring and emmet (probably caused by the same issue). For any other problems, please file dedicated issues. Thank you!

**Comment by bravoalpha79** [comment] 2020-12-07 15:39
Hi Anton,

I can indeed share a snapshot if needed, but that won't do you any good as
the same workspace looked perfectly normally at my end.

Example - my workspace at my end:

[image: image.png]

The same workspace shared and viewed from the student's end:
[image: image.png]

**Comment by akosyakov** [comment] 2020-12-08 05:37
@bravoalpha79 Could you check please the devtools network tab for any broken requests for such students? i.e.:
- start a workspace
- open devtools -> network tab
- reload the page and watch out for any requests which are failing, particularly to wasm files

thank you!

**Comment by bravoalpha79** [comment] 2020-12-08 09:49
Hi Anton,

Please find below an affected workspace URL and the error/warning
screenshots:

https://a073e929-957c-4fd5-a3c2-50ce0bbed1cd.ws-eu03.gitpod.io/#/workspace/Milestone-2-Visit-Norrtalje

[image: image.png]

[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]

Kind regards,
Igor

**Comment by svenefftinge** [comment] 2020-12-08 11:00
Hi Igor, thanks but the images don't show up on GitHub. unfortunately.

**Comment by bravoalpha79** [comment] 2020-12-08 11:43
I see. How else can I send them to you?

**Comment by svenefftinge** [comment] 2020-12-08 11:46
Go to [this page](https://github.com/gitpod-io/gitpod/issues/2444) and drag & drop the image into the text area would work.

**Comment by bravoalpha79** [comment] 2020-12-08 11:49
![image (15)](https://user-images.githubusercontent.com/45522344/101480294-c976b180-3953-11eb-9e32-a2a908728a53.png)
![image (14)](https://user-images.githubusercontent.com/45522344/101480300-cc71a200-3953-11eb-8d31-94975140bd92.png)
![image (13)](https://user-images.githubusercontent.com/45522344/101480311-ce3b6580-3953-11eb-9059-6f4106323845.png)
![image (12)](https://user-images.githubusercontent.com/45522344/101480316-d0052900-3953-11eb-9ff3-426efa6e432e.png)
![image (11)](https://user-images.githubusercontent.com/45522344/101480325-d3001980-3953-11eb-96da-3f3ddce01102.png)

**Comment by bravoalpha79** [comment] 2020-12-08 11:50
Done! :)

**Comment by akosyakov** [comment] 2020-12-08 13:05
the fix is already almost there: https://github.com/gitpod-io/gitpod/pull/2457 😉

**Comment by akosyakov** [comment] 2020-12-09 15:45
We merged the tentative fix and will deploy it at the end of this week. In the meantime it would be helpful if you can verify it by using this env: http://ak-onigasm-from-blobserve.staging.gitpod-dev.com/workspaces/ 

@bravoalpha79 Could you ask students experiencing issues to try it there? If it fails it would be good if they can capture details (request/response headers) of failed requests from devtools network, see: https://developers.google.com/web/tools/chrome-devtools/network#details

**Comment by bravoalpha79** [comment] 2020-12-09 17:25
Hi Anton, I went to the staging workspaces, but have faced two issues:
1. The Emmet seems to be available, however in CSS, most of the shortcuts
are not available (see example below for margin- and font-).
2. I'm only able to do minimal testing, as the staging environment doesn't
seem to allow me to access any of my workspaces with my settings.

**Comment by bravoalpha79** [comment] 2020-12-09 17:29
![image](https://user-images.githubusercontent.com/45522344/101664528-3e2d1700-3a4c-11eb-8b0b-6dceaf2387d1.png)
![image](https://user-images.githubusercontent.com/45522344/101664595-5309aa80-3a4c-11eb-8a82-5485dfd708af.png)
![image](https://user-images.githubusercontent.com/45522344/101664659-63218a00-3a4c-11eb-9908-3293d0b76d37.png)

**Comment by akosyakov** [comment] 2020-12-09 19:24
Oh, it makes sense, in upstream it was changed how html/css are consumed: https://github.com/eclipse-theia/theia/pull/7972 we should add VS Code extensions now explicitly.

But I was concerned with syntax highlighting in general, as far as I understood for some students it did not work at all. Does it work with the staging env?

**Comment by akosyakov** [comment] 2020-12-09 19:29
PR to add missing language smartness for html/css: https://github.com/gitpod-io/gitpod/pull/2483

**Comment by bravoalpha79** [comment] 2020-12-09 19:42
@akosyakov 
As far as I can tell, everything seems fine with code highlighting:
![image](https://user-images.githubusercontent.com/45522344/101678846-d03e1b00-3a5e-11eb-8fd3-63b7f94ce7d2.png)
![image](https://user-images.githubusercontent.com/45522344/101678904-e21fbe00-3a5e-11eb-93b0-73dc021422f6.png)
![image](https://user-images.githubusercontent.com/45522344/101678930-ecda5300-3a5e-11eb-8554-d6b3fdc908b1.png)

However I never experienced any issues with the highlighting in any of my workspaces, so I can't verify that anything has changed in that regard.

**Comment by akosyakov** [comment] 2020-12-11 08:49
fixes were deployed, please open new issues if something still does not work

**Comment by bravoalpha79** [comment] 2020-12-11 09:49
Fix not working. CSS Emmet now works, but HTML Emmet is completely absent.
Moreover, the workspace crashes/disconnects:
![image](https://user-images.githubusercontent.com/45522344/101888319-485f2a80-3b9e-11eb-9623-3b1499b705a2.png)

Two examples of impacted workspaces:
https://f965e451-dbbc-4dc7-8603-a9a2c98b7da5.ws-eu03.gitpod.io/#/workspace/newtestrepo
https://f1abf907-ec9c-42a9-aee4-c500348cbc4a.ws-eu03.gitpod.io/

Note: the second workspace completely refuses to open after several crashes/disconnects.

**Comment by bravoalpha79** [comment] 2020-12-11 16:49
I am now unable to properly open any workspace. When I do and add some code and attempt to save it, the workspace disconnects. 
Even after reconnecting, any attempt to add new code and save it results in a disconnection.
This applies to both workspaces with a Docker template and without it.
Latest example: https://bff21d7d-1fad-474a-8c9c-879b8fa255d6.ws-eu03.gitpod.io/#/workspace/notemplate

![image](https://user-images.githubusercontent.com/45522344/101930988-26cf6480-3bd9-11eb-9794-79415a76552e.png)

**Comment by svenefftinge** [comment] 2020-12-28 07:56
This should have been fixed by now. There has been a couple of other issue reported here as well. Please open new issues for anything that is still prevailing.

**Closed by svenefftinge** 2020-12-28 07:56 UTC
Labels: bug, fixed-not-deployed
