### ISSUE TITLE
Select editor non-scrollable modal UX adds friction to onboarding flow 

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13570] opened 2022-10-04 08:08 UTC
New users are prompted to select an editor after they sign in.

Unfortuntately this modal does not scroll and the action button is off screen for normal sized desktop browsers already taking up a the full height of the screen.

Clicking on the default editor selection does not submit or dismiss the form.

Since part of the form is obscured, a cautious user will look for the cancel/dismiss control and probably click on the X at the top right hoping that this does not have unintended consequences. This adds uncertainty into the flow and forces additional work to find the X. 

<img width="1440" alt="Screenshot 2022-10-04 at 09 55 15" src="https://user-images.githubusercontent.com/849592/193766358-688a942a-1e40-43c4-bdc7-9ca1598146ba.png">

**Comment by jldec** [comment] 2022-10-04 08:09
Related to #13116
cc: @gtsiolis @loujaybee

**Comment by gtsiolis** [comment] 2022-10-04 08:19
Closing this as a duplicate of https://github.com/gitpod-io/gitpod/issues/13497, which already contains a good MVC solution. Cc @andreafalzetti 

Thanks for noticing, @jldec!

**Closed by gtsiolis** 2022-10-04 08:19 UTC
Labels: team: IDE

**Comment by gtsiolis** [comment] 2022-10-04 08:21
Just noticed there's a community contributor who already picked this up in https://github.com/gitpod-io/gitpod/pull/13557.
