### ISSUE TITLE
AUTHORIZATION FAILURE

### ISSUE THREAD

**Issue by shrey12mehrotra** [gitpod-io/gitpod#2771] opened 2021-01-10 13:51 UTC
It says 
Sorry, something went wrong 😓
Authorization failed. Please try again.

**Comment by csweichel** [comment] 2021-01-11 06:42
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by csweichel** 2021-01-11 06:42 UTC
