### ISSUE TITLE
Unexpected error starting a workspace

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#3857] opened 2021-04-08 17:52 UTC
### Bug description

error in the workspace pod
```
Error relocating /ide/node/bin/gitpod-node: gnu_get_libc_version: symbol not found
Error relocating /ide/node/bin/gitpod-node: __register_atfork: symbol not found
Error relocating /ide/node/bin/gitpod-node: __strdup: symbol not found
Error relocating /ide/node/bin/gitpod-node: setcontext: symbol not found
Error relocating /ide/node/bin/gitpod-node: makecontext: symbol not found
Error relocating /ide/node/bin/gitpod-node: backtrace: symbol not found
Error relocating /ide/node/bin/gitpod-node: getcontext: symbol not found
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"exit status 127","level":"warning","message":"IDE was stopped","serviceContext":{"service":"supervisor","version":""},"severity":"WARNING","time":"2021-04-08T17:45:29Z"}
```

The base image uses alpine.

### Steps to reproduce

Open https://gitpod.io/#https://github.com/aledbf/website/tree/gitpod

### Expected behavior

No error

**Comment by AlexTugarev** [comment] 2021-04-09 05:58
Hi @aledbf! I think this is a duplicate of https://github.com/gitpod-io/gitpod/issues/3356

**Closed** 2021-04-09 10:01 UTC
