### ISSUE TITLE
Oh, no! Something went wrong! OutOfmemory: Pod Node didn't have enough resource: memory, requested: 3435973837, used: 65865462583, capacity: 66388008960

### ISSUE THREAD

**Issue by lhartley870** [gitpod-io/gitpod#8378] opened 2022-02-22 10:52 UTC
### Bug description

Oh, no! Something went wrong!
OutOfmemory: Pod Node didn't have enough resource: memory, requested: 3435973837, used: 65865462583, capacity: 66388008960

### Steps to reproduce

Trying to launch my existing gitpod workspace

### Workspace affected

https://gitpod.io/start/#bronze-chinchilla-sc7zx3uc

### Expected behavior

My gitpod workspace to launch without errors

### Anything else?

I have a project due in very soon and I can't open my workspace. There is no option to stop the workspace. It just has an orange dot next to it.

**Comment by JimLynx** [comment] 2022-02-22 11:28
This seems to be an ongoing issue with many of our students experiencing this (and opening tickets that aren't resolved). 

Past ticket responses on the same error are not providing much context on how this can be resolved. either. Any advice would be much appreciated.

**Comment by sagor999** [comment] 2022-02-22 19:03
duplicate of https://github.com/gitpod-io/gitpod/issues/8238

we are working on fixing this. previous fix improved this but have not fixed 100%.

**Closed by sagor999** 2022-02-22 19:03 UTC
