### ISSUE TITLE
Cannot start new workspaces

### ISSUE THREAD

**Issue by stefdworschak** [gitpod-io/gitpod#1558] opened 2020-05-28 09:24 UTC
When clicking on the "GitPod" button to start a new workspace, the loading screen gets stuck forever.
No error message is shown, but tested this on multiple different github repos with the same effect. 

Could you please fix this as soon as possible?

Thanks

![image](https://user-images.githubusercontent.com/31205982/83123880-5bf8e700-a0cd-11ea-90c2-56443f8fa6ef.png)

**Comment by stefdworschak** [comment] 2020-05-28 09:37
This issue seems to be resolved, but we still have issues with starting from our template. Issue: https://github.com/gitpod-io/gitpod/issues/1559

**Comment by Kreyren** [comment] 2020-05-28 17:52
Concluded this being a duplicate of https://github.com/gitpod-io/gitpod/issues/1559

(this issue is newer then 1559, but 1559 was referenced by @jankeromnes so duplicates are being merged there)

**Comment by Kreyren** [comment] 2020-05-28 17:52
> This issue seems to be resolved, but we still have issues with starting from our template. Issue: #1559

@stefdworschak Could you make a new issue if it's not relevant to #1559 ?

**Closed by Kreyren** 2020-05-28 17:52 UTC
Labels: critical, operations
