### ISSUE TITLE
What's the system requirements for GitPod self-hosting

### ISSUE THREAD

**Issue by yyexplore** [gitpod-io/gitpod#2884] opened 2021-01-13 10:52 UTC
Hello 

I'm struggling for gitpod installation these days!   There're no documents to indicate the minimum or recommend platform requirements.

I read from the source code and a youtube video to know that GitPod realized a rootless container solution by user namespace and shiftfs, and ws-daemon does some special operations for it. Obviously  that need support by the operation system of nodes. Gitpod is not like a normal applications

So the question is:  my k8s node system is  Ubuntu 18.04.1 with kernel of  4.15,  does it match the gitpod requirements ?

It's recommended to document the support platforms.  I'd also like to share my experience also.

Thanks !

**Comment by csweichel** [comment] 2021-01-13 11:51
Thank you for raising this, and your input :)
We plan to finally write this up by the end of this month, see https://github.com/gitpod-io/gitpod/issues/2657.

I'm closing this as a duplicate of #2657.

**Closed by csweichel** 2021-01-13 11:51 UTC
