### ISSUE TITLE
Failed image builds can result in many workspace instances, hiding the original issue

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#12978] opened 2022-09-15 02:28 UTC
### Bug description

The workspace can't be started, this started out as an image build failure, but we allowed the user to try restarting the workspace (or restarted the workspace ourselves), resulting in new instances that could not start (because there was no backup).

When an image build fails, we provide the user with an option to start the workspace using the default image. It is possible that happened here.  If that is true, it would mean `image-builder` is not the culprit for this particular issue, because they actually started the workspace...but then had trouble backups "at some point". Please refer to the logs and instance IDs to paint a complete picture.

### Steps to reproduce
Try using a custom image with just this:
```dockerfile
FROM hashicorp/terraform:1.2.9
```

It should fail, but, let you try restarting the workspace, resulting in you seeing a message indicating that the workspace backup doesn't exist.

### Workspace affected

Refer to logs

### Expected behavior

1. If an image build fails, show the reason for the image build failure, rather than a generic headless image build failed. It is presently difficult to know why image builds fail, so it is important to share the actual error with users.
2. If an image build fails, and the user does not run with our default image instead, the ending status for the workspace instance should not allow for restarts. Otherwise the danger is the user may not be able to start the workspace (due to an image build failure), and never see why on the subsequent restarts.

### Anything else?

Logs for the workspace in question:
Internal slack conversation: https://gitpod.slack.com/archives/C02SF4A050W/p1663161853069319
workspace logs: https://cloudlogging.app.goo.gl/A2UvJMTtQd2eaFk38
webapp logs:  https://cloudlogging.app.goo.gl/YpNtszBdZRGx2VXi8

Here is what we saw as a failure for the most recent instance failure that the customer was getting
```
cannot initialize workspace:
    github.com/gitpod-io/gitpod/content-service/pkg/initializer.InitializeWorkspace
        github.com/gitpod-io/gitpod/content-service@v0.0.0-00010101000000-000000000000/pkg/initializer/initializer.go:439
  - no backup found:
    github.com/gitpod-io/gitpod/content-service/pkg/initializer.(*fromBackupInitializer).Run
        github.com/gitpod-io/gitpod/content-service@v0.0.0-00010101000000-000000000000/pkg/initializer/initializer.go:199
```

We're calling `Run` on the initializer [here](https://github.com/gitpod-io/gitpod/blob/c4dfba3a663bb7f0fd01aab1f8270c517a7ea060/components/content-service/pkg/initializer/initializer.go#L437), hasBackup is false, but, the stack trace suggests the initializer we're working with is a [fromBackupInitializer](https://github.com/gitpod-io/gitpod/blob/c4dfba3a663bb7f0fd01aab1f8270c517a7ea060/components/content-service/pkg/initializer/initializer.go#L183) given [this error](https://github.com/gitpod-io/gitpod/blob/c4dfba3a663bb7f0fd01aab1f8270c517a7ea060/components/content-service/pkg/initializer/initializer.go#L199).

In looking at the entire history for this workspace...this particular workspace has five instances in the logs! 

The initial workspace had an error (root cause) of:

```
[adduser -h /home/gitpod -s /bin/sh -D -G 33333 -u 33333 gitpod]: exit status 1: adduser: unknown group 33333:
    github.com/gitpod-io/gitpod/supervisor/pkg/supervisor.addUser
        github.com/gitpod-io/gitpod/supervisor/pkg/supervisor/user.go:172
  - exit status 1

The related message is cannot ensure Gitpod user exists . 
```

The related instance IDs are:
8e70e9a5-b464-4dab-8826-0ed331b88ca9
0aa0fb2b-0cd9-4d12-9330-552797c6a2a0
349a594f-f55a-47ff-ac64-ccca827c2ffa
e61ebcc4-c300-47f8-a729-2b4d45c19365
56adcae2-66ba-463f-9555-7dace043ff90

Lastly, this is related: https://github.com/gitpod-io/gitpod/issues/8908

### Definition of done

When an image build fails, like due to the Gitpod user not existing, the end user sees that corresponding problem, instead of headless task failed.

Also, update the docs on the Gitpod website, so users know how to add the Gitpod user to a custom image not using a Gitpod base image.

**Comment by utam0k** [comment] 2022-09-15 02:36
@jenting ring1 is called twice because of uid mapping, so I think it is natural to appear `ring1 stopped` at one time.
https://cloudlogging.app.goo.gl/QkZXunGJaKnfud6w

**Comment by WVerlaek** [comment] 2022-10-28 15:31
Trying to reproduce this, needed to turn off PVC otherwise a restart would not show the "no backup found" issue.

The failure on the first run is coming from `supervisor` not being able to add the gitpod user: https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/pkg/supervisor/user.go#L67. 
Should I expect to see an image build failure as well? Cause I'm not able to reproduce one 😄 cc @jenting 

Also think there's a different issue, where on the first failed workspace startup, no error is shown to the user at all. The workspace just transitions to "Stopping" and "Stopped" without any details. It looks like errors logged from `supervisor run` no longer end up in the workspace error status, cause iirc there used to be an error message when I tried to reproduce this issue ~2 weeks ago?

From this I'd say there's three issues to solve:
1. Running with an image that does not contain the `gitpod` user should show an error on workspace startup. This error should include a link to the docs on how to set up a custom docker image
2. When a workspace fails to start up due to a supervisor error, this (or at least some) error should be shown to the user
3. Restarting the failed workspace should not run into the "backup not found" error and hide the original error

**Comment by kylos101** [comment] 2022-10-28 16:38
@WVerlaek great observations. What makes you say that 1 and 2 are different? I ask because I thought (and could be wrong) that the missing `gitpod` user error comes from `supervisor`.

May I ask you to add a related issue for observation 3?

**Comment by kylos101** [comment] 2022-10-28 16:49
> Trying to reproduce this, needed to turn off PVC otherwise a restart would not show the "no backup found" issue.

@WVerlaek this is good news, meaning we avoid observation 3 when using PVC? Maybe an issue isn't needed after all! :thinking:

**Comment by WVerlaek** [comment] 2022-10-31 15:47
@kylos101 raised #14293 in the IDE team's inbox, not sure if there's a good solution to implement for observation 1 without having #14293 resolved? Probably the most straightforward solution is to have `supervisor` exit with a more detailed error when it fails to set up the `gitpod` user, including a link to the docs? This would then show up on the dashboard for the user once #14293 gets fixed. Wdyt?

**Comment by kylos101** [comment] 2022-11-02 02:08
Hey @WVerlaek :wave: , 

> Probably the most straightforward solution is to have supervisor exit with a more detailed error when it fails to set up the gitpod user, including a link to the docs?

I think that is where the logic lives now, to check for the `gitpod` user. For which workspace types does it trigger? I assume only regular and prebuild workspaces on start.

Can we catch the lack of a Gitpod user during the image build from `bob`, before we start a prebuild or regular workspace? For example, bubble up the error while streaming the logs, so that they see it as an error at the end of the logs streamed by the imaeg build? The user would potentially see the error (in addition to `headless task failed`) before clicking `Continue with Default Image` and as a result, be able to "act sooner".

**Comment by WVerlaek** [comment] 2022-11-02 10:22
@kylos101 that could be a good alternative, will take a look if we can check for the user in the image build

**Comment by WVerlaek** [comment] 2022-11-02 15:17
@kylos101 after some investigation, the `gitpod` user not existing in the image is OK, as `supervisor` will normally add the user on startup if it doesn't exist yet. What's happening is that there's actually a small bug in `supervisor` which causes it to error on adding the user for `terraform`/`busybox` images:

https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/pkg/supervisor/user.go#L263 should add the user with the group _name_ instead of _id_ (so `-G gitpod` instead of `-G 33333`). Looks like it used to do that as well before the logic got refactored into `supervisor`: https://github.com/gitpod-io/gitpod/blob/453cbeb9a135d0ca1449401206c113c384d5b10e/components/image-builder-mk3/workspace-image-layer/gitpod-layer/alpine/gitpod/layer.sh#L39 so fairly certain it's good to change this back.

Doing some more testing but can then raise a PR to fix this

cc @akosyakov

**Comment by akosyakov** [comment] 2022-11-02 15:20
@WVerlaek sure cc @mustard-mh since you changed it last, could you support?

**Comment by kylos101** [comment] 2022-11-02 16:03
> after some investigation, the gitpod user not existing in the image is OK, as supervisor will normally add the user on startup if it doesn't exist yet. What's happening is that there's actually a small bug in supervisor which causes it to error on adding the user for terraform/busybox images:

@WVerlaek nice find! 

> Doing some more testing but can then raise a PR to fix this

Awesome! Thank you very much @WVerlaek and @mustard-mh . :muscle:

**Comment by WVerlaek** [comment] 2022-11-04 15:10
Chatted with @kylos101, we'll close this issue as observations 1+2 in the [comment above](https://github.com/gitpod-io/gitpod/issues/12978#issuecomment-1295140275) will get solved by the issue+PR raised in the IDE team:
- https://github.com/gitpod-io/gitpod/issues/14293
- https://github.com/gitpod-io/gitpod/pull/14438

and observation 3 goes away when PVC gets enabled

**Closed by WVerlaek** 2022-11-04 15:10 UTC
Labels: type: bug, team: workspace

**Comment by kylos101** [comment] 2022-11-04 17:06
Closing as not planned and removing from Workspace project (it is presently in Awaiting Deployment, which is :upside_down_face: ).
