### ISSUE TITLE
Authorization failed. In Gitlab

### ISSUE THREAD

**Issue by ShashankBagauli** [gitpod-io/gitpod#2783] opened 2021-01-10 16:19 UTC

**Comment by csweichel** [comment] 2021-01-11 06:38
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by csweichel** 2021-01-11 06:38 UTC

**Comment by ShashankBagauli** [comment] 2021-01-11 15:11
Thnks
