### ISSUE TITLE
Ability to specify a Docker image without commiting to the repo e.g. via URL

### ISSUE THREAD

**Issue by peat-psuwit** [gitpod-io/gitpod#11171] opened 2022-07-06 09:53 UTC
## Is your feature request related to a problem? Please describe

It's useful to be able to specify a Docker image without committing to the repo. For example:
- Sometimes I would love to use GitPod for a project. However, I don't want to push GitPod to everyone else in the project (or maybe the project maintainer doesn't like GitPod's concept).
- Or maybe I'm checking out some project for the first time. I happen to know which Docker image works best for it, but I don't want to start a GitPod workspace only to add the `.gitpod.yml` and restart it again.
- Finally, maybe I'm working on a library which is supposed to work on multiple distributions. Being able to hop between multiple distros without actually modifying the git tree is nice.

## Describe the behaviour you'd like

I'm thinking of an extension to GitPod's URL context. For example:

`https://gitpod.io/#https://github.com/gitpod-io/gitpod?image=docker.io/debian:unstable`

would create a workspace based on Debian unstable. This should support public Docker repositories (other than Docker Hub), but not hand-built images.

(The syntax is intended to be an example. Feel free to change it.)

## Describe alternatives you've considered

- Launch a GitPod workspace, create (or modify) `.gitpod.yml`, and restart it again. It currently doesn't work, and it's pretty cumbersome.
- Building in nested docker daemon, while works, isn't as convenient as able to specify the container GitPod runs directly. For example, `compile_commands.json` won't work correctly.

**Comment by axonasif** [comment] 2022-07-06 13:23
Duplicate of https://github.com/gitpod-io/gitpod/issues/6275

**Closed** 2022-07-06 13:25 UTC
