### ISSUE TITLE
gitpod workspace url always located in us-02

### ISSUE THREAD

**Issue by jueinin** [gitpod-io/gitpod#1495] opened 2020-05-12 04:52 UTC
### Describe the bug

i am from HongKong Asia, but the workspace url always  is xxx.us-02.gitpod.io, the latency is a little high.  i need to change us-02 to as-02 manually, and ignore the ssl warning of chrome.so that i can connect to GCP hongkong node.   I hope add a button to choose location or get a more precious location detection.

**Comment by Kreyren** [comment] 2020-05-12 05:00
> i am from HongKong Asia, but the workspace url always is xxx.us-02.gitpod.io, the latency is a little high.

To my knowledge gitpod assigns the workspaces based on end-user's IP adress unless the expected cluster is down and the payload is transferred to nearest available -> Are you using a proxy?

>  and ignore the ssl warning of chrome.so that i can connect to GCP hongkong node.

Elaborate on SSL warnings? gitpod has valid SSL certificate so there shoudn't be any warnings?

**Comment by Kreyren** [comment] 2020-05-12 05:02
>  I hope add a button to choose location or get a more precious location detection.

FWIW i would also like to see more customization of gitpod ^-^

**Comment by jueinin** [comment] 2020-05-12 05:08
well, indeed ,i am from china shenzhen where nearby hongkong.  However,you know, in China it's a little difficult to connect Internet outside China. so i use proxy which locates in hongkong, but sometimes the latency is very high, change url to as-02 sometimes can impove the experience.
GCP may use anycast tech. the error may be related with my proxy.

**Comment by jueinin** [comment] 2020-05-12 05:10
> ### Describe the bug
> i am from HongKong Asia, but the workspace url always is xxx.us-02.gitpod.io, the latency is a little high. i need to change us-02 to as-02 manually, and ignore the ssl warning of chrome.so that i can connect to GCP hongkong node. I hope add a button to choose location or get a more precious location detection.
> 
> ### Steps to reproduce
> ### Expected behavior
> ### Additional information
> ### Example repository



> > i am from HongKong Asia, but the workspace url always is xxx.us-02.gitpod.io, the latency is a little high.
> 
> To my knowledge gitpod assigns the workspace clusters based on end-user's IP adress unless the expected cluster is down and the payload is transferred to nearest available -> Are you using a proxy?
> 
> > and ignore the ssl warning of chrome.so that i can connect to GCP hongkong node.
> 
> Elaborate on SSL warnings? gitpod has valid SSL certificate so there shoudn't be any warnings?

if you change url us-02 to as-02, chrome will warn you about SSL insecurity

**Comment by Kreyren** [comment] 2020-05-12 05:16
Can you check your whois i.e https://www.whatsmyip.org/whois-dns-lookup/?

I want to know what is the country on your proxy
![image](https://user-images.githubusercontent.com/11302521/81640934-1d520400-9420-11ea-885f-060d73d90c69.png)

which i believe is what is gitpod using to determine the cluster.

> if you change url us-02 to as-02, chrome will warn you about SSL insecurity

Confirmed on my system using firefox:
```
Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for REDACTED.ws-us01.gitpod.io. The certificate is only valid for the following names: *.gitpod.io, *.ws-ap.gitpod.io, *.ws-ap0.gitpod.io, *.ws-ap01.gitpod.io, *.ws-ap1.gitpod.io, *.ws-eu.gitpod.io, *.ws-eu0.gitpod.io, *.ws-eu01.gitpod.io, *.ws-eu1.gitpod.io, *.ws-us.gitpod.io, *.ws-us0.gitpod.io, *.ws-us02.gitpod.io, *.ws-us1.gitpod.io, gitpod.io

Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

![image](https://user-images.githubusercontent.com/11302521/81641027-5b4f2800-9420-11ea-8c3c-f79f157fe37e.png)

**Comment by Kreyren** [comment] 2020-05-12 05:21
@jueinin Can you try using either of following: `*.gitpod.io, *.ws-ap.gitpod.io, *.ws-ap0.gitpod.io, *.ws-ap01.gitpod.io, *.ws-ap1.gitpod.io, *.ws-eu.gitpod.io, *.ws-eu0.gitpod.io, *.ws-eu01.gitpod.io, *.ws-eu1.gitpod.io, *.ws-us.gitpod.io, *.ws-us0.gitpod.io, *.ws-us02.gitpod.io, *.ws-us1.gitpod.io, gitpod.io` ?

But i don't think that gitpod should work this way by design so some strange breakage may appear.

**Comment by jueinin** [comment] 2020-05-12 05:33
> I want to know what is the country on your proxy

my country code is AU, it seems to be Austria...

@Kreyren thank you, i seem to have understood the problem, it is relavent to my local ISP, when i use ChinaMobile ISP, it always route to US, when i use ChinaTelecom it always route to HongKong.no matter what the url is.

**Comment by Kreyren** [comment] 2020-05-12 05:35
@jueinin let me know if you were able to fix the issue by using different proxy.

For the feature request about region selection cc @jankeromnes

**Comment by jueinin** [comment] 2020-05-12 06:33
the problem is mostly relevent to ISP, i bought a better VPN proxy just now, the latency back to an acceptable level.  GCP's anycast is no problem.  China Mobile ISP connect to GCP HK will route to USA finallly route to HK. the erperience is  very bad. China Telecom can route to GCP HK directly.

it's not your problem, but mine. sorry for that.

**Comment by jueinin** [comment] 2020-05-12 06:33
> it's not your problem, but mine. sorry for that.

@Kreyren

**Comment by Kreyren** [comment] 2020-05-12 06:34
So is it resolved now?

**Comment by jueinin** [comment] 2020-05-12 06:38
> So is it fixed now?

yes  just proxy problem, not relevent to gitpod

**Comment by Kreyren** [comment] 2020-05-12 06:39
Closing as invalid then

@jueinin i will make a new tracking for the ability to choose the region, because i think it's a good idea ^-^

**Closed by Kreyren** 2020-05-12 06:39 UTC

**Comment by ceefour** [comment] 2020-09-05 08:49
> @jueinin Can you try using either of following: `*.gitpod.io, *.ws-ap.gitpod.io, *.ws-ap0.gitpod.io, *.ws-ap01.gitpod.io, *.ws-ap1.gitpod.io, *.ws-eu.gitpod.io, *.ws-eu0.gitpod.io, *.ws-eu01.gitpod.io, *.ws-eu1.gitpod.io, *.ws-us.gitpod.io, *.ws-us0.gitpod.io, *.ws-us02.gitpod.io, *.ws-us1.gitpod.io, gitpod.io` ?
> 
> But i don't think that gitpod should work this way by design so some strange breakage may appear.

Doesn't work:

![image](https://user-images.githubusercontent.com/24123/92301620-542fc500-ef8f-11ea-9e88-7dd357408422.png)
