### ISSUE TITLE
code: support ubuntu lts as a baseline

### ISSUE THREAD

**Issue by davidar** [gitpod-io/gitpod#3832] opened 2021-04-08 05:18 UTC
### Bug description

I'd been having this issue during the VSCode beta too (but Theia still worked so I didn't worry too much about it).

### Steps to reproduce

Try to open the Source Control and GitHub tabs (see attached screenshots).

### Expected behavior

They work.

### Example repository

I'm not actually sure what is causing this bug to occur, I'm not having it with some repos but I have no idea what the root cause is. Could it be influenced by the choice of Docker image somehow? Git still works in the terminal.

![](https://user-images.githubusercontent.com/24291/113971827-dad9b700-987c-11eb-9bd7-a9a0b62076ce.png)
![](https://user-images.githubusercontent.com/24291/113971875-f3e26800-987c-11eb-912d-e731ddb33997.png)

**Comment by akosyakov** [comment] 2021-04-08 05:50
Could you share the workspace id please? Some part of VS Code seems to fail to start in your workspace.

**Comment by akosyakov** [comment] 2021-04-08 09:41
Duplicate of https://github.com/gitpod-io/gitpod/issues/3797?

**Comment by davidar** [comment] 2021-04-08 10:06
`amethyst-tapir-5ya1y52x`

**Comment by akosyakov** [comment] 2021-04-08 11:37
From logs it looks like duplicate of https://github.com/gitpod-io/gitpod/issues/3797

**Comment by davidar** [comment] 2021-04-11 08:39
This (and #3833) is still an issue for me, despite #3797 being fixed. I created a new workspace (`indigo-cicada-60vljwtv`) just in case but am still seeing the same errors.

**Comment by akosyakov** [comment] 2021-04-12 06:16
Could you share with which repo please?

**Comment by davidar** [comment] 2021-04-12 06:34
https://github.com/davidar/moded-logic

**Comment by akosyakov** [comment] 2021-04-12 06:36
Your image does not seem to be fully compatible with VS Code. I see following in backend logs: `"Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /ide/node_modules/spdlog/build/Release/spdlog.node)\n`

VS Code relies on some native node modules and it does not work with your image. You can learn more about requirements to run VS Code here: https://code.visualstudio.com/docs/remote/linux#_tips-by-linux-distribution Maybe it is just a duplicate of #3356?

**Comment by akosyakov** [comment] 2021-04-12 07:20
I'm going try to rebuild VS Code with LTS version of ubuntu to support older version of glibc. For now you will need to bump up glibc 2.28 as a workaround.

**Comment by davidar** [comment] 2021-04-14 06:18
Thanks, I changed to an image based on Debian Buster and all seems to be working now. Would it be possible to make it a bit more obvious when errors like this occur? At the moment it's a bit difficult when things just fail semi-silently without much in the way of explicit error messages

**Comment by akosyakov** [comment] 2021-04-14 07:07
> Thanks, I changed to an image based on Debian Buster and all seems to be working now. Would it be possible to make it a bit more obvious when errors like this occur? At the moment it's a bit difficult when things just fail semi-silently without much in the way of explicit error messages

Usually you can see the server logs in `Output` -> `Remote Server`, but in this case even logging does not work 😬

**Closed** 2021-04-22 11:24 UTC
Labels: editor: code, type: bug
