### ISSUE TITLE
We could not connect to the extension marketplace at this time, please try again later.

### ISSUE THREAD

**Issue by bgoonz** [gitpod-io/gitpod#4601] opened 2021-06-24 07:07 UTC
### Bug description

The problem description is in the title... I have tried multiple times over the course of the last 10 hours against multiple containers and found this to be a persistent issue.

### Steps to reproduce

Try to open the extension tab.

### Expected behavior

Normal operation

### Example repository

Literally all of them.

![gitpod-issue](https://user-images.githubusercontent.com/66654881/123218074-46551d00-d499-11eb-934f-c2b0c3b7005d.PNG)

**Comment by corneliusludmann** [comment] 2021-06-24 07:50
OpenVSX seems to be down. See https://github.com/EclipseFdn/open-vsx.org/issues/555 and https://www.eclipsestatus.io/incidents/1hs2z6hznqhl.

**Comment by corneliusludmann** [comment] 2021-06-24 07:51
Duplicate of #4600.

**Closed by corneliusludmann** 2021-06-24 07:51 UTC
