### ISSUE TITLE
Unable to sign in using gmail option

### ISSUE THREAD

**Issue by hardik7e** [gitpod-io/gitpod#2764] opened 2021-01-10 11:43 UTC
I dont have an account on Gitpod.
i tried to sign in using gmail option but it says "Sorry, something went wrong. Authorization failed"

**Comment by akosyakov** [comment] 2021-01-10 13:09
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by akosyakov** 2021-01-10 13:09 UTC
