### ISSUE TITLE
[code] does not work with conanio/gcc7 base image

### ISSUE THREAD

**Issue by tonka3000** [gitpod-io/gitpod#2794] opened 2021-01-10 19:58 UTC
Hey,

the `Run` dock-view is always empty. In VSCode normally the is the possibility to create a launch.json file.

![image](https://user-images.githubusercontent.com/3163807/104133810-31bb1780-5386-11eb-9671-38cca1a55c3b.png)

Expected:
![image](https://user-images.githubusercontent.com/3163807/104133840-69c25a80-5386-11eb-8711-42476596eebc.png)

Version: 1.49.0
Commit: 20ded0d97c41cb686098d14b9e1f0533177300d1
Date: 2020-12-17T09:27:27.064Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

Greetings

Michael

**Comment by akosyakov** [comment] 2021-01-11 07:29
I could not reproduce. Could you share the repo which you are trying to run?

**Comment by tonka3000** [comment] 2021-01-11 18:29
Of course 😀 https://gitlab.com/tonka3000/simple-cpp-abi-project . I've just opened the `main` branch via the integrated GitPod button. The ID of the GitPod session is `fc6018b0-3ee1-4b2d-bc12-ed3314e5c12e`.

**Comment by akosyakov** [comment] 2021-03-28 11:28
I think it is related to the base docker image which you use, i.e. `conanio/gcc7`. I don't know what it is, from server logs I see:
```
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /ide/node_modules/spdlog/build/Release/spdlog.node)    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)    at Module.load (internal/modules/cjs/loader.js:863:32)    at Function.Module._load (internal/modules/cjs/loader.js:708:14)    at Module.require (internal/modules/cjs/loader.js:887:19)    at require (internal/modules/cjs/helpers.js:74:18)    at bindings (/ide/node_modules/bindings/bindings.js:112:48)    at Object.<anonymous> (/ide/node_modules/spdlog/index.js:3:35)    at Module._compile (internal/modules/cjs/loader.js:999:30)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)    at Module.load (internal/modules/cjs/loader.js:863:32)    at Function.Module._load (internal/modules/cjs/loader.js:708:14)    at Module.require (internal/modules/cjs/loader.js:887:19)    at require (internal/modules/cjs/helpers.js:74:18)    at nodeRequire (/ide/out/vs/loader.js:1003:24)    at NodeScriptLoader.load (/ide/out/vs/loader.js:797:39)    at OnlyOnceScriptLoader.load (/ide/out/vs/loader.js:610:32)    at loadNextPath (/ide/out/vs/loader.js:1609:41)    at Object.errorback (/ide/out/vs/loader.js:1617:25)    at OnlyOnceScriptLoader.triggerErrorback (/ide/out/vs/loader.js:623:36)    at /ide/out/vs/loader.js:610:151    at NodeScriptLoader.load (/ide/out/vs/loader.js:800:21)    at OnlyOnceScriptLoader.load (/ide/out/vs/loader.js:610:32)    at loadNextPath (/ide/out/vs/loader.js:1609:41)    at ModuleManager._loadModule (/ide/out/vs/loader.js:1621:13)    at ModuleManager._resolve (/ide/out/vs/loader.js:1706:26)    at ModuleManager.defineModule (/ide/out/vs/loader.js:1353:18)    at ModuleManager._relativeRequire (/ide/out/vs/loader.js:1387:18)    at result (/ide/out/vs/loader.js:1561:30)    at _spdlog (/ide/out/vs/gitpod/node/server.js:21105:74)    at new Promise (<anonymous>)    at createSpdLogLogger (/ide/out/vs/gitpod/node/server.js:21105:35)    at SpdLogLogger._createSpdLogLogger (/ide/out/vs/gitpod/node/server.js:21160:20)    at new SpdLogLogger (/ide/out/vs/gitpod/node/server.js:21150:48)    at /ide/out/vs/gitpod/node/server.js:29445:39    at InstantiationService.invokeFunction (/ide/out/vs/gitpod/node/server.js:18427:24)    at main (/ide/out/vs/gitpod/node/server.js:29436:30) { 
```

You can learn more about requirements to run VS Code here: https://code.visualstudio.com/docs/remote/linux#_tips-by-linux-distribution Maybe it is just a duplicate of https://github.com/gitpod-io/gitpod/issues/3356?

**Comment by akosyakov** [comment] 2021-04-12 07:19
closing as a duplicate of https://github.com/gitpod-io/gitpod/issues/3832

**Closed by akosyakov** 2021-04-12 07:19 UTC
Labels: editor: code, meta: :muscle: stretch goal, type: bug
