### ISSUE TITLE
Terminal is invisible

### ISSUE THREAD

**Issue by somehowchris** [gitpod-io/gitpod#5209] opened 2021-08-15 13:58 UTC
### Bug description

As displayed in the forum, when I open the instances webpage and execute a command there is something going on but nothing seems to be outputted.

### Steps to reproduce

 - Get a IPad (pro)
 - Get iOS 15 pb
 - Open an instances webpage in Safari (same in Brave and Chrome)
 - Open a terminal and see

### Expected behavior

The Terminal should output a clearly readable text

### Example repository

Any

### Anything else?

https://community.gitpod.io/t/invisible-terminal/4567/5

**Comment by youssseeef** [comment] 2021-08-15 16:17
I am facing the same issue, it seems that the latest updates for IPadOS 15 cause this to happen (I think from public beta 3), so might be something that changed in Safari that broke this.

**Comment by youssseeef** [comment] 2021-08-15 16:23
@somehowchris seems that there is a workaround for this here: https://github.com/gitpod-io/gitpod/issues/5194#issuecomment-899020876

**Comment by somehowchris** [comment] 2021-08-15 19:01
@somehowchris If I’m correct I am using the public beta 5 and sure a workaround is cool for the time (and thanks for the link) but not the best and hopefully not the final solution

**Comment by akosyakov** [comment] 2021-08-16 07:14
duplicate of https://github.com/gitpod-io/gitpod/issues/5040

**Closed by akosyakov** 2021-08-16 07:14 UTC
