### ISSUE TITLE
actual command NOT FOUND

### ISSUE THREAD

**Issue by xootkama** [gitpod-io/gitpod#7783] opened 2022-01-23 09:22 UTC
### Bug description

the bug while i am editing a large file ( may be 30000 lines). Changes are being made. I got that error. And after then it told saving (file.c) and after then it gave a bug like i have told in last issue.

### Steps to reproduce

Check it

**Comment by pawlean** [comment] 2022-01-23 17:40
Have you got a repo that we can try and reproduce this with? :)

**Comment by axonasif** [comment] 2022-01-24 07:03
A repo indeed would be helpful since the issue description is not clear enough 💯

**Comment by axonasif** [comment] 2022-01-24 07:14
> Test

**Comment by xootkama** [comment] 2022-01-25 13:45
Always has been . Sams giys

**Comment by xootkama** [comment] 2022-01-25 13:45
Repo is GitHub.com/xootkama/CAF-Test

**Comment by axonasif** [comment] 2022-01-25 16:10
> Repo is GitHub.com/xootkama/CAF-Test

It seems that's the linux kernel repo that you forked, are you trying to compile the kernel on Gitpod? Well that's something you have to configure yourself, this is not an "actual Gitpod issue" and I don't see any `.gitpod.yml` either 😕 

Closing this, feel free to open it again if you find something that is happening due to the Gitpod environment.

**Closed by axonasif** 2022-01-25 16:10 UTC
