### ISSUE TITLE
Impossible to uninstall extension(s), uninstalled extensions are synced & installed back

### ISSUE THREAD

**Issue by Foxhoundn** [gitpod-io/gitpod#7330] opened 2021-12-21 12:48 UTC
### Bug description

I already deleted all my cloud sync settings twice. I constantly have to uninstall extensions that should not be installed at all. At this moment it would be probably less time consuming to turn off setting sync and do everything everytime manually.

https://user-images.githubusercontent.com/8861481/146932126-d5546feb-408b-41a8-8b19-70a97de6d200.mp4

### Steps to reproduce

I have no idea, I tried an extension, I didn't like it I wanted to uninstall it but it won't let me. Also all the extensions are marked as to not sync (not by me), yet the are all synced anyway.

### Workspace affected

bronze-barnacle-pgkhcl2n

### Expected behavior

Extension should be uninstalled and properly synced.

**Comment by Foxhoundn** [comment] 2021-12-22 06:46
I've been debugging this a bit more

I uninstalled the extension `Bookmarks`, I refreshed the sync view but no new extensions entry was added. Basically no change.

But then I tried uninstalling the extension `Code Spell Checker` - now 2 things happen, there was both a Settings sync and Extensions sync. 

I would have thought it would now sync both of the changes, yet only the latter was synced as you can see on the diff below. If the sync really works like that (not doing a full sync, but rather picking and pushing) then I am not surprised it's buggy

![CleanShot 2021-12-22 at 07 40 30](https://user-images.githubusercontent.com/8861481/147047672-303d0b94-14f1-47f8-9c7f-4c02f728ab70.png)

![CleanShot 2021-12-22 at 07 40 48](https://user-images.githubusercontent.com/8861481/147047676-b79a822f-02f1-460c-949d-dce3a89e230c.png)

**Comment by Foxhoundn** [comment] 2021-12-22 09:17
More debug info:

After uninstalling an extension I can see in the Sync log that:


[2021-12-22 10:14:22.284] [settingssync] [info] GlobalState: Updated remote ui state
[2021-12-22 10:14:22.292] [settingssync] [info] GlobalState: Updated last synchronized ui state
**_[2021-12-22 10:14:22.802] [settingssync] [info] Extensions: No changes found during synchronizing extensions._**
[2021-12-22 10:14:22.804] [settingssync] [info] Sync done. Took 909ms

That is before clicking on `Reload` after uninstalling (I waited for approx 2 mins for this mesasge to appear)

**Comment by Foxhoundn** [comment] 2021-12-22 09:33
I just (again) cleared all of my Cloud data, and installed 3 extensions
![CleanShot 2021-12-22 at 10 25 42](https://user-images.githubusercontent.com/8861481/147069936-40e42ad6-1aae-49cc-8885-f26be062a317.png)![CleanShot 2021-12-22 at 10 25 57](https://user-images.githubusercontent.com/8861481/147069938-446576ce-69fc-4d43-bf36-51f5928ab5cf.png)

Then I **started** another workspace and it still has all the other old extensions installed

![CleanShot 2021-12-22 at 10 27 38](https://user-images.githubusercontent.com/8861481/147070073-6ed4285a-81d6-474e-a793-53808b85ed64.png)

It looks like, in order to solve this, I would either have to delete every single workspace except one and do the cloud clear there, or I would have to open every workspace and clear the cloud data in every single one?

I don't know but spending hours trying to uninstall extensions is not fun.

**Comment by akosyakov** [comment] 2021-12-22 11:37
duplicate of https://github.com/gitpod-io/gitpod/issues/3342

as a work around don't press reload immediately, wait a bit, or force sync

**Closed by akosyakov** 2021-12-22 11:37 UTC
Labels: team: IDE

**Comment by Foxhoundn** [comment] 2021-12-22 13:51
> duplicate of #3342
> 
> as a work around don't press reload immediately, wait a bit, or force sync

Is half of the issue going to be ignored? Where I cleared my cloud data, installed 2 extensions, opened a completely different workspace and 15 extensions were installed there?

Extension not uninstalling immediately is seriously half of the issue here.
