### ISSUE TITLE
Allow user to stop the workspace

### ISSUE THREAD

**Issue by ret394** [gitpod-io/gitpod#1774] opened 2020-08-30 03:58 UTC
- Allow user to stop the workspace after the build has started.

Implies that there is some undesirable state that the container reaches that the user did not expect. As usually, users don't want features without a reason in mind.

To be clear, gitpod workspaces don't start automatically, there is a trigger. The url appended to the `gitpod.io/#/` or to 'https://gitpod.io/#/'. 

**To Suspend or stop?**

Both are useful, but looking at the history or changelog if you prefer. Gap between Gitlab and Github integration took a long time. It would be great if even a stop option was introduced in a reasonable time-frame.

Useful in many cases, have fun enumerating them one-by-one. I am too efficient (maybe lazy)

One - The user needs to make some changes to container that has already entered the build phase.

**Comment by ret394** [comment] 2020-08-30 03:58
omitted 2 other related issues.
To find first one - hint is share the link to workspace/container. In the above scenario.

thanks. have a nice day. keep up the great work. 👏

[ret394](https://github.com/ret394)

**Comment by Kreyren** [comment] 2020-08-30 08:09
Seems like duplicate of https://github.com/gitpod-io/gitpod/issues/1419 with relevance to https://github.com/gitpod-io/gitpod/issues/551

**Comment by Kreyren** [comment] 2020-08-30 08:10
> Try to keep the static noise to information ratio low - for ex - Kreyren, I think.

Thanku ❤️

**Comment by svenefftinge** [comment] 2020-08-31 06:18
duplicate of #1419

**Closed by svenefftinge** 2020-08-31 06:18 UTC
Labels: duplicate, enhancement
