### ISSUE TITLE
Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: %!w(string=) when creating workspace from template

### ISSUE THREAD

**Issue by lechien73** [gitpod-io/gitpod#1559] opened 2020-05-28 09:32 UTC
### Describe the bug
We're getting the above error when trying to create a workspace from our Gitpod template: https://github.com/Code-Institute-Org/gitpod-full-template/

This was working until this morning, no changes have been made to the template.

### Steps to reproduce
Create a new repo based on the above template. Open it in Gitpod.

### Expected behavior
A new workspace based on the above template would be created.

<img width="1440" alt="Screenshot 2020-05-28 at 10 26 19" src="https://user-images.githubusercontent.com/21156053/83124762-8dbe7d80-a0ce-11ea-9d0e-7890c928bba2.png">

**Comment by lechien73** [comment] 2020-05-28 09:37
Possible dupe of https://github.com/gitpod-io/gitpod/issues/1545 but still happening for us.

**Comment by corneliusludmann** [comment] 2020-05-28 09:41
Thanks for reporting. We're on it.

**Comment by corneliusludmann** [comment] 2020-05-28 09:51
@lechien73 Should be work again. Please let me know if not.

**Comment by rholland** [comment] 2020-05-28 17:40
I have the same problem.

**Comment by Kreyren** [comment] 2020-05-28 17:43
reopening since the issue is not resolved

**Comment by corneliusludmann** [comment] 2020-05-28 17:44
It seems that we have in the US cluster the same issue we solved in EU earlier today. I'm looking into it.

**Comment by Kreyren** [comment] 2020-05-28 17:54
heads-up: Closed duplicate issue in favor of this issue.

**Comment by corneliusludmann** [comment] 2020-05-28 18:18
@rholland Should be fixed for the US cluster as well now. Please let me know and reopen this issue in case it's not.

**Closed by corneliusludmann** 2020-05-28 18:18 UTC
Labels: critical, operations
