### ISSUE TITLE
"Connect to activate this Git Provider" does not work

### ISSUE THREAD

**Issue by skthomasjr** [gitpod-io/gitpod#2479] opened 2020-12-09 16:36 UTC
### Describe the bug
Add a git provider that is self-hosted. Our company has several self-hosted gitlab and github servers.

### Steps to reproduce
Follow GitPods instruction to add a git provider

### Expected behavior
It works and a provider is added.

### Example repository
The repository is private and on a self-hosted server.

**Comment by csweichel** [comment] 2020-12-09 19:31
duplicate of https://github.com/gitpod-io/gitpod/issues/2468

**Closed by csweichel** 2020-12-09 19:31 UTC
