### ISSUE TITLE
Remove other GTAG usages

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#1136] opened 2020-01-23 03:59 UTC
Lots of pages, including the 'port not found' page contain google analytics.

This should only be on the homepage and docs.  Nothing else, please.

**Comment by jankeromnes** [comment] 2020-01-23 08:04
Hi @RDIL, wow, great catch! The 'port not found' page indeed has it, which should not be the case.

This still cannot track anything a user does inside the workspace ('port not found' is sandboxed in an iframe), but I agree that GA / GTAG should be removed from any such error pages.

Duplicate of #956. Sorry for lagging on this, I'll try to look into it today. (Please feel free to ping me again if I forget or get distracted, which happens more than I'd like to these days...)

**Closed by jankeromnes** 2020-01-23 08:04 UTC
