### ISSUE TITLE
Error message after installing Gitpod bot on a new repo

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#9141] opened 2022-04-05 20:30 UTC
### Bug description

In https://github.com/apps/gitpod-io/installations/new, I clicked on `Configure` next to the organization `Phase2`.
I selected 1 new repository to add.
After clicking `Update Access`, it took me to Gitpod page, with this error message -
![image](https://user-images.githubusercontent.com/22901/161843066-c2a3e363-c1de-432b-bf0c-623bb9e75c35.png)

When I go to 
![image](https://user-images.githubusercontent.com/22901/161843519-6361e57c-7abe-42cd-b85e-3a3c72fb51a9.png)
I can find the repository I added and create a new project.

This issue is about the confusing error message, because everything else work as expected.

### Steps to reproduce

Repeat the steps above.

**Comment by gtsiolis** [comment] 2022-04-06 09:52
Thanks, @shaal! Closing this as a duplicate of https://github.com/gitpod-io/gitpod/issues/6421. 📕

**Closed by gtsiolis** 2022-04-06 09:52 UTC
