### ISSUE TITLE
Errors displayed when connecting to Gitpod wokrspace using SSH (w/ Gitpod Local Companion)

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#5261] opened 2021-08-18 15:42 UTC
### Bug description

When connecting to a Gitpod workspace using SSH (with Gitpod Local Companion) - I am getting a few errors.
Perhaps it's related - the PATH env variable is different between Gitpod workspace vs. in the SSH session.

`ssh -F /tmp/gitpod_ssh_config green-swallow-3xe5xcjy`
Result:
```
-bash: rustc: command not found
-bash: /etc/bash_completion.d/cargo: No such file or directory
-bash: rustc: command not found
-bash: /etc/bash_completion.d/cargo: No such file or directory
-bash: pyenv: command not found
-bash: pyenv: command not found
```

One difference I noticed is the PATH env variable:
Gitpod Workspace:
```
PATH=/home/gitpod/.pyenv/plugins/pyenv-virtualenv/shims:/workspace/.cargo/bin:/workspace/.pip-modules/bin:/workspace/.rvm/bin:/home/gitpod/.sdkman/candidates/maven/current/bin:/home/gitpod/.sdkman/candidates/java/current/bin:/home/gitpod/.sdkman/candidates/gradle/current/bin:/home/gitpod/.rvm/gems/ruby-2.7.3/bin:/home/gitpod/.rvm/gems/ruby-2.7.3@global/bin:/home/gitpod/.rvm/rubies/ruby-2.7.3/bin:/home/gitpod/.pyenv/plugins/pyenv-virtualenv/shims:/workspace/.cargo/bin:/workspace/.pip-modules/bin:/workspace/.rvm/bin:/ide/bin:/home/gitpod/.pyenv/bin:/home/gitpod/.pyenv/shims:/workspace/go/bin:/home/gitpod/go/bin:/home/gitpod/go-packages/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin/:/home/gitpod/.nvm/versions/node/v14.17.3/bin:/home/gitpod/.cargo/bin:/usr/games:/usr/games:/home/gitpod/.nvm/versions/node/v14.17.3/bin:/home/gitpod/.rvm/bin:/home/gitpod/.nvm/versions/node/v14.17.3/bin:/home/gitpod/.nvm/versions/node/v14.17.3/bin
```

SSH:
```
PATH=/home/gitpod/.sdkman/candidates/maven/current/bin:/home/gitpod/.sdkman/candidates/java/current/bin:/home/gitpod/.sdkman/candidates/gradle/current/bin:/home/gitpod/.cargo/bin:/home/gitpod/.rvm/gems/ruby-2.7.3/bin:/home/gitpod/.rvm/gems/ruby-2.7.3@global/bin:/home/gitpod/.rvm/rubies/ruby-2.7.3/bin:/workspace/.cargo/bin:/workspace/.pip-modules/bin:/workspace/.rvm/bin:/usr/bin:/bin:/home/gitpod/.nvm/versions/node/v14.17.3/bin:/home/gitpod/.rvm/bin
```

### Steps to reproduce

1. Run Gitpod Local Companion
1. Open Gitpod workspace
1. `ssh -F /tmp/gitpod_ssh_config <gitpod_workspace_id>
1. _(Notice that errors are displayed before you can interact with terminal)_
1. Run `printenv PATH` in both workspace and local terminal and compare the result.

### Expected behavior

1. Connecting to Gitpod workspace through SSH should run smooth with no errors.
1. `printenv PATH` should be the in Gitpod's workspace and local terminal.

### Example repository

https://github.com/shaal/drupalpod

**Comment by akosyakov** [comment] 2021-08-19 05:58
duplicate of https://github.com/gitpod-io/gitpod/issues/4949

We have a fix for it already btw. Hope it is going to be released soon.

**Comment by shaal** [comment] 2021-08-19 11:10
Thank you!

Where can I follow new releases of the local companion app?

**Comment by akosyakov** [comment] 2021-08-20 06:12
We hope to get it out next week. It is not the issue with the local app, but SSH server. It did not propagate env vars to ssh sessions.

**Comment by shism2** [comment] 2021-08-23 03:52
Yes, I can't get it to work at all on windows.

**Comment by scottbradybuckii** [comment] 2021-09-16 17:52
@akosyakov I am still getting the errors in the initial post of this issue and am unable to execute multiple programs that should be in my PATH env, but are not.

We are using a custom Docker image, but I made sure that it is using the latest `gitpod/workspace-full` image, published on September 12th - and it barely changes that image, it just adds a few programs using apt.

I've also downloaded a fresh copy of the Local Companion to make sure that I have the latest version of that as well. Are there any other steps I should take to be able to use the fix that you've made for this issue?

**Comment by akosyakov** [comment] 2021-09-17 06:27
> I've also downloaded a fresh copy of the Local Companion to make sure that I have the latest version of that as well. Are there any other steps I should take to be able to use the fix that you've made for this issue?

No, downloading the latest local companion should be enough. Could you share the reproducible repo?

**Comment by scottbradybuckii** [comment] 2021-09-20 19:44
@akosyakov Any gitpod workspace that I use seems to have this same issue. I have a hello world repo that is producing the same error: https://github.com/scottbradybuckii/gitpod-local-errors

```
-bash: rustc: command not found
-bash: /etc/bash_completion.d/cargo: No such file or directory
-bash: rustc: command not found
-bash: /etc/bash_completion.d/cargo: No such file or directory
-bash: pyenv: command not found
-bash: pyenv: command not found
```

The gitpod-local-companion version is `gitpod-local-companion version main.1440`
I am running on Arch Linux

**Comment by akosyakov** [comment] 2021-09-21 06:34
Could you share logs of the local companion with me please? You can send them to anton@gitpod.io

**Comment by akosyakov** [comment] 2021-09-22 14:03
It seems that your workspace is running us15 and it looks like https://github.com/gitpod-io/gitpod/commit/0564c20b9b9a2c25270bd378be908593c92ea0c3#diff-65cc0869db34e619521c73193ee38a940a8e56d627b7573cb1351fb2cd690af3 change was not deployed there yet. @wulfthimm is it correct?

**Comment by akosyakov** [comment] 2021-09-23 06:05
@scottbradybuckii Yesterday all clusters were updated. Could you try again?

**Comment by scottbradybuckii** [comment] 2021-09-23 14:59
@akosyakov It's working for me now, thank you!

**Closed** 2021-09-23 15:01 UTC
Labels: meta: :thinking: reporter-feedback-needed, component: local app, team: IDE
