### ISSUE TITLE
Cannot delete my account

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5292] opened 2021-08-20 12:20 UTC
In preview environments the account deletion fails with an empty message:
```
construct.js:19 Uncaught (in promise) Error: Request deleteAccount failed with message: 
    at main.js:449
    at main.js:276
    at main.js:260
    at setImmediate.js:40
    at f (setImmediate.js:69)
    at n (setImmediate.js:109)
```

**Comment by svenefftinge** [comment] 2021-08-20 12:22
Oh, it seems like the deletion happened somehow. I'm now always redirected to the log-in page and see an error in the javascript console:
```
construct.js:19 Uncaught (in promise) Error: User has been deleted.
    at main.js:449
    at main.js:276
    at main.js:260
    at setImmediate.js:40
    at f (setImmediate.js:69)
    at n (setImmediate.js:109)
```

**Comment by AlexTugarev** [comment] 2021-08-20 12:22
likely a duplicate of https://github.com/gitpod-io/gitpod/issues/5262

**Comment by JanKoehnlein** [comment] 2021-08-20 13:25
Duplicate of #5262

**Closed by JanKoehnlein** 2021-08-20 13:25 UTC
Labels: priority: highest (user impact)
