### ISSUE TITLE
rename workspace

### ISSUE THREAD

**Issue by haneenmahd** [gitpod-io/gitpod#5365] opened 2021-08-25 04:44 UTC
Currently, there is no way you could edit the names of a workspace.
It is hard to remember those freaky names all the time.

**Comment by ghuntley** [comment] 2021-08-25 05:07
I agree the current naming system needs to be revisited. The current proposal is to change the behaviour to generate names using org followed by the repo-name. Would this help?

> e.g.: gitpod_io-gitpod-12rpnh3r

See https://github.com/gitpod-io/gitpod/issues/3908 and https://github.com/gitpod-io/gitpod/issues/4129#issuecomment-886429830

Personally, I would be hesitant to advocate for a way to rename workspaces because the lifecycle of workspaces should be short lived with a workspace created for each task then thrown away. This video further explains our recommended workflow https://www.gitpod.io/screencasts/fresh-dev-environments-for-each-new-task

**Comment by svenefftinge** [comment] 2021-08-25 06:57
this is a duplicate of https://github.com/gitpod-io/gitpod/issues/4857

**Closed by svenefftinge** 2021-08-25 06:57 UTC
