### ISSUE TITLE
Set timeout on Preview/Web browser

### ISSUE THREAD

**Issue by jaxxstorm** [gitpod-io/gitpod#3749] opened 2021-04-06 05:40 UTC
I have a web request that can take a few minutes running inside GitPod. Unfortunately, due to the proxy timeout, I gate a gateway error.

Is there any way we can increase this value?

**Comment by akosyakov** [comment] 2021-04-06 08:00
It looks like a duplicate of https://github.com/gitpod-io/gitpod/issues/3611

**Comment by JanKoehnlein** [comment] 2021-05-31 14:34
#3611 is closed. Please reopen if this error persists

**Closed by JanKoehnlein** 2021-05-31 14:34 UTC
Labels: component: ws-proxy, type: bug
