### ISSUE TITLE
Create an "after" directive in gitpod.yml

### ISSUE THREAD

**Issue by richardfrankza** [gitpod-io/gitpod#10180] opened 2022-05-23 04:21 UTC
## Is your feature request related to a problem? Please describe

When the workspace goes to sleep, data may be lost. For example, bash history or a database. I'd like to be able to preserve this information and restore it on start up.

## Describe the behaviour you'd like

We have `before` and `init` and `command` but I would like the ability to run a script as the workspace is closing down. For instance making a database snapshot to the workspace directory.

## Describe alternatives you've considered

A cron job running every 3 minutes perhaps?

**Comment by axonasif** [comment] 2022-05-23 05:39
Duplicate of https://github.com/gitpod-io/gitpod/issues/3966

**Closed by axonasif** 2022-05-23 05:39 UTC

**Comment by axonasif** [comment] 2022-05-23 05:42
> When the workspace goes to sleep, data may be lost. For example, bash history or a database. I'd like to be able to preserve this information and restore it on start up.

We have an Epic for shell histories specifically: https://github.com/gitpod-io/gitpod/issues/9019
For the meantime, if you're interested, take a look at here: https://github.com/axonasif/dotfiles, persisting shell histories is already possible with dotifles feature of gitpod, just not straightforward enough.
 
> or a database

If you keep it under `/workspace` dir, your database will persist.
