### ISSUE TITLE
unable to open files i get a string that says [object event] 

### ISSUE THREAD

**Issue by SNmcdarby1** [gitpod-io/gitpod#3874] opened 2021-04-09 15:55 UTC
### Bug description

similar problem to this 
https://crimson-tuna-hpo667r4.ws-eu03.gitpod.io/

### Steps to reproduce

still new in coding  and learning new skills 

### Example repository

https://crimson-tuna-hpo667r4.ws-eu03.gitpod.io/

**Comment by akosyakov** [comment] 2021-04-12 08:28
Does it work now? I cannot reproduce it unfortunately.

**Comment by gtsiolis** [comment] 2021-04-12 08:34
Could this be related to https://github.com/gitpod-io/gitpod/issues/2699? /cc @akosyakov

**Comment by SNmcdarby1** [comment] 2021-04-12 09:45
hello still encountering the same problem. 
![image](https://user-images.githubusercontent.com/69846208/114375027-2d1c2000-9b7c-11eb-9fc2-2c32a304b5ad.png)

**Comment by akosyakov** [comment] 2021-04-12 10:30
Could you try to disable/uninstall extensions one by one to see whether it makes any difference? I assume it is something what is configured for your user, either extensions or setting.

**Comment by akosyakov** [comment] 2021-04-12 10:33
I have following extensions installed, which do you have besides them:
<img width="1904" alt="Screenshot 2021-04-12 at 09 46 18" src="https://user-images.githubusercontent.com/3082655/114381233-2d6fe780-9b8b-11eb-97d7-b8a0ef35e0de.png">

**Comment by SNmcdarby1** [comment] 2021-04-13 13:41
Thank you for responding to my email. I'm away at the moment but will try
when I get back to it.

**Comment by akosyakov** [comment] 2021-04-22 12:47
I have a following suspicion: you copied your user settings from local VS Code and pasted in Gitpod but while doing you maybe forgot a closing bracket and something. So later when we try to load settings we cannot parse them actually. Is it correct?

You can reset your user data (settings/extensions) by:
- starting a workspace
- Run `Show Synced Data` command from the command palette
- then click `...` in the opened view title and `Clean Data in Cloud...`
- click reset and wait a bit till initial settings are restored

**Comment by akosyakov** [comment] 2021-04-22 13:33
Actually I think I found an issue in web dependencies for VS Code, following resource is missing: node_modules/jschardet/dist/jschardet.min.js

**Closed** 2021-04-22 14:54 UTC
Labels: editor: code, type: bug
