### ISSUE TITLE
Gitpod not oppening my files

### ISSUE THREAD

**Issue by LaiMo2020** [gitpod-io/gitpod#1493] opened 2020-05-10 10:25 UTC

**Comment by LaiMo2020** [comment] 2020-05-10 10:38
here is my url: https://gitpod.io/#https://github.com/LaiMo2020/my-full-template

**Comment by Kreyren** [comment] 2020-05-10 10:44
@LaiMo2020 elaborate on the issue

**Comment by Kreyren** [comment] 2020-05-10 10:46
I see 
![image](https://user-images.githubusercontent.com/11302521/81497053-45c0ed80-92bc-11ea-99de-35718362165a.png)

the files from https://github.com/LaiMo2020/my-full-template are ignored?

**Comment by LaiMo2020** [comment] 2020-05-10 15:09
@Kreyren thanks for this, 
My main problem that i can not see the button gitpod actually, even that i have installed the add-on. 
Then i wanted to open gitpod through a template that i got from Code institute, there i got this error ( We are having trouble parsing your context
Error: Unauthorized)

**Comment by LaiMo2020** [comment] 2020-05-10 15:13
hsi is the url for my repo:
https://github.com/LaiMo2020/my-first-repo

**Comment by Kreyren** [comment] 2020-05-10 15:17
> My main problem that i can not see the button gitpod actually, even that i have installed the add-on.

@LaiMo2020 Seems like duplicate of https://github.com/gitpod-io/gitpod/issues/1476 to me. Can you confirm?

> Then i wanted to open gitpod through a template that i got from Code institute, there i got this error ( We are having trouble parsing your context
> Error: Unauthorized)

That seems to be relevant to some configuration of `.gitpod.yml` but i can't reproduce it or understand how you get to thet point -> provide more info

**Comment by LaiMo2020** [comment] 2020-05-10 18:10
@Kreyren  The button that link to gitpod works now, thanks. Which  (info )you want to have ?

**Comment by LaiMo2020** [comment] 2020-05-10 19:26
and no it is not like #1476

**Comment by LaiMo2020** [comment] 2020-05-10 21:36
mostly like this issue; 
https://github.com/gitpod-io/gitpod/issues/957

**Comment by Kreyren** [comment] 2020-05-11 00:07
> Which (info )you want to have ?

Anything relevant that would explain what the issue is, because from the current info provided i don't understand how you got gitpod to output: `error ( We are having trouble parsing your context Error: Unauthorized)`

**Comment by Kreyren** [comment] 2020-05-11 00:08
@LaiMo2020 referenced issue https://github.com/gitpod-io/gitpod/issues/957 has different error message `Error: NotFoundError` so it's not relevant.

**Comment by Kreyren** [comment] 2020-05-11 00:08
@LaiMo2020 If you have issues with english feel free to use your native language ^-^

**Comment by Kreyren** [comment] 2020-05-11 00:14
@LaiMo2020 Also note that i am unable to reproduce your issue using https://github.com/LaiMo2020/my-full-template/blob/master/.gitpod.dockerfile

**Comment by jankeromnes** [comment] 2020-05-11 03:05
(reopening as requested by @Kreyren)

**Comment by LaiMo2020** [comment] 2020-05-11 07:21
Hi @Kreyren , The issue is solved now. It was stupid, I had to delete my caches and cookies, and it works.
Thanks again.
Have anice day!

**Comment by Kreyren** [comment] 2020-05-11 07:30
> I had to delete my caches and cookies, and it works.

Neither of those affect gitpod's runtime to my knowledge you only need cookie `_gitpod_io_` that can be set per session that then generates:
- theme
- gitpod-user
- user-platform
- GCLB
- _gitpod_io_..._...._port_auth_

Without `_gitpod_io_` the website doesn't know who you are and you can't use gitpod since if would just refresh on login screen.

Caches are also irelevant since these only store data per session as needed.

Did you do something stupid and make up an excuse just now? :p
If so there is no shame and admitting and i would be interested to know what you were confused about in case there is something that we can do to avoid similar confusion in the future. ^-^

**Comment by LaiMo2020** [comment] 2020-05-11 07:49
@Kreyren haha, If i had I would tell you ;) 
To give you more details, i had created a github account few month ago with the same email, and probably i didn't deleted correctly. Yesterday I asked help from https://slack.com and that was their explanation for my issue.

**Comment by Kreyren** [comment] 2020-05-11 08:55
Alright O.o assuming solved then ^^

**Closed** 2020-05-11 08:58 UTC
