### ISSUE TITLE
Connection got disposed

### ISSUE THREAD

**Issue by MrArturtleNSCDS** [gitpod-io/gitpod#1086] opened 2020-01-15 16:54 UTC
**Describe the bug**

GitPod does not load from GitHub
**To Reproduce**

Go to a repository, Click on "GitPod" button (chrome extension)
**Expected behavior**

GitPod logo turn Red, connection disposed
**Additional Information**

Uncaught (in promise) Error: Connection got disposed.
    at Object.dispose (start-workspace.js:6)
    at start-workspace.js:88
    at r.invoke (start-workspace.js:6)
    at i.fire (start-workspace.js:6)
    at q (start-workspace.js:6)
    at r.invoke (start-workspace.js:6)
    at i.fire (start-workspace.js:6)
    at t.WebSocketMessageReader.fireClose (start-workspace.js:6)
    at t.WebSocketMessageReader.fireClose (start-workspace.js:28)
    at start-workspace.js:28
/vs/editor/editor.main.css:1 Failed to load resource: the server responded with a status of 500 ()
/vs/loader.js:10 Loading "vs/css!vs/editor/editor.main" failed
n @ /vs/loader.js:10
/vs/loader.js:10 Error: Could not find vs/editor/editor.main.css or it was empty
    at Object.t [as ensureError] (/vs/loader.js:10)
    at s._createLoadError (/vs/loader.js:30)
    at Function.o.error (/vs/loader.js:32)
    at /vs/editor/editor.main.js:10
    at e._onLoadError (/vs/editor/editor.main.js:9)
    at /vs/editor/editor.main.js:10
    at HTMLLinkElement.s (/vs/editor/editor.main.js:9)
n @ /vs/loader.js:10
/vs/loader.js:10 Here are the modules that depend on it:
n @ /vs/loader.js:10
/vs/loader.js:11 Array(69)
n @ /vs/loader.js:11
/vs/editor/editor.main.nls.js:1 Failed to load resource: the server responded with a status of 500 ()
![Screen Shot 2020-01-15 at 10 50 28 AM](https://user-images.githubusercontent.com/31484951/72453879-7026f200-3785-11ea-8a1a-bd37010e2d07.png)

**Comment by RDIL** [comment] 2020-01-15 16:56
Duplicate of #1075

**Comment by MrArturtleNSCDS** [comment] 2020-01-15 16:58
Apologies, I'm very new, I thought I was adding to the previous convo. I'll move it over.

**Comment by JesterOrNot** [comment] 2020-01-16 13:51
Closing in favor of #1075

**Comment by jankeromnes** [comment] 2020-01-16 16:29
Thanks a lot for the report @MrArturtleNSCDS. 💯 This was a blind spot in our monitoring and alerts, so we heavily relied on reports like yours to understand what was happening.

**Comment by jankeromnes** [comment] 2020-01-16 16:30
(Sorry, I pressed the wrong button.)

**Closed by jankeromnes** 2020-01-16 16:30 UTC
