### ISSUE TITLE
Resolve Inter Pod Communication When Using Self-Signed TLS Certificates

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#11005] opened 2022-06-29 12:44 UTC
### Bug description

When selecting the 'Use Self-Signed TLS Certificates' option on the KOTS configuration page it causes an issue where pods are seemingly unable to communicate between each other. This happens at least between the image building pod and registry pod. Further discussion on this can be seen in [this internal Slack thread](https://gitpod.slack.com/archives/C01KLC56NP7/p1655389575693299).

Relates to gitpod-io/customers#62.

### Steps to reproduce

1. Spin up a Gitpod instance.
2. In the configuration screen within KOTS, under the TLS Certificates section, select option 1 which should be to use a self-signed certificate.
3. Once the instance is configured and Gitpod is running, attempt to spin up a workspace.
4. Observe an error about certificate signing - `x509: certificate signed by unknown authority`. This should appear in the image-builder pod logs.

**Comment by lucasvaltl** [comment] 2022-07-06 08:40
@MrSimonEmms would you mind taking a look at this as well and propose some next steps?

**Comment by MrSimonEmms** [comment] 2022-07-06 14:44
I can recreate this, but it requires additional investigation.

I found this error in `image-builder-mk3` pod:

```
{"a":{"All":false,"Explicit":["proxy.replicated.com","registry.replicated.com"],"Additional":null},"level":"error","message":"registry not allowed - you may want to add this to the list of allowed registries in your installation config","ref":{},"reg":"docker.io","serviceContext":{"service":"image-builder-mk3","version":"commit-27ac0cc34b8be917a79018193c76eb913151e8d0"},"severity":"ERROR","time":"2022-07-06T14:37:51Z"}
```

Also, the `imagebuild` pod is returning `Error from server (BadRequest): container "workspace" in pod "imagebuild-16cd261a-3645-4a86-bafe-caf6e29b3372" is waiting to start: trying and failing to pull image`

My thought is that maybe the work I did in adding the registries to `.experimental.webApp.server.defaultBaseImageRegistryWhitelist` broke it in some way (not sure how). I tried with an in-cluster registry, so this will require additional investigation.

**Comment by jimmybrancaccio** [comment] 2022-07-06 15:35
@MrSimonEmms That is _weird_! I had [someone in Discord](https://discord.com/channels/816244985187008514/991418942629351604/991815568451707050) with that same message and I was so confused as to why it was doing anything with Replicated...

**Comment by MrSimonEmms** [comment] 2022-07-19 11:16
Possibly related to https://github.com/gitpod-io/gitpod/pull/9553 - this is a note for me so I don't forget the PR number

**Comment by MrSimonEmms** [comment] 2022-07-26 10:47
Am transferring to @gitpod-io/engineering-workspace team due to https://github.com/gitpod-io/gitpod/pull/11502#issuecomment-1195318516

**Comment by roshvin** [comment] 2022-07-31 10:29
I am also facing this issue. is here any workaround for this .

**Comment by adrienthebo** [comment] 2022-08-04 23:40
I ran through the the Gitpod setup with a self-signed certificate (see https://gitpod-x509.adrien.gitpod-self-hosted.com) using an in-cluster registry, object store, and database. I was able to login, set up GitHub integration, build a workspace, and get a browser editor. Reviewing the logs indicated no TLS issues (aside from agent-smith, but that doesn't impact self-hosted users). All services were working as expected.

Note that these tests didn't handle the case where the container registry was untrusted, but that's an orthogonal topic. (See #9611 and #11811 for related discussions). 

The only point of variation is that I added the self-signed certificate to the Mac system keychain to avoid invalid cert issues from the browser but this shouldn't impact the functional testing of inter-pod communication.

Most of the issues we've observed that appear to be inter-pod communication have all turned out to be either misconfigurations or untrusted registry certificates, which are _not_ issues with inter-pod communication. The following cases stand out:

1. **Misconfiguration of the container registry address:** A typo in a self-hosted user's container registry address (combined with a wildcard certificate signed by a private CA) caused containerd image fetches from `image-build-mk3` and `imagebuilder` pods to be sent to the wrong service that presented an untrusted cert. When the typo was corrected image builds were able to resume normally.
2. **Image registry presents a certificate signed by an untrusted CA**: As described in https://github.com/gitpod-io/customers/issues/62, image fetches failed when gitpod was configured to use a container registry presented a CA certificate that wasn't trusted by containerd. As @sagor999 described in https://github.com/gitpod-io/gitpod/pull/11666#issuecomment-1198659908 this is a matter of dropping the appropriate CA certificate in the containerd config directory and applying the appropriate containerd registry configuration. We've broken out #11811 to address this issue.

At present the the only outstanding issue with inter-pod communication appears to be [#11233](https://github.com/gitpod-io/gitpod/issues/11233). I'm planning on doing more testing with container registries with untrusted certificates tomorrow and will look into blobserve issues as well.

**Next steps**

- Because we appear to have isolated issues with image fetching and ruled out internal misconfiguration of the CA certs for the image-build and imagebuilder pods, we should be able to close out #11666.
- Untrusted registries can be addressed by adding their CA certificates to Gitpod in #9611 and #11811. Instead of disabling TLS certificate verification we can simply add more CA certs to our trust stores.
- Blobserve issues will be addressed in #11233.
- I'll do more testing around blobserve and untrusted container registries shortly and will update this ticket.

This should encompass most (if not all) of our outstanding TLS cert trust issues. Can anyone find cases that aren't covered by the above?

- - -

@roshvin you indicate that you've encountered TLS issues within your Gitpod installation, can you provide more information on how you set up your Gitpod installation or steps to reproduce the failure?

**Comment by sagor999** [comment] 2022-08-05 17:36
Assigning this to @adrienthebo and team self hosted for further investigation\exploration. 
Please feel free to open a separate issue if workspace component needs fixing.

**Comment by adrienthebo** [comment] 2022-08-09 15:35
Since this issue was resolved and we haven't heard any further discussion on this issue I'm closing this ticket. @roshvin if you are still having issues with certificates within Gitpod please create a new ticket with your bug report and we can continue this conversation. Thanks!

**Closed by adrienthebo** 2022-08-09 15:35 UTC
Labels: type: bug, meta: :thinking: reporter-feedback-needed
