### ISSUE TITLE
Segfault in content-service

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#4125] opened 2021-04-30 14:52 UTC
observed today in prod in version `content-service:master.3264`.

Example:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xba6c98]

goroutine 34705 [running]:
github.com/gitpod-io/gitpod/content-service/pkg/storage.(*PresignedGCPStorage).DeleteObject(0xc00011bd00, 0xf0c498, 0xc0009adb30, 0xc000c85200, 0x35, 0xc00059ffe0, 0x0, 0x0)
	github.com/gitpod-io/gitpod/content-service/pkg/storage/gcloud.go:927 +0xe38
github.com/gitpod-io/gitpod/content-service/pkg/service.(*WorkspaceService).DeleteWorkspace(0xc0004ca1e0, 0xf0c498, 0xc0009adb00, 0xc0003f57c0, 0x0, 0x0, 0x0)
	github.com/gitpod-io/gitpod/content-service/pkg/service/workspace-service.go:78 +0x3ea
github.com/gitpod-io/gitpod/content-service/api._WorkspaceService_DeleteWorkspace_Handler.func1(0xf0c498, 0xc0009adb00, 0xd634c0, 0xc0003f57c0, 0xdf4a67, 0xd, 0xe12737, 0x30)
	github.com/gitpod-io/gitpod/content-service/api@v0.0.0-00010101000000-000000000000/workspace_grpc.pb.go:122 +0x89
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0xf0c498, 0xc0009ad8c0, 0xd634c0, 0xc0003f57c0, 0xc00059f800, 0xc0011411a0, 0x3, 0x3, 0x7f0043a2ed58, 0xc001119320)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/tracing/opentracing/server_interceptors.go:34 +0x108
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0xf0c498, 0xc0009ad8c0, 0xd634c0, 0xc0003f57c0, 0x30, 0xc0003f5810, 0x7f0043cae2b8, 0x20)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0xf0c498, 0xc0009ad8c0, 0xd634c0, 0xc0003f57c0, 0xc00059f800, 0xc00059f820, 0xbad73a, 0xd4faa0, 0xc00059f8c0, 0xc00059f800)
	github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0xb0
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0xf0c498, 0xc0009ad8c0, 0xd634c0, 0xc0003f57c0, 0xc0004fe000, 0x0, 0xc00078db30, 0x40e278)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0xf0c498, 0xc0009ad8c0, 0xd634c0, 0xc0003f57c0, 0xc00059f800, 0xc0011411a0, 0xc00078dba0, 0x59dea6, 0xd6e380, 0xc0009ad8c0)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:34 +0xd7
github.com/gitpod-io/gitpod/content-service/api._WorkspaceService_DeleteWorkspace_Handler(0xceed00, 0xc0004ca1e0, 0xf0c498, 0xc0009ad8c0, 0xc000eb1260, 0xc0004ab2f0, 0xf0c498, 0xc0009ad8c0, 0xc000f9cff0, 0x46)
	github.com/gitpod-io/gitpod/content-service/api@v0.0.0-00010101000000-000000000000/workspace_grpc.pb.go:124 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002d1a40, 0xf14918, 0xc0004fc780, 0xc00071be00, 0xc0004abbc0, 0x13ebbd8, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.36.0/server.go:1217 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002d1a40, 0xf14918, 0xc0004fc780, 0xc00071be00, 0x0)
	google.golang.org/grpc@v1.36.0/server.go:1540 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000422060, 0xc0002d1a40, 0xf14918, 0xc0004fc780, 0xc00071be00)
	google.golang.org/grpc@v1.36.0/server.go:878 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.36.0/server.go:876 +0x1fd
```

Search in the logs via `textPayload:"panic" labels."k8s-pod/component"="content-service"` to find them all. 
I did not check if all crashes have the same cause.

**Comment by AlexTugarev** [comment] 2021-05-05 05:32
Closing as duplicate of https://github.com/gitpod-io/gitpod/issues/4077

**Closed by AlexTugarev** 2021-05-05 05:32 UTC
