### ISSUE TITLE
Error starting workspaces based on prebuilds which use git LFS 

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#8117] opened 2022-02-09 11:34 UTC
This is a clarification of #7988 

The git-lfs binary is available in the Gitpod base image, so prebuilds can call now call `git lfs` commands without first installing git-lfs. [[1](https://github.com/gitpod-io/workspace-images/blob/ca92f62a62e65eb404b23fa1cda8a769040b03db/base/Dockerfile#L62)] The git lfs commands are availabe from any default-image Gitpod workspace terminal.

If a prebuild uses a git lfs command like `git lfs pull`, the repository files are modified, and workspaces based on that prebuild will fail on startup. This may be a result of https://github.com/gitpod-io/gitpod/issues/8105.

An example of this can be seen in https://github.com/jldec/lfs-test/pull/4/files

The failure can be reproduced by opening that branch in a gitpod workspace with
https://gitpod.io/#https://github.com/jldec/lfs-test/tree/init

![Screenshot 2022-02-09 at 11 17 06](https://user-images.githubusercontent.com/849592/153189411-0060bec2-5a60-4db1-a639-ead1ab13e319.png)

**error text** (for searches)  
> cannot initialize workspace: cannot initialize workspace: prebuild initializer: git checkout -B init origin/init failed (exit status 1): Branch 'init' set up to track remote branch 'init' from 'origin'. Switched to a new branch 'init' \nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.\n ; last backup failed: workspace does not exist. Please contact support if you need the workspace data.

Starting workspaces on a branch with no prebuild, or with prebuilds which do not use git-lfs, does not fail. E.g.
https://gitpod.io/#https://github.com/jldec/lfs-test/tree/main

For more information about git LFS, see https://jldec.me/what-is-git-lfs

**Comment by csweichel** [comment] 2022-02-09 12:00
This is a duplicate of https://github.com/gitpod-io/gitpod/issues/8105 - LFS init for prebuilds happens as part of the content initializer.

**Closed by csweichel** 2022-02-09 12:00 UTC
Labels: team: workspace
