### ISSUE TITLE
I am not able to login to Gitpod provided by Crio platform.

### ISSUE THREAD

**Issue by piyooshag9** [gitpod-io/gitpod#2878] opened 2021-01-13 07:07 UTC
### Describe the bug

Sorry, something went wrong, Authorization failed. Please try again - I am getting this error when i try to login. I already confirm authorization from github and also confirm from google but still getting this issue.

**Comment by csweichel** [comment] 2021-01-13 08:38
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by csweichel** 2021-01-13 08:38 UTC
