### ISSUE TITLE
cannot open workspace after repository renamed

### ISSUE THREAD

**Issue by timoch** [gitpod-io/gitpod#1074] opened 2020-01-13 12:33 UTC
**Describe the bug**
I renamed one of my private repository. Afterwards, gitpod cannot open the workspace with the following error on screen:
Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: Error response from daemon: No such image: gitpod.io/image-builder/selfbuild:0d43ec8ced752a6866ceff4c4e054184be03c58023cd1270bf5af574a0a2d1cf
Please file an issue if you think this is a bug.

**To Reproduce**
Try opening my private repository, error shows while "Booting up" is shown

**Expected behavior**
Workspace starts

**Comment by jankeromnes** [comment] 2020-01-13 13:09
Thanks a lot for reporting this problem. Duplicate of #1072, which should now be fixed.

**Closed by jankeromnes** 2020-01-13 13:09 UTC
