### ISSUE TITLE
cant login to create a new machine 

### ISSUE THREAD

**Issue by bubsy3d** [gitpod-io/gitpod#2817] opened 2021-01-11 10:00 UTC

**Comment by bubsy3d** [comment] 2021-01-11 10:00
tried to login by linking my google acc via gitlab

**Comment by akosyakov** [comment] 2021-01-11 10:11
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by akosyakov** 2021-01-11 10:11 UTC
