### ISSUE TITLE
"We are having trouble parsing your context" in GitPod

### ISSUE THREAD

**Issue by TiffanyDonner** [gitpod-io/gitpod#1505] opened 2020-05-13 10:23 UTC
### Describe the bug
I created a new repository in GitHub and clicked the green button toopen GitPod however, I get an error of "We are having trouble parsing your context
Error: GitHub API Error. Status: 500
Please file an issue if you think this is a bug.

### Expected behavior
To open my new repository...

**Comment by Kreyren** [comment] 2020-05-13 10:24
afaik this is caused by a syntax error in `.gitpod.yml` please verify

**Comment by jankeromnes** [comment] 2020-05-13 11:19
> afaik this is caused by a syntax error in `.gitpod.yml` please verify

No, the error "We are having trouble parsing your context" is about mis-using the `gitpod.io/#` URL prefix, and has nothing to do with `.gitpod.yml`.

E.g. try visiting https://gitpod.io/#what-is-this

The supported context URLs are currently GitHub or GitLab URLs, e.g.:
- https://gitpod.io/#https://github.com/gitpod-io/website (repo)
- https://gitpod.io/#https://github.com/gitpod-io/website/pull/508 (PR)
- https://gitpod.io/#https://github.com/gitpod-io/website/tree/jx/latex-in-gitpod (branch)
- https://gitpod.io/#https://github.com/gitpod-io/website/issues/74 (issue)
- https://gitpod.io/#https://gitlab.com/gitpod/spring-petclinic (same as above but in GitLab)

Things that are not yet supported by the `gitpod.io/#` prefix:
- Typos (e.g. adding a space after the `#`, or messing up the `https://` in the GitHub/GitLab URL, etc)
- Gists
- Random websites

Note: Support for Bitbucket.org URLs, and for self-managed GitHub/GitLab/Bitbucket instance URLs is coming soon.

**Comment by jankeromnes** [comment] 2020-05-13 11:23
Ah, I just noticed the `Error: GitHub API Error. Status: 500` in the original report.

In that case, maybe the URL was indeed a valid GitHub URL, but for some reason the GitHub API returned `HTTP 500 Internal Server Error` to a request from Gitpod.

This can happen when GitHub.com has a temporary outage (check https://www.githubstatus.com/), but it's almost always temporary, so if you retry the same thing (sometimes immediately, sometimes after after a few minutes) it will likely work.

**Comment by Kreyren** [comment] 2020-05-13 11:28
For the record this is the error message on mis-use of context url alike `https://gitpod.io/#https://githfasfasub.com/gitpod-io/gitpod/issues/1505`:

![image](https://user-images.githubusercontent.com/11302521/81806925-7489ce80-951d-11ea-8350-1dace0d8bd52.png)

**Comment by TiffanyDonner** [comment] 2020-05-13 11:34
Just in case anyone has this issue in the future. I was able to clear it by logging out and logging back in!

**Comment by Kreyren** [comment] 2020-05-13 11:49
> I was able to clear it by logging out and logging back in! @TiffanyDonner

FWIW from the informations provided we believe that it's because GitHub had a temporary shortage which prevented gitpod from authentificating the workspace. So you would likely resolve the issue by re-openning the workspace.

Closing as resolved ^-^

**Closed by Kreyren** 2020-05-13 11:49 UTC
Labels: github
