### ISSUE TITLE
Hostname not correctly parsed, redirect fails: Authorization with "gitlab." is not permitted

### ISSUE THREAD

**Issue by JamesCullum** [gitpod-io/gitpod#2651] opened 2021-01-04 12:13 UTC
### Describe the bug
I tried to connect Gitpod to our self-hosted Gitlab instance.
The connection works fine and it appears with the correct hostname in the control center.

However when I click on the "Gitpod" button (or do it manually via URL), I get a URL such as 
`https://gitpod.io/#https://gitlab.test1.test2.eu/group/folder/repo-name/-/tree/master/`

Once I visit this page, I get the error `This action requires more permissions. Please authorize with gitlab. to continue.`.
The link leads to `https://gitpod.io/api/authorize?returnTo=https%3A%2F%2Fgitpod.io%2F%23https%3A%2F%2Fgitlab.test1.test2.eu%2Fgroup%2Ffolder%2Frepo-name%2F-%2Ftree%2Fmaster%2F&host=gitlab.&scopes=read_user,api`

As you can see, the `host` field is invalid in both the page and the link.
If I click on it, it tells me the host "gitlab." can not be found: https://gitpod.io/sorry/#Authorization%20with%20%22gitlab.%22%20is%20not%20permitted.
Fixing the host parameter in the gitpod.io URL redirects me to the same "Please authorize with gitlab. to continue" URL.

### Steps to reproduce
Visit https://gitpod.io/#https://gitlab.test1.test2.eu/group/folder/repo-name/-/tree/master/ optionally click on the URL

### Expected behavior
It should parse the hostname correctly and detect the session or request authentication to the correct host.

### Additional information
Not needed, but let me know if you need any

### Example repository
https://gitlab.test1.test2.eu/group/folder/repo-name/-/tree/master/

**Comment by JamesCullum** [comment] 2021-01-04 12:21
Potential duplicate of https://github.com/gitpod-io/gitpod/issues/2606

**Comment by svenefftinge** [comment] 2021-01-04 13:05
Thanks for reporting. Yes, it is a duplicate of #2606 .

**Closed by svenefftinge** 2021-01-04 13:05 UTC
