### ISSUE TITLE
Attempting to create a Workspace failed

### ISSUE THREAD

**Issue by domesticmouse** [gitpod-io/gitpod#3545] opened 2021-03-23 01:20 UTC
### Bug description

failed to create containerd task: failed to mount rootfs component &{overlay overlay [workdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/4236/work upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/4236/fs lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/507/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/506/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/505/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/504/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/503/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/502/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/501/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/500/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/499/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/498/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/497/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/496/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/495/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/494/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/493/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/492/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/491/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/490/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/489/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/201/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/200/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/199/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/198/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/197/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/196/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/195/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/193/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/192/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/191/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/190/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/189/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/188/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/187/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/186/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/184/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/183/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/182/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/181/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/180/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/179/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/178/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/177/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/176/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/175/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/174/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/173/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/172/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/171/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/170/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/169/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/168/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/167/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/166/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/165/fs]}: failed to mountat: failed to find pid=3875388 process: no child processes: unknown; last backup failed: workspace content was never ready. Please contact support if you need the workspace data.
Please file an issue if you think this is a bug.

### Steps to reproduce

1) Install Gitpod extension
2) Navigate to https://github.com/domesticmouse/github.dart
3) Click Gitpod button to checkout repo

### Example repository

https://github.com/domesticmouse/github.dart

**Comment by meysholdt** [comment] 2021-03-23 08:00
duplicate of https://github.com/gitpod-io/gitpod/issues/3548. Apologies for the trouble.

**Closed by meysholdt** 2021-03-23 08:00 UTC
