### ISSUE TITLE
Improve support for C#

### ISSUE THREAD

**Issue by GuzioMG** [gitpod-io/gitpod#548] opened 2019-05-07 22:26 UTC
I'm so GLaD*, that C#, JS and Java are all supported, since they are my favorite languages. I just love them. Started with Java, then tried JS (I thought it's similar) and moved to C# (which is closer to Java than Java to JavaScript, which is kinda wired) because of Unity (but Unity (and not only Unity) support is subject of #549). 
BUT! While they are all supported, C# support... Honestly? Just sucks.

A.nd I know, that C# is supported only when it comes to syntax highlighting, but even this is pretty bad. It just detects a few keywords, such as "class", "using", "namespace", "if" and a few more and make it dark blue. Then it detects symbols and makes them white. Everything else is just light blue.

Next thing is total lack of any compilation, run, debug, error detection, etc. I don't even need real-time error highlighting. I just want to compile it and then see where I did mistakes. It can even not highlight errors in the editor itself. Just add jump to file in error window. Then, after successful compilation, I just want to have a way to download output and a debugger. Do I want much? No! All you need to add is compiler (you can actually take any first open source one) and execution engine with debugger. Again. Take any first open source engine with debugger. It'll be fine. You don't yet need to implement some advanced error detection mekanisms.

And third thing: code autocompletion. Right now, on website, you can see C# is still on highlighting-only side. It would be nice to see it in Gitpod.

I think you don't need to focus must on features right now. There is plenty of things, that are arleady implemented. You should focus more on languages right now to attract more devs to this IDE. And C# is probably the most popular on "highlighting-only" list right now.

*I wonder who spotted the joke in saying "GLaD" instead of "glad"... #HelloMyDearPortalPlayers

**Comment by GuzioMG** [comment] 2019-05-07 22:51
Ps. If you don't want to implement full C# support yet, feel free to bring #550 to life.

**Comment by svenefftinge** [comment] 2019-05-08 00:11
Again, thank you! As you'd have guessed we are going to integrate https://github.com/OmniSharp/omnisharp-vscode
Also, we will provide a setup and documentation for using C# with .Net SDK.
Not sure we will soon be able to support Unity, as our workspace nodes currently don't have GPUs.

Closing this as duplicate of #17

**Closed by svenefftinge** 2019-05-08 00:11 UTC

**Comment by frostebite** [comment] 2020-07-25 01:16
@svenefftinge I don’t think you would want to run the unity editor in your vscode instances. You would just need to link the appropriate .dlls to the c# project.

**Comment by frostebite** [comment] 2020-07-25 01:17
Building wouldn’t really be an option, but you might be able to get it so people can edit their unity c# code without syntax highlighting complaining about missing .dlls.
