### ISSUE TITLE
Error 504 again ¬¬.

### ISSUE THREAD

**Issue by HSSANT** [gitpod-io/gitpod#1152] opened 2020-01-27 15:13 UTC
Error 504 again ¬¬.

![image](https://user-images.githubusercontent.com/9882822/73186465-85453e80-40fe-11ea-9b7c-e929a0afbd00.png)

**Comment by jeffersoncbd** [comment] 2020-01-27 15:27
i have the same problem

**Comment by jeffersoncbd** [comment] 2020-01-27 16:07
open through any repository using: gitpod.io/#any_repository

**Comment by jankeromnes** [comment] 2020-01-27 16:15
Thank you @HSSANT and @jeffersoncbd for reporting this. We're investigating this and trying to restore service as fast as possible.

**Comment by jankeromnes** [comment] 2020-01-27 16:26
Duplicate of #1151 -- we'll post any updates there.

**Closed by jankeromnes** 2020-01-27 16:26 UTC
