### ISSUE TITLE
I am constantly getting the message sorry something went wrong when I am trying to login with gitlab since 12 hours.

### ISSUE THREAD

**Issue by Abhiraj3112000** [gitpod-io/gitpod#2778] opened 2021-01-10 14:26 UTC

**Comment by csweichel** [comment] 2021-01-11 06:42
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by csweichel** 2021-01-11 06:42 UTC

**Comment by Abhiraj3112000** [comment] 2021-01-23 13:45
Thank u very much.
