### ISSUE TITLE
Cannot push commits

### ISSUE THREAD

**Issue by RossComputerGuy** [gitpod-io/gitpod#1026] opened 2019-12-20 18:37 UTC
**Describe the bug**
Cannot push commits when changing `.github` files

**To Reproduce**
Edit or add GitHub workflow files and attempt to commit and push

**Expected behavior**
The commits to be pushed

**Additional Information**
```
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 16 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (9/9), 732 bytes | 366.00 KiB/s, done.
Total 9 (delta 3), reused 1 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 2 local objects.
To https://github.com/nero-vi/website.git
 ! [remote rejected] master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/nodejs.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/nero-vi/website.git'
```

**Comment by JesterOrNot** [comment] 2019-12-20 18:59
duplicate of #984

**Closed** 2019-12-21 04:20 UTC
