### ISSUE TITLE
Preferences are not considered at startup on already opened files

### ISSUE THREAD

**Issue by mrussmann** [gitpod-io/gitpod#836] opened 2019-10-07 08:06 UTC
**Describe the bug**
Preferences are not considered at startup on already opened files. 

**To Reproduce**
Switch eg. codelense in your preferences off, adjust fontsize in your preference file. 
Open some files, restart workspace, on already opened files codelense is switched on again and the fontsize is set to default. 
Close the files and reopen everything is ok.

**Expected behavior**
Preferences are also considered on already opened files.

**Comment by JesterOrNot** [comment] 2019-10-07 20:41
What's the link to the repo that might help

**Comment by mrussmann** [comment] 2019-10-07 21:13
on all my workspaces! I am currently writing java code. Just switched codelense off and did a simple reload of the workspace in the  browser -> after the reload codelense is on and the font size is extremly small.

**Comment by JesterOrNot** [comment] 2019-10-07 21:28
So what is the issue? could you explain it in more detail?

**Comment by mrussmann** [comment] 2019-10-07 21:30
switch code lense off - can you do that?

**Comment by mrussmann** [comment] 2019-10-07 21:40
easier example: put this in your pref file:
"editor.fontSize": 22, <- which is big
then open a code file, size should be set to 22,
then do a browser reload, 
the font size is the default font size, not 22

**Comment by JesterOrNot** [comment] 2019-10-07 21:42
in your user preferences is autosave on? it's possible that you didn't save the settings so when you refreshed the changes did not persist

**Comment by mrussmann** [comment] 2019-10-07 21:46
the pref is saved, it is persistent, it only happens on a browser reload and on workspace startup when the files are already opened. it worked before the update last week. have you tried it?

**Comment by JesterOrNot** [comment] 2019-10-07 21:50
I see

**Comment by jankeromnes** [comment] 2019-10-08 09:40
@mrussmann sorry about that problem, and thank you for reporting it. Also, thank you @JesterOrNot for helping reproduce the bug.

@AlexTugarev could you please look into this if you have some time? 🙂

**Comment by AlexTugarev** [comment] 2019-10-08 10:25
Sounds like a bug in Theia. Thanks for reporting!

**Comment by mrussmann** [comment] 2019-10-22 15:03
any news on this? after a reload or a restart the font size of the opened files is nearly unreadable.

**Comment by JesterOrNot** [comment] 2019-10-22 17:03
Should this issue be refiled against theia and if so can we close this issue

**Comment by svenefftinge** [comment] 2019-10-25 17:47
There seems to be a race where the editors are not updated once the preferences are initialized.

**Comment by svenefftinge** [comment] 2019-10-26 17:00
I have fixed it in Theia. https://github.com/eclipse-theia/theia/pull/6450
Will land in Gitpod in a couple of days.

**Comment by svenefftinge** [comment] 2019-12-05 07:15
In production now

**Closed by svenefftinge** 2019-12-05 07:15 UTC
Labels: bug, fixed-not-deployed
