### ISSUE TITLE
The terminal looks weird sometime

### ISSUE THREAD

**Issue by jefer94** [gitpod-io/gitpod#8145] opened 2022-02-10 20:37 UTC
### Bug description

In some time I open a gitpod and the terminal look weird
![image](https://user-images.githubusercontent.com/3018142/153492255-41d34d47-9a80-4f84-ba59-ff3876fbb08a.png)

### Steps to reproduce

I don't know

### Workspace affected

jefer94-apiv2-l5rbzma219o.ws-us31

### Expected behavior

The terminal look normal

### Example repository

https://github.com/jefer94/apiv2/tree/development

### Anything else?

No

**Comment by jefer94** [comment] 2022-02-10 20:43
![image](https://user-images.githubusercontent.com/3018142/153493176-9ae44548-02e4-4326-b0a6-cce59fcd9ec1.png)

**Comment by axonasif** [comment] 2022-02-11 09:58
> Duplicate of #4130?

Could be, it's either his browser config or `terminal.integrated.gpuAcceleration`

**Comment by jefer94** [comment] 2022-02-12 17:30
Many of this configs help to resolve the problem, but this still being a bad behavior of console

**Comment by loujaybee** [comment] 2022-02-14 10:08
Moving to scheduled to assess if the bug is in Gitpod, or an upstream issue (as before).

**Comment by alexanderkoh** [comment] 2022-02-21 19:41
I am facing the same situation since last week. Is there any interim fix?

**Comment by jeanp413** [comment] 2022-03-03 01:46
This is duplicate of https://github.com/gitpod-io/gitpod/issues/5014
@alexanderkoh you can try disabling brave adblocker

**Closed by jeanp413** 2022-03-03 01:46 UTC
Labels: type: bug, team: IDE

**Comment by kellySmi** [comment] 2022-05-03 14:13
Is there an open ticket for this issue, as I am still experiencing it. I noticed when viewing the browser in a second monitor is when this issue occurs. Viewing the browser in my laptop display, it looks as expected.
