### ISSUE TITLE
Gitpod tests taking long to run and fails to respond further

### ISSUE THREAD

**Issue by ArbeenaAzeeb1** [gitpod-io/gitpod#14155] opened 2022-10-25 10:10 UTC
### Bug description

When a user tries to run tests via Gitpod, it shows that the tests are running for a long duration. However, they are not able to receive the response of the test run. It stops responding further.

### Steps to reproduce

Write a test code and try running it using the 'Run' icon

### Workspace affected

All workspaces

### Expected behavior

Tests should run without any lag

### Example repository

Our repo is private as of now. We are working on some student submitting assignments and we have tests written as a part of it. These unit tests are taking long to run

**Comment by ArbeenaAzeeb1** [comment] 2022-10-31 11:03
Hey, we are trying to use the extension 'https://github.com/Microsoft/vscode-java-test' to run the java tests, which seems to run take a long execution time. You can replicate this issue by running the tests in this example repo - https://github.com/gitpod-io/spring-petclinic - given by gitpod itself using the above extension.

**Comment by mustard-mh** [comment] 2022-11-14 15:51
@andreafalzetti Could you try to reproduce it since you're on-call this week 🙏

**Comment by andreafalzetti** [comment] 2022-11-15 07:10
from initial tests, I can reproduce, and I believe the extension gets stuck in detecting the environment (eg maven home) properly. I've tried passing custom settings but didn't work what I tried.

<img width="489" alt="Screenshot 2022-11-15 at 06 15 33" src="https://user-images.githubusercontent.com/2318450/201853034-53ee8fa0-c2e1-4ae4-8a6c-6949e33f5dc5.png">

**Comment by andreafalzetti** [comment] 2022-11-16 12:59
@mustard-mh @jeanp413 is there a way to see logs for vscode extensions? I suspect it gets stuck at detecting the maven home or some other param from the workspace, but without logs it's hard to say.

**Comment by jeanp413** [comment] 2022-11-16 22:09
@ArbeenaAzeeb1 could you try again, we just did some updates related to java extension, can you still reproduce?

**Comment by akosyakov** [comment] 2022-11-17 10:36
@ArbeenaAzeeb1 @LorenzoBettini if you have a reproducible repo it would be helpful that we can confirm exactly for your case 🙏

**Comment by LorenzoBettini** [comment] 2022-11-17 13:28
@akosyakov I did some experiments some time ago in this repo https://github.com/LorenzoBettini/maven-gitpod-example I'm trying to reopen it right now... apparently, installing Java extension pack is taking ages so I still can't verify that the problem is fixed. Is https://github.com/gitpod-io/spring-petclinic working?

**Comment by LorenzoBettini** [comment] 2022-11-17 13:33
and while installing the extension I get a popup on the right-bottom saying "missing gallery"

**Comment by akosyakov** [comment] 2022-11-17 14:07
> apparently, installing Java extension pack is taking ages so I still can't verify that the problem is fixed.

yes, there is a bug in VS Code taking it forever, you can work around by reloading the page

> and while installing the extension I get a popup on the right-bottom saying "missing gallery"

Ouch, I have not seen such. Could you share a screenshot or collect logs https://www.gitpod.io/docs/help/troubleshooting#gitpod-logs-in-vs-code-browser-and-desktop 🙏

**Comment by LorenzoBettini** [comment] 2022-11-17 15:06
@akosyakov yes, reloading seems to fix the problem with Java extensions being installed.

I confirm that now I can run the tests:

![image](https://user-images.githubusercontent.com/1202254/202482086-960f64b8-8021-4152-a10e-92ee84ed439c.png)

:)

**Comment by akosyakov** [comment] 2022-11-18 14:01
@jeanp413 @mustard-mh it seems to be the follow up of https://github.com/gitpod-io/gitpod/issues/14626? Closing as a dup?

**Comment by jeanp413** [comment] 2022-11-18 18:51
> apparently, installing Java extension pack is taking ages so I still can't verify that the problem is fixed.

yep this is duplicate of https://github.com/gitpod-io/gitpod/issues/14626

Original issue about running java test should be fixed now

**Closed by jeanp413** 2022-11-18 18:51 UTC
Labels: type: bug, meta: :thinking: reporter-feedback-needed, editor: code (browser), team: IDE
