### ISSUE TITLE
Support xdg-open

### ISSUE THREAD

**Issue by 32leaves** [gitpod-io/gitpod#274] opened 2019-01-29 11:00 UTC
On Linux there's a widespread utility [`xdg-open`](https://linux.die.net/man/1/xdg-open) which opens files and URLs alike. Some [Node modules](https://github.com/domenic/opener) to open files in a platform-independent manner rely on this utility.

Gitpod already supports a lot of the required functionality in `gp open` and `gp preview`. A first step could be to introduce an alias `xdg-open="gp open"`. To better comply with the expected behaviour of `xdg-open`, `gp open` should be able to handle URLs as well.

**Comment by meysholdt** [comment] 2019-05-31 09:32
I ran into this yesterday but I missed that we already have an issue for this. I'm closing this in favor of the issues I created since they have more details. I hope that's ok.

Duplicate of https://github.com/gitpod-io/gitpod/issues/598 and https://github.com/gitpod-io/gitpod/issues/596

**Closed by meysholdt** 2019-05-31 09:32 UTC
Labels: enhancement
