### ISSUE TITLE
Fixing the Chrome extension button style

### ISSUE THREAD

**Issue by mhewedy** [gitpod-io/gitpod#1624] opened 2020-06-23 23:17 UTC
As now Github has a new style, it is better to fix the style of the GitPod button to match it.

**Comment by Kreyren** [comment] 2020-06-23 23:38
works on my end, can you make a screenshot of the issue?

**Comment by svenefftinge** [comment] 2020-06-26 09:55
Has been fixed, but is not yet published on chrome store.
Dupe of https://github.com/gitpod-io/gitpod/issues/1630

**Closed by svenefftinge** 2020-06-26 09:55 UTC
Labels: browser-extension
