### ISSUE TITLE
Unable to add extension to user and repository at the same time

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1614] opened 2020-06-18 15:10 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/11302521/85038121-826ae900-b186-11ea-840d-980dc29007a1.png)

It is not possible to add an extension for the end-user and for the repository at the same time.

This is required in a case like shellcheck where end-user might want to have this extension installed as user and also to add it into the repository

**Comment by jankeromnes** [comment] 2020-06-18 15:46
@Kreyren Good point. As a workaround, can you install it for a project, then copy the `.gitpod.yml` entry, then open a different repository, and install it for user, and then add the copied entry to `.gitpod.yml`?

**Comment by Kreyren** [comment] 2020-06-18 15:47
@jankeromnes I've just downloaded the extension and drag-and-dropped them into the both as workaround, but it's pretty annoying especially when i am doing this for every repository~

**Comment by jankeromnes** [comment] 2020-06-18 15:48
I would say this is a duplicate of #1615 (because fixing #1615 will allow installing an extension at both user- and project-level -- I don't think we want a specific option that says "install in both at the same time" because that seems like a fringe use case)

**Closed by jankeromnes** 2020-06-18 15:48 UTC
Labels: bug, theia
