### ISSUE TITLE
[prebuild] prebuilds are marked as error even though they are in ready state

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#10054] opened 2022-05-16 23:12 UTC
### Bug description

Here is a loom video showing an issue:
https://www.loom.com/share/55988106aa8a4fc39544a53a0611daaa

Here is a description from: https://github.com/gitpod-io/gitpod/issues/9710#issuecomment-1128221314
```
while trying to repro this case, I noticed an odd behaviour that I think is due to a fix for 
https://github.com/gitpod-io/gitpod/issues/9676 :
when prebuild has finished, and snapshot is being taken, prebuild will show up in dashboard in ERROR state. 
After snapshot was taken, it will get updated into READY state. But when I go into list of prebuilds,
it still shows up there as in ERROR state.
```

### Steps to reproduce

follow the steps in loom video

**Comment by geropl** [comment] 2022-05-17 07:12
This is clearly a "misunderstanding" on the API level, about what intermediate conditions a workspace can be in. After #10053 got merged this should be clear.

When fixing this, we should extend our tests to not only cover singular status -> prebuild mappings, but also chains, and enforce constraints like "never go to error and back to available" etc. :+1:

**Comment by laushinka** [comment] 2022-05-17 14:27
Hi @sagor999, would you mind checking if this still happening? I checked in the Admin dashboard for your `prebuild-experiment` project and the prebuilds show as ready. We had a bug in the fix for #9676 and the fix was just deployed this morning. 

<img width="640" alt="Screenshot 2022-05-17 at 16 27 24" src="https://user-images.githubusercontent.com/8015191/168835482-f4cc9d01-d2fa-4804-9895-eab7b23873d0.png">

**Comment by jldec** [comment] 2022-05-17 17:36
@laushinka it looks like there may be other instances of this after the deploy this morning.
see [slack](https://gitpod.slack.com/archives/C03145ZD98D/p1652801913728589) (internal)

**Comment by sagor999** [comment] 2022-05-17 19:17
@laushinka just tested and I am still seeing same behaviour. Prebuild is marked as failed after it is finished, and then once snapshot is created, it is updated to "ready". 
When I go into prebuilds for the project though, I still see prebuild is marked as failed.

**Comment by DaniAkash** [comment] 2022-05-18 07:00
@laushinka this is still happening in my workspace as well

**Comment by jldec** [comment] 2022-05-18 09:31
NOTE:
With this issue, even though prebuild status is being incorrectly reported, prebuilds are succeeding, and workspaces should start properly. We are looking for a fix for the incorrect status.

**Closed** 2022-05-18 12:59 UTC
Labels: type: bug, component: ws-manager-bridge, team: webapp

**Comment by DaniAkash** [comment] 2022-05-19 05:54
Prebuilds are still getting marked as failed after they successfully finish.
<img width="570" alt="Screenshot 2022-05-19 at 11 01 49 AM" src="https://user-images.githubusercontent.com/6841445/169219669-3663d314-f955-445e-9d76-6bbc855600e5.png">

This is causing issues with merging PRs since gitpod is a mandatory check in our repositories

**Comment by DaniAkash** [comment] 2022-05-19 09:52
Not sure if a fix is merged as part of any other PRs, but the issue is fixed now 👍🏽

**Comment by laushinka** [comment] 2022-05-19 09:55
> Not sure if a fix is merged as part of any other PRs, but the issue is fixed now 👍🏽

Hi @DaniAkash, thanks for updating that it's fixed now. We only just deployed the fix less than two hours ago 🙏🏽
