### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by rayson1223** [gitpod-io/gitpod#1244] opened 2020-02-21 01:29 UTC
### Describe the bug
cannot initialize workspace: cannot initialize workspace: cannot initialize workspace: git initializer: git clone https://github.com/eclipse-theia/theia.git . failed (exit status 128): Cloning into '.'... fatal: write error: No space left on device fatal: index-pack failed
Please file an issue if you think this is a bug.

### Steps to reproduce

Generate a new pod

### Expected behavior

Expected a new workspace is open

**Comment by JesterOrNot** [comment] 2020-02-21 01:52
Hello @rayson1223 and welcome to the Gitpod community
This is a duplicate of #1243 please voice your concerns there if you would like

Thank you for contributing!

**Closed by JesterOrNot** 2020-02-21 01:52 UTC

**Comment by rayson1223** [comment] 2020-02-21 02:39
Hello @JesterOrNot , my bad that didn't check the issues list before I posting. 
Thank you for verifying! =)

**Comment by JesterOrNot** [comment] 2020-02-21 02:40
It's no problem 😃
