### ISSUE TITLE
Can't view PDF files in gitpod using vscode 

### ISSUE THREAD

**Issue by Kreijstal** [gitpod-io/gitpod#4193] opened 2021-05-10 16:23 UTC
### Bug description

Google console seems to suggest this has to do with CORS headers. I'll post the error message here. This doesn't happen with Theia.

```
Refused to frame 'https://34427-olive-octopus-119p1edf.ws-eu04.gitpod.io/' because it violates the following Content Security Policy directive: "default-src http://localhost:* http://127.0.0.1:*". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
```

### Steps to reproduce

Go to gitpod using vscode

### Expected behavior

Well, it should be able to preview pdfs

**Comment by AlexTugarev** [comment] 2021-05-11 06:57
@akosyakov, do you know if and how it's possible to preview PDF documents in Code?

**Comment by akosyakov** [comment] 2021-05-14 07:26
It is a duplicate of https://github.com/gitpod-io/gitpod/issues/3831 please try Five Server extension

**Closed by akosyakov** 2021-05-14 07:26 UTC
Labels: editor: code
