### ISSUE TITLE
Investigate Pending for long duration while the actual state was pod terminating

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/gitpod#9673] opened 2022-05-02 03:41 UTC
### Bug description

Several prebuild pods were stuck in terminating phase for several hours in `us43` and `us43xl` clusters. However, the phase count in the dashboard was `Prebuild Pending`. Investigate why we had a conflicting states.

~~The outcome of this issue can be another issue to add timeout to pending prebuilds.~~

This problem impacted prebuild and regular.

Most of the nodes on which these prebuilds were scheduled were gone.

<details>
<summary>us43
</summary>

```console

➜  us-stuck-in-pending kubectl get po -owide | grep pre | grep Ter
prebuild-0c45f4e9-abc3-4c29-9c85-a51abadd7300   0/1     Terminating         0               19h     10.20.7.155     headless-ws-us43-pool-thcf    <none>           <none>
prebuild-0d3ca6b9-04ee-4da5-bd7b-493221ffe879   0/1     Terminating         0               19h     10.20.251.202   headless-ws-us43-pool-xdfm    <none>           <none>
prebuild-1996722a-f3f9-4a64-a2dc-04f237f3f3ae   0/1     Terminating         0               8m22s   10.20.253.235   headless-ws-us43-pool-ll7f    <none>           <none>
prebuild-1fb2ff5e-3255-42e3-a484-b46202cf05d8   0/1     Terminating         0               19h     10.20.251.199   headless-ws-us43-pool-xdfm    <none>           <none>
prebuild-27493cd3-1b9a-4de7-b1cb-6bbba07e791c   0/1     Terminating         0               19h     10.20.96.12     headless-ws-us43-pool-lq8j    <none>           <none>
prebuild-30494f3c-0800-4243-9153-83474cf7d9a3   0/1     Terminating         0               31m     10.20.25.117    headless-ws-us43-pool-tvlr    <none>           <none>
prebuild-42829b9d-601c-411d-9dfa-87efa818d71b   0/1     Terminating         0               19h     10.20.81.8      headless-ws-us43-pool-9s4l    <none>           <none>
prebuild-48ee6d5d-7880-4864-ac52-53c0a44111e5   0/1     Terminating         0               19h     10.20.96.11     headless-ws-us43-pool-lq8j    <none>           <none>
prebuild-4d729152-892c-4969-a480-6f18aa3343c7   0/1     Terminating         0               11m     10.20.22.204    headless-ws-us43-pool-pt26    <none>           <none>
prebuild-5284f1f7-c6d8-4b7a-ad03-260c63a41a4e   0/1     Terminating         0               19h     10.20.7.149     headless-ws-us43-pool-thcf    <none>           <none>
prebuild-5ecad41c-636d-4827-a061-07446e009f34   0/1     Terminating         0               19h     10.20.96.6      headless-ws-us43-pool-lq8j    <none>           <none>
prebuild-60495392-bae2-4417-9e44-f91cda87fe21   0/1     Terminating         0               19h     10.20.248.153   headless-ws-us43-pool-29d8    <none>           <none>
prebuild-62ebdc8a-1d08-4967-9624-bf28273ec1ba   0/1     Terminating         0               19h     10.20.251.204   headless-ws-us43-pool-xdfm    <none>           <none>
prebuild-6cdea1ae-7512-4134-9312-fcf3f44972ca   0/1     Terminating         0               19h     10.20.81.14     headless-ws-us43-pool-9s4l    <none>           <none>
prebuild-6e39ed53-a4a4-4812-88ad-f916dba9557c   0/1     Terminating         0               19h     10.20.81.5      headless-ws-us43-pool-9s4l    <none>           <none>
prebuild-6edcd793-9ebd-42b7-ba92-6ebad560f41f   0/1     Terminating         0               19h     10.20.225.7     headless-ws-us43-pool-gtj7    <none>           <none>
prebuild-7bcdc9bb-143a-4b6e-b9bc-47e847eaef70   0/1     Terminating         0               19h     10.20.81.6      headless-ws-us43-pool-9s4l    <none>           <none>
prebuild-7e0a943e-b729-401d-b66c-3fc0c80f4027   0/1     Terminating         0               19h     10.20.225.6     headless-ws-us43-pool-gtj7    <none>           <none>
prebuild-84ff8457-83f6-47f9-8c9f-4943b6cae10f   0/1     Terminating         0               2d16h   10.20.193.111   headless-ws-us43-pool-gj1f    <none>           <none>
prebuild-85cf7eda-74cf-4046-88a2-f9119dfdc976   0/1     Terminating         0               19h     10.20.203.211   headless-ws-us43-pool-ft4q    <none>           <none>
prebuild-89e9bc32-4031-4d64-977f-1f960525d7bf   0/1     Terminating         0               19h     10.20.33.175    headless-ws-us43-pool-rwqf    <none>           <none>
prebuild-8f003460-b59b-450a-8afc-b70b811330ba   0/1     Terminating         0               19h     10.20.81.12     headless-ws-us43-pool-9s4l    <none>           <none>
prebuild-9154d2c9-190b-4afb-8fb4-2412d17c8d8f   0/1     Terminating         0               19h     10.20.117.77    headless-ws-us43-pool-frw7    <none>           <none>
prebuild-920ba800-b699-4080-a493-7bcb8cac9e65   0/1     Terminating         0               19h     10.20.81.10     headless-ws-us43-pool-9s4l    <none>           <none>
prebuild-a7fa5a49-e4b1-4243-be34-85cd5c48464c   0/1     Terminating         0               19h     10.20.81.13     headless-ws-us43-pool-9s4l    <none>           <none>
prebuild-b1056668-17e8-450c-a55a-64541b7febc0   0/1     Terminating         0               25h     10.20.112.254   headless-ws-us43-pool-46rb    <none>           <none>
prebuild-b1cdb3d8-d24d-4361-baed-eae8d66b4a69   0/1     Terminating         0               19h     10.20.225.5     headless-ws-us43-pool-gtj7    <none>           <none>
prebuild-b1ef75ed-c279-4238-935a-8ca3b4920a14   0/1     Terminating         0               19h     10.20.33.137    headless-ws-us43-pool-rwqf    <none>           <none>
prebuild-b3fb4185-0dd9-4644-bc0f-97437f295e6f   0/1     Terminating         0               19h     10.20.248.142   headless-ws-us43-pool-29d8    <none>           <none>
prebuild-b9192d09-b31a-48c4-98ce-3d501f0392c1   0/1     Terminating         0               19h     10.20.251.200   headless-ws-us43-pool-xdfm    <none>           <none>
prebuild-bffc2fc2-e975-4b98-81fc-51904087d2bf   0/1     Terminating         0               19h     10.20.117.74    headless-ws-us43-pool-frw7    <none>           <none>
prebuild-c9edd92a-f6bb-4d53-8b91-9ba1c4664f80   0/1     Terminating         0               19h     10.20.251.205   headless-ws-us43-pool-xdfm    <none>           <none>
prebuild-ce19a222-ea77-4557-b500-034c259577be   0/1     Terminating         0               19h     10.20.81.7      headless-ws-us43-pool-9s4l    <none>           <none>
prebuild-ce66042d-a7d5-48c2-acb6-acc744f5ce57   0/1     Terminating         0               19h     10.20.117.81    headless-ws-us43-pool-frw7    <none>           <none>
prebuild-db866803-82cc-4531-9924-7e7143b13a43   0/1     Terminating         0               19h     10.20.251.198   headless-ws-us43-pool-xdfm    <none>           <none>
prebuild-e420c81c-8111-4cb9-8a49-d2816d6df314   0/1     Terminating         0               19h     10.20.211.82    headless-ws-us43-pool-r4p6    <none>           <none>
prebuild-e52cfb9b-feb7-4233-b1df-3be49d6822e0   0/1     Terminating         0               19h     10.20.21.69     headless-ws-us43-pool-frmk    <none>           <none>
prebuild-e5d548a3-b1c7-4db9-85e0-373642029f45   0/1     Terminating         0               19h     10.20.21.70     headless-ws-us43-pool-frmk    <none>           <none>
prebuild-ecac6eb4-8aa1-475d-b67f-77dbafa860e8   0/1     Terminating         0               2d9h    10.20.34.95     headless-ws-us43-pool-z644    <none>           <none>
prebuild-f2ed52ef-ae7f-4ebc-83b6-dc458275d8a7   0/1     Terminating         0               19h     10.20.251.197   headless-ws-us43-pool-xdfm    <none>           <none>
```

</details>

<details>
<summary>us43xl
</summary>

```console
➜  us-stuck-in-pending kubectl get po -owide | grep pre | grep Ter
prebuild-025802bb-ad03-41d8-a5e4-d95ca82c3b69   0/1     Terminating   0              4h53m   10.20.109.127   headless-ws-us43xl-pool-qqcx    <none>           <none>
prebuild-07a2c9f3-1254-4671-96cd-9452ee88c3b5   0/1     Terminating   0              4h53m   10.20.66.69     headless-ws-us43xl-pool-vsh9    <none>           <none>
prebuild-0cb0ffcc-87ff-4902-b3e3-9fb94eeb5464   0/1     Terminating   0              4h53m   10.20.2.8       headless-ws-us43xl-pool-266x    <none>           <none>
prebuild-1cb16bb3-0698-470c-815f-cd3ac075791c   0/1     Terminating   0              4h53m   10.20.109.122   headless-ws-us43xl-pool-qqcx    <none>           <none>
prebuild-1e135b5d-18d0-444c-bdea-5f2b9fba3f92   0/1     Terminating   0              4h53m   10.20.66.71     headless-ws-us43xl-pool-vsh9    <none>           <none>
prebuild-2b5f9d48-2916-437f-8e4e-4be848b0f453   0/1     Terminating   0              4h53m   10.20.152.44    headless-ws-us43xl-pool-t6rw    <none>           <none>
prebuild-43fb3f88-62b9-4fd0-b87e-1e5c6164a7fc   0/1     Terminating   0              4h53m   10.20.247.70    headless-ws-us43xl-pool-mfk9    <none>           <none>
prebuild-579286db-109f-4d88-8915-b622037a0d6c   0/1     Terminating   0              4h53m   10.20.2.6       headless-ws-us43xl-pool-266x    <none>           <none>
prebuild-5e74793f-36bd-4f8f-a897-6e7edc70b31b   0/1     Terminating   0              4h53m   10.20.32.184    headless-ws-us43xl-pool-ttzt    <none>           <none>
prebuild-5ec0e8fb-ce22-4956-9d8c-ce6fa6cb45ae   0/1     Terminating   0              4h53m   10.20.2.7       headless-ws-us43xl-pool-266x    <none>           <none>
prebuild-78ab8b38-d4ef-4940-94e5-2497ff6861b1   0/1     Terminating   0              4h53m   10.20.66.72     headless-ws-us43xl-pool-vsh9    <none>           <none>
prebuild-8745f4e3-45ab-478e-bd9c-ad45c0a23968   0/1     Terminating   0              4h53m   10.20.152.40    headless-ws-us43xl-pool-t6rw    <none>           <none>
prebuild-892d4962-0147-47ee-989d-6955baebc7cc   0/1     Terminating   0              4h53m   10.20.109.125   headless-ws-us43xl-pool-qqcx    <none>           <none>
prebuild-8c4b2943-370e-4961-9400-be9418f79dbb   0/1     Terminating   0              4h53m   10.20.32.152    headless-ws-us43xl-pool-ttzt    <none>           <none>
prebuild-99573ed9-4fb6-4bf6-84df-840a51e37717   0/1     Terminating   0              4h53m   10.20.32.182    headless-ws-us43xl-pool-ttzt    <none>           <none>
prebuild-b4875fb2-c758-4523-a650-589a3c638a72   0/1     Terminating   0              4h53m   10.20.109.126   headless-ws-us43xl-pool-qqcx    <none>           <none>
prebuild-b9ad6d80-d2d2-49f1-9ad6-b55071e68153   0/1     Terminating   0              4h53m   10.20.109.70    headless-ws-us43xl-pool-qqcx    <none>           <none>
prebuild-c024777b-af8d-46cc-947d-d361e6cc601b   0/1     Terminating   0              4h53m   10.20.66.70     headless-ws-us43xl-pool-vsh9    <none>           <none>
prebuild-f6ad0b5a-21ac-4991-8f02-0d12d4d42ac6   0/1     Terminating   0              4h53m   10.20.2.5       headless-ws-us43xl-pool-266x    <none>           <none>
➜  us-stuck-in-pending
```

</details>

### Steps to reproduce

NA

**Comment by princerachit** [comment] 2022-05-02 04:17
As @utam0k pointed out in an internal slack thread here is a [log](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-05-01T22:04:48Z;pinnedLogId=2022-05-01T22:04:48Z%2F0651t6si9ycfawrx;query=resource.labels.pod_name%3D%22prebuild-025802bb-ad03-41d8-a5e4-d95ca82c3b69%22%0Atimestamp%3D%222022-05-01T22:04:48Z%22%0AinsertId%3D%220651t6si9ycfawrx%22;timeRange=PT9H?project=workspace-clusters) which matches to the [linked PR fix ](https://github.com/gitpod-io/gitpod/pull/9551)
.

The current issue is probably fixed by above PR. We had [similar incident](https://gitpod.pagerduty.com/incidents/Q3ER8E9NJB3Z3C) for regular workspaces.


``` 
socket did not appear before context was canceled:
    github.com/gitpod-io/gitpod/workspacekit/cmd.connectToInWorkspaceDaemonService
        /tmp/build/components-workspacekit--app.b775f52c06c0a05987a471fcf5d3dd3673075cac/cmd/rings.go:936
```

**Comment by kylos101** [comment] 2022-05-10 02:43
Alejandro created this issue, which was another manifestation of this issue:
https://github.com/gitpod-io/gitpod/issues/9835

**Comment by kylos101** [comment] 2022-05-10 23:04
Internal Slack references [[1](https://gitpod.slack.com/archives/C0201TXMV54/p1652118990939579)][[2](https://gitpod.slack.com/archives/C0201TXMV54/p1651483044084359)][[3](https://gitpod.slack.com/archives/C01TNS8EVQT/p1651754208011489?thread_ts=1651754203.695529&cid=C01TNS8EVQT)]

**Comment by kylos101** [comment] 2022-05-10 23:11
@utam0k one way to start researching this issue, may be to look at the [occurrences](https://github.com/gitpod-io/gitpod/issues/9673#issuecomment-1122995224) for when it happened (roughly) and check for high CPU, memory, or garbage collection [in Grafana](https://grafana.gitpod.io/d/ws-daemon/gitpod-component-ws-daemon?orgId=1&refresh=30s), to see if maybe there is a related trend?

Grafana for ws-daemon has three sections:
1. gRPC Metrics
2. Pod Metrics 
3. Go Runtime Metrics

**Comment by kylos101** [comment] 2022-05-10 23:24
[Starting here](https://github.com/gitpod-io/gitpod/issues/9893#issue-1230919250) is probably the best.

**Comment by utam0k** [comment] 2022-05-11 04:54
- [ws-daemon is causing multiple restarts](https://cloudlogging.app.goo.gl/WJZj3AihMANnuasm6)
- [Go Routine leaks](https://grafana.gitpod.io/d/ws-daemon/gitpod-component-ws-daemon?orgId=1&from=1651234789948&to=1651446296610&var-cluster=us43xl&var-node=headless-ws-us43xl-pool-qqcx&var-pod=ws-daemon-lqjhs&var-grpc_method=Check&var-grpc_method=DisposeWorkspace&var-grpc_method=TakeSnapshot&var-datasource=VictoriaMetrics)
- This seems likely to occur immediately after a ws-daemon crash loop[[1](https://gitpod.slack.com/archives/C01TNS8EVQT/p1651754203695529)][[2](https://gitpod.slack.com/archives/C01TNS8EVQT/p1650976446553049)]

**Comment by utam0k** [comment] 2022-05-12 09:39
This is one scenario I've considered.

1. Add some new nodes by the autoscaler
2. The workspace starts up all at once
3. Write load (and CPU utilization) increases all at once, causing file creation to be delayed
4. Slower generation of IWS services, i.e., creating uds file(`daemon.sock`)  is delayed.
5. workspacekit attempts to connect to the IWS service, but the file for uds does not exist.
    - At this time it tries to reconnect until the timeout (currently 2 minutes), but probably due to delays(because of 4) in creating the file, it will not be able to do so in time
6. And failure, in this case, is not expected in the ws-manager monitor. Therefore, the finalizer remains marked all the time.

This scenario can be reproduced by installing the sleeping code before creating the file for uds.
https://github.com/gitpod-io/gitpod/commit/b869dbe3455fb2727a39d026c758d95ddaa91277

What should we do next?

- Extend workspacekit reconnect time
- Enhanced logging
- Ensure that pods are properly erased in such cases in the ws-manager's monitor

@kylos101 WDYT?

**Comment by kylos101** [comment] 2022-05-13 00:39
@utam0k what did you see in the logs and grafana about yesterday's issue? I think `ws-daemon` cannot init workspaces (but am not sure why), fails the liveness check (am not sure why), and then gets restarted.

> Extend workspacekit reconnect time

I am not sure on this. Since the liveness check fails, I am skeptical reconnect time will help. :thinking: 

> Enhanced logging

How so? Probably. :smile: 

> Ensure that pods are properly erased in such cases in the ws-manager's monitor

That idea makes sense to me, because this issue impacts existing and new nodes, where content init fails. To me, this is a signal that if X number of workspaces land on a single node at the same time, we have this problem. So, we should theoretically be able to recreate (using loadgen perhaps) with a single node cluster. Recreating would be nice, because then you could test ws-manager doing GC of these workspaces having failed doing init.

Can you think of a scenario where auto scaling is not needed, and you can use Harvestor preview environment? I ask because that is likely a fast feedback loop. Even workspace-preview might be a good option, before using an ephemeral cluster. For example, perhaps you could run a test where you throw 20-25 workspaces at a single node? If auto scaler must be used, then, you'll need an ephemeral cluster to test.

> Find a way to prevent workspaces from being launched simultaneously on a new node all at once. (I'm not sure how can wedo. It may be tough)

I think this is the job of the scheduler, and, we need this ability.

CC: @aledbf and @sagor999 for thoughts

**Comment by utam0k** [comment] 2022-05-13 01:06
@kylos101 Thanks for your comment.
Checking the logs, I observed a large number of connection timeouts from workspace to ws-daemon at the same time.[[1](https://cloudlogging.app.goo.gl/JmNG7TJAM4qp7KwY6)] This is probably due to a delay in generating files for uds. This is not confirmed due to lack of logs.
So why the delay in generation? As you can see from the commit above, the uds file is created when the workspace is created, not when ws-daemon starts. This means that they are spared from the liveness check when the ws-damon pod starts.

> what did you see in the logs and grafana about yesterday's issue? I think ws-daemon cannot init workspaces (but am not sure why), fails the liveness check (am not sure why), and then gets restarted.

> I am not sure on this. Since the liveness check fails, I am skeptical reconnect time will help. 🤔

Have you seen this commit https://github.com/gitpod-io/gitpod/commit/b869dbe3455fb2727a39d026c758d95ddaa91277 I mentioned? This will reproduce the same error message. But I really don't know if this is the cause. it would be interesting to try launching multiple workspaces at the same time using loadgen. I will try a few.

> That idea makes sense to me, because this issue impacts existing and new nodes, where content init fails. To me, this is a signal that if X number of workspaces land on a single node at the same time, we have this problem. So, we should theoretically be able to recreate (using loadgen perhaps) with a single node cluster. Recreating would be nice, because then you could test ws-manager doing GC of these workspaces having failed doing init.

Can you think of a scenario where auto scaling is not needed, and you can use Harvestor preview environment? I ask because that is likely a fast feedback loop. Even workspace-preview might be a good option, before using an ephemeral cluster. For example, perhaps you could run a test where you throw 20-25 workspaces at a single node? If auto scaler must be used, then, you'll need an ephemeral cluster to test.

**Comment by kylos101** [comment] 2022-05-13 01:10
> This scenario can be reproduced by installing the sleeping code before creating the file for uds.
https://github.com/gitpod-io/gitpod/commit/b869dbe3455fb2727a39d026c758d95ddaa91277

Ah, I see, so, artificially recreate a timeout to see how things behave? I like it. Worth a shot. Especially if loadgen doesn't help recreate.

**Comment by utam0k** [comment] 2022-05-13 01:30
> > This scenario can be reproduced by installing the sleeping code before creating the file for uds.
> > [b869dbe](https://github.com/gitpod-io/gitpod/commit/b869dbe3455fb2727a39d026c758d95ddaa91277)
> 
> Ah, I see, so, artificially recreate a timeout to see how things behave? I like it. Worth a shot. Especially if loadgen doesn't help recreate.

@kylos101 In fact, this is how I was able to reproduce it yesterday. By reproduction, I mean that a workspace stops with the same error messages and pending status.

**Comment by utam0k** [comment] 2022-05-13 10:13
Hi, @Furisto. Did this problem appear when you did the load test?

**Comment by utam0k** [comment] 2022-05-13 10:24
Today, I created workspace-preview and then tried launching multiple workspaces at the same time with a significant load (using stress-ng and dd commands), but could not reproduce the problem 😭 

Perhaps this PR might be effective, but I don't know because I cannot reproduce the problem. However, it is worthwhile: xfs limits use locks, and depend on the number of workspaces managed by ws-manager, it is not surprising that in some cases the search and locking can take quite a long time. This would be especially possible in cases where nodes are added all at once.
So, in this PR, I tried to set up IWS server before xfs limit so that workspacekit can connect to IWS server regardless of the time of xfs limit process. It may be a valid strike, but I cannot be sure.
https://github.com/gitpod-io/gitpod/pull/9992

It probably fails because the uds file does not exist, but I will record it just in case.
https://github.com/gitpod-io/gitpod/pull/9996

Next step: 
1. If @Furisto  was able to reproduce this problem in a load test, then I will put the above PR into a load test to confirm
(Perhaps extending the timeout for ring1 might be useful.)
3. Put it into production and see how it goes.
4. If it recurs, we will reopen an investigation into this issue.

@kylos101 What do you think about the above next steps?

**Comment by kylos101** [comment] 2022-05-15 22:30
Hey @utam0k ,

I am thinking the following:

> If @Furisto was able to reproduce this problem in a load test, then I will put the above PR into a load test to confirm
(Perhaps extending the timeout for ring1 might be useful.)

Will be interesting to see if gen45 (with ws-daemon backup improvements from @aledbf ) is less susceptible to this problem. Maybe add logging for now in 9996? This way we have logged errors, just in case, and will make it into next deployment.

> Put it into production and see how it goes.

Rather than increase timeouts, let's add logging (like above). If, we're able to recreate with loadgen (@Furisto ) we can revisit increasing the timeout.

> If it recurs, we will reopen an investigation into this issue.

I was talking with @Furisto about this issue today. It would be nice if `ws-manager` could find workspace pods in Pending (where they failed init and still have a finalizer). It would log when this is found and remove the finalizer from the pod. Doing so is actually good house keeping, and will help prevent these pods from lingering. Here is house keepin:

https://github.com/gitpod-io/gitpod/blob/cc893bee208c768118720ca3c050e000b0ebc29f/components/ws-manager/pkg/manager/monitor.go#L416

WDYT? :thinking:  :wave:

**Comment by utam0k** [comment] 2022-05-15 23:28
I talked with @kylos101. Next steps
- Enhance `housekeeping` to save money and time.
- If we need, I put the traces into the startup process of a workspace

**Comment by utam0k** [comment] 2022-05-15 23:28
I talked with @kylos101. Next steps
- Enhance `housekeeping` to save money and time.
- If we need, I put the traces into the startup process of a workspace

**Closed** 2022-05-25 08:26 UTC
Labels: team: workspace
