### ISSUE TITLE
workspace failed to start

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#1510] opened 2020-05-14 13:05 UTC
### Describe the bug
failed to create containerd task: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/theia/supervisor\": stat /theia/supervisor: no such file or directory": unknown
Please file an issue if you think this is a bug.

I really need the contents of this workspace so please fix it :)

**Comment by RDIL** [comment] 2020-05-14 13:08
Yeah no @jankeromnes @JesterOrNot @Kreyren none of my existing or new workspaces are working

**Comment by RDIL** [comment] 2020-05-15 02:19
@svenefftinge @meysholdt please help I have work I need to do

**Comment by Kreyren** [comment] 2020-05-15 04:40
Closing as duplicate of https://github.com/gitpod-io/gitpod/issues/1511

**Closed by Kreyren** 2020-05-15 04:40 UTC
