### ISSUE TITLE
stopped to work, completely unable to do anything

### ISSUE THREAD

**Issue by DejanHinic** [gitpod-io/gitpod#1103] opened 2020-01-16 15:16 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by Kreyren** [comment] 2020-01-16 15:47
Can you elaborate? 

Is there any error message? 

What did you do to get into this issue? 

Possible duplicate of #1075?

**Comment by DejanHinic** [comment] 2020-01-16 15:53
Really don't have a clue, I was changing html file and when I refreshed in
browser exposed page it returned 403 error. Tried to push in terminal but
all was frozen. I copied my code and restarted git pod and after that all
was back from the last push.

**Comment by jankeromnes** [comment] 2020-01-16 16:41
Hi @DejanHinic, thank you for reporting this problem, and sorry that it happened to you.

This does indeed sound very similar to #1075. However, that incident was resolved 10+ hours ago. When did the problems you describe happen to you? Also, are you still able to reproduce them?

**Comment by BobHerold** [comment] 2020-01-16 18:58
I"m unable to open by Gitpod workspaces;    it tells me remaining time is 0;0,  then says upgrade subscription;     when i go to account profile;   it shows I have "unlimited team" via Code Institute.   whats going on here gitpod?

**Comment by jankeromnes** [comment] 2020-01-17 09:58
Hi @BobHerold, thanks for letting us know. Let's track this in #1104.

@DejanHinic I'll close this issue, because it looks like a duplicate of #1075 which is now resolved. If you're still having problems in Gitpod, please re-open a new issue, and provide as many details as you can (screenshots, URLs, exact error messages, etc). Thanks again for reporting bugs -- it really helps a lot. 💯

**Closed by jankeromnes** 2020-01-17 09:58 UTC
