### ISSUE TITLE
Getting a message saying Authorization failed, even after multiple tries. I tried to access using Github 

### ISSUE THREAD

**Issue by Prathyusha2210** [gitpod-io/gitpod#2779] opened 2021-01-10 14:43 UTC

**Comment by csweichel** [comment] 2021-01-11 06:41
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by csweichel** 2021-01-11 06:41 UTC
