### ISSUE TITLE
gitpod workspace: pod the node was low on resource.

### ISSUE THREAD

**Issue by G00359991** [gitpod-io/gitpod#1228] opened 2020-02-17 14:01 UTC

**Comment by G00359991** [comment] 2020-02-17 14:02
It's telling me the resource is low, but it was working fine a few hours ago, and I hadn't added anything or taken away anything in that time. So why is this happening?

**Comment by jankeromnes** [comment] 2020-02-17 15:04
Thank you @G00359991 for filing this issue. We're investigating this problem.

Closing as duplicate of #1187. Please add any information that could help the investigation over there (workspace IDs, URLs, screenshots, etc.)

**Closed by jankeromnes** 2020-02-17 15:04 UTC
