### ISSUE TITLE
Blank docker build screen 

### ISSUE THREAD

**Issue by richardfrankza** [gitpod-io/gitpod#10051] opened 2022-05-16 20:01 UTC
### Bug description

I use a custom dockerfile. When the image is building I receive no output. There is blank space where I think you should be printing the results of the docker build output?

### Steps to reproduce

Add a custom dockerfile as per the docs and add some more commands.

I've got 

```
FROM gitpod/workspace-full

# Install custom tools, runtime, etc.
RUN brew install drud/ddev/ddev
RUN sudo apt-get update && sudo apt-get install -y xdg-utils tree rsync

```

### Expected behavior

I should see the steps of the docker build not a blank grey box.

**Comment by axonasif** [comment] 2022-05-17 18:59
Duplicate of https://github.com/gitpod-io/gitpod/issues/9875

**Closed by axonasif** 2022-05-17 18:59 UTC
Labels: type: bug
