### ISSUE TITLE
[PVC] Prebuild+PVC, user's account without PVC, open from prebuild, still use PVC

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#12463] opened 2022-08-29 09:50 UTC
### Bug description

Prebuild+PVC, user's account without PVC, open from prebuild, still use PVC

### Steps to reproduce

- Create the project with prebuild and enable PVC
- The user account does not enable PVC
- The user open the workspace from prebuild
- The workspace still uses PVC

### Anything else?

#7901

**Comment by kylos101** [comment] 2022-08-30 01:45
@jenting this is expected behavior, cc: @sagor999 , any regular workspace opened from a project's prebuild, where PVC is enabled, will also be PVC (regardless of user setting). Closing for now and removing from our project. Please reopen if you disagree.

**Closed by kylos101** 2022-08-30 01:45 UTC
Labels: type: bug, team: workspace

**Comment by jenting** [comment] 2022-08-30 01:47
🤔 I'm not agree because it should open without PVC and since there is no prebuild, opening the workspace should fall back to git clone.

**Comment by sagor999** [comment] 2022-08-30 01:59
This was intentional choice.
We want to make it easy to enroll users into PVC.
So we have two toggles for that:
1. Feature flag in user settings that allows to use PVC for any workspace that user opens.
2. Project settings flag that enables PVC for prebuilds and forces any user that opens such prebuild to also use PVC.

Otherwise, if we were to allow user to open PVC prebuild, but user does not have PVC enabled, now we would need to implement the feature of extracting data from PVC and somehow shoveling it into GCS which then gets uploaded into workspace (complicated), or as you suggested @jenting, fall back to git clone, but then user will not get any benefit from PVC use at all. Effectively that user will not be able to use prebuilds, and will not be able to enroll in PVC, since feature flags enablement is an admin feature. So user experience in that case would not be great in my opinion.

**Comment by jenting** [comment] 2022-08-30 02:10
Make sense, the only left concern is if we enable the prebuilds for gitpod projects, and we haven't enable the users and customers PVC yet.
Then, all the users who open the workspace with the gitpod projects, they will benefit the PVC feature. It makes the user suddenly uses the PVC feature, and I think we should have a way to inform the users.

WDYT?

**Comment by sagor999** [comment] 2022-08-30 02:24
It would be potentially good to indicate to user that they are using PVC, but at the same time, what they really gonna do with that information?
Our storage backing is internal. In theory, it should not matter what we are using, GCS or PVC, both should be transparent to the user.

**Comment by jenting** [comment] 2022-08-30 02:41
Okay, agree on you.
So, let's keep this issue close now, and if we have users have concerns in the future, let's reopen it.
Thank for all your feedback 🙏
