### ISSUE TITLE
Remove DevX friction by adding sign-up option without a git provider

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#11848] opened 2022-08-03 15:58 UTC
## Is your feature request related to a problem? Please describe

Most new users, experience Gitpod for the first time by opening a public repo that already has support for Gitpod.
Today, users have to choose between Github / Gitlab / BitBucket, and then they're asked to give Gitpod read permissions.
People are testing out Gitpod for the first time, not necessarily feel comfortable trusting Gitpod right away, and might leave the page.

![image](https://user-images.githubusercontent.com/22901/182653449-cff44731-391b-45a9-8b82-a6a647865924.png)

## Describe the behaviour you'd like

When opening public repos, users should have an additional option -
* Login "directly" to Gitpod, using Google or username/password, without any git provider, or giving any permissions.

**Comment by pawlean** [comment] 2022-08-03 17:24
This seems like a duplicate of #7761. Thanks for raising, @shaal! Definitely a big +1 from me 🙌

**Closed by pawlean** 2022-08-03 17:24 UTC
