### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by yashgupta18** [gitpod-io/gitpod#2848] opened 2021-01-12 08:15 UTC
### Describe the bug

Cannot login 
### Expected behavior

I expected to login but due to some issue it's showing  something went wrong

**Comment by csweichel** [comment] 2021-01-12 10:25
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by csweichel** 2021-01-12 10:25 UTC
