### ISSUE TITLE
Dashboard remove the horizontal scrollbars

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#4512] opened 2021-06-15 10:01 UTC
### Bug description

On a few pages on the dashboard, there are horizontal scrollbars that are not needed and they don't look good. 
The pages are `https://gitpod.io/integrations` and `https://gitpod.io/plans`

![Screen Shot 2021-06-15 at 2 51 02 PM](https://user-images.githubusercontent.com/46004116/122032614-3f6b4200-cde9-11eb-9822-1c2af8a8f213.png)

### Steps to reproduce

Visit https://gitpod.io/integrations and https://gitpod.io/plans

**Comment by corneliusludmann** [comment] 2021-06-16 08:31
It's a duplicate of #3859, right? If yes, it's fixed in #4417.

**Closed** 2021-06-17 11:58 UTC
