### ISSUE TITLE
 Error: Not connected to message bus.

### ISSUE THREAD

**Issue by PrakashSinghRawat** [gitpod-io/gitpod#3518] opened 2021-03-20 09:17 UTC

**Comment by Bubbler-4** [comment] 2021-03-20 09:35
Can confirm this.

![error](https://user-images.githubusercontent.com/22365659/111865492-a9bb4480-89aa-11eb-8a3f-2253a733d779.PNG)

![error2](https://user-images.githubusercontent.com/22365659/111865517-de2f0080-89aa-11eb-9732-f762f4c9b856.PNG)

status.gitpod.io says it is back to operational, but it's not.

**Comment by Bubbler-4** [comment] 2021-03-20 11:33
Update: Now it works, but it took ages to start a workspace (~20 minutes).

**Comment by amafjarkasi** [comment] 2021-03-22 02:51
I'm having the same issue.. 
![image](https://user-images.githubusercontent.com/65797881/111934511-edd84300-8a97-11eb-803d-c0b66144b304.png)

**Comment by jankeromnes** [comment] 2021-03-22 09:23
Thanks for reporting this incident! Duplicate of https://github.com/gitpod-io/gitpod/issues/3515

**Closed by jankeromnes** 2021-03-22 09:23 UTC
