### ISSUE TITLE
Dependencies lost upon workspace reopening

### ISSUE THREAD

**Issue by bravoalpha79** [gitpod-io/gitpod#5589] opened 2021-09-08 07:59 UTC
### Bug description

Upon starting an existing workspace today, three students report (and I confirmed it with `pip3 freeze --local`) that all installed dependencies are gone. The workspaces were opened from the Gitpod Dashboard.

`pip3 install -r requirements.txt` reinstalled all dependencies as expected, but they should never have been gone to begin with. 

### Steps to reproduce

1. Open workspace, try to start the app (e.g. `python3 run.py`)
2.  "no module XXX found" is raised. (on a module/dependency that was previously installed)
3.  Run `pip3 freeze --local` - the result is empty (no dependencies installed).

### Expected behavior

Installed dependencies are kept in the existing workspace.

### Example repository

https://gray-gerbil-p6ckklb7.ws-eu15.gitpod.io/
https://azure-snail-aw1src7l.ws-eu15.gitpod.io/
https://amethyst-scallop-5kfji6x2.ws-eu16.gitpod.io/

**Comment by Jays-T** [comment] 2021-09-08 08:14
Same issue with another student and same steps taken to produce the error, below is affected workspace:
https://bronze-orca-cznmphft.ws-eu15.gitpod.io/

**Comment by bravoalpha79** [comment] 2021-09-08 08:40
One more workspace impacted by the same issue:
https://moccasin-cricket-fkkxz0tu.ws-eu15.gitpod.io/

**Comment by Jays-T** [comment] 2021-09-08 08:43
And another workspace affected:
https://salmon-condor-3u077sv0.ws-eu15.gitpod.io/

**Comment by Wings30306** [comment] 2021-09-08 08:44
And another one: 
![image](https://user-images.githubusercontent.com/40639285/132476755-822f8a54-37b4-4c92-b5de-d220c7934924.png)
from workspace https://tomato-thrush-3619mlgr.ws-eu15.gitpod.io/ - error appearing on attempting to re-install dependencies. Student is attempting to re-install in a new workspace as we speak, so 🤞🏻 - TBC

**Comment by corneliusludmann** [comment] 2021-09-08 09:00
Thanks for reporting. We are investing.

**Comment by corneliusludmann** [comment] 2021-09-08 09:15
https://www.gitpodstatus.com/incidents/fk6prflgvvth

**Comment by bravoalpha79** [comment] 2021-09-08 09:17
Almost certainly related, installation of dependencies shows some weird warnings, and causes issues subsequently:
![image](https://user-images.githubusercontent.com/45522344/132480836-7743adff-5123-4efd-9221-450d5b4f098c.png)
https://jade-orangutan-vyo2dp1j.ws-eu15.gitpod.io/

**Comment by geropl** [comment] 2021-09-08 09:55
Closing as dupe of #5594. We're ~currently rolling~ rolled out a fix: https://github.com/gitpod-io/gitpod/issues/5594#issuecomment-915091895

Sorry for the inconvenience, and thank a lot for reporting this @bravoalpha79 and @Jays-T ! :pray:

**Closed by geropl** 2021-09-08 09:55 UTC
