### ISSUE TITLE
i am unable to open my gitpod account

### ISSUE THREAD

**Issue by Anujg9778** [gitpod-io/gitpod#2962] opened 2021-01-19 06:44 UTC

**Comment by gtsiolis** [comment] 2021-01-19 08:27
Hey @Anujg9778, see https://github.com/gitpod-io/gitpod/issues/2746#issuecomment-757423846.

Closing this as a duplicate of https://github.com/gitpod-io/gitpod/issues/2746.

**Closed by gtsiolis** 2021-01-19 08:27 UTC
