### ISSUE TITLE
unable to launch chromium

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#2078] opened 2020-10-28 15:24 UTC
### Describe the bug

The Chromium Renderer process seems to be crashing when I try `npm test` which uses Cypress under the hood.

![image](https://user-images.githubusercontent.com/46004116/97457262-6a3c7f00-195b-11eb-9647-e8cd02794871.png)
![image](https://user-images.githubusercontent.com/46004116/97457303-71638d00-195b-11eb-853f-003a4e81f8ba.png)

### Steps to reproduce

Open https://github.com/nisarhassan12/EddieJaoudeCommunity.github.io in Gitpod and try `npm test` in one of the terminals.

**Comment by ArthurSens** [comment] 2021-02-11 13:01
Hey @nisarhassan12, I understand that this issue is a duplicate of #1413.

I'm closing this one just to make sure we don't split the discussion into multiple places. Please reopen it if you think that that issue is not related

**Closed by ArthurSens** 2021-02-11 13:01 UTC
Labels: type: bug
