### ISSUE TITLE
Cannot generate a workspace snapshot

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#5862] opened 2021-09-24 13:29 UTC
### Bug description

After opening DrupalPod in Gitpod, I open the hamburger menu on top-left corner, and choose `Gitpod: Share Workspace Snapshot`

I see `Capturing workspace snapshot` dialog -
![image](https://user-images.githubusercontent.com/22901/134681256-c4891509-15e3-46d8-b8ed-9c3b449e9f18.png)

After a few minutes, it displays an error -
![image](https://user-images.githubusercontent.com/22901/134681365-c2eaa7d7-defd-4083-94a6-e309f52cd4cd.png)

Errors in console:
![image](https://user-images.githubusercontent.com/22901/134682005-77eb82ed-44c0-4724-8038-6ecf2604c24f.png)

(Using Gitpod's VScode v1.59)

### Steps to reproduce

1. Open DrupalPod in gitpod:
  https://gitpod.io/#https://github.com/shaal/DrupalPod
1. Open the hamburger menu on top-left corner
1. Choose `Gitpod: Share Workspace Snapshot`

### Expected behavior

I was able to take snapshots of DrupalPod workspace in the past, but somehow I can no longer able to.

### Example repository

https://github.com/shaal/DrupalPod

### Anything else?

I am able to create workspace snapshot on 'simpler' repos, such as - https://gitpod.io/#https://github.com/gitpod-io/template-typescript-node

**Comment by shaal** [comment] 2021-09-28 00:29
I tested this also by opening https://github.com/gitpod-io/gitpod in Gitpod, and coose from the menu: `Gitpod: Share Workspace Snapshot`, same error.

**Comment by pawlean** [comment] 2021-09-28 08:59
I could not replicate this. 🤔 This is what I see:

<img width="457" alt="2021-09-28 at 09 59 00 - Google Chrome" src="https://user-images.githubusercontent.com/17087373/135056788-ac5beadd-8a84-47ee-b0a3-0cb78aa6ecc1.png">

What version of VS Code are you on?

**Comment by shaal** [comment] 2021-09-28 11:27
Vscode 1.59
I tried various browsers - Chrome, edge, Firefox. Still see the same error on both Gitpod repo and drupalpod repo.

**Comment by shaal** [comment] 2021-09-28 11:57
I updated the description of this issue, to clarify this bug is happening only on some complex repos (DrupalPod, Gitpod, etc.), while on simpler repo (typescript demo workspace) I am able to create a snapshot.

**Comment by shaal** [comment] 2021-09-28 12:05
@akosyakov I tested this times, one after the other, different repos, etc.
Are you able to take a snapshot of Gitpod or drupalpod repos?

**Comment by akosyakov** [comment] 2021-09-28 12:17
`takeSnapshot` server api hangs for very long time. I think meta team should look why is it. cc @JanKoehnlein @gtsiolis

**Comment by gtsiolis** [comment] 2021-09-28 12:20
I could reproduce the issue. Thanks @shaal for reporting and @akosyakov for the ping. 🏓

**Comment by roboquat** [comment] 2021-09-29 08:09
@csweichel: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5862#issuecomment-929941338):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment] 2021-10-05 07:50
I'm not sure this will be an issue anymore with the [recent changes to websocket](https://github.com/gitpod-io/gitpod/issues/5042) (to be deployed). The MessageConnection stays intact depsite the underlying transport (websocket) is reconnecting, so we should still receive the response after reconnect and have the long-running call return. Will try to test and verify.

**Comment by shaal** [comment] 2021-10-08 02:26
I created a minimal repo to replicate this bug.
When `/workspace` storage space is 4GB or larger - snapshot fails.
When `/workspace` storage space is 3GB or smaller - snapshot successful.
https://github.com/shaal/gitpod-test-failing-snapshot

**Comment by geropl** [comment] 2021-10-12 14:05
@akosyakov We have multiple options how to solve this; none of which I find super-nice because they're rather involving. Happy to re-iterate in sync, but here's the alternatives:
 - we could add a `state` to `DBSnapshot` and communicate over this table. Pro is that the operation becomes stateful, con is that we'd have to use polling - unless we make ws-manager stream snapshot state as well
 - we make snapshots part of the workspace updates in the first place - feels like the wrong solution

@csweichel Would be interested in your thoughts as well.

**Comment by geropl** [comment] 2021-11-11 07:32
No, roboquat! :upside_down_face:

**Comment by JanKoehnlein** [comment] 2021-11-11 09:13
@geropl Which state is this issue in now?

**Comment by geropl** [comment] 2021-11-11 09:17
in progress. Waiting 1 day before merging the IDE PR, and then waiting for it being deployed: https://github.com/gitpod-io/openvscode-server/pull/169

lessons for me after this issue: try hard to have 1 issue per PR; everything else is cumbersome.

**Comment by geropl** [comment] 2021-11-19 12:24
IDE part got merged: https://github.com/gitpod-io/openvscode-server/pull/169#pullrequestreview-810983135
Available on "insiders" per tomorrow.

**Comment by shaal** [comment] 2021-11-19 14:06
@geropl Thank you! cannot wait to test it out!

**Comment by gtsiolis** [comment] 2021-11-25 23:45
Closing this as the fix has landed in production. Cc @shaal @zuernBernhard

1. https://github.com/gitpod-io/gitpod/pull/6144
2. https://github.com/gitpod-io/openvscode-server/pull/169

Thanks, everyone!

Cc @geropl

**Closed by gtsiolis** 2021-11-25 23:45 UTC
Labels: type: bug, editor: code (browser), component: server, priority: highest (user impact), groundwork: in review, team: meta

**Comment by shaal** [comment] 2021-11-26 04:42
Thank you for fixing this!
I can confirm I am able to make snapshots again.

**Comment by geropl** [comment] 2021-11-26 07:50
Thx @gtsiolis , missed the deployment.
