### ISSUE TITLE
Unable to start JetBrains IDE (greyscreen)

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6741] opened 2021-11-17 09:11 UTC
### Bug description

Some users are reporting issues opening the JetBrains IDE's, I haven't yet reproduced these issues, so raising an issue to investigate. Based on [this Discord discussion](https://discord.com/channels/816244985187008514/905926786339188746/909768556151988224). 

> they give you the command to spin up a client but no link to dump into your existing copy of IntelliJ that I can see to "just join"

![image](https://user-images.githubusercontent.com/5528307/142170542-00cf5725-0ddc-4531-b0b9-2360e5d2c454.png)

> when the downloadable did spin up, it then threw an error and I just have a grey screen

Stack trace: 

```2021-11-15 11:37:24,936 [  10225]   WARN - .SecureWireOverStreamTransport - setFaultedState due to throwable:
com.jetbrains.rd.platform.codeWithMe.protocol.ICodeWithMeWire$PeerVisibleErrorCode
    at com.jetbrains.rd.platform.codeWithMe.protocol.SecureWireOverStreamTransport$runConnectionFlow$job$1.invokeSuspend(SecureWireOverStreamTransport.kt:331)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

> then if I go back and try and reconnect, it waits for host approval, if I go back and click on Open In IntelliJ Idea, I end up just with a Code with me placeholder and no action

> All I see now is this, even on a new workspace

![image](https://user-images.githubusercontent.com/5528307/142170567-c8a492b7-2ca3-48a7-af04-7b9e3c574ae7.png)

### Steps to reproduce

I cannot yet reproduce.

**Comment by loujaybee** [comment] 2021-11-17 09:11
Also mentioned (possibly related, possibly not)

> For me opening in a workspace only works using the CMD command. When trying to open it directly it starts downloading the client but then it just stops and doesn't open it.

![image](https://user-images.githubusercontent.com/5528307/142171143-89b75866-52a1-4c64-9e7a-924aeaef9514.png)

**Comment by corneliusludmann** [comment] 2021-12-02 13:22
In my opinion, there is nothing we can do here for the following reasons:

- I cannot reproduce the issues.
- These seem to be issues on JetBrains' side. The only thing we can do is to report issues to JetBrains.
- They may be fixed already with the latest JetBrains release.
- Most of them will be not relevant anymore once we get rid of the Code With Me path.

I'm closing this issue for now. Feel free to re-open if you think there is still an action needed.

**Closed by corneliusludmann** 2021-12-02 13:22 UTC
Labels: team: IDE, editor: jetbrains
