### ISSUE TITLE
Terminal Font Issue Has Returned with v1.58.2

### ISSUE THREAD

**Issue by lechien73** [gitpod-io/gitpod#5014] opened 2021-07-29 15:45 UTC
### Bug description

The terminal font issues that were fixed in https://github.com/gitpod-io/gitpod/issues/4130 have returned in the new version of VS Code.

![Screenshot 2021-07-29 at 16 38 07](https://user-images.githubusercontent.com/21156053/127522222-d0ed5483-a465-48be-883c-9557e7b199e4.png)

Again, the terminal font is distorted; however, this time, cycling the font in Settings doesn't make a difference.

### Steps to reproduce

Open a workspace (I use Brave browser). Observe the terminal font and try to change it in Settings.

### Expected behavior

A normal terminal.

### Anything else?

I cleared the cache in my browser and hard refreshed. Colleagues have confirmed they experience the same behaviour.

**Comment by Sarosim** [comment] 2021-07-29 17:42
Same here, Brave Version 1.27.108 Chromium: 92.0.4515.107 (Official Build) (64-bit)

**Comment by heldr** [comment] 2021-07-29 19:09
A workaround I found is using [nativefier](https://www.npmjs.com/package/nativefier) to build your own Electron workspace.

```sh
nativefier <GITPOD_WORKSPACE_URL> -n <YOUR_APP_NAME> --fast-quit --internal-urls gitpod.io
```

**Comment by ghuntley** [comment] 2021-07-30 04:45
Confirming this happened to me moments ago on `https://peach-rabbit-vh29qfah.ws-us13.gitpod.io/` 


```
about://

92.0.4515.107 (Official Build) (arm64)
--
Revision | 87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634}
OS | macOS Version 11.5.1 (Build 20G80)
JavaScript | V8 9.2.230.20
User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36


<br class="Apple-interchange-newline">
```

**Comment by jjperezaguinaga** [comment] 2021-07-31 15:46
Confirming the same bug here, just started a new workspace now.

![image](https://user-images.githubusercontent.com/1128312/127745224-7afa1655-2ca1-4fee-a839-6b5e6e803b3b.png)

**Comment by TheBotlyNoob** [comment] 2021-07-31 23:41
Same thing for me

**Comment by lechien73** [comment] 2021-08-03 11:49
My current workaround has been to edit `settings.json` and add the following new settings:

```{
    "terminal.integrated.lineHeight": 1.2,
    "terminal.integrated.letterSpacing": 2
}```

**Comment by hrithikrtiwari** [comment] 2021-08-21 06:08
I still have the same problem with this latest August Update
![image](https://user-images.githubusercontent.com/42163313/130312395-469912be-b170-4199-94d8-0e70aad3abb2.png)

**Comment by ghuntley** [comment] 2021-08-21 06:16
Same problem with GitHub Codespaces as well so confirming upstream vscode
issue.

**Comment by neuronick** [comment] 2021-09-15 10:33
My current solution, which fixes the font problem for me on MacOS Mojave + Chrome:
```"terminal.integrated.gpuAcceleration": "canvas"```

This works event better than lineHeight / letterSpacing proposed earlier.

Without this setting:
![image](https://user-images.githubusercontent.com/838476/133417809-6e15a1d5-1ab1-4bbb-98b6-440b43881d76.png)

With this setting:
![image](https://user-images.githubusercontent.com/838476/133417873-ff53aa32-fcd0-412d-9a00-8aa36337476f.png)

**Comment by wolfy01** [comment] 2021-09-29 00:39
Brave's adblocker did it for me. Disabling it fixed the issue

**Comment by hrithikrtiwari** [comment] 2021-10-09 02:20
@wolfy01 can you tell how to do it, I tried disabling the adblocker but it doesn't work, also check this https://community.brave.com/t/i-keep-getting-reports-due-to-canvas-fingerprint-prevention/288876

**Comment by Bulletninja** [comment] 2021-10-20 01:43
@hrithikrtiwari I just clicked the brave icon and disabled it.
![Screen Shot 2021-10-19 at 19 41 59](https://user-images.githubusercontent.com/71659/138013871-3bde3a5a-a0d3-4169-9e9b-96e78deaf289.jpg)

**Comment by hrithikrtiwari** [comment] 2021-10-20 16:49
Ohh great, I tried it on youtube and it works

**Comment by scottyeager** [comment] 2021-11-24 22:47
Disabling Brave's adblocker also resolved this issue for me.

**Comment by oktayacikalin** [comment] 2022-02-10 23:53
> Disabling Brave's adblocker also resolved this issue for me.

Same here in elementary OS 6.1.

**Comment by loujaybee** [comment] 2022-02-14 10:09
Moving to scheduled to investigate. 🙏

**Comment by mustard-mh** [comment] 2022-03-10 09:49
Close because we cannot reproduce it anymore. FYI [xtermjsFAQ/characters-are-getting-cut-off-in-the-terminal](https://github.com/xtermjs/xterm.js/wiki/FAQ#characters-are-getting-cut-off-in-the-terminal)

**Closed by mustard-mh** 2022-03-10 09:49 UTC
Labels: type: bug, editor: code (browser), groundwork: scheduled, team: IDE, meta: blocked

**Comment by uriva** [comment] 2022-03-10 10:54
@mustard-mh reproduction: install brave on ubuntu and open this repo in gitpod: https://github.com/hyroai/gamla

**Comment by mustard-mh** [comment] 2022-03-10 11:16
@uriva  we should go to and disable fingerprinting `brave://settings/shields`. 
> Some browsers (eg. Brave) have privacy features that prevent some fingerprinting techniques that use the canvas such as checking what fonts are installed or determining how certain fonts are actual rasterized. [source](https://github.com/xtermjs/xterm.js/wiki/FAQ#characters-are-getting-cut-off-in-the-terminal)

**Comment by uriva** [comment] 2022-03-10 13:19
> @mustard-mh reproduction: install brave on ubuntu and open this repo in gitpod: https://github.com/hyroai/gamla

just saying it's reproducible, so maybe you mean to close because it's a problem with a dependency rather than gitpod itself?

**Comment by mustard-mh** [comment] 2022-03-10 13:23
Yes, sorry for misleading @uriva, we can't do anything according to this wiki

**Comment by imorri** [comment] 2022-04-26 12:59
Had the same issue with Brave on Mac and Solus, Firefox and Safari no issue.
I found disabling fingerprint tracking in Brave settings resolved the issue.
