### ISSUE TITLE
[vscode-web] extension host process times out on startup

### ISSUE THREAD

**Issue by thisisommore** [gitpod-io/gitpod#7863] opened 2022-01-27 09:25 UTC
### Bug description

The VsCode command to stop gitpod workspace is missing sometimes
![image](https://user-images.githubusercontent.com/51229945/151329485-1c5dc054-56dd-4920-ba1b-6d007850d445.png)
Also this button doesn't work when the issue occurs
![image](https://user-images.githubusercontent.com/51229945/151329602-dabf85c3-c091-4bfb-a68d-139cec1c7e63.png)

### Steps to reproduce

Run any workspace and try to stop it after a while.
This most of the time works, but still more frequently I started seeing such issue

### Expected behavior

The gitpod button should always be clickable and the stop workspace command always be available

### Anything else?

After reloading the tab it works

**Comment by akosyakov** [comment] 2022-01-27 09:32
Do you use stable or insiders? Is anything else working, i.e. do you have terminals, git integration and so on?  It sounds like the extension host process does not start at all?

**Comment by thisisommore** [comment] 2022-01-27 09:40
@akosyakov Yeah, I am using stable and Saas (not self-hosted), also the terminal works but the git integration doesn't.

**Comment by thisisommore** [comment] 2022-01-27 09:41
Yeah, I guess some issue with the extension host process, I will try to reproduce it again and capture logs In dev tools, will it be helpful?

**Comment by mustard-mh** [comment] 2022-01-27 09:46
Does refresh this page help? @thisisommore

**Comment by akosyakov** [comment] 2022-01-27 09:47
@thisisommore You connection is good? VS Code tries to start up extensions for 1 minute and then gives up leaving such state usually. 

You can also share your startup performance in such case, maybe there is something interesting:
<img width="685" alt="Screenshot 2022-01-27 at 10 46 49" src="https://user-images.githubusercontent.com/3082655/151334110-9a0e0a36-0397-4d43-8ae6-b41a1709694a.png">

> Does refresh this page help? @thisisommore

👍 It should work like a workaround.

**Comment by thisisommore** [comment] 2022-01-27 11:41
> 

@mustard-mh  Yes it does

**Comment by thisisommore** [comment] 2022-01-27 11:41
> @thisisommore You connection is good? VS Code tries to start up extensions for 1 minute and then gives up leaving such state usually.
> 
> You can also share your startup performance in such case, maybe there is something interesting: <img alt="Screenshot 2022-01-27 at 10 46 49" width="685" src="https://user-images.githubusercontent.com/3082655/151334110-9a0e0a36-0397-4d43-8ae6-b41a1709694a.png">
> 
> > Does refresh this page help? @thisisommore
> 
> 👍 It should work like a workaround.

Got it will check

**Comment by shaal** [comment] 2022-01-27 20:10
I've seeing this for the last few months, most time everything is good, sometimes a workspace loads without the "Gitpod extras", and a refresh of the tab fixes it.
I didn't find a way to reproduce it, for me it happens randomly. I use regular VSCode (not insiders).

@akosyakov can you write what information should we collect when it happens next time?

**Comment by akosyakov** [comment] 2022-01-28 09:52
@shaal This command should let you to get logs (stored locally in your browser), for any window session:
<img width="765" alt="Screenshot 2022-01-28 at 10 50 35" src="https://user-images.githubusercontent.com/3082655/151525342-eab98be8-9aea-4da9-87a7-61066afaf123.png">

Also startup performance file maybe can help to track down what is going on.

If you have such you can send them support@gitpod.io and mention this issue.

**Comment by shaal** [comment] 2022-01-28 19:06
Thank you @akosyakov, will do!

How can I get `startup performance file` ?

**Comment by thisisommore** [comment] 2022-01-30 07:59
@akosyakov I have logs for window session and startup performance, it is safe to share it here?

**Comment by axonasif** [comment] 2022-01-30 09:41
> I have got the issue again today and have saved logs for window session and startup performance, it is safe to share it here?

No, you should send them to support@gitpod.io and mention this issue as Anton told above.

**Comment by shaal** [comment] 2022-01-31 03:53
@akosyakov @axonasif I was able to capture that information when I encountered this issue in a workspace today, and sent it to support@gitpod.io I hope it helps :)

**Comment by akosyakov** [comment] 2022-02-09 10:50
@mustard-mh is going to look into, but since it is hard to reproduce and needs good knowledge of VS Code @jeanp413 please mentor here and provide all necessary support 🙏

**Comment by akosyakov** [comment] 2022-02-09 21:04
@shaal I looked at your logs unfortunately they are not really helpful :( they do confirm my assumption that extension host process does not start but they don't point to any error.

Could you try to collect data from ouput view behind the separator, especially for `Remote Server` and `Remote Extension Host` please: 
<img width="1444" alt="Screenshot 2022-02-09 at 22 02 43" src="https://user-images.githubusercontent.com/3082655/153289619-dc235267-7aa0-4553-9ae7-ae3ee117fa1a.png">

**Comment by jeanp413** [comment] 2022-03-04 04:46
This is fixed in insiders by https://github.com/gitpod-io/gitpod/pull/8313, will be available in next stable release 1.65 tomorrow Friday

**Comment by jeanp413** [comment] 2022-03-04 21:09
Version 1.65 released, closing this.

**Closed by jeanp413** 2022-03-04 21:09 UTC
Labels: type: bug, editor: code (browser), team: IDE
