### ISSUE TITLE
Terminal is unvisible

### ISSUE THREAD

**Issue by Dattito** [gitpod-io/gitpod#5062] opened 2021-08-05 09:11 UTC
### Bug description

When opening Gitpod on my iPad, the terminal is unvisible:
[![image](https://www.linkpicture.com/q/5F1999BA-7002-43B8-B3A4-BD5B93FA4F22.jpeg)](https://www.linkpicture.com/view.php?img=LPic610baacb76c881295080329)
I tried different Color-Styles, but nothing changed. 
Maybe it is because I use iPadOS 15 beta?

### Steps to reproduce

- Open GitPod on iPad

### Anything else?

Using Code-Server instead of GitPod, it is unvisible too

**Comment by akosyakov** [comment] 2021-08-05 09:13
duplicate of https://github.com/gitpod-io/gitpod/issues/5040

**Closed by akosyakov** 2021-08-05 09:13 UTC
