### ISSUE TITLE
Showing unauthorized despite of me logged in 

### ISSUE THREAD

**Issue by manishdasa100** [gitpod-io/gitpod#3095] opened 2021-02-04 06:10 UTC
### Describe the bug

I logged in with my github account and the login was successful but it was requesting for further authorization from Gitlab.com. I did that and after I logged in with my Gitlab account it was showing me "Authorization failed. Please try again". I don't know what's happening may be it's a bug.

**Comment by csweichel** [comment] 2021-02-04 06:16
Probably a duplicate of #2746.
Please reopen if that's not the case.

**Closed by csweichel** 2021-02-04 06:16 UTC
