### ISSUE TITLE
Dart/Flutter support

### ISSUE THREAD

**Issue by wanderlan** [gitpod-io/gitpod#792] opened 2019-09-15 20:43 UTC
Some date?

**Comment by svenefftinge** [comment] 2019-09-16 10:56
The VS Code extension works now, only the issue with the proxy is left. 
Closing this as duplicate of #114

**Closed by svenefftinge** 2019-09-16 10:56 UTC

**Comment by VinayBaviri** [comment] 2021-08-03 13:43
Any suggestions on #5047 !!
