### ISSUE TITLE
No Open Preview for HTML files when using VS Code

### ISSUE THREAD

**Issue by Poay-Kin-Loo** [gitpod-io/gitpod#4345] opened 2021-05-30 20:46 UTC
### Bug description

Open Preview icon for HTML files is missing from Gitpod when using VS code.

The icon is still visible for README.md file.

### Steps to reproduce

In your project under Gitpod Explorer create a simple README.md and index.html file.

Click on README.md file to see it in the editor - you should also see Open Preview icon.

Click on index.html file to see in in the editor - no Open Preview icon.

### Expected behavior

There should be Open Preview icon for HTML file (it was added for Thei under https://github.com/gitpod-io/gitpod/issues/137?)

### Anything else?

Print-screen here:

![gitpod_readme](https://user-images.githubusercontent.com/82480209/120119580-6b06ef00-c190-11eb-9a87-b3dfe841f746.png)

**Comment by rl-gitpod** [comment] 2021-05-31 00:46
This is not supported in [VS Code](https://code.visualstudio.com/docs/languages/html#_does-vs-code-have-html-preview)
As mentioned in that link there are plugins that might work for you.

Closing as this is not a bug per se.

**Closed by rl-gitpod** 2021-05-31 00:46 UTC
