### ISSUE TITLE
CLI command for Running Tasks

### ISSUE THREAD

**Issue by ChevronTango** [gitpod-io/gitpod#17578] opened 2023-05-11 15:58 UTC
## Is your feature request related to a problem? Please describe

Currently its very difficult to rerun a task, or test a task, when building out a `.gitpod.yml`

## Describe the behaviour you'd like

the ability to use the gitpod command line to call specific tasks in the `.gitpod.yml` eg:

```console
gp tasks run init "My Task1"
gp tasks run command "My Second Task"
```

## Describe alternatives you've considered

whilst you can just copy and paste the commands, it gets a bit cumbersome, so a quick way to trigger the commands in the same way gitpod would, would help with quick and easy testing of these commands.

**Comment by loujaybee** [comment] 2023-05-15 12:16
@ChevronTango have you tried using `gp validate`, yet? 

https://www.gitpod.io/docs/references/gitpod-cli#validate
https://www.gitpod.io/docs/configure/workspaces#validate-your-gitpod-configuration
https://www.gitpod.io/changelog/validate-gitpod-yaml-without-commit

I'd be keen to hear what you think, and if it solves your issue 🙏

**Comment by loujaybee** [comment] 2023-05-15 12:18
I think a duplicate of: 

- https://github.com/gitpod-io/gitpod/issues/8691

And relates to:

- https://github.com/gitpod-io/gitpod/issues/7671

Will close, but please do re-open if you have issues, or you have more information to share 🙏

**Closed by loujaybee** 2023-05-15 12:18 UTC
