### ISSUE TITLE
Two windows opening instead of one

### ISSUE THREAD

**Issue by superboss224** [gitpod-io/gitpod#12349] opened 2022-08-24 14:55 UTC
### Bug description

Hello, I'm having a bug where gitpod opens two windows when one port gets opened, and I have been able to reproduce it on a public repository.

Here is the repository (which is a fork of the sveltekit template) :
https://github.com/superboss224/gitpod-svelte-test

Just launch a workspace with it and you should see two windows opening instead of only one, it forces me to close one of them everytime, and often creates an unwanted error because on of them seem to be opened too early.

The bug also happens when you configure `gitpod.yml` to open previews instead of windows, it will also open two web previews in VSCode instead of one.

Why is this problem happening ? Is there a way make GitPod behave normally ?

### Steps to reproduce

Launch a workspace based on that repository : 
https://github.com/superboss224/gitpod-svelte-test

### Expected behavior

I should see only one windows opening when `npm run dev` starts

### Example repository

https://github.com/superboss224/gitpod-svelte-test

**Comment by pawlean** [comment] 2022-08-25 10:55
Hey @superboss224! I've been trying to replicate this using the same repository but unfortunately, I don't see this. Can you share a screenshot with me (_if it's still happening_)? 🐞

**Comment by superboss224** [comment] 2022-08-27 12:54
I've updated the example repository to have a more "open in GitPod button".

Then, I used a new browser, freshly installed, and:
- I clicked on the button "Open in GitPod" in the readme of the repository
- I was asked to connect to GitHub since it's a new browser, so I logged into GitHub
- It started prebuilding, I waited for 5 minutes, and it was still prebuilding for some reason, but with a blank log, so I clicked on "Skip Prebuild"
- It navigated me to web VSCode, and prompted me that the website tried to open **two** windows, I then authorized the website to open pop-ups, I reloaded the editor, and it indeed opened **two** windows

This process means the bug is still here, even with a fresh browser and on a simple project directly forked from sveltekit's template

**Comment by loujaybee** [comment] 2022-09-09 11:43
Small update, I've added this to our next iteration for review. We did some investigation but could not consistently replicate, however we'll keep digging in until we find the issue, thanks for raising @superboss224, hopefully we can get the issue fixed up soon!

**Comment by jeanp413** [comment] 2022-09-25 03:06
I took a look but couldn't reproduce it

**Comment by LorenzHenk** [comment] 2022-09-26 11:55
Looks like this was fixed recently, doesn't happen for me anymore 👍

**Comment by jeanp413** [comment] 2022-09-26 19:18
> Looks like this was fixed recently, doesn't happen for me anymore +1

Closing this :+1:

**Closed by jeanp413** 2022-09-26 19:18 UTC
Labels: type: bug, editor: code (browser), feature: gitpod yml, team: IDE, editor: code (desktop)
