### ISSUE TITLE
Cannot access my workspace

### ISSUE THREAD

**Issue by Domchap90** [gitpod-io/gitpod#1980] opened 2020-10-12 09:12 UTC
### Describe the bug

Upon trying to gain access to my workspace, in stage 2/3 i get the error message in red:
cannot pull image: Back-off pulling image "reg.gitpod.io:8081/remote/e8fed701-9738-4cc7-837b-cd85bb2ccbfd"

### Steps to reproduce

Simply opening my work space.

### Expected behavior

The work space to open.

**Comment by corneliusludmann** [comment] 2020-10-12 09:21
Thanks for reporting. Duplicate of #1979?

**Closed** 2020-10-12 14:28 UTC
Labels: duplicate
