### ISSUE TITLE
Support for gist

### ISSUE THREAD

**Issue by th3c0d3br34ker** [gitpod-io/gitpod#1574] opened 2020-06-03 18:31 UTC
Just like opening git repository,  opening git in a simple code editor would be a helpful feature.

**Comment by th3c0d3br34ker** [comment] 2020-06-16 18:20
Any updates?

**Comment by jankeromnes** [comment] 2021-03-10 14:36
Many thanks for this request! 👍

I'll close this one as a duplicate of #70, so that we can track it over there.

Also, I've tentatively added #70 to the April 2021 milestone (unfortunately I can't promise that we'll actually have engineering resources to allocate, since there are many other high-priority items, but at least this puts it on the radar again.)

**Closed by jankeromnes** 2021-03-10 14:36 UTC
Labels: type: feature request
