### ISSUE TITLE
Gitlab Login Problem

### ISSUE THREAD

**Issue by MandlaGowtham** [gitpod-io/gitpod#2825] opened 2021-01-11 13:22 UTC
### Example repository

Unable to login in the gitpod workspace.

**Comment by jankeromnes** [comment] 2021-01-11 16:20
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by jankeromnes** 2021-01-11 16:20 UTC
