### ISSUE TITLE
Allow for selection of editor By Repository

### ISSUE THREAD

**Issue by melaraj2** [gitpod-io/gitpod#12490] opened 2022-08-29 19:53 UTC
## Is your feature request related to a problem? Please describe
My team uses different editors depending on the project.  We write applications in Go, Java, NodeJs, Rust.  Depending on the language we use different Editors.  For Example Java Projects we use IntelliJ, but for Go we typically use Goland, and for Rust, we use VS Code.  Currently, we have to first navigate to GitPod preferences and change the editor prior to launching each Repository GitPod.  Besides it being tedious, there is no way to store in the repository the appropriate editor configuration that the core team for the project intended.  We can store all the other configurations such as databases, but a core thing is an editor that works best for this project.

## Describe the behavior you'd like
At a minimum, we should be able to select the editor at launch time, so that when we click on the GitPod button in github, that it would ask which editor we want to use for that session.  Rather than launch a java project with VS Code, or pyCharm. 

A more robust solution is to store the preferred editor in the repository so that we have an en environment that is complete and is ready to use when you hit the button.  Of course, we should be able to change it at launch, so this would be the preselected editor when you first launch the GitPod.

## Describe alternatives you've considered
currently, prior to opening a gitpod for a repository, we change the use preferences in gitpod.io

**Comment by axonasif** [comment] 2022-08-30 11:05
Hey @melaraj2, thanks for posting this.
However it seems to be a duplicate of https://github.com/gitpod-io/gitpod/issues/8573 😅

**Closed by axonasif** 2022-08-30 11:05 UTC

**Comment by loujaybee** [comment] 2022-08-30 12:32
Thanks for the feedback, @melaraj2 ! This is definitely a use case we've heard before, especially in the context of open source, where users are often jumping between projects or for companies where many repo's are more the norm than a single repo or mono-repo. Generally speaking we do want to facilitate the ability for Gitpod to provide a "golden path" for those using your project, so as much as possible of your configuration is stored in the repo, gitpod.yml etc and the best possible experience is provided by default, which can then be overridden by users if they have an alternate preference. 

As @axonasif mentioned, I think this is mostly covered by these two issues:

* https://github.com/gitpod-io/gitpod/issues/8573
* https://github.com/gitpod-io/gitpod/issues/6874

However I'm going to copy over your comment onto #8573 as I think it's most relevant there. 

Any further thoughts or input you have would be useful and hopefully we can soon start to roll out some additional changes that implement this flexibility for you 🙏
