### ISSUE TITLE
Feature Request: Support creating a workspace without an existing git repo

### ISSUE THREAD

**Issue by mickmister** [gitpod-io/gitpod#7936] opened 2022-02-01 00:44 UTC
## Describe the behaviour you'd like

An example use case would be that I want to try out some framework or library, but I'm not committed enough at the moment to create a git repo for the purpose of trying out said framework/library

**Comment by utam0k** [comment] 2022-02-01 05:58
@mickmister Hi! Thanks for your feature request. Even if you don't have a git repository, you can create a workspace from the "New Workspace" section on the following page. Is it different from this?
https://gitpod.io/workspaces

**Comment by mickmister** [comment] 2022-02-03 03:02
@utam0k When I click "New Workspace", I'm given a choice for what to use as the starting point of my new workspace. There is a "Recent" tab that shows repositories from my existing workspaces, and an "Examples" tab that has different templates made for GitPod. 

I suppose what I'm asking for is a blank slate. This would be the equivalent of a git repository with no commits, or the equivalent of running `git init` in an empty directory. I personally really like the feeling of doing this, it feels like a ritual of sorts.

The `workspace-full` image Gitpod uses seems to cover much of the tooling needed for someone to   create their own project. Having this "blank" template option gives developers the freedom to start the project the way they want to, with no distractions or friction from other thoughts. This is especially true if the project doesn't fit any of the existing templates, e.g. it's in a different language than the available templates.

**Comment by pawlean** [comment] 2022-02-03 08:32
Hey @mickmister, this seems to be a duplicate of #605. Is that right?

**Comment by axonasif** [comment] 2022-02-03 08:34
It might not be.

**Comment by geropl** [comment] 2022-04-07 07:43
I think there is sufficient overlap to see it as dupe of #605. 

@mickmister If you think I'm missing sth please bring it up in #605 for discussion, and if there is sufficient difference, create a new issue with more context. :pray:

**Closed by geropl** 2022-04-07 07:43 UTC
Labels: type: feature request, team: webapp
