### ISSUE TITLE
/usr/bin/gp: not found

### ISSUE THREAD

**Issue by eric-wieser** [gitpod-io/gitpod#13267] opened 2022-09-25 11:51 UTC
### Bug description

The [gitpod command line interface, `gp`](https://www.gitpod.io/docs/command-line-interface), seems not to be present on the default gitpod image.
The configured git `credential.helper` setting expects it to be there.

### Steps to reproduce

Checkout a clean workspace of a repo that does not contain a `gitpod.yml`. Attempt to run `git push`:
```
gitpod /workspace/my_repo (master) $ git push
/usr/bin/gp credential-helper get: 1: /usr/bin/gp: not found
Username for 'https://github.com':
```

### Workspace affected

ericwieser-icacga2022-7t6m3tak3q3.ws-eu68

### Expected behavior

The credential helper should either not be configured with git in the first place if it is no longer supported, or it should work.

**Comment by csweichel** [comment] 2022-09-25 12:45
I saw the same behaviour:

My workspace is also missing `/usr/bin/gp`. I started more workspaces which all landed on the same node (`workspace-ws-eu68-large-pvc-pool-7wvj`), and there `/usr/bin/gp` is missing, too.

@eric-wieser's workspace is running on `workspace-ws-eu68-pool-s7zk`, i.e. a different (non-PVC) node.

In the same workspaces docker isn't running, because
```json
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"listen unix /var/run/docker.sock: bind: value too large for defined data type","level":"error","message":"cannot provide Docker activation socket","serviceContext":{"service":"supervisor","version":"commit-9aa153e559070b28547d3ceff055d90898088994"},"severity":"ERROR","time":"2022-09-25T12:17:02Z"}
```

Trying to write to `/usr/bin` also returns value too large for defined data type.
<img width="572" alt="image" src="https://user-images.githubusercontent.com/3210701/192144076-94a022e4-0001-40c7-bb62-f7286f2110a8.png">

**Comment by aledbf** [comment] 2022-09-25 13:24
> Trying to write to /usr/bin also returns value too large for defined data type.

that sounds an issue with shiftfs

**Comment by eric-wieser** [comment] 2022-09-25 13:26
> Trying to write to /usr/bin also returns value too large for defined data type.

Yes, I got the same thing.

**Comment by richardfrankza** [comment] 2022-09-25 13:27
Same here, hitting this issue currently on eu67.

**Comment by kylos101** [comment] 2022-09-25 14:06
@richardfrankza we were not able to recreate the issue on eu67 or us67. Are you still having trouble? If yes, could you share the workspace name so we can examine?

**Comment by kylos101** [comment] 2022-09-25 15:41
@eric-wieser @richardfrankza we've shifted traffic back to eu67 and us67 to avoid this issue, @aledbf confirmed it is an issue with shiftfs on eu68 and us68.

If you continue to have trouble, let us know which workspace it's on? Closing this issue for now.

**Closed by kylos101** 2022-09-25 15:41 UTC
Labels: type: bug, priority: highest (user impact), team: workspace
