### ISSUE TITLE
texlive failed to build, returned a non-zero code: 100

### ISSUE THREAD

**Issue by rholland** [gitpod-io/gitpod#1561] opened 2020-05-28 17:13 UTC
I used the docker config file in your docs.  Is there a better config then the following?

```
FROM gitpod/workspace-full

# Install LaTeX
RUN sudo apt-get -q update && \
    sudo apt-get install -yq texlive-full && \
    sudo rm -rf /var/lib/apt/lists/*

```
Here is the end of the build before it failed - it ran for a few minutes successfully before hitting the following:   

```
Errors were encountered while processing:
 /tmp/apt-dpkg-install-9g8OWa/477-texlive-lang-french_2019.20200218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/478-texlive-lang-german_2019.20200218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/479-texlive-lang-italian_2019.20200218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/480-texlive-lang-polish_2019.20200218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/481-texlive-lang-spanish_2019.20200218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/482-texlive-luatex_2019.20200218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/483-texlive-lang-czechslovak_2019.20200218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/484-texlive-lang-greek_2019.20200218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/485-texlive-lang-japanese_2019.20200218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/486-texlive-lang-korean_2019.20200218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/487-texlive-lang-portuguese_2019.20200218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/488-texlive-latex-base-doc_2019.20200218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/489-texlive-latex-extra-doc_2019.202000218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/490-texlive-latex-recommended-doc_2019.20200218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/491-texlive-metapost-doc_2019.20200218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/492-texlive-music_2019.202000218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/493-texlive-pictures-doc_2019.20200218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/494-texlive-pstricks-doc_2019.202000218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/495-texlive-publishers_2019.202000218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/496-texlive-publishers-doc_2019.202000218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/497-texlive-science_2019.202000218-1_all.deb
 /tmp/apt-dpkg-install-9g8OWa/498-texlive-science-doc_2019.202000218-1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Error: build failed: cannot build base image:
```

**Comment by rholland** [comment] 2020-05-28 17:28
Tried to install using texlive instead of texlive-full.   Now getting

```
Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: %!w(string=)
Please file an issue if you think this is a bug.
```

**Comment by Kreyren** [comment] 2020-05-28 17:50
Concluded this being a duplicate of https://github.com/gitpod-io/gitpod/issues/1559

**Comment by rholland** [comment] 2020-05-28 17:52
I changed install to texlive from texlive-full and it built.

**Comment by Kreyren** [comment] 2020-05-28 17:54
reopening, The https://github.com/gitpod-io/gitpod/issues/1561#issuecomment-635489080 is duplicate of #1559, but OP is a different issue.

**Comment by Kreyren** [comment] 2020-05-28 17:56
@rholland i would avoid using `sudo` in gitpod's docker-build environment it seems to cause a breakage if you are not privileged user (only developers are privileged users atm)

Try this:

```dockerfile
FROM gitpod/workspace-full

# Install LaTeX
USER root
RUN true \
	&& apt-get -q update \
	&& apt-get install -yq \
		texlive-full \
	&& apt-get autoremove -qy \
	&& rm -rf /var/lib/apt/lists/*
```

**Comment by rholland** [comment] 2020-05-28 18:04
Thanks Kreyren.  You guys do a great job.  You may want to update your docs - that is where I got the template with sudo.  In any case I changed the install to texlive from texlive-full and that did install with sudo.  The smaller package may also be better for your example.  The full install is 10x the size!

```
Package                    Archives  Disk Space
-------------------------  --------  ----------
texlive-latex-base            59 MB      216 MB
texlive-latex-recommended     74 MB      248 MB
texlive-pictures              83 MB      277 MB
texlive-fonts-recommended     83 MB      281 MB
texlive                       98 MB      314 MB
texlive-plain-generic         82 MB      261 MB
texlive-latex-extra          144 MB      452 MB
texlive-full                2804 MB     5358 MB
```

**Comment by Kreyren** [comment] 2020-05-28 18:36
> You may want to update your docs - that is where I got the template with sudo. 

Updated in https://github.com/Kreyren/gitpod-website/commit/3e44d52bdd78f4c15bf98950db2335a64737ff8b

> In any case I changed the install to texlive from texlive-full and that did install with sudo. The smaller package may also be better for your example. The full install is 10x the size!

Updated in https://github.com/gitpod-io/website/pull/669

---

Concluded this being solved -> Closing ^-^

**Closed by Kreyren** 2020-05-28 18:36 UTC
Labels: operations, question
