### ISSUE TITLE
No delegateCommandHandler for vscode.java.startDebugSession when starting

### ISSUE THREAD

**Issue by dsyer** [gitpod-io/gitpod#1018] opened 2019-12-20 08:02 UTC
**Describe the bug**
No run links on Java source code. Running the project results in an error dialog "No delegateCommandHandler for vscode.java.startDebugSession". Apparently this would be fixed with a new version of https://github.com/microsoft/vscode-java-debug.

**To Reproduce**
Open any Java project, e.g. https://gitpod.io/#https://github.com/spring-projects/spring-petclinic

**Expected behavior**
Tests and main classes have"Run" links.  Debug->Start Debugging should run the main class.

**Additional Information**
https://github.com/microsoft/vscode-java-debug/issues/728

**Comment by akosyakov** [comment] 2019-12-20 08:30
@dsyer We will update Gitpod to latest java support. For time being you can upload latest version of extensions into your repo to enable them, see https://www.gitpod.io/docs/vscode-extensions/#installing-an-extension

**Comment by akosyakov** [comment] 2019-12-20 08:49
Duplicate of https://github.com/gitpod-io/gitpod/issues/886

**Comment by dsyer** [comment] 2019-12-20 09:04
Thanks for the link. Actually I’m not sure I know where to get a .vsix file from (also drag and drop is rubbish for anyone without a file explorer). Normally I just click on the “Install” button. Why can’t Gitpod do it the normal way? Where do you find those files?

**Comment by akosyakov** [comment] 2019-12-20 09:11
@dsyer yes, it is not very convenient right now :( Unfortunately MS does not let us to access VS Code marketplace: https://www.gitpod.io/docs/vscode-extensions/#where-do-i-find-extensions We are working on the open marketplace which will be hosted under Eclipse Foundation.

**Comment by akosyakov** [comment] 2019-12-20 09:16
vscode-java-debug: https://github.com/microsoft/vscode-java-debug/releases/download/0.23.0/vscode-java-debug-0.23.0.vsix
redhat.java: https://github.com/redhat-developer/vscode-java/releases/download/v0.54.2/redhat.java-0.54.2.vsix

**Comment by dsyer** [comment] 2019-12-20 09:30
Thanks. Found it. Unfortunately it doesn't seem to fix anything. How do I know if that extension is active?

**Comment by akosyakov** [comment] 2019-12-20 09:38
@dsyer It should be like that:
<img width="1552" alt="Screen Shot 2019-12-20 at 10 34 40" src="https://user-images.githubusercontent.com/3082655/71245131-5b854480-2314-11ea-81d3-08edfaac6b20.png">

You need to reload the page to enabled latest versions. I've opened a bug in Theia to make it work automatically in the future: https://github.com/eclipse-theia/theia/issues/6777

**Comment by dsyer** [comment] 2019-12-20 09:39
OK now I have this in `.gitpod.yml`:

```
vscode:
  extensions:
    - vscjava.vscode-java-pack@0.8.1:LRImBn//d5JhH4PUEI1BaQ==
    - vscjava.vscode-java-debug@0.23.0:3ARqL3kPh1J1SwpVjYUjqw==
    - vscjava.vscode-java-test@0.22.0:BlvjRRJyZszeJzIS+xEHIA==
```

The first one is supposed to be a collection of extensions that include the rest, but using it on its own didn't seem to work at all.

I was able to run the app. But I get this on the tests:

```
Error: 'org.eclipse.jdt.core.IJavaProject org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(java.lang.String)'.Error: 'org.eclipse.jdt.core.IJavaProject org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(java.lang.String)'.Error: 'org.eclipse.jdt.core.IJavaProject org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(java.lang.String)'.Error: 'org.eclipse.jdt.core.IJavaProject org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(java.lang.String)'.Error: 'org.eclipse.jdt.core.IJavaProject org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(java.lang.String)'.Error: 'org.eclipse.jdt.core.IJavaProject org.eclipse.jdt.ls.core.internal.ProjectUtils.getJavaProject(java.lang.String)'.
```

Nothing very helpful there.

**Comment by dsyer** [comment] 2019-12-20 09:48
Got it working almost:

```
vscode:
  extensions:
    - vscjava.vscode-java-pack@0.8.1:LRImBn//d5JhH4PUEI1BaQ==
    - vscjava.vscode-java-debug@0.23.0:3ARqL3kPh1J1SwpVjYUjqw==
    - vscjava.vscode-java-test@0.22.0:BlvjRRJyZszeJzIS+xEHIA==
    - redhat.java@0.54.2:Q60n5quUtfd1EcwzkRq96A==
    - vscjava.vscode-maven@0.20.1:gdyOPlzH3PU5IkrigIg85g==
```

(Adding more extensions from the `vscode-java-pack` manually.)

The next thing that breaks is that when the tests run you don't get feedback about whether it was successful or not, just a placeholder (see screenshot).

![Screenshot from 2019-12-20 09-45-12](https://user-images.githubusercontent.com/124075/71245975-bf583f00-230d-11ea-8d9b-6557d56788a3.png)

Also, when you run the app there is no way to stop it (usually in vscode there is a little floating dialog with play/stop/refresh type buttons).

**Comment by akosyakov** [comment] 2019-12-20 09:50
@dsyer please replace `.gitpod.yml` with and reload:
```yml
vscode:
  extensions:
    - vscjava.vscode-java-debug@0.23.0:3ARqL3kPh1J1SwpVjYUjqw==
    - redhat.java@0.54.2:Q60n5quUtfd1EcwzkRq96A==
    - vscjava.vscode-java-test@0.22.0:BlvjRRJyZszeJzIS+xEHIA==
```

I don't see that `redhat.java` is updated to latest in your gitpod.yml. The bug was in this extension. You should also see in the extension view that a version of `redhat.java` is correct.

For me app and test running work with such configuration:
<img width="1552" alt="Screen Shot 2019-12-20 at 10 48 24" src="https://user-images.githubusercontent.com/3082655/71246100-5a551700-2316-11ea-9a4b-78ef3594ae35.png">
<img width="1552" alt="Screen Shot 2019-12-20 at 10 49 37" src="https://user-images.githubusercontent.com/3082655/71246155-6e007d80-2316-11ea-94dc-9a87d8c47159.png">

**Comment by akosyakov** [comment] 2019-12-20 09:50
> Also, when you run the app there is no way to stop it (usually in vscode there is a little floating dialog with play/stop/refresh type buttons).

In Theia, it is always docked in the debug view.

**Comment by akosyakov** [comment] 2019-12-20 09:51
> The next thing that breaks is that when the tests run you don't get feedback about whether it was successful or not, just a placeholder (see screenshot).

Could you elaborate on it? How does it look in VS Code? I see test in the test view.

**Comment by dsyer** [comment] 2019-12-20 09:56
> In Theia, it is always docked in the debug view.

Got it thanks. Finding it hard to figure out how to force Gitpod to close and reopen the workspace. Is there an action for that?

I also found that I need the Maven extension, otherwise the run/debug links are not rendered.

> Could you elaborate on it? How does it look in VS Code?

Your screenshot shows the `$(checkbox)` placeholder on the test (should be a "tick" or "cross" to indicate success or failure).

**Comment by akosyakov** [comment] 2019-12-20 10:01
> Finding it hard to figure out how to force Gitpod to close and reopen the workspace. Is there an action for that?

In the top right corner there is your account icon, if you click on it then you can stop the workspace or open the dashboard from there:
<img width="511" alt="Screen Shot 2019-12-20 at 10 59 13" src="https://user-images.githubusercontent.com/3082655/71246874-dd2aa180-2317-11ea-81ea-17ba0ad890c6.png">

You can see all your workspaces here:  https://gitpod.io/workspaces

> Your screenshot shows the $(check) placeholder on the test (should be a "tick" or "cross" to indicate success or failure).

Thanks! I will bring it to Theia.

> I also found that I need the Maven extension, otherwise the run/debug links are not rendered.

Do you mean code lens links?

**Comment by dsyer** [comment] 2019-12-20 10:02
> Do you mean code lens links?

I guess. Is that what they call them.

**Comment by svenefftinge** [comment] 2020-02-03 08:33
Deployed to production. Please verify.

**Closed by svenefftinge** 2020-02-03 08:33 UTC
Labels: bug, java

**Comment by dsyer** [comment] 2020-02-03 09:36
Nothing changed for me. What was it that was "deployed to production"?
