### ISSUE TITLE
Show logs from docker build when it fails

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#491] opened 2019-04-16 14:51 UTC
Currently, we remove the output from docker build when it fails. This makes iterating on Dockerfiles for the Gitpod config no fun.

**Comment by jankeromnes** [comment] 2019-04-18 16:23
Now sometimes I don't even see the build logs, it goes straight from `Starting ...` to the unhelpful error screen.

I need to refresh to see build logs (e.g. to take a screenshot just before the error disappears).

**Comment by AlexTugarev** [comment] 2019-04-24 13:48
<img width="834" alt="Screen Shot 2019-04-24 at 15 47 15" src="https://user-images.githubusercontent.com/914497/56664372-4d5d2680-66a8-11e9-919a-4b6ca19e7af0.png">

We can inspect build logs now :-)

**Comment by svenefftinge** [comment] 2019-08-09 12:35
It quickly shows the error and then goes to
![image](https://user-images.githubusercontent.com/372735/62779231-e62a7d00-bab2-11e9-8ff4-e3126ab34ba9.png)

**Comment by jankeromnes** [comment] 2019-08-28 08:50
Duplicate of #423.

**Closed by jankeromnes** 2019-08-28 08:50 UTC
Labels: bug, ux
