### ISSUE TITLE
Build gitpod.Dockerfile in terminal as if starting a workspace

### ISSUE THREAD

**Issue by mteam88** [gitpod-io/gitpod#9865] opened 2022-05-09 12:04 UTC
## Is your feature request related to a problem? Please describe
When using Gitpod to develop my application, I am forced to restart the workspace on every edit to the .gitpod.Dockerfile or use the #imagebuild url trick. This takes a lot of time and the logs are not super accessible.

## Describe the behaviour you'd like
In the Gitpod command prompt (Ctrl+Shift+P) a command could be like `Gitpod: Build .gitpod.Dockerfile in terminal`

## Describe alternatives you've considered
This sequence here:
``docker build -f .gitpod.Dockerfile -t gitpod-dockerfile-test .``

``docker run -it gitpod-dockerfile-test bash``

Is sorta useful, and is essentially what I have been doing, but it **does not completely simulate starting a workspace**. My project (based on the workspace-vnc-full gitpod image) requires that. Rather annoying to start a whole new workspace. And recently I have had problems with that build system [link to discord issue](https://discord.com/channels/816244985187008514/972590280446476308/972597412352901140)

**Comment by axonasif** [comment] 2022-05-09 15:06
Duplicate of https://github.com/gitpod-io/gitpod/issues/7671

**Closed** 2022-05-09 15:07 UTC
