### ISSUE TITLE
Traces for Werft jobs are missing phases and spans

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#8727] opened 2022-03-10 16:22 UTC
## Is your feature request related to a problem? Please describe
Traces are missing phases and spans. Example: 
https://ui.honeycomb.io/gitpod/datasets/werft/trace/6oNaVv7xGTR?span=missing%20root
Related discussion: https://gitpod.slack.com/archives/C01KGM9EBD4/p1646904136525909
We observed the errors on https://github.com/gitpod-io/gitpod/pull/8696. That PR got superseded by https://github.com/gitpod-io/gitpod/pull/8706 on which tracing was working fine and thus we merged it.
Now, however, we see broken traces on `main`.

It's not clear yet what causes this and I filed https://github.com/gitpod-io/gitpod/issues/8707 to rule out potential causes. 

## Describe the behaviour you'd like
Traces without missing spans/phases.

**Comment by mads-hartmann** [comment] 2022-03-11 13:10
I haven't been able to reproduce this since https://github.com/gitpod-io/gitpod/pull/8743 so I'm closing this for now. We an reopen it if we see it again.

**Closed by mads-hartmann** 2022-03-11 13:10 UTC
