### ISSUE TITLE
ERROR : Request startWorkspace failed with message: Not connected to message bus

### ISSUE THREAD

**Issue by HSSANT** [gitpod-io/gitpod#1117] opened 2020-01-18 16:25 UTC
Again when i tried to open my workspace im facing the error described in title.

This month every day gitpod was awfull.

Anyone can support me with this?

Indeed, i am using premium account. We will have any refund for all those errors?

**Comment by jankeromnes** [comment] 2020-01-18 16:58
Thank you for reporting this. Duplicate of #1110 and should work again.

Also, we sincerely apologize for the recent problems that happened in the gcloud us02 datacenter. There may be some underlying issues with this datacenter, in which case we'll migrate to a different one. Also I would like to offer affected users some sort of compensation or refund and will discuss this with the team.

**Closed by jankeromnes** 2020-01-18 16:58 UTC
