### ISSUE TITLE
[Theia] supervisor client error

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#1940] opened 2020-10-04 07:25 UTC
On load I see 
```
VM3236:1 Uncaught ReferenceError: response is not defined
    at eval (eval at <anonymous> (supervisor-service-client.js:69), <anonymous>:1:1)
    at supervisor-service-client.js:69
    at supervisor-service-client.js:38
    at Object.next (supervisor-service-client.js:19)
    at s (supervisor-service-client.js:10)
```

**Comment by akosyakov** [comment] 2020-10-04 13:32
It is a duplicate of https://github.com/gitpod-io/gitpod/issues/1939

**Closed by akosyakov** 2020-10-04 13:32 UTC
