### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by lrgongora** [gitpod-io/gitpod#1135] opened 2020-01-22 22:19 UTC
**Describe the bug**
Receiving the following error when trying to access dashboard and/or open workspaces:

500 Internal Server Error
nginx/1.14.1

**To Reproduce**
Try to access Dashboard or open any workspace

**Expected behavior**
Show Dashboard with the list of workspaces. Be able to open workspaces.

**Additional Information**
DevTools console showed all requests were being canceled.

**Comment by Kreyren** [comment] 2020-01-22 22:26
Seems like duplicate of https://github.com/gitpod-io/gitpod/issues/1128

**Comment by jankeromnes** [comment] 2020-01-23 08:53
Thanks for reporting this. We're aware of this intermittent error, and are currently able to fix it in under 30 minutes whenever it pops up. Also, we're working on preventing it from happening at all.

> Seems like duplicate of #1128

Indeed thanks, good catch.

**Closed by jankeromnes** 2020-01-23 08:53 UTC
