### ISSUE TITLE
VSCode JavaScript debug terminal error

### ISSUE THREAD

**Issue by MeStrak** [gitpod-io/gitpod#2630] opened 2020-12-28 18:13 UTC
I'm trying out Gitpod after several issues with my local dev environment (including a blown motherboard on 25th December). Before going into the details of the bug, I would just like to say that I love it - great job!

### Describe the bug
I'm trying to debug my node.js app with no success - I can't attach to the debugger. Now that VS Code is available I decided to try with the JavaScript Debug Terminal which works fine on my Mac. As soon as I try and launch any process I get an error message

### Steps to reproduce
1. Activate VSCode for Gitpod and launch workspace
2. Run `gitpod /workspace/catkin/backend $ yarn start` (actually any of my start scripts, not specific to this one)
3.  The following error is produced

```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/home/gitpod/.gitpod-code/User/workspaceStorage/-1c80148e/ms-vscode.js-debug/bootloader.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1147:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:446:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:74:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}<!-- Steps to reproduce the behavior -->
```

### Expected behaviour
Node app should launch in debug mode. The same command on my local Mac works:

`mylocalmac:backend strak$ yarn start`

```
Debugger attached.
yarn run v1.22.10
$ ts-node -r tsconfig-paths/register src/main.ts
Debugger attached.
[Nest] 49878   - 12/28/2020, 5:56:02 PM   [NestFactory] Starting Nest application...
[Nest] 49878   - 12/28/2020, 5:56:02 PM   [InstanceLoader] MongooseModule dependencies initialized +83ms
[Nest] 49878   - 12/28/2020, 5:56:02 PM   [InstanceLoader] AuthModule dependencies initialized +0ms
[Nest] 49878   - 12/28/2020, 5:56:02 PM   [InstanceLoader] PassportModule dependencies initialized +1ms
...
...
```

### Additional information

Separately to this issue I have also had many general issues getting debugging to work. This was a last resort after trying different launch configs and start scripts which did not work, but as I find that behaviour quite flaky in VSCode I tried this which worked with no config locally.

The start scripts I tried included `--inspect` which runs through without breaking, `-- inspect-brk`, `--inspect-brk=0.0.0.0` which don't start, presumably because the debugger isn't actually attached. I'm actually trying to debug my e2e tests so the command I was running was `yarn test:e2e:debug` which runs:
` "test:e2e:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand --config ./test/jest-e2e.json"`

### Example repository
https://github.com/MeStrak/catkin

**Comment by MeStrak** [comment] 2020-12-28 18:16
I should also add that using a normal terminal I am able to start both my app and tests, just not in debug mode:

`gitpod /workspace/catkin/backend $ yarn start`

```
yarn run v1.22.10
$ ts-node -r tsconfig-paths/register src/main.ts
[Nest] 3773   - 12/28/2020, 6:15:23 PM   [NestFactory] Starting Nest application...
[Nest] 3773   - 12/28/2020, 6:15:23 PM   [InstanceLoader] MongooseModule dependencies initialized +30ms
[Nest] 3773   - 12/28/2020, 6:15:23 PM   [InstanceLoader] AuthModule dependencies initialized +0ms
[Nest] 3773   - 12/28/2020, 6:15:23 PM   [InstanceLoader] PassportModule dependencies initialized +1ms
[Nest] 3773   - 12/28/2020, 6:15:23 PM   [InstanceLoader] HttpModule dependencies initialized +0ms
...
...
```

**Comment by svenefftinge** [comment] 2020-12-29 09:56
I tried to reproduce your issue, but it is not clear to me how.

> Run gitpod /workspace/catkin/backend $ yarn start (actually any of my start scripts, not specific to this one)

Could you share the launch config (.vscode/launch.json) you tried? 

When I first started the repo, the yarn install failed in backend, due to interference of two concurrently running installs.
You should add `--mutex network` to the parallel `yarn install` commands to avoid them tripping on each other's feet.

The processes don't start for me in the standard terminal, as it cannot connect to the DB. That said it takes some time until that error comes. I could launch the same `yarn start` script using a launch config and it produced the same output.

**Comment by MeStrak** [comment] 2020-12-29 10:46
Hi @svenefftinge, thanks for looking into this. The db connection issue is just a missing .env file in the backend folder with the value `MONGO_CONNECTION='mongodb://localhost:27017'` - adding that makes the db connection work.

Weirdly, I just checked again and this is actually working fine for me this morning, so I'm pretty happy!

![Screen Shot 2020-12-29 at 10 41 07](https://user-images.githubusercontent.com/31989238/103278238-f18d8980-49c2-11eb-8847-85e4a9e02637.png)

However I really don't know why - I didn't change anything at all but I no longer get that error when using the Javascript debug console - the tests start and it hits breakpoints. I can't think of anything that I'm doing differently to last night. Any ideas?

For info I don't currently have a launch config on my local machine currently because I was unable to get anything running properly and attaching to the debugger. However, the JavaScript debug terminal works fine with no lauch.json.

This is the contents of.vscode/launch.json:
`{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  "version": "0.2.0",
  "configurations": []
}`

You're right about the parallel yarn installs, thanks for the tip. I have just added `--mutex network` and pushed to the branch I'm currently working on: https://github.com/MeStrak/catkin/tree/test/e2e-test-fixes.

**Comment by svenefftinge** [comment] 2020-12-29 11:04
Ok, strange. I'll close this for now, as it is unclear what we can do about it. But please file a new issue when this happens again.

**Closed by svenefftinge** 2020-12-29 11:04 UTC
Labels: reporter-feedback-needed

**Comment by MeStrak** [comment] 2020-12-29 13:37
@svenefftinge I just went back to try this and had the same issue as last night:

![Screen Shot 2020-12-29 at 13 24 39](https://user-images.githubusercontent.com/31989238/103287347-353fbd80-49da-11eb-85ff-b79cac50895a.png)
_Same error message I saw last night in the JavaScript debug terminal._

I then closed and deleted the Gitpod workspace, and launched a new one from the same branch, added the .env file and it worked fine:
![Screen Shot 2020-12-29 at 13 29 37](https://user-images.githubusercontent.com/31989238/103287383-4d174180-49da-11eb-8561-59e3e004bffc.png)
_Working after recreating the workspace from the same branch (ignore the error message in the terminal - that's just part of the console logs)._

I will wait for the workspace to time out, then start it again to see if it could be related to that.

**Comment by MeStrak** [comment] 2020-12-29 17:43
I tried it again after a few hours but it still worked fine.

**Comment by empz** [comment] 2021-09-14 09:01
I'm having the same issue. After workspace is suspended, I go back to work on it and node/npm are broken.

Just typing `node` or `npm` in the shell throws that error.

More info here: https://community.gitpod.io/t/node-not-working-in-existing-workspace/4994/2
