### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by teroyks** [gitpod-io/gitpod#279] opened 2019-02-04 10:58 UTC
**Describe the bug**
Trying to log in with github for the first time fails

**To Reproduce**
- authorize gitpod
- check both "i agree to terms" and "send me email" checkboxes
- click the submit button

**Expected behavior**
log in to gitpod should happen. Instead gives a "this should not have happened" message.

Going back to the authorize screen and clicking the authorize button again seems to work around the issue.

**Comment by geropl** [comment] 2019-02-04 13:02
Hi teroyks,

I could not reproduce the issue with a fresh set of cookies and a new GitHub user. Therefore I'll close the issue. Please feel free to re-open with additional information ones it happens again.

**Closed by geropl** 2019-02-04 13:02 UTC
