### ISSUE TITLE
Error: build failed: rpc error: code = Internal desc = cannot create build volume: 

### ISSUE THREAD

**Issue by rholland** [gitpod-io/gitpod#1562] opened 2020-05-28 17:39 UTC
A simple latex template from your docs is failing to build with the immediate error:

```
Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: %!w(string=)
Please file an issue if you think this is a bug. 
```

Is a server down or a disk full as was reported in previous similar incidents?

**Comment by rholland** [comment] 2020-05-28 17:47
now it has started building.

**Comment by Kreyren** [comment] 2020-05-28 17:51
Concluded this being a duplicate of https://github.com/gitpod-io/gitpod/issues/1559

**Comment by rholland** [comment] 2020-05-28 17:51
everything works now

**Closed by Kreyren** 2020-05-28 17:51 UTC

**Comment by Kreyren** [comment] 2020-05-28 18:02
@rholland let me know if it breaks again, currently being tracked in #1559 ^-^
