### ISSUE TITLE
i am unable to conect to git lab i have even authorized my git hub account for use to gitlab but i don't know what's wrong with that?

### ISSUE THREAD

**Issue by Shreyansh252001** [gitpod-io/gitpod#2915] opened 2021-01-15 06:30 UTC

**Comment by akosyakov** [comment] 2021-01-15 08:18
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by akosyakov** 2021-01-15 08:18 UTC
