### ISSUE TITLE
Error: Cannot read property 'sha' of undefined

### ISSUE THREAD

**Issue by nico-abram** [gitpod-io/gitpod#643] opened 2019-07-01 12:29 UTC
When attempting to open https://gitpod.io/#https://github.com/nico-abram/rusty-boy-advance/ , I get the following: https://i.imgur.com/uBmFwI4.png

**Comment by nico-abram** [comment] 2019-07-01 12:32
I think the issue was I had `file: Dockerfile` and it was called `dockerfile`. However, a better error message would be nice.

**Comment by JesterOrNot** [comment] 2019-10-16 11:45
see #692

**Comment by jankeromnes** [comment] 2019-10-17 13:15
Ah, sorry about the misleading error message. I'm glad that you found the root cause anyway! 💯 

I'll close this issue, because the original problem was solved, and there is already #717 requesting a better error message.

**Closed by jankeromnes** 2019-10-17 13:15 UTC
Labels: bug, docker-build

**Comment by flamecopper** [comment] 2020-09-14 08:41
I just faced this issues today, has it been fixed? It has been over a year
