### ISSUE TITLE
Unable to export environment variable

### ISSUE THREAD

**Issue by HindujaVelupula** [gitpod-io/gitpod#11107] opened 2022-07-04 10:01 UTC
### Bug description

We want to configure vim editor in gitpod

### Steps to reproduce

1st approach: Add environment variable in .gitpod.Dockerfile in this way:
`ENV GIT_EDITOR=/usr/bin/vim` and open a workspace and check the GIT_EDITOR value
2nd approach: Add environment variable in .gitpod.yml file under tasks in this way:
```
tasks:
    env:
      GIT_EDITOR: /usr/bin/vim
```
open a workspace and check the GIT_EDITOR value

### Expected behavior

Configure Vim editor based on environment variable namely GIT_EDITOR.

**Comment by axonasif** [comment] 2022-07-06 08:30
Duplicate of https://github.com/gitpod-io/gitpod/issues/10958

**Closed by axonasif** 2022-07-06 08:30 UTC
Labels: type: bug
