### ISSUE TITLE
Cannot backup when trying to migrate from latest to 0.6.0-beta4

### ISSUE THREAD

**Issue by Lorac** [gitpod-io/gitpod#2875] opened 2021-01-13 04:21 UTC
### Describe the bug
I have a gitpod environment with self-hosted :latest tag docker image. When I try the latest beta tag 0.6.0-beta4. I am greeted with this:

```
docker run --rm -it \
    -v $PWD/gcloud:/root/.config/gcloud \
    -v $PWD/gpinstall:/workspace \
    eu.gcr.io/gitpod-io/self-hosted/installer:v0.6.0-beta4 \
    gcp
   Copying installation scripts
The version of the installer scripts has changed.
        old version: 0.5.0
        new version: v0.6.0-beta4

✔ {Backup existing files and continue with new version (recommended) 1}
!! 
!! cannot prepare the installation scripts:
!!      "cannot backup /workspace/gitpod to /workspace/backup/1610511301: rename /workspace/gitpod /workspace/backup/1610511301: permission denied"
!! 
```

### Steps to reproduce
Create a `:latest` workspace and try to migrate to `0.6.0-beta4`

### Expected behavior
It should not error out.

**Comment by csweichel** [comment] 2021-02-01 08:31
I'm not sure we can do anything else but err out here. If we cannot rename the directory, chances are we cannot write to it either. Also, we were just asked to create a backup, if we were to simply overwrite the previous files that would lead to confusion/frustration, too.

The only thing we could do is come up with a better error message. Due to the indirection caused by the volume mount that's not sensible though, because we could not provide a concrete path/command to act on but would have to refer to the directory as something like the "installation directory".

I'll close this issue for now, because there aren't many good alternatives how we could behave here.
If you disagree, please comment and re-open the issue.

**Closed by csweichel** 2021-02-01 08:31 UTC
Labels: component: install, type: bug
