### ISSUE TITLE
Hook when a workspace is destroyed

### ISSUE THREAD

**Issue by josepjaume** [gitpod-io/gitpod#9022] opened 2022-03-30 14:43 UTC
## Is your feature request related to a problem? Please describe
Our application hooks to some external services like Stripe that need us to use their API key to create a development user for each workspace. We'd like to have a hook when a workspace gets cleaned up so we can also clean up on Stripe.

## Describe the behaviour you'd like
The `.gitpod.yaml` allows a command to be called when an environment is getting destroyed, ideally with some secrets/variables that have been figured out at provisioning time. 

It could also be a simple webhook, but it definitely needs some kind of `id` that has been provided when starting the workspace (maybe via the `gp` command?).

## Describe alternatives you've considered
Just leaving data there, but it can grow unsustainable over time, particularly on a big company with many engineers. Mocking these services for development is also an option, but there's the risk of breaking the API and implementing wrong behavior.

## Additional context
None that's relevant.

**Comment by axonasif** [comment] 2022-03-30 15:03
Hey @josepjaume, this seems to be a duplicate of https://github.com/gitpod-io/gitpod/issues/3966. Could you please forward your use case there to bump that issue 🙏 ?

As a temporary workaround, you can save sensitive files anywhere other than `/workspace` and they will get automatically cleaned up. So for example, you can put a file as `$HOME/.myapi.json` on workspace start and symlink it back to somewhere inside `$GITPOD_REPO_ROOT/` for use if necessary, or you can just read from `$HOME` instead.

Now that's one way of doing this, another way of doing this would be to create a `tmpfs` storage inside `/workspace` which stays in RAM and will get automatically cleaned up on workspace shutdown _because RAM_.
```bash
dir="$GITPOD_REPO_ROOT/stripe"
mkdir -p "$dir" && sudo mount -t tmpfs stripevol "$dir"
```
Now everything you put on `stripe` dir will be lost on workspace shutdown since `tmpfs` is volatile, hope this helps in the meanwhile 😄

**Closed** 2022-04-05 16:35 UTC
