### ISSUE TITLE
Ports not opening

### ISSUE THREAD

**Issue by dunnry** [gitpod-io/gitpod#747] opened 2019-08-22 17:22 UTC
**Describe the bug**
After pulling the prebuilt environment, there is a startup command that starts Theia.  Normally, this prompts the user that a port is opened and asks to preview or open in browser.  This is not happening and a view of ports is not showing the port.

![image](https://user-images.githubusercontent.com/699725/63535500-96e74200-c4df-11e9-9d1f-8b8e28de44e5.png)

![image](https://user-images.githubusercontent.com/699725/63535534-aa92a880-c4df-11e9-887d-2aa22188cb9a.png)

**To Reproduce**
Please pull the master branch from our repository (TypeFox has this already).

**Comment by jankeromnes** [comment] 2019-08-22 20:27
Thanks a lot for reporting this issue! And sorry that this is not working properly.

At first I thought it looked similar to https://github.com/gitpod-io/gitpod/issues/742, but in your case even the "Open Ports" view is empty.

Something seems to be up with how we detect and handle port activity. We'll investigate and attempt to make this much more robust.

**Comment by svenefftinge** [comment] 2019-08-26 06:54
I believe this is due to the pressure we experienced on the message bus last week.
Do you see this reliably with one project, or was it happening once?

**Comment by AlexTugarev** [comment] 2019-08-27 09:41
I could reproduce it by restarting a timed out workspace and the Theia repo.

**Comment by svenefftinge** [comment] 2019-08-30 09:51
Closing this, as we haven't seen it happening again.

**Closed by svenefftinge** 2019-08-30 09:51 UTC

**Comment by josephflorian365** [comment] 2021-11-23 23:03
Why is the open ports widget not appearing in the gitpod IDE?

**Comment by akosyakov** [comment] 2021-11-24 09:33
@josephflorian365 Could you check remote explorer view please? We are talking about web version, right?
