### ISSUE TITLE
extensions: Don't override sync setting for an extension if installed before opening a repository with that extension on Gitpod workspace conig's vscode.extensions

### ISSUE THREAD

**Issue by ajhalili2006** [gitpod-io/gitpod#7363] opened 2021-12-26 13:39 UTC
## Is your feature request related to a problem? Please describe

When I add some of the extensions I use to `.gitpod.yml` on one repo and then creates a fresh workspace on another repo, some of these extensions are not installed due to `Sync This Extension` being unmarked when opening a repository with that extension on their configuration.

## Describe the behaviour you'd like

If a user has that extension installed BEFORE opening that repository with some of user's extensions on the `vsocde.extensions` list in the configuration YAML file, respect `Sync This Extension` setting for these extensions.

## Describe alternatives you've considered

You may need to manually tick that on every extension that got ignored by Gitpod Web due to extensions being mentioned on the config file, which is sometimes a painful chore to do.

## Additional context

N/A

**Comment by akosyakov** [comment] 2021-12-28 14:47
Could you clarify steps to reproduce:
- install golang extension as sync in some repo without .gitpod.yml
- open [gitpod-io/gitpod](https://github.com/gitpod-io/gitpod) which has golang in .gitpod.yml
- try to start another workspace on some repo without .gitpod.yml
  - expected that golang extension is installed, but it is not?

**Comment by ajhalili2006** [comment] 2021-12-29 12:03
I tried installing Golang extension on an existing workspace, leaving `Sync This Extension` option checked.

![photo_2021-12-29_12-47-08](https://user-images.githubusercontent.com/34998342/147639759-9405a9a8-2140-4d68-a8ae-b0377ec0a552.jpg)

Then created a fresh workspace using `github:gitpod-io/gitpod` where that extension is added to the Gitpod config, and confirmed that option is unchecked.

![photo_2021-12-29_12-47-03](https://user-images.githubusercontent.com/34998342/147639620-100dcc08-e626-40a0-8545-9a8854b0c293.jpg)

But when I created another fresh workspace without that extension in the config, it has `Sync This Extension` option checked.

![photo_2021-12-29_13-24-47](https://user-images.githubusercontent.com/34998342/147639725-179221ec-b6c5-4db4-a718-570447fe3ca0.jpg)

Maybe this is probably an accidental bug on the UI/Setting Sync backend/Gitpod config parser?

**Comment by ajhalili2006** [comment] 2021-12-29 12:04
I tried installing Golang extension on an existing workspace, leaving `Sync This Extension` option checked.

![photo_2021-12-29_12-47-08](https://user-images.githubusercontent.com/34998342/147639759-9405a9a8-2140-4d68-a8ae-b0377ec0a552.jpg)

Then created a fresh workspace using `github:gitpod-io/gitpod` where that extension is added to the Gitpod config, and confirmed that option is unchecked.

![photo_2021-12-29_12-47-03](https://user-images.githubusercontent.com/34998342/147639620-100dcc08-e626-40a0-8545-9a8854b0c293.jpg)

But when I created another fresh workspace without that extension in the config, it has `Sync This Extension` option checked.

![photo_2021-12-29_13-24-47](https://user-images.githubusercontent.com/34998342/147639725-179221ec-b6c5-4db4-a718-570447fe3ca0.jpg)

Maybe this is probably an accidental bug on the UI/Setting Sync backend/Gitpod config parser?

**Comment by akosyakov** [comment] 2021-12-29 12:31
> But when I created another fresh workspace without that extension in the config, it has Sync This Extension option checked.

It looks expected: If you install an extension like `sync` then it will be installed like sync in all your workspaces except which have configured it explicitly in .gitpod.yml

**Comment by akosyakov** [comment] 2022-01-07 09:58
Can be closed? I am still uncertain what is the bug. @jeanp413 could you have a look as well, not fixing, but help to understand the issue

**Comment by jeanp413** [comment] 2022-01-07 11:51
Yeah, I'll close it as it's the intended behavior as you explained.

> If you install an extension like sync then it will be installed like sync in all your workspaces except which have configured it explicitly in .gitpod.yml

**Closed by jeanp413** 2022-01-07 11:51 UTC
Labels: type: bug, meta: :thinking: reporter-feedback-needed, editor: code (browser), team: IDE
