### ISSUE TITLE
Sorry, something went wrong 😓 Authorization failed. Please try again. Please file an issue if you think this is a bug.

### ISSUE THREAD

**Issue by akkiee11** [gitpod-io/gitpod#2743] opened 2021-01-10 04:23 UTC

**Comment by akosyakov** [comment] 2021-01-10 06:23
Please go to gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of https://github.com/gitpod-io/gitpod/issues/2746 Please reopen if you did not try to login with GitLab account.

**Closed by akosyakov** 2021-01-10 06:23 UTC
