### ISSUE TITLE
gp open/preview should await till UI is available

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#4036] opened 2021-04-22 06:47 UTC
### Bug description

Otherwise they can break in tasks currently: https://community.gitpod.io/t/using-code-or-gp-open-in-start-tasks-fail-hard/3376

### Steps to reproduce

See above.

**Comment by svenefftinge** [comment] 2021-04-22 06:50
Do we want to have an explicit command that awaits a connection of a code editor and then also internally use it from the two mentioned commands?

**Comment by JanKoehnlein** [comment] 2021-06-03 13:55
Do we want to block on opening editors until the IDE is ready? This could be problematic when misused in non-interactive scenarios (like `init` in prebuilds). I'm not sure if we'd rather want an `async-open` command that retries than force blocking. Can we detect whether we run in a prebuild?

The `code` CLI connects to the Gitpod code server via REST. The CLI would have to retry until the server is up and an IDE client has connected. But we could also add that retry logic for all CLI commands that delegate to the server. Should we?

**Comment by akosyakov** [comment] 2021-06-07 03:51
Maybe we can detect that we are in prebuild context and fail then.

**Comment by apolopena** [comment] 2021-06-15 06:31
I believe this issue also happens intermittently when calling `gp preview` and that that error message has changed (as a result of resolving issue https://github.com/gitpod-io/gitpod/issues/3195) from:
`error while issuing request: Post "http://localhost:23000/gitpod/cli": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`
to something about a `404` error.  I am unable to reproduce the exact error message at the moment since it is an intermittent issue. I will update this post then the bug resurfaces.

**Closed** 2021-06-28 12:29 UTC
Labels: component: gp cli, feature: tasks, type: bug
