### ISSUE TITLE
Unable to launch workspace

### ISSUE THREAD

**Issue by kunxin-chor** [gitpod-io/gitpod#3523] opened 2021-03-21 14:54 UTC
### Bug description

Launching a workspace is stuck in loading Docker images.

### Steps to reproduce

Click on the green Gitpod button to launch workspace

**Comment by jankeromnes** [comment] 2021-03-22 09:25
Thanks for reporting this incident! Duplicate of https://github.com/gitpod-io/gitpod/issues/3515

**Closed by jankeromnes** 2021-03-22 09:25 UTC
