### ISSUE TITLE
Prebuild logs are hanging

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2165] opened 2020-11-12 10:13 UTC
When running a prebuild (e.g. http://gitpod-staging.com/#prebuild/https://github.com/gitpod-io/spring-petclinic) the logs are pushed to the frontend but eventually there are no more updates.

Reloading the page enabled this again for a bit before it again stops to update.

**Comment by akosyakov** [comment] 2020-11-14 13:46
It is caused by disconnects to the server:
<img width="1904" alt="Screenshot 2020-11-14 at 14 44 46" src="https://user-images.githubusercontent.com/3082655/99148452-fce15b80-2687-11eb-8519-82986df51a93.png">

It would be addressed in: https://github.com/gitpod-io/gitpod/pull/2173 

But it is not clear to my why the server is dropping connections each 30 seconds on good network.

**Comment by akosyakov** [comment] 2020-11-16 09:58
Staging load balancer was misconfigured, but https://github.com/gitpod-io/gitpod/pull/2173 is still required.

**Comment by akosyakov** [comment] 2020-11-19 07:47
closed by https://github.com/gitpod-io/gitpod/pull/2173

**Closed by akosyakov** 2020-11-19 07:47 UTC
Labels: bug, prebuilds, staging
