### ISSUE TITLE
Fresh workspace, but out of diskspace

### ISSUE THREAD

**Issue by dhavalmshah** [gitpod-io/gitpod#1043] opened 2020-01-02 06:05 UTC
**Describe the bug**

I cannot do anything because the server is out of disk space. This is a fresh workspace, and this should not happen!

**To Reproduce**

1. Navigate to https://d5ae0d9d-208c-46ce-a84b-aa881b504f16.ws-ap01.gitpod.io/
2. Try to create a directory in terminal under /workspace

**Expected behavior**

The directory should get created

**Additional Information**

![image](https://user-images.githubusercontent.com/9105352/71653707-f5f17900-2d53-11ea-9b5c-f2a1f801af70.png)

**Comment by Seniru** [comment] 2020-01-02 07:07
I also got a similar error. But I think it has been fixed now. Check #1044

**Comment by svenefftinge** [comment] 2020-01-02 12:14
duplicate of #1044

**Closed by svenefftinge** 2020-01-02 12:14 UTC
