### ISSUE TITLE
Ports detecting

### ISSUE THREAD

**Issue by farrelleoin93** [gitpod-io/gitpod#4022] opened 2021-04-20 17:12 UTC
### Bug description

Hey, 
I am having an issue where the ports are just detecting. 
![ports](https://user-images.githubusercontent.com/70948100/115437244-dbbb0300-a203-11eb-82d7-a872e8cfb9d2.JPG)

### Steps to reproduce

I have tried reloading the browser but it hasn't helped. Any advice would be appreciated

**Comment by corneliusludmann** [comment] 2021-04-21 08:11
Thanks for the report. Does it still happen?

For investigating this case we need your workspace ID (part of the URL).

**Comment by akosyakov** [comment] 2021-04-21 08:26
duplicate of https://github.com/gitpod-io/gitpod/issues/3160

**Closed by akosyakov** 2021-04-21 08:26 UTC
Labels: feature: ports, meta: :thinking: reporter-feedback-needed
