### ISSUE TITLE
Adding SQL Databases

### ISSUE THREAD

**Issue by patlecat** [gitpod-io/gitpod#432] opened 2019-04-05 15:23 UTC
Would be nice to have also a way to use DBs since they are often closely intertwined in applications and can't be simply switched on or off!

**Comment by svenefftinge** [comment] 2019-04-05 20:06
You can have installed DBs through your Docker image. We are going to prepare some examples for mysql and postgresql within the next days/weeks.

**Comment by meysholdt** [comment] 2019-04-06 14:55
here is a work-in-progress example for MySQL in Gitpod:
https://github.com/meysholdt/laravel-apache-mysql-php-in-gitpod-example

This blog post from @geropl shows how to use Postgres in Gitpod:
https://medium.com/gitpod/bring-your-own-docker-image-to-gitpod-52db1aa861de

**Comment by jankeromnes** [comment] 2019-04-06 16:52
I'm creating an auto-building Docker image [here](https://github.com/gitpod-io/workspace-images/pull/80) that will give you a PostgreSQL environment by simply using this in your project's `.gitpod.yml`:

```yaml
image: gitpod/workspace-postgres
```

It should even auto-start the server, and just work without you having to worry about starting it or connecting to it.

**Comment by teirureddo** [comment] 2019-04-12 09:39
https://github.com/teirureddo/envinits-gitpod-php

**Comment by alesanchezr** [comment] 2019-05-17 19:17
But I cannot use the psql command line tool with this.

![Screen Shot 2019-05-17 at 3 12 28 PM](https://user-images.githubusercontent.com/426452/57950996-e30a6100-78b6-11e9-9659-f06d680d60d8.png)

**Comment by jankeromnes** [comment] 2019-05-18 09:44
@alesanchezr Hi! We now also have a `gitpod/workspace-postgres` Docker image.

You can use it in your project by adding this to your `.gitpod.yml`:

```yaml
image: gitpod/workspace-postgres
```

And then you'll be able to use `pg_start`, `pg_stop` and `pg_ctl status`:

```bash
$ pg_ctl status
pg_ctl: no server running

$ pg_start
waiting for server to start.... done
server started

$ pg_ctl status
pg_ctl: server is running (PID: 1758)
```

(Also, in theory, PostgreSQL server should auto-start every time you open a terminal, so you shouldn't have to worry about that.)

(FYI, this image is used by the [dev.to project](https://github.com/thepracticaldev/dev.to/).)

**Comment by hamza0867** [comment] 2019-06-04 16:46
@jankeromnes Hi! so all we need to do is add a .`gitpod.yml` file to the repo with the content: 
`image: gitpod/workspace-postgres` , and it will give us the pg_start ...etc commands ??

**Comment by jankeromnes** [comment] 2019-06-04 19:26
Hi @hamza0867, yes that is correct! Gitpod will automatically detect the `.gitpod.yml` file at the root of your repo, so it will use the specified image (postgres), and then your workspace should have all the right commands. :)

Please let me know if can help you with that or if it doesn't work.

**Comment by hamza0867** [comment] 2019-06-04 21:15
@jankeromnes If you try [this repo](https://github.com/hamza0867/gitpod-yaml-config) for example (it is an empty repo with just a .gitpod.yml file) then it doesn't have the pg_start ... etc commands, only pg_config is available

**Comment by jankeromnes** [comment] 2019-06-05 08:25
Hi @hamza0867, oh, that's unfortunate. 😐 I'm not quite sure what's going wrong, because when I try [your repo](https://gitpod.io/#https://github.com/hamza0867/gitpod-yaml-config), I do get a `pg_start` command:

```bash
gitpod /workspace/gitpod-yaml-config $ which pg_start
/home/gitpod/.pg_ctl/bin/pg_start

gitpod /workspace/gitpod-yaml-config $ pg_start
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start.... stopped waiting
pg_ctl: could not start server
Examine the log output.

gitpod /workspace/gitpod-yaml-config $ pg_ctl status
pg_ctl: server is running (PID: 676)
/usr/lib/postgresql/10/bin/postgres "-D" "/home/gitpod/.pg_ctl/data" "-k" "/home/gitpod/.pg_ctl/sockets"
```

Could you please share a Snapshot of the workspace where you don't have a `pg_start`? (You can create one by clicking the top-right Avatar.)

**Comment by hamza0867** [comment] 2019-06-05 09:12
Hi @jankeromnes , you are correct it is working now. I guess it just takes it some time to install all dependencies ?? However when I hit `psql` I get
`psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?`
knowing that I already called pg_start (and it shows it is running on port 5432 ). 
Am I doing something wrong ? 

Thank you so much @jankeromnes for your help. I deeply appreciate it

**Comment by jankeromnes** [comment] 2019-06-05 09:26
No problem. 😄 I'm very happy to help out, and I'd love to make sure that SQL databases work great in Gitpod.

It's good news that you now have a `pg_start` command! (Note: When you configure a repository to use a different Docker image, your Gitpod workspace will not "live-reload", so you have to create new workspaces for the changes to take effect. Maybe that's what caused the missing `pg_start`.)

> However when I hit `psql` I get `psql: could not connect to server`

Oops, that issue I was able to reproduce. It seems that by default, `psql` will try to connect via a Unix socket, which doesn't work in our unprivileged PostgreSQL install.

The correct command to connect to the db is:

```
psql -h localhost -d postgres
```

I expect that many people will run into this issue. Maybe there is a way to make `psql` work out of the box in Gitpod? I'll investigate.

**Comment by jankeromnes** [comment] 2019-06-05 09:37
Ok, I found these two environment variables that seem helpful:

```
$ export PGHOSTADDR="127.0.0.1"
$ export PGDATABASE="postgres"
$ psql
psql (10.8 (Ubuntu 10.8-0ubuntu0.18.10.1))
Type "help" for help.

postgres=#
```

I'll try to set them to the correct values by default in the [`gitpod/workspace-postgres` image](https://github.com/gitpod-io/workspace-images/blob/master/postgres/Dockerfile). Thanks a lot for the feedback! 😄

**Comment by hamza0867** [comment] 2019-06-05 12:29
@jankeromnes What if I wanted to add monogodb to my workspace as well. Do I need to write a custom Dockerfile to support it or can I just put something in my .gitpod.yml to make it work ??

**Comment by jankeromnes** [comment] 2019-06-05 12:39
@hamza0867 unfortunately, we don't yet have a custom image for MongoDB, so you'd have to write a custom Dockerfile implementing [MongoDB's Ubuntu installation instructions](https://hevodata.com/blog/install-mongodb-on-ubuntu/).

For inspiration, here are [all our custom Dockerfiles](https://github.com/gitpod-io/workspace-images/). I guess the most challenging part will be to make the MongoDB service run as the `gitpod` user without requiring `sudo`.

If you run into any trouble along the way, please let me know, I'm happy to collaborate on this. 😄

**Comment by hamza0867** [comment] 2019-06-05 12:40
@jankeromnes Thanks man. You're awsome

**Comment by hamza0867** [comment] 2019-06-05 18:42
Hi @jankeromnes ! I wrote a Dockerfile that installs mongodb to the system however when I launch the `mongod` command, I get the following error:
 `exception in initAndListen: IllegalOperation: Attempted to create a lock file on a read-only directory: /data/db, terminating`
knowing that in my Dockerfile I already have `RUN sudo chown mongodb:mongodb -R /data/db` .
But it appears as it has no effect since running `ls -al /data/db` gives the following results:
`drwxr-xr-x 1 mongodb mongodb 4096 Jun  5 17:23 .
drwxr-xr-x 1 root    root    4096 Jun  5 17:23 ..`
How can I give the right privileges to make mongod work ?? 
 You can test it on [the same repo](https://github.com/hamza0867/gitpod-yaml-config)

**Comment by meysholdt** [comment] 2019-06-05 19:18
Can you try to run `mongodb` as user `gitpod` and have `RUN sudo chown gitpod:gitpod -R /data/db`?

**Comment by jankeromnes** [comment] 2019-06-05 19:22
@hamza0867 cool progress! Thank you for sharing. 😄

So, unfortunately, you can't use `sudo` or root privileges in Gitpod (well, you can in the Dockerfile, but no longer once a workspace is running). This also means that you can't run commands as another user than `gitpod`, i.e. the `mongodb` command will run as the `gitpod` user and not the `mongodb` user.

I think you have two options here:

1. Use `RUN sudo chown gitpod:gitpod -R /data/db` in your Dockerfile

2. Or configure the `mongodb` command (e.g. with an env variable, or a command line argument, or a configuration file) to use a different data directory, e.g. under `/home/gitpod/.mongodb`

**Comment by hamza0867** [comment] 2019-06-05 19:29
@meysholdt @jankeromnes Yes I can confirm that it is working now with changing ownership of  `/data/db`  to `gitpod:gitpod` maybe we can add a mongodb setup to the gitpod workspaces like the one with postgres ??

**Comment by jankeromnes** [comment] 2019-06-06 09:09
Excellent news! Many thanks for powering through this! 💯

And actually yes, we'd love to have a MongoDB setup in [gitpod/workspace-images](https://github.com/gitpod-io/workspace-images/). 😮 Would you like to make a pull request?

**Comment by hamza0867** [comment] 2019-06-06 10:32
@jankeromnes I just created a pull request for that purpose. You can check it out

**Comment by meysholdt** [comment] 2019-06-11 07:05
We now have MySQL, Postgres, Mongo...I think the original intention of this issue is satisfied. Closing.

Thank you @hamza0867 for your contribution!

**Closed by meysholdt** 2019-06-11 07:05 UTC

**Comment by josuecarames** [comment] 2019-12-02 19:42
Fantastic, thank you all for this great job!

**Comment by alesanchezr** [comment] 2019-12-02 20:05
Yeah, it's all working.
