### ISSUE TITLE
Workspace stuck building image

### ISSUE THREAD

**Issue by M-E-C-20** [gitpod-io/gitpod#5009] opened 2021-07-29 15:02 UTC
### Bug description

The workspace is stuck trying to open and appears to be stuck at the building image stage.

![image](https://user-images.githubusercontent.com/69533668/127515940-f293946e-f525-4a83-87db-9764911f8ab0.png)

### Steps to reproduce

Open a workspace in gitpod.

### Expected behavior

Should open to workspace.

**Comment by jankeromnes** [comment] 2021-07-29 15:12
Thanks for reporting this problem @M-E-C-20! And sorry that this is affecting you.

Closing as a duplicate of https://github.com/gitpod-io/gitpod/issues/5005 -- see also [this comment](https://github.com/gitpod-io/gitpod/issues/5005#issuecomment-889207141).

**Closed by jankeromnes** 2021-07-29 15:12 UTC
