### ISSUE TITLE
Run task on Shutdown

### ISSUE THREAD

**Issue by karpa** [gitpod-io/gitpod#13468] opened 2022-09-29 18:11 UTC
## Is your feature request related to a problem? Please describe
Large (in terms of file count and GB) workspaces are slow to open.
 
## Describe the behaviour you'd like
We would like to have the ability to delete files and data on shutdown, in order to have faster workspaces on open.
i.e add a 'shutdown' task like the 'command' task https://www.gitpod.io/docs/references/gitpod-yml#tasksncommand

## Describe alternatives you've considered
We would like to have the ability to delete files and run commands that will reduce the size of the workspace on shutdown.
We can restore or regenerate the files deleted on workspace open (like cache, compiled css, static html files etc)

## Additional context
The task should be run either on manual shutdown or automatic shutdown due to inactivity.

**Comment by csweichel** [comment] 2022-09-30 12:54
Thank you for opening this issue.
It does look like a duplicate of https://github.com/gitpod-io/gitpod/issues/3966.

Please feel free to reopen if you disagree.

**Closed by csweichel** 2022-09-30 12:54 UTC
