### ISSUE TITLE
High error rate on 'openPort'

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#13239] opened 2022-09-23 11:39 UTC
The last week we regularly see nigh rates on the `openPort` API call. Things that seem to happen:
 - client (IDE) calls `api.openPort`
 - `server` talks to `ws-manger`
 - `ws-manager` at some point returns error codes `RESOURCE_EXHAUSTED` and `DEADLINE_EXCEEDED`
 - client does retry

This leads to these questions:
 - What is the root cause for `DEADLINE_EXCEEDED`?
 - Could it be that `RESOURCE_EXHAUSTED` is a sign for clients to re-try too often (rate limited)? :thinking:

**Comment by kylos101** [comment] 2022-09-23 22:26
[High rate](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22sum%28rate%28grpc_server_handled_total%7Bservice%3D%5C%22gitpod-ws-manager%5C%22,%20grpc_method%3D%5C%22ControlPort%5C%22%7D%29%29%20by%20%28cluster,%20grpc_code%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D):
![image](https://user-images.githubusercontent.com/1272076/192064653-6df927cd-59ba-4af2-9a2f-5e7f529d0e47.png)

**Comment by easyCZ** [comment] 2022-09-24 21:54
<img width="1608" alt="Screenshot 2022-09-24 at 23 50 33" src="https://user-images.githubusercontent.com/1419286/192119862-151bd8a0-1893-48ab-bf77-40bf4597b837.png">

The above shows requests (and failures with codes) across our systems. Most notably, `WorkspaceManager.ControlPort` is returning ResourceExhausted. 

This is caused by our own rate-limiter - [dashboard](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22sum%28increase%28grpc_server_rate_limiter_calls_total%5B1m%5D%29%29%20by%20%28cluster,%20rate_limited%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%221663731751654%22,%22to%22:%221663773068505%22%7D%7D)

<img width="1595" alt="Screenshot 2022-09-24 at 23 53 36" src="https://user-images.githubusercontent.com/1419286/192119938-85ab4ae6-dad9-46fc-bddb-b9efc4d3c702.png">

**Comment by easyCZ** [comment] 2022-09-24 22:01
Because we use go-grpc-middleware on our gRPC clients, [we'll automatically retry](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/retry/options.go#L19) `ResourceExhausted` requests. This is the root cause of the `DEADLINE_EXCEEDED` - each request has a maximum deadline and because we retry (and keep getting ResourceExhausted), we reach the context deadline.

**Comment by easyCZ** [comment] 2022-09-24 22:46
Each time this issue occurs, there's also a [spike in ETCD errors](https://grafana.gitpod.io/d/dxEjpXn4z/grpc-client?orgId=1&from=1663738229888&to=1663763966058&var-service=etcdserverpb.KV&var-service=etcdserverpb.Lease&var-service=etcdserverpb.Maintenance&var-service=etcdserverpb.Watch&var-method=All&var-type=All):
<img width="1603" alt="Screenshot 2022-09-25 at 0 45 46" src="https://user-images.githubusercontent.com/1419286/192121187-1b0210f4-9961-4e95-9a40-ddb08f4cbabc.png">

**Comment by easyCZ** [comment] 2022-09-24 22:49
Interestingly enough, it looks like the `ws-manager` does not seem to have any explicit rate limiting config. However, from the metrics, [it looks like the rate limit is set to 100 per minute per method](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22sum%28increase%28grpc_server_rate_limiter_calls_total%5B1m%5D%29%29%20by%20%28cluster,%20rate_limited%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%221663731751654%22,%22to%22:%221663773068505%22%7D%7D). Where is this defined?

**Comment by kylos101** [comment] 2022-09-24 23:43
:wave: @easyCZ where were you looking at `ws-manager` where you didn't see related config? I assume webapp cluster or a preview environment?

Here is the ControlPort config in `eu68`:

```
gitpod /workspace/gitpod (main) $ kubectx -c
eu68
gitpod /workspace/gitpod (main) $ kubectl describe cm ws-manager | grep ControlPort -A 30
      "/wsman.WorkspaceManager/ControlPort": {
        "block": true,
        "bucketSize": 5,
        "refillInterval": "1s"
      },
```

We configure [here](https://github.com/gitpod-io/ops/blob/299ad451d1ef5d67ad5c15412786aaea665dd557/deploy/workspace/installer-values.yaml#L29-L32) via installer settings.

**Comment by kylos101** [comment] 2022-09-25 00:08
@easyCZ let us know if you need any support from the Workspace Team? For now I'm going to leave it in the inbox, but if you need help next week please reach out to @aledbf . :pray:

**Comment by easyCZ** [comment] 2022-09-25 19:09
Thanks @kylos101, I was indeed looking at `ws-manager` in the WebApp clusters. I'll separately try to follow-up why it's in the WebApp clusters if that's not the instance being used.

Current hypothesis is that this issue is due to natural increase in traffic on EU clusters over time. It could be compounded by the nature of "engineers beginning their work at the time of the incident and thus starting more instances and going over the rate limit.

I am digging into the behaviour of the rate limiter to understand the behaviour and be able to assess if increasing the rate limit is in fact the fix, or it would only be a bandage on the underlying problem. I'll keep posting updates in this issue.

**Comment by kylos101** [comment] 2022-09-25 20:31
@easyCZ :+1: :+1: 

> I'll separately try to follow-up why it's in the WebApp clusters if that's not the instance being used.

I believe `ws-manager` is in WebApp cluster because we have `image-builder-mk3` there. As a expected effect, that gives us the ability to see image builds in webapp clusters on the [grafana dashboard](https://grafana.gitpod.io/?orgId=1&refresh=5m&var-datasource=VictoriaMetrics&var-cluster=All).

> Current hypothesis is that this issue is due to natural increase in traffic on EU clusters over time. It could be compounded by the nature of "engineers beginning their work at the time of the incident and thus starting more instances and going over the rate limit.

Good point. Our peek concurrent workspaces has been quite high lately. 

We might be able to create a means to test this in a preview environment by (1) configuring the `ws-manager` rate limit for ControlPort and (2) using [loadgen](https://github.com/gitpod-io/gitpod/tree/main/dev/loadgen) to run many workspaces that have tasks to expose ports using the `gp`. A config to start with might be [this one](https://github.com/gitpod-io/gitpod/blob/main/dev/loadgen/configs/workspace-preview-benchmark.yaml).

> I am digging into the behaviour of the rate limiter to understand the behaviour and be able to assess if increasing the rate limit is in fact the fix, or it would only be a bandage on the underlying problem. I'll keep posting updates in this issue.

:heart: thank you! I spoke with @csweichel earlier in the week, and if I recall correctly, the flow is `ide` -> `supervisor` -> `server` -> `ws-manager` -> `ws-proxy` (instructing `ws-proxy` to expose the port via an annotation).

**Comment by easyCZ** [comment] 2022-09-26 13:49
I've dug a bit deeper into this and I've got the following observations:

There is a very direct correlation between a WebApp deployment and requests to `openPort`. After a rollout, when clients re-connect, they seem to "verify that the correct ports are in fact open" - this results in increased calls to `openPort`.
<img width="3280" alt="Screenshot 2022-09-26 at 15 41 07" src="https://user-images.githubusercontent.com/1419286/192291910-14de01df-96e0-4e42-abef-bd308286a93e.png">

Here, yellow are server connections, green are requests to `openPort`.

We can further correlate this against ETCD - 
<img width="3286" alt="Screenshot 2022-09-26 at 15 42 49" src="https://user-images.githubusercontent.com/1419286/192292403-c8115a10-1c7b-4a43-8608-8958dfde5dbd.png">

Blue is ETCD request latency.
Whenever there's a rollout, an increase in `openPort` results in increase in ETCD response latency.

If we now look at request success rate on ETCD (from the client side), we see an increase in Cancellations. This happens when the client gives up waiting for a response (presumably it took too long).
<img width="3277" alt="Screenshot 2022-09-26 at 15 45 09" src="https://user-images.githubusercontent.com/1419286/192292935-42e65351-931e-41ab-8d21-1b5b29d2fba9.png">


**Hypothesis**
Increase in requests which ultimately result in ETCD operations actually results in ETCD not handling the request volume in a timely manner and causing clients to Cancel. This in turn results in retry-backoff putting pressure on services again (`ws-manager`). 

Here, `ws-manager` actually does a good job rejecting requests which are above a rate limit (else it would bring down ETCD entirely). To fully confirm this, I'd like team Workspace to investigate the ETCD side of the cluster to understand how the cluster performed during this time-frame. CC @kylos101

**Comment by aledbf** [comment] 2022-09-26 14:28
@easyCZ the ETCD queries are from meta clusters?

**Comment by easyCZ** [comment] 2022-09-26 14:45
EU-67
```
sum(increase(grpc_client_handled_total{grpc_service=~"etcd.*", grpc_code!="OK"}[1m])) by (grpc_code, cluster)
```

**Comment by mustard-mh** [comment] 2022-09-27 08:21
We can also reduce num of `openPort` requests by change `supervisor` and `proxy` 's behavior

Open ports with private must be default behavior, we don't need to send openPort(private) requests

It (private) should be done in `proxy` component

**Comment by easyCZ** [comment] 2022-09-27 12:12
We're currently looking into how the backoff strategy works from the IDE <> Server side. @AlexTugarev is also exploring how we can better propagate context cancellations (client decides to give up) into the grpc call made against `ws-manager`. Both of these are short term fixes.

We need to understand what impact the current rate of calls has on the cluster level ETCD. We need to assess if increasing the `ws-manager` rate limit is actually a viable short-term fix, or if it risks putting client-level load directly against the cluster risking overloading ETCD.

Mid-term, we need to look at removing directly mapped calls from the client against the cluster - client calls shouldn't result in the same number of cluster level operations. To do this, we can introduce a control loop and sync the updates on our own schedule as opposed to having synchronous calls directly against the cluster.

**Comment by sagor999** [comment] 2022-09-27 22:34
I believe ETCD load is due to what `ControlPort` does internally: it lists pods (etcd operation), and then updates annotations on the pod if open port was changed (etcd operation). 

Is it possible that after webapp rollout there is an excessive influx of ControlPort calls that switch ports off and on again? Causing annotations churn on the pods? :thinking:

**Comment by easyCZ** [comment] 2022-09-30 14:36
For now we've not seen a recurrence. Closing for now and we can re-open if this makes a come-back.

**Comment by easyCZ** [comment] 2022-10-10 12:30
@aledbf Looks like the rate limit either did not work, was not sufficient, or was not the cause of this issue. We're still observing this.

@akosyakov Has the randomized backoff change been released?

**Comment by akosyakov** [comment] 2022-10-10 12:39
> @akosyakov Has the randomized backoff change been released?

yes

@mustard-mh has a PR to improve decrease expose attempts for private, but we did not have time to review it yet

**Comment by easyCZ** [comment] 2022-10-10 13:30
I'm also moving the WebApp deploy 15 minutes earlier to get a clearer signal between IDE and WebApp rollouts - [PR](https://github.com/gitpod-io/ops/pull/5787)

**Comment by akosyakov** [comment] 2022-10-10 13:44
> I'm also moving the WebApp deploy 15 minutes earlier to get a clearer signal between IDE and WebApp rollouts - https://github.com/gitpod-io/ops/pull/5787

fyi we already moved deployment to 12 CET. there is 2 hours delay.

**Comment by easyCZ** [comment] 2022-10-10 14:02
The updated rate limit looks to apply - we're seeing it at 72 per minute.

![Image](https://user-images.githubusercontent.com/1419286/194879639-fd237925-a47d-406a-97ff-dd1f57d665ed.png)

But we're still hitting it, and fairly regularly at 8.25 UTC.

I've adjusted the response codes from server to treat it as a 429 rather than a 500 [here](https://github.com/gitpod-io/gitpod/pull/13717)

**Comment by easyCZ** [comment] 2022-10-10 14:14
> fyi we already moved deployment to 12 CET. there is 2 hours delay.

Ah, didn't notice. Will close my change. Thanks!

**Comment by easyCZ** [comment] 2022-10-10 20:49
The linked issue https://github.com/gitpod-io/gitpod/pull/13449 looks super nice, it would remove the source of the requests and hence mitigate this issue 👀

**Comment by mustard-mh** [comment] 2022-10-12 10:08
Ports local expose works well so far [[grafana](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22sum%28rate%28grpc_client_handled_total%7Bgrpc_method%3D%5C%22ControlPort%5C%22,%20service%3D%5C%22gitpod-server%5C%22%7D%29%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-3d%22,%22to%22:%22now%22%7D%7D)]

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/20944364/195314844-138e42b2-1493-4f57-a287-e4d033fa4ed2.png">
(point to deploy time for PR #13449)

**Comment by akosyakov** [comment] 2022-10-13 08:02
Could be closed?

**Comment by easyCZ** [comment] 2022-10-13 08:04
Will close today after the critical time window just to have an extra day of validation.

**Comment by easyCZ** [comment] 2022-10-13 11:40
Pattern looks good. Closing.
<img width="2687" alt="Screenshot 2022-10-13 at 13 39 45" src="https://user-images.githubusercontent.com/1419286/195586860-5d1ed11a-abc8-4fc8-8b19-95c27e884444.png">

**Closed by easyCZ** 2022-10-13 11:40 UTC
Labels: type: incident, team: webapp, team: workspace, team: IDE, :question: clarification required
