### ISSUE TITLE
Gitpod to support `gp install`

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#1400] opened 2020-04-16 01:37 UTC
I would like to propose a new subcommand for the Gitpod CLI `gp install` this would take a path to a `*.vsix` file and install it. This would make working with VSCode extension development in Gitpod a bit easier.

**Comment by Kreyren** [comment] 2020-04-16 03:19
dup of https://github.com/gitpod-io/gitpod/issues/1097

**Comment by svenefftinge** [comment] 2020-04-17 06:47
Could you outline some concrete use cases to better understand this request?

**Comment by JesterOrNot** [comment] 2020-04-18 03:10
For Gitpodifying VSCode extensions

```yaml
tasks:
  - init: vsce package
    command: gp install *.vsix
```

Then contributors could open a workspace and then test the latest version of the extension

My current workflow is

1. `vsce package`
2. Go to explorer
3. Download vsix file
4. Open file explorer
5. open extensions view
6. drag and drop to install
7. Reload tab if need be

With `gp install` you could completely automate the building and testing of VSCode extensions in Gitpod.

**Comment by akosyakov** [comment] 2020-04-20 15:29
One can add `node` launch configuration similar to https://github.com/eclipse-theia/theia/issues/3251#issuecomment-468166533 then you go to `Debug` view and click run. At least till we don't support `extensionHost` target.

The stopper for it is to allow running VS Code extensions from source by Gitpod Theia. @svenefftinge Would it be fine to enable it?

**Comment by philschatz** [comment] 2021-03-13 00:16
Hello, I am helping write a VSCode extension specifically to run in gitpod. I tried adapting the instructions in https://github.com/eclipse-theia/theia/issues/3251#issuecomment-468166533 but was unable to get the breakpoints to work and the solution required using VNC (see [this PR](https://github.com/openstax/poet/pull/24)).

If the method mentioned above is not possible, do you have any suggestions for how to approach adding this feature? I am not familiar with go but could try a bit.

**Comment by akosyakov** [comment] 2021-03-15 07:40
Closing as a duplicate of https://github.com/gitpod-io/gitpod/issues/3166

It is not yet possible, but we are going to add ability to manage extension in March milestone.

**Closed by akosyakov** 2021-03-15 07:40 UTC
Labels: component: gp cli, type: feature request
