### ISSUE TITLE
Docker development in gitpod?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1199] opened 2020-02-07 10:43 UTC
Seems that it is not possible to get docker deamon running on gitpod

```console
gitpod /workspace/Zernit $ docker run hello-world
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```

### Expected
Method to test `docker build` on gitpod for development of dockerfiles

### Example repository
https://github.com/RXT0112/Zernit/tree/7d0a5f609288a271cf5ca80d706022b5e31693f4

**Comment by JesterOrNot** [comment] 2020-02-07 12:40
Closing as duplicate of #52 @Kreyren Please leave any suggestions/help there! 😄

**Closed by JesterOrNot** 2020-02-07 12:40 UTC
