### ISSUE TITLE
Network issues do not fail gracefully

### ISSUE THREAD

**Issue by apolopena** [gitpod-io/gitpod#3983] opened 2021-04-16 18:28 UTC
### Bug description

20+ minutes stuck on Opening IDE should just not happen. A timeout and a true error message on the page should be displayed.
![image](https://user-images.githubusercontent.com/3060702/115068298-efcecf80-9ea6-11eb-96ab-3bb7fff69b08.png)

### Steps to reproduce

Intermittant but happening almost daily during the workday here on the West Coast of the US.

### Expected behavior

A standard timeout on network issues. A true error message on the webpage after a certain amount of time for all types of network failures.

### Example repository

Any

**Comment by jankeromnes** [comment] 2021-04-16 18:33
Indeed, that's an excellent point, thanks @apolopena!

I believe this is caused by the Start page not handling network interruptions, so this is likely a duplicate of https://github.com/gitpod-io/gitpod/issues/3811 and already fixed in `main`. The fix should go live with the next regular deployment.

**Closed by jankeromnes** 2021-04-16 18:33 UTC

**Comment by jankeromnes** [comment] 2021-04-16 18:35
> Intermittant but happening almost daily during the workday here on the West Coast of the US.

This doesn't sound so good though. Are you really observing this symptom near-daily? Any other recurring errors or network issues?

**Comment by ArthurSens** [comment] 2021-04-16 18:43
> > Intermittant but happening almost daily during the workday here on the West Coast of the US.
> 
> 
> 
> This doesn't sound so good though. Are you really observing this symptom near-daily? Any other recurring errors or network issues?

I can confirm that too, it has been like that in the last 2 days as well 😕

**Comment by apolopena** [comment] 2021-04-16 18:51
Yeah just this week is been  but it there have been weekly intermittant network issues for months.
I noticed the time of these issues often happen 8:00pm-10:30 PDT or around 10:30am PDT

**Some of the symptoms are**:

- 503 errors when building a workspace image (almost always gone in 30 minutes)
- Cannot build workspace image: `Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: %!w(string=)`
- Really slow CPU. 5 minute builds taking 10 or 12 minutes.
- Prompt in the IDE asking to reconnect

**Comment by apolopena** [comment] 2021-04-16 18:53
I feel that if an issue has not been deployed and tested live then it should not be closed.
