### ISSUE TITLE
some theme extensions (monokai++)  are not enabling in new workspace. (resetting back to default vscode theme in new workspace)

### ISSUE THREAD

**Issue by AnudeepGunukula** [gitpod-io/gitpod#5427] opened 2021-08-28 08:45 UTC
### Bug description

extensions like monokai++ and some theme extensions are not showing as installed in new workspace.

even after making monokai++ as default in the settings also it is resetting to vscode default theme after opening new workspace.

while installing theme it is showing it is globally enabled but after opening new workspace, for 2 sec it is showing
monokai++ theme and then it is resetting back to vscode default theme.

### Steps to reproduce

kindly make sure that all the extensions are enabled globally and activate all extensions.
and the new workspace gets the theme and settings of the old workspace.

### Expected behavior

once theme is installed and set as default, make sure all the workspaces follow the same theme.
so that no need to install that theme extension every time we open a workspace.

**Comment by akosyakov** [comment] 2021-08-30 04:36
duplicate of https://github.com/gitpod-io/gitpod/issues/5405

**Closed by akosyakov** 2021-08-30 04:36 UTC

**Comment by AnudeepGunukula** [comment] 2021-08-30 06:09
Hi , its good to know that this issue has already raised.
Thankyou @akosyakov

**Comment by akosyakov** [comment] 2021-08-30 06:16
sorry linked the wrong issues, it should be https://github.com/gitpod-io/gitpod/issues/4520
