### ISSUE TITLE
[monaco-diff] diff isn't computed/rendered

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#2129] opened 2020-11-05 08:46 UTC
<img width="2007" alt="Screen Shot 2020-11-05 at 09 43 10" src="https://user-images.githubusercontent.com/914497/98218033-90f64900-1f4b-11eb-912d-e80e86eda818.png">
<img width="1904" alt="Screen Shot 2020-11-05 at 09 43 25" src="https://user-images.githubusercontent.com/914497/98218039-918edf80-1f4b-11eb-805d-bc37338b7888.png">

/cc. @akosyakov, this might be already known?

**Comment by akosyakov** [comment] 2020-11-05 08:50
duplicate of https://github.com/gitpod-io/gitpod/issues/2061

**Closed by akosyakov** 2020-11-05 08:50 UTC
Labels: bug, staging
