### ISSUE TITLE
Unable to see workspaces 

### ISSUE THREAD

**Issue by kunxin-chor** [gitpod-io/gitpod#3547] opened 2021-03-23 04:01 UTC
### Bug description

Going to the Workspaces page results in no workspaces shown, when logged in via Github

### Steps to reproduce

Click on the workspaces page

### Expected behavior

Able to see workspaces

**Comment by mai1015** [comment] 2021-03-23 04:30
same here, cannot even login

**Comment by suipingooi** [comment] 2021-03-23 04:31
same. again!

**Comment by meysholdt** [comment] 2021-03-23 07:59
duplicate of https://github.com/gitpod-io/gitpod/issues/3548. Apologies for the trouble.

**Closed** 2021-03-23 08:01 UTC
