### ISSUE TITLE
Move project from one team to another

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#14133] opened 2022-10-24 15:20 UTC
## Is your feature request related to a problem? Please describe

We created a Gitpod project in my company's team. Now it's time to handoff the project to the client, but I cannot give the client access to our company's Gitpod team. 

## Describe the behaviour you'd like

MVP - I would like to have the option to move project from one team to another, where I am an owner in both teams.

Even better - choose a project I would like to move, which will create a link I can send to a client. That way, I don't have to be part of the team that is receiving the project.

## Describe alternatives you've considered

Manually contacting Gitpod support every time we need to handoff a project.

## Additional context

Seems like it should be part of the recent change in #2934 and #14035

**Comment by gtsiolis** [comment] 2022-10-24 15:46
Thanks, @shaal! Closing this as a duplicate of https://github.com/gitpod-io/gitpod/issues/7101.

I guess, the MVP you described is usually the common approach for this.

See also https://github.com/gitpod-io/gitpod/issues/7101#issuecomment-1289234164 as a workaround:

> Until we ship this feature, 🅰️ removing the project from the initial team or 🅱️ deleting the initial team first can make the project available to be added in any other team.

Looping in @jldec for visibility.

**Closed by gtsiolis** 2022-10-24 15:46 UTC

**Comment by jldec** [comment] 2022-10-26 19:14
### 💡 ⚡  
Thanks @shaal, I really like the suggestion of generating a URL for "here-is-your-gitpod-project".
