### ISSUE TITLE
iPad (white bar) viewport bug - VSCode in the Browser

### ISSUE THREAD

**Issue by vultuk** [gitpod-io/gitpod#15447] opened 2022-12-20 21:01 UTC
### Bug description

When opening a repository in the Browser based version of VSCode a white bar is shown at the bottom of the screen when the 'shortcuts' bar is active and not minimized. This takes up a lot of screen space which could be better used and also is very bright when coding in dark mode. The issue presents as per the screenshot below.

![32F28708-FF98-4493-9E72-F9E9D65025FC](https://user-images.githubusercontent.com/271838/208763520-57379bdf-860c-4446-864f-0cf00c4f2fd0.png)

When minimizing the shortcut bar the white bar vanishes, as per this screenshot

![E07B788A-9517-49BA-94C4-85DF57A2D054](https://user-images.githubusercontent.com/271838/208763631-64a953a2-a671-4424-a970-abf6a030038f.png)

However, this introduces another issue where it is impossible to scroll any of the windows using Mouse wheel or trackpad meaning that the shortcut bar ideally needs to stay open. (The shortcut bar issue has been mentioned before in issue #6814 however this issue appears to have been deleted.)

### Steps to reproduce

- Turn on the shortcuts bar (Settings -> General -> Keyboards -> 'Shortcuts')
- Open any repo in the browser based version of VSCode using GitPod
- Ensure the Shortcuts bar is not minimized

### Expected behavior

When working in the browser based version of VSCode the full page should be used and a white bar shouldn't appear at the bottom of the screen.

Here are two screenshots (using the same repository) from the GitHub Codespaces version of VSCode who appear to have corrected the issue recently.

![46C1E926-6372-4F16-8394-9346B4FA2726](https://user-images.githubusercontent.com/271838/208764618-b837c30c-ed2e-44e9-b91a-e2031f5fc8f8.png)

![1877004B-B726-4FEE-94D3-91CC9CEB7333](https://user-images.githubusercontent.com/271838/208764632-b18e3670-d83a-46a7-b87c-dbe2f802caae.png)

As a note, the mouse wheel / touchpad scroll bug still persists in GitHub Codespaces.

### Anything else?

- https://github.com/microsoft/vscode/issues/149048
Here is a link to the github issue on the vscode repo, although the issue is still open it appears as if GitHub themselves have fixed the issue.
- https://bugs.webkit.org/show_bug.cgi?id=247410
This is a link found on the previous link to a webkit bug someone has submitted

**Comment by akosyakov** [comment] 2023-02-01 16:24
@vultuk Is it the same with latest version. You can enable in: https://gitpod.io/preferences

**Comment by vultuk** [comment] 2023-02-02 14:41
@akosyakov Yes it is unfortunately. Just tested it now. I've been set on `latest` since switching to the ipad on the hope that it would get fixed there first. ;)

![78989710-852C-45EB-8A8C-8F3533EF4C4B](https://user-images.githubusercontent.com/271838/216354998-8f9b4b16-574b-4c8c-aaa5-3bfc42d10d6c.png)

**Comment by filiptronicek** [comment] 2023-03-07 18:18
I have taken a look with an `iPad Pro 12.9`: both the 2021 and the 2022 version. I could not reproduce this, but I figure it is because I could not open the Shortcuts bar (I assume you need an external keyboard for that). I will try to get a hold of one and try to reproduce tomorrow. 

Without an external keyboard the bar seems to never appear at least.

**Comment by filiptronicek** [comment] 2023-03-08 20:48
I can repro, it seems the only way to get around it is to disable Shortcuts. I am not sure how Codespaces could have fixed it, because I would assume they would commit it to https://github.com/microsoft/vscode. [I asked about it](https://github.com/microsoft/vscode/issues/149048#issuecomment-1460854042).

![image](https://user-images.githubusercontent.com/29888641/223842013-0be43818-56bd-45da-9da5-c27e7f85d25b.png)

**Comment by jeanp413** [comment] 2023-05-27 04:27
Fixed in insiders, will be available next stable release

**Closed by jeanp413** 2023-05-27 04:27 UTC
Labels: type: bug, editor: code (browser), team: IDE
