### ISSUE TITLE
[desktop] workspace timeouts if you close the browser tab prematurely

### ISSUE THREAD

**Issue by dragonDScript** [gitpod-io/gitpod#7057] opened 2021-12-03 14:14 UTC
### Bug description

If you open a workspace in vscode and immediately close the tab it won't let you to connect.

### Steps to reproduce

1. Open a workspace.
2. Open the workspace in VSCode. When vscode is open and prompts you to "Continue", close the gitpod tab.
3. See error.

### Expected behavior

Workspace should open no matter if the tab is open or closed.

### Example repository

Any repo is valid

### Anything else?

See the discord for more info

**Comment by akosyakov** [comment] 2022-01-17 12:47
It is going to be a problem for all desktop apps. Maybe we should avoid sending close event from ready screen if desktop app was opened. Or have a special one.

**Comment by dragonDScript** [comment] 2022-01-17 15:20
> It is going to be a problem for all desktop apps. Maybe we should avoid sending close event from ready screen if desktop app was opened. Or have a special one.

Probably just vscode, due to how it works.

**Comment by dragonDScript** [comment] 2022-04-19 11:40
don't stale

**Comment by loujaybee** [comment] 2022-06-28 10:40
Thanks for raising @dragonDScript, I think this issue is a duplicate of: 

- https://github.com/gitpod-io/gitpod/issues/10373

Please watch that one for updates, we're actively looking into this one currently.

**Closed by loujaybee** 2022-06-28 10:40 UTC
Labels: type: bug, component: supervisor, team: IDE, editor: jetbrains, editor: code (desktop), feature: timeout
