### ISSUE TITLE
`jq` error on opening new workspace: some object and `null (null) cannot be multiplied`

### ISSUE THREAD

**Issue by david-bakin** [gitpod-io/gitpod#12850] opened 2022-09-10 01:00 UTC
### Bug description

Opened a workspace.  This workspace has no `.gitpod.yml` nor `.gitpod.Dockerfile` in the branch being opened.  However, on opening:

1. There are both a `.gitpod.yml` and `.gitpod.Dockerfile` in the repo at top-level.
2. terminal window for `Gitpod Task 1: bash` shows:
    ```
    jq: error (at /workspace/.vscode-remote/data/Machine/.tmp:0): object ({"python.de...) and null (null) cannot be multiplied
    ```

Also:

Not my `.gitpod.yml`:
```
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install AWScli
    init: |
      apt install curl apt-transport-https ca-certificates --yes 
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
      unzip awscliv2.zip 
      ./aws/install

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6080
    onOpen: open-browser
```

Not my `.gitpod.Dockerfile`:
```
# You can find the new timestamped tags here: https://hub.docker.com/r/gitpod/workspace-full/tags
FROM gitpod/workspace-full:latest

# Install custom tools, runtime, etc.
RUN sudo apt-get update

# Install apt-transport-https
RUN sudo apt-get install apt-transport-https ca-certificates gnupg software-properties-common curl --yes

# RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
# RUN unzip awscliv2.zip
# RUN sudo ./aws/install

# Add the gcloud CLI distribution URI as a package source
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

# Import the Google Cloud public key.
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

# Install the gcloud CLI
RUN sudo apt-get update && sudo apt-get install google-cloud-cli

RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

RUN sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

RUN sudo apt-get update && sudo apt-get install terraform
```

### Steps to reproduce

Open workspace.  Observe error in terminal window.

### Workspace affected

bakinsbits-gitpodsetupf-2d3fkhpggxz on https://gitlab.com/bakins-bits/gitpod-setup-for-bitcoin-core-dev/-/tree/test-dockerfile

**Comment by axonasif** [comment] 2022-09-10 04:09
Hey @david-bakin, I just opened your repo but I don't see this error :eyes:
Can you try again?

**Comment by david-bakin** [comment] 2022-09-10 04:27
I just got it again on a new open (via the gitpod button on the repo)!  But I also had opened it a little earlier and didn't get it.  So it seems intermittent.

**Comment by axonasif** [comment] 2022-09-10 05:01
I opened it twice right now to recheck, if you spot it again, do share.
A fix for that issue was pushed https://github.com/gitpod-io/workspace-images/pull/922. Sometimes your workspace might use a cached `workspace-full` image since it hasn't been long, so using `#imagebuild` helps.

**Comment by david-bakin** [comment] 2022-09-10 05:02
ok, but this is a new workspace with a new .gitpod.yml referencing workspace-python:latest.  I mean, I only started using it on this branch of the repo tonight - even the branch is new tonight.

**Comment by axonasif** [comment] 2022-09-11 14:57
Closing this as it's a duplicate of https://github.com/gitpod-io/workspace-images/issues/925
If you notice it again, please feel free to comment here.

**Closed by axonasif** 2022-09-11 14:57 UTC
Labels: type: bug
