### ISSUE TITLE
no basic auth credentials

### ISSUE THREAD

**Issue by vickybiswas** [gitpod-io/gitpod#2056] opened 2020-10-24 14:26 UTC
### Describe the bug
Cannot create or start Workspace

### Steps to reproduce
Create or start a workspace

### Expected behavior
start thea

### Additional information
Sorry, something went wrong 😓
Error: Request createWorkspace failed with message: 13 INTERNAL: cannot resolve workspace image: Error response from daemon: Head https://060260394319.dkr.ecr.us-east-1.amazonaws.com/v2/workspace-images/manifests/835c95423ec4d3254bb7fa41910686e75630a97a4b74f8cc9accb9d01a8d4841: no basic auth credentials

### Example repository
Any

**Comment by corneliusludmann** [comment] 2020-10-26 09:24
Could you please provide more information about your setting? Is it a self-hosted installation or gitpod.io?

**Comment by corneliusludmann** [comment] 2020-10-26 09:25
Is it a duplicate of #2055?

**Closed** 2020-10-28 14:58 UTC
Labels: duplicate, reporter-feedback-needed
