### ISSUE TITLE
Regarding Gitlab

### ISSUE THREAD

**Issue by Jassi10000** [gitpod-io/gitpod#2898] opened 2021-01-14 06:40 UTC
### Describe the bug

https://gitpod.io/#https://gitlab.com/crio-bytes/me_http 
This is the link am trying to visit and after authorizing my Github to Gitlab also , its showing the error (Authorization failed)

### Expected behavior

The link should work properly as this is the part of a competition and gitlab  and gitpod should work smoothly

**Comment by svenefftinge** [comment] 2021-01-14 06:49
This is a duplicate of #2746

**Closed by svenefftinge** 2021-01-14 06:49 UTC
