### ISSUE TITLE
.gitpod.yml not read, Custom Docker container not created

### ISSUE THREAD

**Issue by alxmhe** [gitpod-io/gitpod#4967] opened 2021-07-27 09:20 UTC
### Bug description

I am unable to bootstrap my workspace with an initial setup from a Dockerfile.
When editing my fairly simple `.gitpod.yml`, I have this error:
```
Unable to load schema from 'https://gitpod.io/schemas/gitpod-schema.json': No content.
```

Here is the file :
```
image:
  file: .gitpod.Dockerfile

tasks:
  - init: yarn && yarn storybook

ports:
  - port: 6006
    onOpen: open-preview
```

Tasks and ports configurations are also not read, so I believe the problem would be with the `.gitpod.yml` file.

### Steps to reproduce

Clone repository from Github, add a .gitpod.yml and .gitpod.Dockerfile, terminate workspace, launch workspace.
The instructions in the Dockerfile are not used to bootstrap the workspace.

### Expected behavior

.gitpod.yml should be used to configure the workspace on boot.

**Comment by pawlean** [comment] 2021-07-27 12:52
Can you share your .Dockerfile as well? Or your repo where this is happening? Another user also brought this up recently:&nbsp;<a href="https://community.gitpod.io/t/error-loading-a-docker-file/4304" target="_blank" rel="noopener noreferrer">https://community.gitpod.io/t/error-loading-a-docker-file/4304</a>

**Comment by alxmhe** [comment] 2021-07-27 17:14
Sorry I'm unable to share this private repository. I tried deleting the workspace and recreating it from scratch but the issue is still there.

Here is the `.gitpod.Dockerfile` file :
```
FROM gitpod/workspace-full

RUN sudo apt-get update && \
    sudo apt-get install -y \
        ca-certificates \
        fonts-liberation \
        libappindicator3-1 \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libc6 \
        libcairo2 \
        libcups2 \
        libdbus-1-3 \
        libexpat1 \
        libfontconfig1 \
        libgbm1 \
        libgcc1 \
        libglib2.0-0 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libpango-1.0-0 \
        libpangocairo-1.0-0 \
        libstdc++6 \
        libx11-6 \
        libx11-xcb1 \
        libxcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxext6 \
        libxfixes3 \
        libxi6 \
        libxrandr2 \
        libxrender1 \
        libxss1 \
        libxtst6 \
        lsb-release \
        wget \
        xdg-utils && \
    sudo rm -rf /var/lib/apt/lists/*
```

**Comment by alxmhe** [comment] 2021-07-27 17:16
Here is a screenshot of the error mentioned above.

<img width="847" alt="Screenshot 2021-07-27 at 19 16 17" src="https://user-images.githubusercontent.com/6876954/127198758-2ef1bf47-7efd-4947-bf31-1e67f54b5fa9.png">

**Comment by alxmhe** [comment] 2021-07-27 17:18
Also, sometimes, but rarely, the error is not displayed, the schema (gitpod-schema.json) is parsed (I can open it), but the Dockerfile is still not executed on workspace creation.

**Comment by apolopena** [comment] 2021-07-28 06:19
I get this error too
![image](https://user-images.githubusercontent.com/3060702/127273533-36fb0abe-92dc-46be-a114-a8c804f0b8c4.png)

**Comment by alxmhe** [comment] 2021-07-28 11:50
This repository, for example, also has the error.
https://github.com/laboiteadons/laboiteadons/tree/feature/gitpod
You may need to close and reopen the workspace to trigger the error.

**Comment by alxmhe** [comment] 2021-07-28 11:55
I see the container is building correctly when starting Gitpod with this repository. Maybe the problem comes from .gitpod.yml and .gitpod.Dockerfile not being committed to git before.
Although, I often need these files to stay out of the repository.

**Comment by alxmhe** [comment] 2021-07-28 11:58
Nope, on second opening the issue persists. Which mean you should be able to reproduce the bug now.

**Comment by pawlean** [comment] 2021-07-28 14:43
Ah yes, I see this as well. Thanks @alxmhe! I've flagged this as a bug, our engineering team will be notified here :)

**Comment by akosyakov** [comment] 2021-08-03 05:09
Hm, I cannot reproduce. Just to clarify:
- you do changes to .gitpod.yml
- you commit and push them (without this step your changes won't be applied)
- you start a new workspace and it fails to start, correct?

**Comment by alxmhe** [comment] 2021-08-03 07:52
Two ways I triggered this bug (with the classic way of configuring .gitpod.yml).

1. Clone a repo, create the .gitpod.yml file, do not commit it (maybe because it's not my repo), restart container, .gitpod.yml is not read.

2. Clone a repo with a .gitpod.yml already configured (it's versioned!), the workspace seems to be created correctly, close the workspace, reopen the workspace, .gitpod.yml is not read.

**Comment by csweichel** [comment] 2021-08-03 09:46
> Clone a repo, create the .gitpod.yml file, do not commit it (maybe because it's not my repo), restart container, .gitpod.yml is not read.

That's expected behaviour. Gitpod will only ever read a `.gitpod.yml` (w.r.t. to the image used for the workspace) from the repository. I.e. changing the image in `.gitpod.yml` in a running workspace, and restarting that workspace will not see the `image` change applied.
Note: this is by design. Workspaces remain "stable" across restarts.

Regarding 2: I've tried to reproduce the behaviour using https://github.com/laboiteadons/laboiteadons/tree/feature/gitpod. As expected the correct image was used after a workspace restart.

I suspect the failure to load the schema was due to a minor service interruption during deployment.

Considering we cannot reproduce the issue, I'll close this for now. Please re-open when the issue re-occurs.

**Closed by csweichel** 2021-08-03 09:46 UTC
Labels: type: bug
