### ISSUE TITLE
random containers fails to start

### ISSUE THREAD

**Issue by jmls** [gitpod-io/gitpod#7294] opened 2021-12-17 16:01 UTC
### Bug description

when using docker in docker, we occasionally get a docker runtime error 

```
ERROR: for my-srv  Cannot start service my-srv: OCI runtime create failed: container_linux.go:380: starting container process caused: close exec fds: open /proc/self/fd: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```
The container affected constantly varies , and the containers run perfectly outside of a gitpod.io instance, so there is no issue with the container definition

### Steps to reproduce

cannot reproduce - doesn't always happen, and is always a random error when it does

### Workspace affected

any

### Expected behavior

I expect the containers to start without problem

### Anything else?

this always seems to be in the prebuild (init) section

**Comment by aledbf** [comment] 2021-12-18 16:08
> when using docker in docker, we occasionally get a docker runtime error

Please make sure the docker version in the workspace is `20.XX` and not `19.XX`.

**Comment by jmls** [comment] 2021-12-21 09:22
![image](https://user-images.githubusercontent.com/929523/146904820-cf4c5f97-8913-49fe-a933-6a9aba61bf79.png)

**Comment by jmls** [comment] 2022-01-11 10:00
bump .. hitting this error quite often now. Very frustratiing

**Comment by kylos101** [comment] 2022-01-12 02:40
Hi @jmls,

May we ask you to share the name of a workspace where you encountered this trouble? Also, if you could share a timestamp for approximately when it happened, both pieces of info would help us better search through logs and traces. 

Also, I realize it may not be possible, but if you're able to share a public repo where this issue can be reliably recreated, that would be super.

[It looks like you found a workaround](https://github.com/gitpod-io/gitpod/issues/5945#issuecomment-1009790674). Let us know if that workaround is okay for now? We've added this issue to our backlog, and will prioritize it as soon as possible.

**Comment by jmls** [comment] 2022-01-13 12:41
I just hit this issue on the workspace 

amethyst-junglefowl-k8ue6rec.ws-eu25.gitpod.io 

just before 

Thu 13 Jan 2022 12:39:08 PM UTC

I have left the workspace open . Two containers failed to start

 Cannot start service node-data: OCI runtime create failed: container_linux.go:380: starting container process caused: close exec fds: open /proc/self/fd: no such file or directory: unknown

**Comment by jmls** [comment] 2022-01-17 07:26
any further news on this ?

**Comment by kylos101** [comment] 2022-01-18 04:59
Hi @jmls yes, the info you shared helped me explore our logs and traces. :pray:  Unfortunately, I was unable to find meaningful data. :disappointed: 

We're actively researching this and #5945 :thinking: , and may end adding additional logging. 

If you'd be willing to [share a snapshot URL for a workspace](https://www.gitpod.io/docs/sharing-and-collaboration#sharing-snapshots) using our [support page](https://www.gitpod.io/contact/support), that would help us more reliably recreate the problem. Please don't share snapshot URLs here in Github, as the URL will grant folks access to those files.

CC: @csweichel and @utam0k

**Comment by jmls** [comment] 2022-01-18 07:17
will do

**Comment by csweichel** [comment] 2022-01-18 07:39
Probably a duplicate of https://github.com/gitpod-io/gitpod/issues/5945

**Comment by jmls** [comment] 2022-01-18 11:17
I have posted 2 instances of the problem we had this morning to the support pages

**Comment by csweichel** [comment] 2022-01-18 15:21
We just rolled out what we hope is a fix for this issue (#7657). I'll close this issue for now. Please re-open/file a new one if this problem persists.

**Closed by csweichel** 2022-01-18 15:21 UTC
Labels: meta: :thinking: reporter-feedback-needed, priority: highest (user impact), team: workspace

**Comment by jmls** [comment] 2022-01-18 16:33
oh ! excited ! when will this be live ? or is it already ? :)

**Comment by csweichel** [comment] 2022-01-19 06:44
It is live already :)
