### ISSUE TITLE
Unable to open workspace - I tried multiple times and I appear to have broken it!

### ISSUE THREAD

**Issue by Archierowe** [gitpod-io/gitpod#1595] opened 2020-06-11 14:49 UTC
### Describe the bug

OutOfmemory: Pod Node didn't have enough resource: memory, requested: 2254438400, used: 55585013760, capacity: 57639526400
Please file an issue if you think this is a bug.

**Comment by Archierowe** [comment] 2020-06-11 14:53
I thought the workspace was being slow - clicked several times to open the workspace and I appear to have broken it! Argh - please help!

**Comment by alesanchezr** [comment] 2020-06-11 15:15
the same, this is only in europe.

**Comment by Kreyren** [comment] 2020-06-11 15:19
Assuming duplicate of https://github.com/gitpod-io/gitpod/issues/1593

Ping me if it's unrelated

**Closed by Kreyren** 2020-06-11 15:19 UTC
