### ISSUE TITLE
registry-facade restart loop

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#13915] opened 2022-10-17 14:59 UTC
Incident: https://app.incident.io/incidents/251

Today we noticed a a high "workspace stop" failure rate. After initial investigation it quickly became clear that:
 - all failed workspace (stops) were on one node (`workspace-ws-us71-pool-nqc6`)
 - one of the symptoms was high CPU usage
 - new workspace would continue to be scheduled to that node (until we cordoned it), and those immediately failed and accounted for a rise in "failed stopped workspaces"
 - we checked the logs, and found that `registry-facade` was starting a restart cycle just before the failure rate starte to rise

GCloud logs of the first restart entry: [link](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-10-17T13:19:23Z;pinnedLogId=2022-10-17T13:19:23Z%2F1ielw13fje9587dm;query=resource.labels.cluster_name%20:%20%2528%22us71%22%2529%0A%22nqc6%22%0Atimestamp%3D%222022-10-17T13:19:23Z%22%0AinsertId%3D%221ielw13fje9587dm%22;summaryFields=jsonPayload%252Fstatus%252Fruntime%252Fnode_name,jsonPayload%252Fstatus%252Fconditions%252Ffailed:false:32:beginning;timeRange=2022-10-17T13:17:30.000Z%2F2022-10-17T13:19:45.000Z?project=workspace-clusters)

Definition of done:
1. Run [a couple tests](https://github.com/gitpod-io/gitpod/issues/13915#issuecomment-1286022638) to assert the happy and sad path for registry-facade's pre lifecycle hook.
2. Fix it if it's broken

**Comment by kylos101** [comment] 2022-10-18 14:12
[72](https://jaeger-us-prod.workspace-preview.gitpod-io-dev.com/search?end=1666097640000000&limit=1500&lookback=custom&maxDuration&minDuration&service=registry-facade&start=1665979200000000&tags=%7B%22error%22%3A%22true%22%7D) getBlob trace errors in registry-facade over last two days. Four pods  have restarted, two in the last 48 hours. Also, around the time of this incident, our success rate started to suffer (which makes sense, considering this caused workspace stop failures).

**Comment by kylos101** [comment] 2022-10-18 14:28
Seems like our `NetworkIsReachable` probe was having trouble resolving the GCR host when getting supervisor. [Logs](https://cloudlogging.app.goo.gl/tZH5B6xycEbGNH1b6)

The [log](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-10-17T13:18:52Z;pinnedLogId=2022-10-17T13:19:23Z%2F1ielw13fje9587dm;query=resource.labels.cluster_name%20:%20%2528%22us71%22%2529%0A%22workspace-ws-us71-pool-nqc6%22%0A%22registry-facade%22%0Atimestamp%3D%222022-10-17T13:18:37Z%22%0AinsertId%3D%22x200kgr94jhfqxr9%22;summaryFields=jsonPayload%252Fstatus%252Fruntime%252Fnode_name,jsonPayload%252Fstatus%252Fconditions%252Ffailed:false:32:beginning;timeRange=P2D?project=workspace-clusters) and error message:
`unexpected error checking URL https://eu.gcr.io/gitpod-core-dev/build/supervisor:commit-cb77bdffc2410a522a180bf4522f15548ae7caa3: Get "https://eu.gcr.io/gitpod-core-dev/build/supervisor:commit-cb77bdffc2410a522a180bf4522f15548ae7caa3": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

The log is firing from: `export.go:129`

This problem has existed since April ([error group](https://console.cloud.google.com/errors/detail/CPykpJaY7Oy_iQE?project=workspace-clusters))

Given [this error](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-10-17T13:19:23Z;pinnedLogId=2022-10-17T13:19:23Z%2F1ielw13fje9587dm;query=resource.labels.cluster_name%20:%20%2528%22us71%22%2529%0A%22workspace-ws-us71-pool-nqc6%22%0A%22registry-facade%22%0Atimestamp%3D%222022-10-17T13:19:02Z%22%0AinsertId%3D%22l4cax2kkdz401bot%22;summaryFields=jsonPayload%252Fstatus%252Fruntime%252Fnode_name,jsonPayload%252Fstatus%252Fconditions%252Ffailed:false:32:beginning;timeRange=P3D?project=workspace-clusters), it seems like a DNS issue, being caught by [our readiness probe](https://github.com/gitpod-io/gitpod/blob/90b737a16eda7d0b6f24f4cab6d029c713904ed6/components/registry-facade/cmd/run.go#L135).

**Comment by kylos101** [comment] 2022-10-18 14:30
It seems like this node fell for trap, where it'd recover, we'd use it some more, and then it'd fail again. 

@aledbf @sagor999 @jenting should we have a pattern where we taint a node, to avoid scheduling to it (so that the autoscaler removes it once workspaces are gone) regardless readiness? I'm curious to get your input, to help avoid this scenario in the future, so we can maximize our success rate.

It feels like we've had this issue in the past, where there was DNS flakiness with GCR.

**Comment by aledbf** [comment] 2022-10-18 14:40
> should we have a pattern where we taint a node, to avoid scheduling to it (so that the autoscaler removes it once workspaces are gone) regardless readiness?

That's what the node labeler does during the restart. Or do you want to refactor that to use taints?

> It feels like we've had this issue in the past, where there was DNS flakiness with GCR.

The component is not aware of where the issue is located. Could be the node, the network, or the endpoint itself. In any case we should not allow workspaces to land in the node.

> [72](https://jaeger-us-prod.workspace-preview.gitpod-io-dev.com/search?end=1666097640000000&limit=1500&lookback=custom&maxDuration&minDuration&service=registry-facade&start=1665979200000000&tags=%7B%22error%22%3A%22true%22%7D) getBlob trace errors in registry-facade over last two days. Four pods have restarted, two in the last 48 hours.**

We need to investigate what happened at the time

**Comment by kylos101** [comment] 2022-10-18 18:12
> That's what the node labeler does during the restart. Or do you want to refactor that to use taints?

I don't want to refactor, per say. Sorry, I should have been more clear. I was suggesting as a means to permanently stop scheduling to a node, say for example if it consistently goes on and offline, while other nodes remain healthy.

> The component is not aware of where the issue is located. Could be the node, the network, or the endpoint itself.

oooo, really good points. I had my goggles on, and was only focusing on the individual node. But you're right to consider the network and endpoint.

**Comment by sagor999** [comment] 2022-10-20 18:44
@aledbf correct me if I am wrong, but when registry facade pod starts up, it has a container for `node-labeler` that will add a label to the node when registry facade is up.
And then it will remove label when container is shutting down.
But I think it will not remove the label if registry facade container is crash looping though, does it? 
Which would be the case in this particular case, where registry facade is initially up, but then starts crash looping after some time, yet the label on the node is still present and we end up scheduling workspaces on it. WDYT?

**Comment by kylos101** [comment] 2022-10-20 19:17
[The ready-probe-labeler is a binary run by a Kubernetes life cycle hook.](https://github.com/gitpod-io/gitpod/blob/c46250a72e1aa4c5cf24c359a29fe167d9cb2094/install/installer/pkg/components/registry-facade/daemonset.go#L317-L319)

We need to prove it runs (or not) on a crash loop of registry-facade.

[This](https://github.com/kubernetes/kubernetes/issues/93818#issuecomment-729584956) mentions that on an OOMKill, the pod is killed immediately, so as a result the life cycle hook would not run, potentially leaving the node in a state where we can assign workspace pods to it.

**Comment by kylos101** [comment] 2022-11-12 05:49
Similar trouble in `us75`:
```
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"lookup eu.gcr.io on 10.30.0.10:53: dial udp 10.30.0.10:53: i/o timeout","file":"probes.go:64","func":"func1","host":"eu.gcr.io","level":"error","message":"NetworkIsReachableProbe: unexpected error resolving host","serviceContext":{"service":"registry-facade","version":"commit-c9528c8c3ef22757646a623898c4e7d01975edf8"},"severity":"ERROR","time":"2022-11-12T04:54:33Z"}
```

**Comment by scasei** [comment] 2022-11-17 07:18
Any news here? Have the same error on my cluster. My workaround is to edit the replicaset and have higher timeout values. Is it possible, that google has some thing of firewall and blocks some IPs?

**Comment by scasei** [comment] 2022-11-17 18:35
@msiegenthaler thanks, this fixes it for me also

**Comment by kylos101** [comment] 2022-11-28 13:39
@utam0k what do you think of [this test](https://github.com/gitpod-io/gitpod/issues/13915#issuecomment-1286022638)? Are you able to share test results? :pray:

**Comment by utam0k** [comment] 2022-11-28 23:35
> @utam0k what do you think of [this test](https://github.com/gitpod-io/gitpod/issues/13915#issuecomment-1286022638)? Are you able to share test results?

OOMKill of the registry-facade process did not delete the label on the node. The logic is simple: node-labeler only runs the label operation once at startup.
I plan to change this so that node-labeler periodically checks the state of the registry-facade.

**Comment by utam0k** [comment] 2022-11-28 23:37
and when I ran deleting pod via kubectl, the node label was deleted.

**Comment by aledbf** [comment] 2022-11-28 23:40
> I plan to change this so that node-labeler periodically checks the state of the registry-facade.

The labels are removed when the pod stops during the [PreStop Lifecycle](https://github.com/gitpod-io/gitpod/blob/e34c6d6a285f61aef7edfc7a1bacc9711c93b4d2/install/installer/pkg/components/registry-facade/daemonset.go#L314)

**Comment by utam0k** [comment] 2022-11-28 23:52
> > I plan to change this so that node-labeler periodically checks the state of the registry-facade.
> 
> The labels are removed when the pod stops during the [PreStop Lifecycle](https://github.com/gitpod-io/gitpod/blob/e34c6d6a285f61aef7edfc7a1bacc9711c93b4d2/install/installer/pkg/components/registry-facade/daemonset.go#L314)

@aledbf 
If only the registry-facade container is deleted, this PreStop won't run, right? Couldn't that happen? I would love to know because I have OOM'd the process directly and am a little unsure myself if this can happen.

**Comment by kylos101** [comment] 2022-11-29 01:03
> I would love to know because I have OOM'd the process directly and am a little unsure if this can happen.

There are two tests [here](https://github.com/gitpod-io/gitpod/issues/13915#issuecomment-1286022638). The result of the 2nd test will help us understand if, when `registry-facade` is OOMKill'd, if the prestop lifecycle hook is triggering or not. 

@utam0k can you run both tests to assert the outcome? If the hook is not working on OOMKill, please share the input and output of your test (maybe a Loom?) and block this issue. Why? If prestop hook is not working, we'll need to socialize solutions. In other words, right now, you should just be trying to assert the behavior of the Kubernetes prestop hook when a pod's container is oomkilled.

If it is working, the prestop will use curl successfully and you will see in server. If it is not working, the curl will never be sent, and from the server, you will not see a related connection.

**Comment by kylos101** [comment] 2022-11-29 01:05
@utam0k I moved this to 'in-progress`, as you are actively working. 👋

**Comment by utam0k** [comment] 2022-11-29 03:03
@kylos101 I made a video.
1. When I tried to delete a registry-facade **container**, the label was still present while the registry-facade was being restarted
2. In delete of pod from kubectl, the label was properly erased.
https://www.loom.com/share/a80dd056ca76427e830ae40b7510defa

So I will try to make node-labeler turn off the label if the container of registry-facade is restarted.

**Comment by kylos101** [comment] 2022-11-29 03:21
> So I will try to make node-labeler turn off the label if the container of registry-facade is restarted.

@utam0k do you mean, have the `node-labeler` component check readiness on some frequency, this way, it can intercept when `registry-facade` is in a bad state, and remove the label, to avoid scheduling? Assuming yes, that sounds logical.

**Comment by utam0k** [comment] 2022-11-29 03:24
> > So I will try to make node-labeler turn off the label if the container of registry-facade is restarted.
> 
> @utam0k do you mean, have the `node-labeler` component check readiness on some frequency, this way, it can intercept when `registry-facade` is in a bad state, and remove the label, to avoid scheduling? Assuming yes, that sounds logical.

Yes! That is correct. Thanks for checking with me.

**Closed** 2022-12-06 01:53 UTC
Labels: type: bug, component: registry-facade, type: incident, team: workspace
