### ISSUE TITLE
Unable to open workspace

### ISSUE THREAD

**Issue by CarterStefan** [gitpod-io/gitpod#3214] opened 2021-02-18 07:24 UTC
### Describe the bug
I am unable to open my workspace. At first it was saying "Error: 2 UNKNOWN: Channel Destroyed" 
Now, after a few attempts, I am getting "Error: 14 UNAVAILABLE: failed to connect to all addresses"

### Steps to reproduce
I go to workspaces and click 'open workspace'

### Expected behavior
AI expect my workspace to open.

### Additional information
purple-quail-85at856o

**Comment by CarterStefan** [comment] 2021-02-18 07:41
Update: I am now able to connect to and open my workspace

**Comment by jankeromnes** [comment] 2021-02-18 07:56
Hi @CarterStefan, many thanks for reporting this problem & for confirming the service works again!

FYI, this was related to an ongoing Gitpod incident currently being worked on: http://status.gitpod.io/incidents/90f9d190

We've put mitigations in place, so the service should be back to normal now.

Closing as duplicate of https://github.com/gitpod-io/gitpod/issues/3215

**Closed by jankeromnes** 2021-02-18 07:56 UTC
