### ISSUE TITLE
vsicons extension not working

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#818] opened 2019-09-30 16:50 UTC
**Describe the bug**
When installing the extension vsicons the icons don't change and this shows up in preferences
![image](https://user-images.githubusercontent.com/50386709/65898911-2fdb6980-e378-11e9-9d37-1aa9471eefb6.png)

**To Reproduce**
install this in gitpod
https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons
**Expected behavior**
icons change

**Comment by jankeromnes** [comment] 2019-10-01 07:48
Thanks for reporting this bug, @JesterOrNot! 🙏

VS Code extension support is being worked on in the [Theia IDE](https://github.com/eclipse-theia/theia) repository, so I've re-filed this issue as https://github.com/eclipse-theia/theia/issues/6300.

As you can see in the replies, the root cause is that Theia doesn't yet support VS Code theming: https://github.com/eclipse-theia/theia/issues/4831

**Comment by JesterOrNot** [comment] 2019-10-01 10:07
ok, should I close this issue?

**Comment by jankeromnes** [comment] 2019-10-01 10:27
Yes, thanks, I think that this should be tracked and resolved in the Theia repository. So I'll close this issue. 🙂

**Closed by jankeromnes** 2019-10-01 10:27 UTC
Labels: bug, theia, vscode

**Comment by jankeromnes** [comment] 2019-12-30 10:45
Update: This has been fixed in Theia: https://github.com/eclipse-theia/theia/pull/6475

Next we need to update Theia in Gitpod, and deploy to production again. This will likely happen in early January. 🎄
