### ISSUE TITLE
Custom ssh config is permanent

### ISSUE THREAD

**Issue by antunderwood** [gitpod-io/gitpod#7620] opened 2022-01-15 10:42 UTC
### Bug description

When opening a workspace on VS Code desktop the custom ssh config is changed permanently so that I can no longer access the ssh cofig at .ssh/config

![image](https://user-images.githubusercontent.com/423/149618839-b1c55612-7198-4a94-af52-7e8b0619343f.png)

### Steps to reproduce

Open a workspace in VS Code desktop

### Expected behavior

Custom ssh config is removed when the workspace is stopped

**Comment by akosyakov** [comment] 2022-01-15 10:46
duplicate of https://github.com/gitpod-io/gitpod/issues/5889

**Closed by akosyakov** 2022-01-15 10:46 UTC
