### ISSUE TITLE
Letters do not show up clearly on terminal.

### ISSUE THREAD

**Issue by xxkabasakalxx** [gitpod-io/gitpod#9350] opened 2022-04-15 11:58 UTC
### Bug description

Hi,
On my Gitpod ide (brave Browser) letters do not show up cleary on terminal, as you can see on below. How can i fix this problem.
Thank you for your attention.
Have a good day.

![Letters on termimal](https://user-images.githubusercontent.com/63397523/163568028-07a07e15-a726-41dd-96b4-bcea0b16f2e1.PNG)

### Steps to reproduce

![Letters on termimal](https://user-images.githubusercontent.com/63397523/163568164-9f466855-241c-4def-9505-5e73d6bfde92.PNG)

**Comment by jeanp413** [comment] 2022-04-18 20:22
duplicate of https://github.com/gitpod-io/gitpod/issues/5014
@xxkabasakalxx you can workaround it by disabling fingerprinting in `brave://settings/shields`

**Closed by jeanp413** 2022-04-18 20:22 UTC

**Comment by xxkabasakalxx** [comment] 2022-04-18 20:26
Thank you very much.
