### ISSUE TITLE
Error user deleting account

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/gitpod#5276] opened 2021-08-19 13:46 UTC
### Bug description

Received this from a user:

> Hi,
> I'm trying to delete my account, and there is a bug in the process, so I can't complete it.
> Web dev console error logs:
> 
> Uncaught (in promise) Error: Request deleteAccount failed with message:
> at main.js:449
> at main.js:276
> at main.js:260
> at setImmediate.js:40
> at f (setImmediate.js:69)
> at n (setImmediate.js:109)

I believe that they have now deleted their account as I can no longer see it, but I thought it was worth having this issue raised just in case it needs extra eyes on it.

### Steps to reproduce

Try to delete an account

### Expected behavior

Successfully deleting an account

**Comment by gtsiolis** [comment] 2021-08-19 13:48
Thanks @pawlean! 🐾 

Closing this as a duplicate of https://github.com/gitpod-io/gitpod/issues/5262, which is already scheduled in the engineering groundwork. Cc @JanKoehnlein

**Closed by gtsiolis** 2021-08-19 13:48 UTC
Labels: type: bug
