### ISSUE TITLE
[code] connection to the extension host suddenly breaks

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3797] opened 2021-04-07 07:47 UTC
I was coding along and after an hour or so, parts of the IDE (search, scm, open file) didn't work anymore.

Turned out the connection to the code server dropped and reconnection didn't work.
logs from the console:
```
 INFO [remote-connection][ExtensionHost][0759f…][reconnect] resolving connection...
log.ts:284  INFO [remote-connection][ExtensionHost][0759f…][reconnect] connecting to jade-toucan-3bgkxdet.ws-eu03.gitpod.io:443...
log.ts:284  INFO [remote-connection][ExtensionHost][0759f…][reconnect] A network error occurred while trying to reconnect, will try again...
log.ts:284  INFO [remote-connection][ExtensionHost][0759f…][reconnect] waiting for 30 seconds before reconnecting...
log.ts:284  INFO [remote-connection][ExtensionHost][0759f…][reconnect] resolving connection...
log.ts:284  INFO [remote-connection][ExtensionHost][0759f…][reconnect] connecting to jade-toucan-3bgkxdet.ws-eu03.gitpod.io:443...
log.ts:284  INFO [remote-connection][ExtensionHost][0759f…][reconnect] A network error occurred while trying to reconnect, will try again...
log.ts:284  INFO [remote-connection][ExtensionHost][0759f…][reconnect] waiting for 30 seconds before reconnecting...
log.ts:284  INFO [remote-connection][ExtensionHost][0759f…][reconnect] resolving connection...
log.ts:284  INFO [remote-connection][ExtensionHost][0759f…][reconnect] connecting to jade-toucan-3bgkxdet.ws-eu03.gitpod.io:443...
log.ts:284  INFO [remote-connection][ExtensionHost][0759f…][reconnect] A network error occurred while trying to reconnect, will try again...
log.ts:284  INFO [remote-connection][ExtensionHost][0759f…][reconnect] waiting for 30 seconds before reconnecting...
```

**Comment by akosyakov** [comment] 2021-04-07 07:48
probably related to https://github.com/gitpod-io/gitpod/issues/3370 if not a duplicate

**Comment by akosyakov** [comment] 2021-04-07 07:48
A workaround is to reload or open another page.

**Comment by akosyakov** [comment] 2021-04-08 08:20
I was able to reproduce it, by capturing WebSocket object to the extension host process from the heap snapshot and closing it. Handshake on the reconnection is broken. Looking into the fix. That’s really hard to reproduce otherwise, because if the connection is completely offline, VS Code treats it differently.

**Comment by akosyakov** [comment] 2021-04-08 12:20
We are going to deploy the fix tomorrow morning.

**Closed** 2021-04-08 12:19 UTC
Labels: editor: code, type: bug
