### ISSUE TITLE
Azure Git support

### ISSUE THREAD

**Issue by dragonDScript** [gitpod-io/gitpod#8620] opened 2022-03-05 16:30 UTC
## Is your feature request related to a problem? Please describe
I use Azure to store code. But I can't use gitpod with it.

## Describe the behaviour you'd like
Gitpod support for azure

**Comment by MrSimonEmms** [comment] 2022-03-06 16:29
Duplicate of #5321

**Closed by MrSimonEmms** 2022-03-06 16:29 UTC
Labels: type: feature request
