### ISSUE TITLE
VSCode Feature Preview doesn't install extensions in .gitpod.yml

### ISSUE THREAD

**Issue by Michaelhobo** [gitpod-io/gitpod#2530] opened 2020-12-14 13:20 UTC
### Describe the bug

I just enabled the vscode editor feature preview, and my extensions don't get installed.

Here's the extensions portion of my .gitpod.yml file

```yaml
vscode:
  extensions:
    - zxh404.vscode-proto3@0.4.2:ZnPmyF/Pb8AIWeCqc83gPw==
    - mhutchie.git-graph@1.26.0:m8EvA1owa1dL2R6+Swieyg==
```

Then I go to the extensions tab, and search mhutchie.git-graph, and I can still install it. No extensions are installed by default.

### Steps to reproduce

Enable Feature Preview, switch editor from theia to vscode, open a workspace from a repo with vscode extensions set in .gitpod.yml, and look at the extensions tab.

### Expected behavior

Extensions should be installed.

**Comment by akosyakov** [comment] 2020-12-14 13:34
It will be addressed by https://github.com/gitpod-io/gitpod/pull/2493

**Comment by Michaelhobo** [comment] 2020-12-14 13:36
awesome!

**Comment by akosyakov** [comment] 2020-12-16 12:14
resolved by https://github.com/gitpod-io/gitpod/pull/2493 but not deployed yet

**Comment by akosyakov** [comment] 2020-12-18 08:11
deployed

**Closed by akosyakov** 2020-12-18 08:11 UTC
Labels: bug, editor: code, fixed-not-deployed

**Comment by arctiqtim** [comment] 2021-02-03 14:19
Looks like this didn't resolve the issue with vscode installing extensions from .gitpod.yml ... I have extensions listed in this file and when starting up a workspace with Theia all is good and extensions are installed.  When starting up Code instead via feature preview, it is ignored and no extensions listed are installed.

**Comment by akosyakov** [comment] 2021-02-08 20:41
@arctiqtim Could you file a new bug report please and provide steps to reproduce? for instance reproducible repo

**Comment by arctiqtim** [comment] 2021-02-12 14:58
Actually it looks good.  It was a case where an existing workspace wasn't re-reading the .gitpod.yaml config
