### ISSUE TITLE
Theia don't start, upon start crashes with: We are having trouble parsing your context Error: Cannot read property 'Symbol(Symbol.iterator)' of undefined Please file an issue if you think this is a bug.

### ISSUE THREAD

**Issue by mjobuda** [gitpod-io/gitpod#2392] opened 2020-12-03 12:33 UTC
### Describe the bug
eclipse theia don't start

### Steps to reproduce
fork https://gitlab.com/owsikowski/gdates
start gitpod

### Expected behavior
eclipse theia should appear

**Comment by mjobuda** [comment] 2020-12-03 12:37
seems that for some reason this happens with all my projects!!

**Comment by svenefftinge** [comment] 2020-12-03 17:10
Hey @mjobuda,
we have fixed it already and can hopefully deploy in a few hours.

duplicate of https://github.com/gitpod-io/gitpod/issues/2382

**Closed by svenefftinge** 2020-12-03 17:10 UTC

**Comment by svenefftinge** [comment] 2020-12-03 17:13
For the time being there is a workaround https://github.com/gitpod-io/gitpod/issues/2382#issuecomment-738082051
