### ISSUE TITLE
Gitpod workspaces not loading 

### ISSUE THREAD

**Issue by amymaldonado** [gitpod-io/gitpod#3501] opened 2021-03-19 08:09 UTC
### Bug description

I am unable to access any of my workspaces on Gitpod. When I load the page it is completely blank. 

### Steps to reproduce

I tried logging in through github in Incognito mode and get "sorry something went wrong Error 504." I've also restarted my computer, tried logging in on another computers and same results. Github and Gitpod statuses say all systems are operational at the moment. 

### Expected behavior

I should see all my workspaces 

blank homepage 
![image](https://user-images.githubusercontent.com/77379122/111749656-77093300-8868-11eb-8207-8410cf45fdd3.png)

connection got disposed 
![image](https://user-images.githubusercontent.com/77379122/111749729-93a56b00-8868-11eb-8c17-d447e10b432b.png)

504 error
![image](https://user-images.githubusercontent.com/77379122/111749892-d404e900-8868-11eb-91c2-563d335829c4.png)

**Comment by amymaldonado** [comment] 2021-03-19 08:11
Oops I just saw that this was a recent incident in the previous issues

**Comment by jankeromnes** [comment] 2021-03-19 08:11
No worries, thanks for the report! Closing as duplicate of https://github.com/gitpod-io/gitpod/issues/3499

**Closed by jankeromnes** 2021-03-19 08:11 UTC
