### ISSUE TITLE
Ports not serving (detecting)

### ISSUE THREAD

**Issue by tembo84** [gitpod-io/gitpod#17445] opened 2023-04-29 15:24 UTC
### Bug description

I think there must have been an update to Gitpod recently that is effect my ports. They constantly are in a "detecting" state

### Steps to reproduce

I run "Docker-compose up" and the ports are not working

**Comment by axonasif** [comment] 2023-04-30 17:33
Hi @tembo84, is this still happening?

**Comment by tembo84** [comment] 2023-05-01 23:01
Yes, I am still experiencing these issues, please advise


Sent from Yahoo Mail for iPhone


On Sunday, April 30, 2023, 1:33 PM, AXON ***@***.***> wrote:




Hi @tembo84, is this still happening?

**Comment by axonasif** [comment] 2023-05-02 01:44
Ok, thanks for confirming.
I'm closing this as a duplicate of https://github.com/gitpod-io/gitpod/issues/17446

**Closed by axonasif** 2023-05-02 01:44 UTC
Labels: type: bug
