### ISSUE TITLE
The Gitpod website doesn't let me login to my account

### ISSUE THREAD

**Issue by RhuthuHegde** [gitpod-io/gitpod#2873] opened 2021-01-12 18:47 UTC

**Comment by csweichel** [comment] 2021-01-13 06:46
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by csweichel** 2021-01-13 06:46 UTC
