### ISSUE TITLE
Gitpod browser plugin - Bitbucket branch detection problem

### ISSUE THREAD

**Issue by adampapl** [gitpod-io/gitpod#5380] opened 2021-08-25 13:18 UTC
### Bug description

I'm getting Not Found error when trying to create gitpod workspace from bitbucket branches where branch name consists of two parts eg: 'feature/gitpod' while all works ok with simple branch names like 'develop'

![image](https://user-images.githubusercontent.com/213903/130797270-56a82064-3c2c-4f6b-bd6a-d775424f4fa1.png)

Creating branch from single commit from the same branch works (but workspace is created with git in detached state which is uncomfortable)

### Steps to reproduce

1. install gitpod browser extension
2. go to your bitbucket repository to specific branch (other than develop or master) eg: feature/gitpod
3. click gitpod button or gitpod extension icon
4. observe Not Found error
![image](https://user-images.githubusercontent.com/213903/130796669-4aac2534-62cb-4210-8fe1-ca47252af25b.png)

I'm getting error with example url:
https://gitpod.io/#https://bitbucket.org/contentportal/user-portal/branch/feature/gitpod

and strange thing is that all works nice with simple branch name like 'develop' branch:
https://gitpod.io/#https://bitbucket.org/contentportal/user-portal/branch/develop

### Expected behavior

Workspace should be created.

**Comment by gtsiolis** [comment] 2021-08-25 13:35
Thanks for catching this @adampapl! ⚾ 

It seems to be an issue with parsing branch names with `/` but only for repositories in Butbucket.

**Comment by gtsiolis** [comment] 2021-08-25 13:41
Oh, closing this as a duplicate of https://github.com/gitpod-io/gitpod/issues/5364. It seems a fix could be already underway in https://github.com/gitpod-io/gitpod/pull/5367. Cc @ghuntley

**Closed by gtsiolis** 2021-08-25 13:41 UTC
Labels: type: bug, git provider: bitbucket, feature: context awareness
