### ISSUE TITLE
Capitalising GitHub.com in context URL causes a Parse Context error

### ISSUE THREAD

**Issue by sujaikumar** [gitpod-io/gitpod#18564] opened 2023-08-21 15:57 UTC
### Bug description

If I visit this context URL, it works fine:

  https://gitpod.io/new/#https://github.com/bgacademy23/earlgrey

If I capitalise GitHub:

  https://gitpod.io/new/#https://GitHub.com/bgacademy23/earlgrey

I get this error:

> We're sorry, there seems to have been an error.
> Couldn't parse context 'https://GitHub.com/bgacademy23/earlgrey'.

![image](https://github.com/gitpod-io/gitpod/assets/136828943/c11ec016-5d99-4fa1-a0cd-38ad2e2a97c2)

### Steps to reproduce

1. Type a github.com context URL
2. Capitalise GitHub.com in the URL

### Workspace affected

ALL workspaces

### Expected behavior

1. Expect it to work the same as URL capitalisation should not matter

### Example repository

ALL repositories

### Anything else?

Chrome and Safari on Mac both had this problem

**Comment by gtsiolis** [comment] 2023-08-23 17:46
Nice catch, @sujaikumar. ⚾ 

I'm closing this as a duplicate of https://github.com/gitpod-io/gitpod/issues/8807.

**Closed by gtsiolis** 2023-08-23 17:46 UTC
Labels: type: bug, team: team-experience
