### ISSUE TITLE
Group avatars fail to load for GitLab groups

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5330] opened 2021-08-23 17:09 UTC
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/5120#discussion_r690467889, group avatars fail to load for GitLab groups. 🦊 

| Missing avatars on groups (a) | Missing avatars on personal accounts (b)|
|-|-|
| <img width="840" alt="Screenshot 2021-08-17 at 5 44 31 PM" src="https://user-images.githubusercontent.com/120486/129751165-38363e59-9b1a-4b19-9e12-0fe0aa05e33a.png"> | <img width="772" alt="Frame 34" src="https://user-images.githubusercontent.com/120486/129752105-ae42c776-e95f-4775-9efc-957f610f061e.png"> |

**Comment by roboquat** [comment] 2021-09-29 08:16
@svenefftinge: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5330#issuecomment-929947550):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by JanKoehnlein** [comment] 2021-09-30 11:35
Let's do this after the launch

**Comment by laushinka** [comment] 2021-10-01 09:44
Is this still happening? I tried with my personal account and I can see my avatar.
<img width="382" alt="Screenshot 2021-10-01 at 11 41 06" src="https://user-images.githubusercontent.com/8015191/135599872-00569677-3e15-4b0a-bf1d-0702cd280a59.png">
:

**Comment by gtsiolis** [comment] 2021-10-01 09:52
@laushinka Yes, this is still happening but only affects group avatars as described in the issue! You can add more groups at GitLab.com first in order to see these here, see [relevant docs](https://docs.gitlab.com/ee/user/group/#create-a-group).

**Comment by laushinka** [comment] 2021-10-01 09:56
> @laushinka Yes, this is still happening but only affects group avatars as described in the issue! You can add more groups at GitLab.com first in order to see these here, see [relevant docs](https://docs.gitlab.com/ee/user/group/#create-a-group).

@gtsiolis Turns out I needed to create a project first on GitLab under the group, in order for it to show up in the New Project page. It didn't show up with only a group for me.

**Comment by gtsiolis** [comment] 2021-10-01 09:58
> Turns out I needed to create a project first on GitLab under the group, in order for it to show up in the New Project page. It didn't show up with only a group for me.

Ah, yes! That's expected as it does not make much sense to list it there when there are no projects inside, right? What do you think?

**Comment by roboquat** [comment] 2021-12-21 09:03
@jldec: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5330#issuecomment-998594983):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by laushinka** [comment] 2022-01-10 14:24
Sorry was assigned this since before the holiday. Going to pick something else for now.

/unassign

**Comment by gtsiolis** [comment] 2022-01-10 15:09
@laushinka shall we also change the issue status on the groundwork board for visibility?

@jldec shall we :a: keep as scheduled until someone picks this up again or :b: remove it altogether from groundwork for now?

**Comment by jankeromnes** [comment] 2022-03-15 09:02
Will take a look today 😁

**Comment by jankeromnes** [comment] 2022-03-15 12:08
For me, it looks like all the groups that do have avatars (e.g. [jankeromnes](https://gitlab.com/jankeromnes), [gitpod](https://gitlab.com/gitpod)) work as intended, while the groups that don't actually have an avatar (e.g. [gitpod-io](https://gitlab.com/groups/gitpod-io), [gitpod-team](https://gitlab.com/gitpod-team)) also have no avatar in Gitpod.

<img width="769" alt="Screenshot 2022-03-15 at 13 05 12" src="https://user-images.githubusercontent.com/599268/158374543-30aeca1e-2b14-420c-8322-82e414bc8aca.png">

Do we have a GitLab group that actually has an avatar, but it doesn't show up in Gitpod? 🤔

**Comment by gtsiolis** [comment] 2022-03-15 12:51
Re-posting from the discussion with @jankeromnes:

> For those that the avatar is visible, it’s because **gitpod** is a user, not a group. See [relevant discussion](https://gitpod.slack.com/archives/C01KPEPLLRY/p1607436074133900) (internal).

> GitLab auto-generates an avatar based on the group name and using a colored background in combination with the first letter of the group name.

> However, with or without an uploaded image, avatars fail to load on the Gitpod side.

**Closed** 2022-04-04 17:24 UTC
Labels: user experience, component: dashboard, groundwork: scheduled, feature: teams and projects, team: webapp
