### ISSUE TITLE
Custom Webview rendering is not working

### ISSUE THREAD

**Issue by toddewilliams** [gitpod-io/gitpod#7898] opened 2022-01-28 14:57 UTC
### Bug description

The [CodeTogether extension](https://open-vsx.org/extension/genuitecllc/codetogether) uses a custom web view to render its UI. Even though a workaround to the [OpenVSCode Server Issue 175 "Webview Views via vscode.window.registerWebviewViewProvider are not working"](https://github.com/gitpod-io/openvscode-server/issues/175) works in OpenVSCode Server, it does not work in GitPod. Instead, the webview shoes an error message with a bad URL.
<img width="1119" alt="Screen Shot 2022-01-28 at 8 16 05 AM" src="https://user-images.githubusercontent.com/61880410/151568333-9ad29032-22bb-4d16-b3da-7f443b627fd3.png">

### Steps to reproduce

1. Open a new example workspace on GitPod
2. Navigate to "Extensions" and install CodeTogether from the open-vsx marketplace
3.  Click on the CodeTogether icon in the left navigation bar to show the CodeTogether view
4. Note that the CodeTogether view's webview component is broken and shows the following message: "webviewview-com-genuitec-codetogether-presence-webview-webview-foreign.ws-us29.gitpod.io's server IP address could not be found."

### Workspace affected

Any workspace is affected

### Expected behavior

I expect the CodeTogether web view to render appropriately, especially given usage of the [workaround shown in the OpenVSCode Server bug report](https://github.com/gitpod-io/openvscode-server/issues/175#issuecomment-952041523).

**Comment by akosyakov** [comment] 2022-02-21 10:52
@jeanp413 I think we don't override `vscode-webview.net` in blobserve. My guess is that this custom webview is loaded in webworker, so it still tries to connect to MS endpoint, i.e. it is caused by https://github.com/gitpod-io/gitpod/issues/6437

**Comment by jeanp413** [comment] 2022-02-24 04:22
@akosyakov webviews fail to load because subdomain name is longer than 64 chars `https://webviewview-com-genuitec-codetogether-presence-webview-webview-foreign.ws-dev.jp-fix-webview-view.staging.gitpod-dev.com` this only affects us because we append `-webview-foreign`

**Comment by akosyakov** [comment] 2022-02-24 07:25
we prepend only `-foreign` as far as I remember. Why `webviewview-com-genuitec-codetogether-presence-webview-webview` is so long? It used to UUID. Did they change something in logic?

**Comment by akosyakov** [comment] 2022-02-24 07:30
I think we should report it to upstream. Generally it will break on codespaces too if an extension name is 10 more characters long.

**Comment by akosyakov** [comment] 2022-02-24 07:31
Particularly to fix this case you can replace: https://github.com/gitpod-io/openvscode-server/blob/6cc478c99ab7b4216e4c58f590a2a82afb0ad053/src/vs/gitpod/browser/workbench/workbench.ts#L573

with `https://{{uuid}}-foreign`

**Comment by jeanp413** [comment] 2022-02-24 13:58
For webview views id is generated from provider id [here](https://github.com/microsoft/vscode-extension-samples/blob/2feab6d8f185417e63eaef73b38dae36a6a5dafb/webview-view-sample/src/extension.ts#L7-L8) and [here](https://github.com/microsoft/vscode-extension-samples/blob/2feab6d8f185417e63eaef73b38dae36a6a5dafb/webview-view-sample/src/extension.ts#L23)

**Comment by TimWebb** [comment] 2022-02-24 15:58
Interesting details. If I'm following right, a workaround we can do on our side is change:
`vscode.window.registerWebviewViewProvider('com.genuitec.codetogether.presence.webview', ...`
To something short to workaround the issue? Aka.
`vscode.window.registerWebviewViewProvider('ct-presence', ...`
Basically any ID less than 32 characters or so to stay under the 64 limit with appendages.

For context, I did a quick check on calls to registerWebviewViewProvider on GitHub and while most are quite short, there are other "long" ones like `'vscode-jmbg-sidebar-random-generator'` and `"salesforce-profile-modifier-sidebar"`.

**Comment by jeanp413** [comment] 2022-02-24 17:29
Hi @TimWebb, yes a workaround would be to shorten the webview provider id in you extension, I'll also shorten the `-webview-foreign` suffix to `-foreign` in our side

**Comment by TimWebb** [comment] 2022-02-24 22:29
Happy to confirm @jeanp413 that this works!  Thanks kindly for the assistance.

<img width="301" alt="ss" src="https://user-images.githubusercontent.com/6605430/155618223-e883f50c-8181-4781-8497-bcf01c797630.png">
.

**Comment by jeanp413** [comment] 2022-02-25 14:23
Also created an upstream PR https://github.com/microsoft/vscode/pull/143951 so it uses an uuid internally like other webviews, will keep this open until that it's merged

**Comment by jeanp413** [comment] 2022-02-28 23:57
Upstream PR got merged, closing this.

**Closed by jeanp413** 2022-02-28 23:57 UTC
Labels: type: bug, editor: code (browser), team: IDE
