### ISSUE TITLE
Gitpod doesn't work in Safari (and neither does this bug report)

### ISSUE THREAD

**Issue by kirstenhunter** [gitpod-io/gitpod#2910] opened 2021-01-14 17:18 UTC
### Describe the bug
I have a link from https://github.com/synedra-datastax/battlestax/blob/master/README_step01.md to https://gitpod.io/from-referrer/

I have tried this link with two different accounts (synedra-datastax and kirstenhunter).  With the first, I got right to the terms and conditions, but then got this error:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/76977358/104621913-7aecbf00-5645-11eb-8dd2-d9839ad8cdc8.png">

Logged out and logged in with GitHub as kirstenhunter, tried again.  This time I could login with GitHub, but after I accepted the terms and conditions I got the same error.

Looks like a Safari issue.  Works in Chrome.

### Steps to reproduce
Use Safari, try to use the link

### Expected behavior
Thought it would work

### Additional information
Would be super fabulous if you folks don't support safari to say so on your error page.  Right now 20% of internet users use Safari, so it's a Class A browser.  Not supporting it is a big deal.

### Example repository

https://github.com/synedra-datastax/battlestax

**Comment by svenefftinge** [comment] 2021-01-15 04:40
duplicate of #2746

**Closed by svenefftinge** 2021-01-15 04:40 UTC
