### ISSUE TITLE
OCI runtime create failed - no such file or directory: unknown

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#7666] opened 2022-01-18 20:58 UTC
### Bug description

Filing this issue on behalf of @konne. @konne (listening in), please confirm if this is intermittent, or always failing?

[The following error](https://github.com/gitpod-io/gitpod/issues/7440#issuecomment-1015488244) was received in workspace: vizlib-gucci-jgm70a009op

![image](https://user-images.githubusercontent.com/1272076/150017273-5159b63b-3df3-4178-acfa-bb9cfb7d603e.png)

This occurred on January 18th 2022 around 2:51pm.

### Steps to reproduce

Unknown

### Workspace affected

vizlib-gucci-jgm70a009op

### Expected behavior

An existing file or folder should be able to be opened.

### Example repository

n/a

### Anything else?

A related issue was resolved in #5945

**Comment by utam0k** [comment] 2022-01-19 05:47
It looks like the error in the runc is here.
https://github.com/opencontainers/runc/blob/4144b63817ebcc5b358fc2c8ef95f7cddd709aa7/libcontainer/container_linux.go#L380

**Comment by utam0k** [comment] 2022-01-19 06:46
Maybe `/` or `/proc` etc is overwritten at the image creation stage, so `/proc/self/fd` doesn't exit. I was able to reproduce what appeared to be the same error (the error message was cut off in the middle, so I'm not sure 😭 ) when I generated the image with the following Dockerfile on gitpod.
Please make sure that you are not using VOLUME like this in your `Dockerfile` or `docker-compose.yml`.
```Dockerfile
FROM busybox
VOLUME . /test
CMD ["sleep", "5"]
```

I also want to check first if this is a gitpod specific problem.

**Comment by csweichel** [comment] 2022-01-19 07:12
I don't think this issue makes sense at this point. When @konne reported it over in #7440 the fix had not yet been rolled out. That's since happened, hence this is an issue we hope to have fixed already.

Closing for now until this issue re-appears.

**Closed by csweichel** 2022-01-19 07:12 UTC
Labels: meta: :thinking: reporter-feedback-needed, feature: docker in workspaces, priority: highest (user impact), team: workspace
