### ISSUE TITLE
Cannot initialize workspace

### ISSUE THREAD

**Issue by tianhaoz95** [gitpod-io/gitpod#1515] opened 2020-05-15 02:59 UTC
### Describe the bug

When opening a repository from GitHub, it errors out.

Example repository and branch: https://github.com/tianhaoz95/iwfp/tree/feature/redo-promo-editing

Error message:

```bash
failed to create containerd task: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/theia/supervisor\": stat /theia/supervisor: no such file or directory": unknown
Please file an issue if you think this is a bug.
```

### Steps to reproduce
Click on the "gitpod" extension button from the repository linked above.

### Expected behavior
It should open a workspace.

### Additional information
Not Applicable

### Example repository
https://github.com/tianhaoz95/iwfp/tree/feature/redo-promo-editing

**Comment by Kreyren** [comment] 2020-05-15 04:41
Closing as duplicate of https://github.com/gitpod-io/gitpod/issues/1511

**Closed by Kreyren** 2020-05-15 04:41 UTC
