### ISSUE TITLE
Alert/notification for workspace timeout

### ISSUE THREAD

**Issue by mittalyashu** [gitpod-io/gitpod#13498] opened 2022-09-30 17:26 UTC
## Is your feature request related to a problem? Please describe

While working in a workspace and if you get distracted with some other work or something, after a certain period of time the workspace timeouts automatically without a notification or alert.

## Describe the behaviour you'd like

It would be nice to have a notification telling the workspace is timing out soon.

## Additional context

| screenshot |
| --- |
| <img width="475" alt="CleanShot 2022-09-30 at 22 51 24@2x" src="https://user-images.githubusercontent.com/29014463/193324304-4706710f-c4fb-4434-8922-06af3bb22795.png"> |

**Comment by axonasif** [comment] 2022-10-01 06:23
Possibly related: https://github.com/gitpod-io/gitpod/issues/7685

**Comment by loujaybee** [comment] 2022-10-04 14:23
I would consider this as part of: 

- https://github.com/gitpod-io/gitpod/issues/9038

Which is dependent on: 

- https://www.gitpod.io/docs/configure/billing/usage-based-billing

I will remove from inbox for now, and link to that epic 🙏

**Comment by loujaybee** [comment] 2022-10-04 14:23
This also looks like a duplicate of: 

- https://github.com/gitpod-io/gitpod/issues/11263

**Comment by loujaybee** [comment] 2023-01-31 08:30
Closing as duplicate of: 

- https://github.com/gitpod-io/gitpod/issues/11263

**Closed** 2023-01-31 08:31 UTC
Labels: user experience, component: supervisor, team: IDE, feature: timeout
