### ISSUE TITLE
Introduce a way to opt out from sending anonymous usage data through the admin dashboard

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7531] opened 2022-01-10 21:04 UTC
### Problem to solve

Following the proposal in https://github.com/gitpod-io/gitpod/issues/7530, opting out from sending anonymous usage data through the admin dashboard is not possible.

### Proposal

Introduce a way to opt out from sending anonymous usage data through the admin dashboard.

TBD (To be discussed)

**Comment by MrSimonEmms** [comment] 2022-01-25 10:41
Duplicate of #7498

**Closed by MrSimonEmms** 2022-01-25 10:41 UTC
Labels: type: feature request, user experience, self-hosted, feature: admin dashboard, needs visual design 💄, team: self-hosted
