### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by Robrowno** [gitpod-io/gitpod#8382] opened 2022-02-22 12:23 UTC
### Bug description

Error where workspace becomes corrupt and unable to open. 
Displays Out of Memory error when workspace is clicked on. 

When opening a new workspace it reverts to an older version despite git commits and pushes. 

![image](https://user-images.githubusercontent.com/98883458/155130847-c600880a-f4cb-4f7e-8240-96cafc162b1b.png)

### Steps to reproduce

Open Github dashboard
Attempt to open desired workspace
Out of Memory error displayed - cannot open workspace at all
Open new workspace, but it reverts to an older version
In the new workspace, you cannot open new browsers in port 8000 to view website 
cannot git push successful either, but git add and commit work as normal

### Workspace affected

https://gitpod.io/start/#robrowno-loverunning-74ee5fgvc3u

### Expected behavior

Open the workspace

**Comment by axonasif** [comment] 2022-02-22 19:11
Duplicate of #7969 https://github.com/gitpod-io/gitpod/issues/8238

**Closed** 2022-02-22 19:11 UTC
Labels: type: bug
