### ISSUE TITLE
Per-user homedir?

### ISSUE THREAD

**Issue by Michaelhobo** [gitpod-io/gitpod#2527] opened 2020-12-14 00:17 UTC
While using gitpod, I often want to persist user-specific data, e.g. gcloud credentials, RC files, etc etc. Today, these workflows need to be regenerated every time. Can we NFS-mount a volume onto the user's homedir that's shared between all of a user's workspaces? That would allow me to save settings, credentials, etc across my different workspaces.

**Comment by gtsiolis** [comment] 2020-12-14 08:45
Hi @Michaelhobo! We've been using [Environment Variables](https://www.gitpod.io/docs/environment-variables/) to store variables like GCP credentials.

I think it makes sense to also support file env vars in the future to support file (multiline) variables like certificates, RC files, and more. Feel free to upvote https://github.com/gitpod-io/gitpod/issues/2058.

See also the workaround mentioned in https://github.com/gitpod-io/gitpod/issues/2058#issuecomment-716417639.

**Comment by Michaelhobo** [comment] 2020-12-15 04:13
Thanks for the env vars mention, I didn't know about that, and it helps for a few of my needs. But, here are some more reasons for mounting a volume instead of (or in addition to) having file env vars.

- With env vars, setup of a new user becomes a lot harder, because you're forcing users to set up tools a non-standard way. This might require an onboarding doc that says "run this command once, base64 encode the contents of this key file, copy it into an env var on this gitpod page, etc. If you had a volume shared between all your workspaces, all standard tools **just work**, which I think would be magical. It would feel like I'm using my desktop, but with docker workspaces that are easy to spawn and checked into code.
- With a mounted volume, you can sync data between workspaces
- With a mounted volume, you can support workflows that read and write to a file in the homedir, like bazel cache (it was a huge pain to make bazel work with a different bazel output directory). As well as some files that are updated more often (e.g. some vim plugin data, ssh configs).

**Comment by Michaelhobo** [comment] 2020-12-15 17:19
This is also very similar to #2016

**Comment by csweichel** [comment] 2020-12-16 17:15
duplicate of https://github.com/gitpod-io/gitpod/issues/2016

**Closed by csweichel** 2020-12-16 17:15 UTC
Labels: question
