### ISSUE TITLE
MinIO Template Issue

### ISSUE THREAD

**Issue by supersebe** [gitpod-io/gitpod#2696] opened 2021-01-07 17:06 UTC
### Describe the bug
When i try to install gitpod with the internal minio, got this error:
`Error: template: gitpod/charts/minio/templates/deployment.yaml:192:20: executing "gitpod/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled`

### Steps to reproduce
Just trying to install gitpod with helm. I get this error message at version 0.4.0, and 0.5.0, right after `Release "gitpod" does not exist. Installing it now.`

### Expected behavior
Helm starts the gitpod installation

I tried to edit the minio-demployment.yaml but it didn't have any effect. The error remains.

**Comment by corneliusludmann** [comment] 2021-01-07 20:57
Duplicate of #1740. It's fixed in the upcoming 0.6.0 release. See the other issue for a workaround

**Closed by corneliusludmann** 2021-01-07 20:57 UTC
Labels: self-hosted
