### ISSUE TITLE
Can't create new workspaces on a repo

### ISSUE THREAD

**Issue by tbfleming** [gitpod-io/gitpod#895] opened 2019-11-04 19:57 UTC
**Describe the bug**

Starting a new workspace on a repo which was formerly working causes this error:

```
Error: Request createWorkspace failed with message: 5 NOT_FOUND: cannot resolve base image: not found
```

**To Reproduce**

Open https://gitpod.io/#https://github.com/EOSIO/eosio-web-ide

**Expected behavior**

**Additional Information**

**Comment by 32leaves** [comment] 2019-11-05 08:19
Hi @tbfleming, this is indeed a bug on our end introduced with the latest update. We should have this fixed within the next few hours.

**Comment by 32leaves** [comment] 2019-11-05 12:20
We have just deployed the fix and the repo works again as intended. Again, sorry for the inconvenience.

**Closed by 32leaves** 2019-11-05 12:20 UTC
Labels: bug, docker-build
