### ISSUE TITLE
Workspace contents not deleted

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#9631] opened 2022-04-28 16:39 UTC
### Bug description

I can still find *.tar files for old workspaces that are marked `hardDeleted` in the database.
For only my user this means we are unnecessarily carrying 3TB with us.

### Steps to reproduce

```
sven@cloudshell:~ (gitpod-191109)$ gsutil du -sch gs://gitpod-prod-user-9a4481e8-c13b-492d-9c6b-44fd0a5c5165/
2.89 TiB     gs://gitpod-prod-user-9a4481e8-c13b-492d-9c6b-44fd0a5c5165
```

### Workspace affected

e.g. a002f42d-169a-463b-9d24-4b3f9d1ea844

### Expected behavior

Workspace contents should be deleted when a workspace is marked as deleted in the database.

### Anything else?

There is other data in our cloud projects that we should take a look at and clean up.

**Comment by jankeromnes** [comment] 2022-05-02 17:20
After [further investigation](https://github.com/gitpod-io/ops/issues/2087#issuecomment-1115135240) (internal), the most likely culprit for the increased storage seems to be that, when we garbage-collect old prebuilds, we do not properly delete to contents from the GCP bucket.

Here is the relevant code:

https://github.com/gitpod-io/gitpod/blob/50d7afdd9a20f50228bdb42a8148a7206d564c24/components/server/src/workspace/garbage-collector.ts#L108-L119

https://github.com/gitpod-io/gitpod/blob/50d7afdd9a20f50228bdb42a8148a7206d564c24/components/server/src/workspace/workspace-deletion-service.ts#L73-L81

**Comment by geropl** [comment] 2022-05-03 06:47
@jankeromnes Did you check:
 - `server` logs for `wsgc: error during prebuild deletion`?
 - honeycomb traces `name = deleteOldPrebuilds`, especially a `HEATMAP(nrOfCollectedPrebuilds)` would be interesting

**Comment by jankeromnes** [comment] 2022-05-03 15:18
Good ideas @geropl, thanks. Will look into this.

Also, at first glance, my current guess is that we successfully delete GC'd prebuild backups for **US users**, but fail to delete them for **EU users**.

**Comment by jankeromnes** [comment] 2022-05-20 07:48
Okay, after investigating this for a bit (with long-running GCP-storage-probing scripts running in the background over many days), I have some good and bad news.

### The good news

By checking all officially garbage-collected prebuilds, I was able to find 96803 prebuild backups that were supposedly deleted (according to our DB) but were in fact still present in GCP. 🐛

I've thus deleted these 96803 left-over backups, saving a total of around 17.85 TB of cloud storage. 💸

### The bad news

The un-deleted backups I found all had a "content deleted" time between `2020-04-07T07:01:45.948Z` and `2020-04-26T13:58:55.462Z`. Thus, this seems to be only left-overs from an old GC bug from over 2 years ago.

FYI, the example workspace you've shared @svenefftinge, `a002f42d-169a-463b-9d24-4b3f9d1ea844`, was indeed a prebuild with a "content deleted" time of `2020-04-14T00:31:18.770Z` (so within the affected range).

### Next steps

Cleaning up these old prebuilds was a good thing, and saves us from a small but still significant monthly recurring cost.

Still, this doesn't explain recent increases in storage use, which remain to be investigated.

Some promising ideas for next steps:
- [ ] Also probe workspace backups, not just prebuilds, in particular within the problematic time range (I assume this to be a prebuilds-only bug, but I could be wrong, and it's definitely worth checking)
- [ ] Investigate why we're now running (& storing) prebuilds for repositories that do not have a `.gitpod.yml` (or even a DB config)
- [ ] Verify whether the increased storage use could be just related to the increase in prebuilds (i.e. working as intended)

**Comment by jankeromnes** [comment] 2022-08-29 14:12
Marking this as closed, because the identified problem was resolved successfully. I didn't have time to investigate other potential problems.

**Closed by jankeromnes** 2022-08-29 14:12 UTC
Labels: type: bug, component: content-service, component: server, team: webapp, team: workspace
