### ISSUE TITLE
All uncommitted data in active workspaces lost

### ISSUE THREAD

**Issue by lechien73** [gitpod-io/gitpod#4671] opened 2021-07-01 08:06 UTC
### Bug description

As of this morning, any uncommitted data in non-garbage collected workspaces has been lost.

A workspace can show any number of changes between it and the main branch on GitHub, but when opening the workspace the changes are no longer there. I lost a workspace with 4,264 pending changes this morning. Students are reporting mass loss of data and work.

### Steps to reproduce

Find a workspace that shows changes:
![Screenshot 2021-07-01 at 09 05 12](https://user-images.githubusercontent.com/21156053/124089090-79744f00-da4b-11eb-8898-869ead3b8f4d.png)

Start the workspace and it will revert to:
![Screenshot 2021-07-01 at 09 06 03](https://user-images.githubusercontent.com/21156053/124089199-9577f080-da4b-11eb-9512-5fc8b9ffc0a9.png)

Losing the uncommitted changes.

### Expected behavior

The expected behaviour would be for Gitpod to open workspaces normally, and for the uncommitted changes to be there.

**Comment by Franciskadtt** [comment] 2021-07-01 08:35
My workspace was affected by this issue this morning. When I typed python3 app.py in terminal today for my workspace, it said Flask is not installed. Also my env.py file was missing.

**Comment by yetnetbehailu** [comment] 2021-07-01 08:36
> My workspace was affected by this issue this morning. When I typed python3 app.py in terminal today for my workspace, it said Flask is not installed. Also my env.py file was missing.

Same thing happened to me had to re-create my env.py file

**Comment by jankeromnes** [comment] 2021-07-01 08:44
Hi @lechien73 and @Franciskadtt, we're so sorry about this unexpected critical incident.

We're actively investigating this problem. We'll try to mitigate it as soon as possible, and try to safe and recover any lost data.

If you have an affected workspace, please:

1. Save the workspace ID or URL somewhere (this might help with restoring data later)

2. Then, create a fresh new workspace, to continue work from there (that's because continuing work in the old affected workspace, or restarting that workspace again multiple times, could interfere with the backup & restore mechanism and decrease our chances of restoring the old data)

**Comment by BXS-Archipelago** [comment] 2021-07-01 08:48
Same problems for me.  I'm running a Django project and it giese message : " ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?"

**Comment by lechien73** [comment] 2021-07-01 08:49
Thanks @jankeromnes - we'll get that out there to our affected students.

For me, the main two are: amaranth-aardwolf-lj653ml1 and maroon-dog-9xusrtau

**Comment by BXS-Archipelago** [comment] 2021-07-01 08:53
Just FYI thanks...   My main workspace is https://pink-nightingale-71ra1tyl.ws-eu09.gitpod.io/

Now it is giving :    This page isn’t workingIf the problem continues, contact the site owner.
HTTP ERROR 401

**Comment by corneliusludmann** [comment] 2021-07-01 10:27
We updated our status page: https://www.gitpodstatus.com/incidents/ggspjq9qlbwx

**Comment by JochenFM** [comment] 2021-07-01 11:14
What do you mean no data is lost? Does not apply to me unfortunately. I lost a complete database this morning and there was nothing I could have done to prevent this, apparently. Gitpod people, this is not good enough, I am sorry! Heroku manages to send heads-up emails when maintenance is required. Do the same and add information as to what the possible consequences are  for users and how to prevent/mitigate them.

**Comment by meysholdt** [comment] 2021-07-01 11:24
> What do you mean no data is lost?

it means we're in the process of recovering the data and will make it available to you (and all other affected users) ASAP.

**Comment by JochenFM** [comment] 2021-07-01 11:26
That sounds very good - thank you!

**Comment by higorgeous** [comment] 2021-07-01 12:29
If we continue to develop into the workspace, will those be affected by the data recovery?

**Comment by C-Undritz** [comment] 2021-07-01 13:23
Do you yet have an ETA as to when we can start our workspaces and check whether they are wokring as expected yet?

**Comment by JanKoehnlein** [comment] 2021-07-01 14:31
Status: We've identified and fixed the bug.

1) If you re-start a workspace now that has a backup from before 5:30 UTC today, that backup will be restored
2) If you have started a workspace between 5:30 UTC today and 12:36 UTC today, we will still do a backup, but if there is one from before the incident, that one will be loaded on the next re-start.  Please contact us via contact@gitpod.io if you need access to the newer backup.

We are very sorry for this incident and all the damage it caused to our users.

**Comment by pmeeny** [comment] 2021-07-01 15:12
Thanks for fixing, I can confirm my workspace is back working. Thanks for the resolution and the updates.

**Comment by higorgeous** [comment] 2021-07-02 00:26
We are still having issues. Sent an email to support@gitpod.io and replied to the messages from your support team.

We noticed the workspace had been restored last night AEST and continued working, however this morning, it's now reverted again. Can we get pink-stingray-8ty21riw reverted to what it was at 1:30am AEST. Thank you.

**Comment by jlaasonen** [comment] 2021-07-02 06:48
My workspace was working yesterday (17:00 UTC), but when I started it today the changes from yesterday afternoon were lost.

**Comment by higorgeous** [comment] 2021-07-02 06:51
> My workspace was working yesterday (17:00 UTC), but when I started it today the changes from yesterday afternoon were lost.

Same.

**Comment by csweichel** [comment] 2021-07-02 07:20
@higorgeous I have (hopefully) restored the state to what it was at 1:30am AEST. Due to the nature of the incident we're left with a sort of "split brain" situation where we have two backups for the same workspace in different states. That makes it rather hard to communicate the options, but also to keep track of what's what. I'm very sorry for this mess.

**Comment by csweichel** [comment] 2021-07-02 07:24
@jlaasonen I have (hopefully) restored your workspace backup to its latest state. Please let me know if it is in the state you expected it to be in.

**Comment by higorgeous** [comment] 2021-07-02 07:35
> @higorgeous I have (hopefully) restored the state to what it was at 1:30am AEST. Due to the nature of the incident we're left with a sort of "split brain" situation where we have two backups for the same workspace in different states. That makes it rather hard to communicate the options, but also to keep track of what's what. I'm very sorry for this mess.

Thank you for your help but I am not seeing any of these changes available in the workspace. If you can see the files, we should have a `.env.local` in the root and within `src/components` there should be a `Library` containing `Textarea`, `Textfield` and `Form` directories,  and  `AddCharity` directory containing `index.tsx` and `styles.tsx`. Inside `src/context` we should also have a directory called `Theme` that contains `index.tsx`.

**Comment by jlaasonen** [comment] 2021-07-02 07:39
> @jlaasonen I have (hopefully) restored your workspace backup to its latest state. Please let me know if it is in the state you expected it to be in.

Unfortunately, it is not the expected state. Looks like the state from earlier today, or yesterday before the latest changes. I would need the state from 1.7. about 15-16 CEST.

**Comment by higorgeous** [comment] 2021-07-02 07:50
> > @higorgeous I have (hopefully) restored the state to what it was at 1:30am AEST. Due to the nature of the incident we're left with a sort of "split brain" situation where we have two backups for the same workspace in different states. That makes it rather hard to communicate the options, but also to keep track of what's what. I'm very sorry for this mess.
> 
> Thank you for your help but I am not seeing any of these changes available in the workspace. If you can see the files, we should have a `.env.local` in the root and within `src/components` there should be a `Library` containing `Textarea`, `Textfield` and `Form` directories, and `AddCharity` directory containing `index.tsx` and `styles.tsx`. Inside `src/context` we should also have a directory called `Theme` that contains `index.tsx`. I think off the top of my head, we had 35 commits to be `pushed`.

Stopping and restarting did not help.

**Comment by jlaasonen** [comment] 2021-07-02 08:25
@csweichel Thank you for the help, my workspace is now correct. Got a message from support that "Your workspace should be restored and reflect now your uncommited changes during 5:20 UTC and 12:36 UTC", but the state is actually the correct one from yesterday afternoon.

**Comment by csweichel** [comment] 2021-07-02 08:34
@jlaasonen very happy to hear that - thank you for letting me know
@higorgeous I've replied to your email - please let me know if that helps. Best we continue this conversation via email.

**Comment by higorgeous** [comment] 2021-07-02 09:37
> @jlaasonen very happy to hear that - thank you for letting me know
> @higorgeous I've replied to your email - please let me know if that helps. Best we continue this conversation via email.

Thank you Chris. I have replied to the email with the correct backup. Thank you.

**Comment by ShavingSeagull** [comment] 2021-07-02 21:02
Hi, gang. I have a student here who is losing changes to his work regardless of saving it, since the update a couple days ago. He mentioned that simply clearing his cache was enough to cause it. Essentially, if he doesn't push his changes to GitHub, they will be gone when he next opens the workspace. Could this be a lingering post-update bug?

For clarity, the affected workspace is:
https://aqua-bat-y9axljm3.ws-eu10.gitpod.io/

Cheers.

**Comment by meysholdt** [comment] 2021-07-05 13:00
Hi @ShavingSeagull,

can you please tell the student to reach out via support@gitpod.io so that we can help recover the data?

I'm closing this issue since the incident is resolved. 
See https://www.gitpodstatus.com/incidents/ggspjq9qlbwx for full details.

**Closed by meysholdt** 2021-07-05 13:00 UTC
Labels: type: incident

**Comment by kevinhq** [comment] 2022-09-14 13:18
this is happening again on my workspace. pretty disappointing. I've send you email to restore it asap

**Comment by ashwathirao** [comment] 2022-10-17 10:46
Created a workspace and left it idle for sometime all the files i created under /workspace/ directory is lost.

This has been happening since 14 October

Steps to reproduce

Create a workspace
Create a file in /workspace/ directory
Let the workspace timeout
