### ISSUE TITLE
Gitpod workspace UI loads huge CSS/JS files that are not minified

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#3819] opened 2021-04-07 15:10 UTC
### Bug description

When starting a workspace, Gitpod UI is loading `workbench.web.api.js` (3.5MB) and other JS and CSS files that are not minified.

### Steps to reproduce

Open the browser's devtools -> Network tab.
Start a gitpod Workspace and preview any of the `workbench.*.*` JS or CSS files, you will see that they are not minified.

### Expected behavior

Minified CSS and JS files.

**Comment by akosyakov** [comment] 2021-04-08 06:21
duplicate of https://github.com/gitpod-io/gitpod/issues/2117

Just for reference, we use long term caching, so you download it once for all workspaces and never ask the server again.

**Closed by akosyakov** 2021-04-08 06:21 UTC
