### ISSUE TITLE
Update gradle in gitpod/workspace-full

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#334] opened 2019-02-22 09:24 UTC
**Describe the bug**
Currently running `gradle init` in a fresh `gitpod/workspace-full` based workspace yields:
```
FAILURE: Build failed with an exception.

* What went wrong:
java.lang.ExceptionInInitializerError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**To Reproduce**
 1. Open a fresh repository
 1. run `gradle init --type java-library`

**Expected behavior**
Gradle should initialize the project.

It seems to be a [gradle incompatibility](https://stackoverflow.com/questions/42851099/java-lang-exceptionininitializererror-with-gradle) with java 8 (we have `jdk 1.8.0_201`). Updating to `gradle-4.10.3` solves the issues; sadly this is not available from the ubuntu repos.

**Comment by meysholdt** [comment] 2019-02-22 09:45
see https://github.com/gitpod-io/gitpod/issues/69#issuecomment-443358420

Maybe we can use https://sdkman.io/ to install Java, Maven and Gradle into `workspace-full`

**Comment by jankeromnes** [comment] 2019-02-22 09:59
Thanks for the pointers! I'll look into upgrading Gradle to latest stable in `workspace-full` (possibly using tarballs, or sdkman.io, or homebrew, or something else that makes sense).

**Comment by jankeromnes** [comment] 2019-02-22 10:02
Actually this is a duplicate of #69. Closing.

**Comment by kittaakos** [comment] 2019-03-05 10:49
I am having a very similar if not the same issue.
Steps to reproduce:
 - Start Theia with `yarn --cwd ./examples/browser start --hostname 0.0.0.0 --port 3000`
 - Open a terminal and create a new folder: `mkdir jdt-ls-gh-28 && cd jdt-ls-gh-28`.
 - Execute `gradle init --type java-library`.

```
Picked up JAVA_TOOL_OPTIONS: -Xmx3189m
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.4.1/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Picked up JAVA_TOOL_OPTIONS: -Xmx3189m

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.ExceptionInInitializerError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by jankeromnes** [comment] 2019-03-05 10:58
Oh oh, that's unfortunate, because we expected this issue (actually, #69) to be fixed since we've now upgraded Gradle in production.

@AlexTugarev when you have some time, could you please look into this problem?

**Comment by jankeromnes** [comment] 2019-09-30 12:13
Closing this as it's been a while. Please re-open if the problem is still there.

**Closed by jankeromnes** 2019-09-30 12:13 UTC
