### ISSUE TITLE
Mouse wheel scrolling in editor is too slow on Firefox / Windows

### ISSUE THREAD

**Issue by spoenemann** [gitpod-io/gitpod#854] opened 2019-10-16 09:30 UTC
**Describe the bug**
Scrolling up / down with the mouse wheel is too slow in the editor. It's fine in other views such as the file explorer.

**To Reproduce**
Open Gitpod with Firefox on Windows, open an editor.

**Expected behavior**
Scrolling speed should be natural, i.e. roughly the same as for the browser-native scrollbars.

**Comment by geropl** [comment] 2019-10-16 13:00
:sweat_smile: Created the same issue yesterday on theia repo: https://github.com/eclipse-theia/theia/issues/6390

It's basically solved, we _just_ need to update Theia and Gitpod

**Comment by svenefftinge** [comment] 2019-12-05 07:14
In production now

**Comment by geropl** [comment] 2019-12-05 13:40
Sadly not, scrolling is still slow - and the issues upstream are open, too.

**Comment by randomir** [comment] 2020-01-18 11:55
Any update on when will this fix be deployed to GitPod?

**Comment by akosyakov** [comment] 2020-01-20 02:52
I don't think it was fixed, Theia needs new Monaco and update only was planned.

**Comment by imdigo** [comment] 2020-02-26 11:09
Any update? 
Did it fixed on theia-ide?

**Comment by Kartikkman** [comment] 2020-04-15 17:01
@svenefftinge  Hi thanks for Awesome product , but we are facing scroll issue , Can you fix it ? It makes hard to scroll through Code !!

**Comment by svenefftinge** [comment] 2020-04-21 09:55
We are deploying the fix to this tomorrow.

**Comment by Kreyren** [comment] 2020-04-21 10:24
FWIW I also found it annoying, but it seemed to me as intended design so i solved it by using:

```json
"editor.mouseWheelScrollSensitivity": 10,
```

**Comment by svenefftinge** [comment] 2020-04-23 06:42
This has been fixed and deployed to production.

**Closed by svenefftinge** 2020-04-23 06:42 UTC
Labels: fixed-not-deployed, theia, ux
