### ISSUE TITLE
We are having trouble parsing your context

### ISSUE THREAD

**Issue by ghost** [gitpod-io/gitpod#2821] opened 2021-01-11 11:43 UTC

**Comment by thomasfinnegan** [comment] 2021-01-11 11:44
We are having trouble parsing your context

**Comment by jankeromnes** [comment] 2021-01-11 16:21
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by jankeromnes** 2021-01-11 16:21 UTC
