### ISSUE TITLE
Gitpod authorization failed

### ISSUE THREAD

**Issue by aabharbhatt99** [gitpod-io/gitpod#2781] opened 2021-01-10 15:44 UTC

**Comment by aabharbhatt99** [comment] 2021-01-10 15:45
error in authorizing the account.

**Comment by csweichel** [comment] 2021-01-11 06:38
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Closed by csweichel** 2021-01-11 06:38 UTC
