### ISSUE TITLE
Scala source can't be opened

### ISSUE THREAD

**Issue by menya84** [gitpod-io/gitpod#97] opened 2018-10-12 09:08 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Comment by mwz** [comment] 2018-10-13 20:57
This is a duplicate of #35.

**Comment by svenefftinge** [comment] 2018-10-18 08:10
see comment https://github.com/gitpod-io/gitpod/issues/97#issuecomment-429574674

**Closed by svenefftinge** 2018-10-18 08:10 UTC
